### ISSUE TITLE
Keyboard controls don't work with non-English keyboard layouts

### ISSUE THREAD

**Issue by MelomanCool** [MCMrARM/mcpelauncher-linux#1]
Tested on Russian keyboard layout.

**Comment by sliceofcode** [comment]
:+1:

**Comment by MCMrARM** [comment]
I'll look into this some time later.

**Comment by MCMrARM** [comment]
Is this still an issue?

**Comment by MCMrARM** [comment]
As far as I know, this issue has been fixed some time ago. Closing.
