### ISSUE TITLE
/usr/bin/ld: cannot find -lpng

### ISSUE THREAD

**Issue by egr7v8** [MCMrARM/mcpelauncher-linux#10]
Linking CXX executable mcpelauncher
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_getstackaddr':
hooks.c:(.text+0x3f7): warning: the use of`pthread_attr_getstackaddr' is deprecated, use `pthread_attr_getstack'
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function`my_pthread_attr_setstackaddr':
hooks.c:(.text+0x3d6): warning: the use of `pthread_attr_setstackaddr' is deprecated, use`pthread_attr_setstack'
/usr/bin/ld: cannot find -lEGL
/usr/bin/ld: cannot find -lpng
collect2: error: ld returned 1 exit status
make[2]: **\* [mcpelauncher] Ошибка 1
make[1]: **\* [CMakeFiles/mcpelauncher.dir/all] Ошибка 2
make: **\* [all] Ошибка 2

**Comment by SopaXorzTaker** [comment]
You probably didn't install the appropriate libraries. Please see #3 and README.md.

**Comment by egr7v8** [comment]
@SopaXorzTaker 

egr7v8@egr7v8-desktop:~/mcpe/m$ make
make[2]: *** Нет правила для сборки цели `/usr/lib/x86_64-linux-gnu/libpng.so', требуемой для `mcpelauncher'.  Останов.
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Ошибка 2
make: *** [all] Ошибка 2

**Comment by SopaXorzTaker** [comment]
@egr7v8, you can try installing the libpng stuff manually.

`sudo apt-get install libpng libpng-dev libpng:i386 libpng-dev:i386`

**Comment by egr7v8** [comment]
@SopaXorzTaker , Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
Заметьте, вместо «libpng-dev» выбирается «libpng12-dev»
Заметьте, вместо «libpng-dev:i386» выбирается «libpng12-dev:i386»
E: Не удалось найти пакет libpng
E: Не удалось найти пакет libpng

**Comment by SopaXorzTaker** [comment]
Oops! Try libpng12 instead:

`sudo apt-get install libpng12 libpng12-dev libpng12:i386 libpng12-dev:i386`

**Comment by egr7v8** [comment]
@SopaXorzTaker , :D

egr7v8@egr7v8-desktop:~/mcpe/m$ sudo apt-get install libpng12 libpng12-dev libpng12:i386 libpng12-dev:i386
Чтение списков пакетов… Готово
Построение дерева зависимостей       
Чтение информации о состоянии… Готово
E: Не удалось найти пакет libpng12
E: Не удалось найти пакет libpng12
egr7v8@egr7v8-desktop:~/mcpe/m$

**Comment by SopaXorzTaker** [comment]
Oh, so maybe try doing `apt-cache search libpng | more`? This will show you the needed package. Replace the `libpng12*` in the line with the proper name.

<details>
    <summary>If you understand Russian better than English</summary>
    Советую выполнить `apt-cache search libpng | more` и найти нужное имя пакета и заменить им `libpng12*`
</details>
