### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by svilex** [MCMrARM/mcpelauncher-linux#102]
> ./mcpelauncher
loading native libraries
oslib: libGLESv2.so: 144545264
oslib: /home/giovanni/Desktop/mcpe/libs/native/libfmod.so.8.2: 144547216
loading hybris libraries
loading MCPE
loaded MCPE (at 4101378048)
apply patches
original: 85 83 87 86 131
post patch: 233 46 231 38 18
original: 85 83 87 86 131
post patch: 233 164 119 39 18
original: 85 83 87 86 129
post patch: 233 254 116 39 18
original: 83 87 86 131 236
post patch: 233 172 117 39 18
original: 83 131 236 8 232
post patch: 233 42 99 227 17
original: 83 87 86 131 236
post patch: 233 56 106 227 17
original: 85 83 87 86 131
post patch: 233 218 206 215 17
original: 83 87 86 131 236
post patch: 233 156 218 3 18
original: 83 131 236 8 232
post patch: 233 158 205 3 18
original: 83 131 236 8 232
post patch: 233 174 204 3 18
original: 83 86 80 232 0
post patch: 233 92 15 104 18
patches applied!
init app platform vtable
AppPlatform size = 117
init app platform
app platform initialized
init window
EGL_VERSION = 1.4
fetch patch notes
create minecraft client
userdata path = data/user/
userdata path for levels = data/user/
userdata path = data/user/
init minecraft client
userdata path = data/user/
device id = linux
get data url: assets/
external storage path = data/public/
userdata path = data/user/
userdata path = data/user/
userdata path = data/user/
userdata path = data/user/
userdata path = data/user/
userdata path = data/user/
userdata path = data/user/
userdata path = data/user/
get data url: assets/
get assert full path: uniforms.json
Signal 11 received
Getting stacktrace...
Backtrace elements: 4
\# 0 ./mcpelauncher(_Z12handleSignali+0x5d) [0x8061f8e]
\# 1 [0xf7713bc0]
\# 2 /lib/i386-linux-gnu/libc.so.6(strstr+0x1a) [0xf728c1fa]
\# 3 HYBRIS mce::FeatureSupportOGL::FeatureSupportOGL()+383 in libminecraftpe.so+0x1c5178f [0xf63b278f]
Signal 6 received
Aborted (core dumped)

**Comment by guppy42** [comment]
If you want some help you should really provide some context, ie;

**Operating system**:

**MCPE version**:

**Graphics Driver and version**:

you could also provide what version of the required libs you have installed if you know.
other potentially usefull data is the output of gcc -v

**Comment by svilex** [comment]
**MCPE version:** mcpe 1.0.3.0 x86 apk
**Graphics Driver and version:** nvidia-378
**what version of the required libs you have installed:** all of them from the readme:
> sudo apt-get install cmake zlib1g-dev:i386 libncurses5-dev:i386 libgles2-mesa-dev gcc-multilib g++-multilib zlib1g-dev:i386 libx11-dev:i386 linux-libc-dev:i386 uuid-dev:i386 libpng-dev:i386 libx11-dev:i386 libxext6:i386

and also

>libgles2-mesa-dev:i386 and libegl1-mesa-dev:i386

**potentially usefull data is the output of gcc -v :**
> gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure \-v \-\-with-pkgversion=\'Ubuntu 5.4.0\-6ubuntu1\~16.04.4' \-\-with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)

**Comment by svilex** [comment]
also the cmake . output:

> cmake .
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'egl'
--   Found egl, version 11.2.0
-- Found EGL: /usr/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/giovanni/Desktop/mcpe

and the make output:

>

**Comment by svilex** [comment]
nevermind it's now working with no reason why, thanks anyway :)
