### ISSUE TITLE
Crash at starting(AMD)

### ISSUE THREAD

**Issue by Tarik02** [MCMrARM/mcpelauncher-linux#103]
When i run mcpelauncher it crashes:

```
$ gdb --args mcpelauncher --fix-amd
GNU gdb (Ubuntu 7.11.90.20161005-0ubuntu1) 7.11.90.20161005-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
---Type <return> to continue, or q <return> to quit---
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from mcpelauncher...done.
(gdb) run
Starting program: /home/tarik02/.mcpe/mcpelauncher-linux/mcpelauncher --fix-amd
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
loading native libraries
oslib: libGLESv2.so: 1448775288
oslib: /home/tarik02/.mcpe/mcpelauncher-linux/libs/native/libfmod.so.8.2: 1448776480
loading hybris libraries
loading MCPE
loaded MCPE (at 4106579968)
apply patches
original: 85 83 87 86 131
post patch: 233 197 13 252 95
original: 85 83 87 86 131
post patch: 233 222 164 252 95
original: 85 83 87 86 129
post patch: 233 66 162 252 95
original: 83 87 86 131 236
post patch: 233 4 163 252 95
original: 83 131 236 8 232
post patch: 233 10 178 184 95
original: 83 87 86 131 236
post patch: 233 44 185 184 95
original: 85 83 87 86 131
post patch: 233 226 29 173 95
original: 83 87 86 131 236
post patch: 233 120 13 217 95
original: 83 131 236 8 232
post patch: 233 142 0 217 95
original: 83 131 236 8 232
post patch: 233 158 255 216 95
original: 85 83 87 86 131
post patch: 233 208 61 66 96
patches applied!
init app platform vtable
AppPlatform size = 119
init app platform
app platform initialized
init window
EGL_VERSION = 1.4
[New Thread 0xf2182b40 (LWP 11022)]
[New Thread 0xf1981b40 (LWP 11023)]
[New Thread 0xf0fffb40 (LWP 11024)]
fetch patch notes
create minecraft client
userdata path = data/user/
userdata path for levels = data/user/
userdata path = data/user/
init minecraft client
userdata path = data/user/
device id = linux
get data url: assets/
external storage path = data/public/
internal storage path = data/private/
userdata path for levels = data/user/
userdata path for levels = data/user/
userdata path for levels = data/user/
userdata path for levels = data/user/
userdata path for levels = data/user/
userdata path = data/user/
userdata path = data/user/
get data url: assets/
get assert full path: uniforms.json
get system region: 0xdeadbeef
[New Thread 0xf1179b40 (LWP 11027)]
[New Thread 0xf116db40 (LWP 11028)]
[New Thread 0xe7ae3b40 (LWP 11029)]
getjvmenv
[New Thread 0xe72e2b40 (LWP 11030)]
getjvmenv
[New Thread 0xe6ae1b40 (LWP 11031)]
getjvmenv
[New Thread 0xe62e0b40 (LWP 11032)]
getjvmenv
[New Thread 0xe5adfb40 (LWP 11033)]
getjvmenv
[New Thread 0xe52deb40 (LWP 11034)]
getjvmenv
[New Thread 0xe4addb40 (LWP 11035)]
getjvmenv
[New Thread 0xe42dcb40 (LWP 11036)]
getjvmenv
[New Thread 0xe3adbb40 (LWP 11037)]
getjvmenv
[New Thread 0xe32dab40 (LWP 11038)]
getjvmenv
[New Thread 0xe2ad9b40 (LWP 11039)]
getjvmenv
[New Thread 0xe22d8b40 (LWP 11040)]
getjvmenv
[New Thread 0xe1ad7b40 (LWP 11041)]
getjvmenv
[New Thread 0xe12d6b40 (LWP 11042)]
getjvmenv
[New Thread 0xe0ad5b40 (LWP 11043)]
getjvmenv
[New Thread 0xe02d4b40 (LWP 11044)]
getjvmenv
[New Thread 0xdfad3b40 (LWP 11045)]
getjvmenv
[New Thread 0xdf2d2b40 (LWP 11046)]
getjvmenv
[New Thread 0xdead1b40 (LWP 11047)]
getjvmenv
[New Thread 0xde2d0b40 (LWP 11048)]
getjvmenv
[New Thread 0xddacfb40 (LWP 11049)]
getjvmenv
[New Thread 0xdd2ceb40 (LWP 11050)]
getjvmenv
[New Thread 0xdcacdb40 (LWP 11051)]
getjvmenv
[New Thread 0xdc2ccb40 (LWP 11052)]
getjvmenv
[New Thread 0xdbacbb40 (LWP 11053)]
getjvmenv
[New Thread 0xdb2cab40 (LWP 11054)]
getjvmenv
[New Thread 0xdaac9b40 (LWP 11055)]
getjvmenv
[New Thread 0xda2c8b40 (LWP 11056)]
getjvmenv
[New Thread 0xd9ac7b40 (LWP 11057)]
getjvmenv
[New Thread 0xd92c6b40 (LWP 11058)]
getjvmenv
[New Thread 0xd8ac5b40 (LWP 11059)]
getjvmenv
[New Thread 0xd82c4b40 (LWP 11060)]
getjvmenv
[New Thread 0xd7ac3b40 (LWP 11061)]
getjvmenv
[New Thread 0xd72c2b40 (LWP 11062)]
getjvmenv
[New Thread 0xd6ac1b40 (LWP 11063)]
getjvmenv
[New Thread 0xd62c0b40 (LWP 11064)]
getjvmenv
[New Thread 0xd5abfb40 (LWP 11065)]
getjvmenv
[New Thread 0xd52beb40 (LWP 11066)]
getjvmenv
[New Thread 0xd4abdb40 (LWP 11067)]
getjvmenv
[New Thread 0xd42bcb40 (LWP 11068)]
internal storage path = data/private/
device id = linux
creating fake store <MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqU9snkqLkTCYZQfQgNy9eabP/OcumQTgcoYhuBbmx2isicIX8mSUNJn64yxiA6acqnJzJxGbKW9H+gSWMuRtCtwI3Exb3sCq19EiVtjos4u5BJatzBKXXDDJeeYrejGk8FgT6ffokcilJFY4wgQQxDGFdfE/reAqm6+VKUtoqnjMpG0wVZn+o0bJfxNvE/ydJPlabDmoywEn9zEl0hXo0i+cimVlFZcTT6ed7U9celM2Ywg+7qVIu7fmBHPucTIoUAbipEAIvP2EntOqrhUG6GKJ219Qhdr43fvnyBailudNBiDRqA+x0rCH1JgmV/BvyAHTBylPzroeh9rWJNNPxQIDAQAB>
allows subscriptions: false
restore from cache
register license change callback
getjvmenv
get assert full path: commands/pregame.json
device id = linux
xbox get app config singleton
device id = linux
xbox config: set sandbox (stub)
xbox get app config singleton
xbox config: set sandbox (stub)
userdata path for levels = data/user/
userdata path for levels = data/user/
userdata path = data/user/
userdata path for levels = data/user/
userdata path = data/user/
userdata path for levels = data/user/
initialized lib
initialized display
get store id: LinuxStore
get sub platform store id: LinuxStore
send http request
destroying http request
send http request
destroying http request
[MinecraftPE] VERBOSE RAKNET [IPv6] multicast listen on interface 0



[New Thread 0xd19ffb40 (LWP 11070)]
[New Thread 0xd17feb40 (LWP 11071)]
[New Thread 0xd15fdb40 (LWP 11072)]
send http request
destroying http request
send http request
destroying http request

Thread 1 "mcpelauncher" received signal SIGILL, Illegal instruction.
0xf5b35ea7 in ?? ()
(gdb) 
(gdb) q
A debugging session is active.

        Inferior 1 [process 11018] will be killed.

Quit anyway? (y or n) y
```

```
$ cat /proc/cpuinfo
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 15
model           : 107
model name      : AMD Athlon(tm) 64 X2 Dual Core Processor 4400+
stepping        : 1
cpu MHz         : 2288.330
cache size      : 512 KB
physical id     : 0
siblings        : 2
core id         : 0
cpu cores       : 2
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 1
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt rdtscp lm 3dnowext 3dnow rep_good nopl extd_apicid eagerfpu pni cx16 lahf_lm cmp_legacy svm extapic cr8_legacy 3dnowprefetch vmmcall lbrv
bugs            : apic_c1e fxsave_leak sysret_ss_attrs null_seg swapgs_fence
bogomips        : 4576.66
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management: ts fid vid ttp tm stc 100mhzsteps

processor       : 1
vendor_id       : AuthenticAMD
cpu family      : 15
model           : 107
model name      : AMD Athlon(tm) 64 X2 Dual Core Processor 4400+
stepping        : 1
cpu MHz         : 2288.330
cache size      : 512 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 1
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt rdtscp lm 3dnowext 3dnow rep_good nopl extd_apicid eagerfpu pni cx16 lahf_lm cmp_legacy svm extapic cr8_legacy 3dnowprefetch vmmcall lbrv
bugs            : apic_c1e fxsave_leak sysret_ss_attrs null_seg swapgs_fence
bogomips        : 4576.93
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management: ts fid vid ttp tm stc 100mhzsteps
```

Using AMD-compatible libs from #14

**Comment by DaMatrix** [comment]
Try without the compat libs. I use an A3-5300 and it runs fine when simply following the installation instructions on the README.

**Comment by Tarik02** [comment]
Without libs, it crashes just after runnung.

**Comment by KennFatt** [comment]
search older closed issue, there was a new lib for amd by the developer it self. @Tarik02

**Comment by Tarik02** [comment]
@KennFatt, where? In all issues i find the same libs.

**Comment by kris27mc** [comment]
[Try these](https://github.com/MCMrARM/mcpelauncher-linux/files/1148977/mcpelauncher_libs_amd.zip)

**Comment by MCMrARM** [comment]
If this is still an issue please provide me with output from valgrind.

**Comment by Tarik02** [comment]
@MCMrARM test on 1.2 or 1.1?

**Comment by Tarik02** [comment]
@MCMrARM it is still crashing :(. I will provide output from valgrind soon

**Comment by Tarik02** [comment]
WTF? It starts normally(but with very bad performace) when i am using valgrind, but still crashes when running just.
Valgrind output: https://gist.github.com/Tarik02/34c1d3e3d2cc13c343909a1d62e9aef8

**Comment by Tarik02** [comment]
Also i compiled without CEF

**Comment by Tarik02** [comment]
Branch: 1.2-xboxlive

**Comment by EasyTorrents** [comment]
I think i am hitting the same bug with the master branch.

If i just run with valgrind it will load but its so slow its not playable. My valgrind log is about the same as the one posted by Tarik02 running without the amd patch.

./mcpelauncher --help   advises to use --amd-workaround which is another bug as the correct command is ./mcpelauncher --amd-fix but that gives Signal 11

Tarik02 do you get the same if use --amd-fix and not --fix-amd?

My valgrind output with the amd fix is below

`==23871== Memcheck, a memory error detector
==23871== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==23871== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==23871== Command: ./mcpelauncher --amd-fix
==23871== Parent PID: 6666
==23871== 
==23871== Invalid read of size 1
==23871==    at 0x80AA289: patchCallInstruction(void*, void*, bool) (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==    by 0x80A4632: main (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==  Address 0xcf is not stack'd, malloc'd or (recently) free'd
==23871== 
==23871== Conditional jump or move depends on uninitialised value(s)
==23871==    at 0x809931D: find_containing_library (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==    by 0x809846A: android_dladdr (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==    by 0x809502A: hybris_dladdr (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==    by 0x80AA576: handleSignal(int, void*) (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==    by 0x4057EE7: ??? (in /lib/libpthread-2.26.so)
==23871==    by 0x80A4632: main (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871== 
==23871== Conditional jump or move depends on uninitialised value(s)
==23871==    at 0x8099338: find_containing_library (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==    by 0x809846A: android_dladdr (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==    by 0x809502A: hybris_dladdr (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==    by 0x80AA576: handleSignal(int, void*) (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==    by 0x4057EE7: ??? (in /lib/libpthread-2.26.so)
==23871==    by 0x80A4632: main (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871== 
==23871== Conditional jump or move depends on uninitialised value(s)
==23871==    at 0x80993A3: find_containing_symbol (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==    by 0x80984AF: android_dladdr (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==    by 0x809502A: hybris_dladdr (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==    by 0x80AA576: handleSignal(int, void*) (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==    by 0x4057EE7: ??? (in /lib/libpthread-2.26.so)
==23871==    by 0x80A4632: main (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871== 
==23871== Conditional jump or move depends on uninitialised value(s)
==23871==    at 0x80993B6: find_containing_symbol (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==    by 0x80984AF: android_dladdr (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==    by 0x809502A: hybris_dladdr (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==    by 0x80AA576: handleSignal(int, void*) (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==    by 0x4057EE7: ??? (in /lib/libpthread-2.26.so)
==23871==    by 0x80A4632: main (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871== 
==23871== Invalid read of size 4
==23871==    at 0x80AA560: handleSignal(int, void*) (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==    by 0x4057EE7: ??? (in /lib/libpthread-2.26.so)
==23871==    by 0x80A4632: main (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==  Address 0xfee12a68 is on thread 1's stack
==23871== 
==23871== 
==23871== Process terminating with default action of signal 6 (SIGABRT)
==23871==    at 0x47BE7BD: raise (in /lib/libc-2.26.so)
==23871==    by 0x47C01C1: abort (in /lib/libc-2.26.so)
==23871==    by 0x80AA61E: handleSignal(int, void*) (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871==    by 0x4057EE7: ??? (in /lib/libpthread-2.26.so)
==23871==    by 0x80A4632: main (in /home/savo/Downloads/mcpe-git/mcpelauncher-linux/mcpelauncher)
==23871== 
==23871== HEAP SUMMARY:
==23871==     in use at exit: 7,655,226 bytes in 34,111 blocks
==23871==   total heap usage: 41,899 allocs, 7,788 frees, 7,858,972 bytes allocated
==23871== 
==23871== LEAK SUMMARY:
==23871==    definitely lost: 0 bytes in 0 blocks
==23871==    indirectly lost: 0 bytes in 0 blocks
==23871==      possibly lost: 6,616,148 bytes in 3 blocks
==23871==    still reachable: 1,039,078 bytes in 34,108 blocks
==23871==                       of which reachable via heuristic:
==23871==                         stdstring          : 173,352 bytes in 7,106 blocks
==23871==                         newarray           : 32 bytes in 2 blocks
==23871==         suppressed: 0 bytes in 0 blocks
==23871== Rerun with --leak-check=full to see details of leaked memory
==23871== 
==23871== For counts of detected and suppressed errors, rerun with: -v
==23871== Use --track-origins=yes to see where uninitialised values come from
==23871== ERROR SUMMARY: 303848 errors from 6 contexts (suppressed: 0 from 0)`
