### ISSUE TITLE
Mac support?

### ISSUE THREAD

**Issue by ili-codes** [MCMrARM/mcpelauncher-linux#104]
I'm trying to launch MCPE on my MacBook Pro. Is there a way I can use MacPorts or Homebrew to install the required packages and it'll work?

**Comment by DaMatrix** [comment]
It's mcpelauncher-linux, not mcpelauncher-osx.

**Comment by ili-codes** [comment]
Well, I tried. :)

**Comment by DaMatrix** [comment]
@MCMrARM might do that, not sure if it's possible to get all the required libraries on osx though.

**Comment by mhsjlw** [comment]
Check it out here: https://github.com/mhsjlw/mcpelauncher-mac (it's work in progress, hope to have it merged back into mcpelauncher-linux)

See announcement here: https://twitter.com/MCMrARM/status/950113062912188417

Some screenshots:

![Titlescreen](https://i.imgur.com/mHKIRGb.png)

![Game](https://i.imgur.com/cRnJyHm.png)
