### ISSUE TITLE
How should i compile the foalder the make commanddoesn't work :(

### ISSUE THREAD

**Issue by FRISCOWZMCPE** [MCMrARM/mcpelauncher-linux#105]
Please if you can make a shell script to compile the laucnher do it

**Comment by DaMatrix** [comment]
Well send the error, "doesn't work" doesn't help us fix the issue.

**Comment by sliceofcode** [comment]
Follow the instructions in the README closely. Post us the error if it doesn't work.

**Comment by Tarik02** [comment]
cmake .

**Comment by MCMrARM** [comment]
Invalid issue. Please at least specify the exact build error if you want help.
