### ISSUE TITLE
MCPE 1.0.5 - Data are not saved.

### ISSUE THREAD

**Issue by KennFatt** [MCMrARM/mcpelauncher-linux#109]
- There was no skin. (only steve and alex, i didnt tried with custom skin).
- If we change our nickname, and restart or relaunch the app, our nickname will automatically back to 'Steve'
- Even we cant generate new world. It says ( "NewWorldName" cannot be opened ).

Maybe this bug related with storage feature? External and application options maybe affect it.

**Comment by DaMatrix** [comment]
Never had this issue before, all my stuff saves fine.

**Comment by KennFatt** [comment]
@DaMatrix sure on 1.0.5?

**Comment by DaMatrix** [comment]
I've been using this since 0.15.2 and never had any similar issue.

**Comment by DaMatrix** [comment]
I'm on 1.0.5 now.

**Comment by KennFatt** [comment]
me too, i just had this issue on 1.0.5 :(

**Comment by KennFatt** [comment]
![screenshot from 2017-03-21 21-40-36](https://cloud.githubusercontent.com/assets/10755895/24152677/ec02a3c0-0e7e-11e7-9c4c-d1d91f9d8356.png)

**Comment by InusualZ** [comment]
My your system it have an permission issue. Try to `chmod` the executable

**Comment by KennFatt** [comment]
@InusualZ thanks to notice me, i was install as root, and run as user :(
