### ISSUE TITLE
Make fails, after cmake has run succesfully

### ISSUE THREAD

**Issue by phunni** [MCMrARM/mcpelauncher-linux#11]
Error message is as follows:

`$ make` <br/>
`[  5%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/cache.c.o
make[2]: gcc-4.9: Command not found
CMakeFiles/mcpelauncher.dir/build.make:62: recipe for target 'CMakeFiles/mcpelauncher.dir/hybris/src/cache.c.o' failed
make[2]: *** [CMakeFiles/mcpelauncher.dir/hybris/src/cache.c.o] Error 127
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mcpelauncher.dir/all' failed
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2`

gcc version 5.2.0 is installed and `cmake .` has run succesfully.

**Comment by sliceofcode** [comment]
`gcc-4.9: Command not found`
Odd. Try installing `build-essential`.

**Comment by MCMrARM** [comment]
You should try removing those two lines: https://github.com/MCMrARM/mcpelauncher-linux/blob/master/CMakeLists.txt#L4 related to gcc and g++ 4.9

**Comment by phunni** [comment]
That worked - it now compiles and fails with:

failed to load library libgnustl_shared.so: Cannot load library: load_library[1109]: Library '/opt/git/mcpelauncher-linux/libs/libgnustl_shared.so' not found

**Comment by sliceofcode** [comment]
You need to extract the MC:PE APK in order for it to work.
