### ISSUE TITLE
Launcher won't start

### ISSUE THREAD

**Issue by EpicSteve33** [MCMrARM/mcpelauncher-linux#110]
Yesterday I was able to run the launcher just fine

I would do `./extract.sh mcpe.apk` and I would run the launcher, everything started up just fine

today I did the same thing and when trying to open the launcher it would not open at all

I would `execute in terminal ` after clicking the launcher and nothing happens 
![screenshot from 2017-03-21 01 48 33](https://cloud.githubusercontent.com/assets/12077835/24175748/2647fe42-0e55-11e7-936e-effb5826ec05.png)

I ran the `./extract.sh mcpe.apk` command many times to check if something went wrong I got no errors, even tried running different versions like 1.0.4 and 1.0.5 and neither would start up, I even recompiled the launcher and it still would not start

any idea why this is happening 

Linux: Elementary OS Loki
MCPE: 1.0.4.11 and 1.0.5.13
mcpelauncher: Latest commit c3c2c27

**Comment by DaMatrix** [comment]
Use./mcpelauncher, not double-click.

**Comment by EpicSteve33** [comment]
epicsteve33@epicsteve33-MacBook:~/mcpe-lunix$ ./mcpelauncher
loading native libraries
oslib: libGLESv2.so: 155160192
failed to load library /home/epicsteve33/mcpe-lunix/libs/native/libfmod.so.8.2: /home/epicsteve33/mcpe-lunix/libs/native/libfmod.so.8.2: cannot open shared object file: No such file or directory

**Comment by EpicSteve33** [comment]
I do not understand what happend yesterday I was able to play just fine ;-;

**Comment by EpicSteve33** [comment]
@DaMatrix any idea how I could fix this?

**Comment by EpicSteve33** [comment]
I fixed this issue XD
