### ISSUE TITLE
on newer versions i get prompted to buy the game, most settings aren't avalible, multiplayer isn't avalible

### ISSUE THREAD

**Issue by DaMatrix** [MCMrARM/mcpelauncher-linux#111]
title.

**Comment by EpicSteve33** [comment]
I only have this problem on older versions, like 1.0.4 but 1.0.5.13 works just fine for me

**Comment by DaMatrix** [comment]
I can say that 1.0.3 5 commits back from the current state doesn't have this, but 1.0.3 after a git pull does.

**Comment by MCMrARM** [comment]
1.0.3 is not supported (whatever's in master should support the latest release build only). Why stick to an older minor version?

**Comment by EpicSteve33** [comment]
I think the problem is if you use a version that's not supported by the current build like an older or newer version it will say that you need to buy the game

**Comment by DaMatrix** [comment]
What I'm trying to say is that this only happens in newer builds, older versions don't have it. I've only been able this on 1.0.4 (haven't tried 1.0.5 yet) and not on any version below that.

**Comment by guppy42** [comment]
In issue #116 this was caused by a bad apk - have you tried downloading again ?

But as only the current version of MCPE is supported I think this issue should be closed.

**Comment by EpicSteve33** [comment]
Yes it was caused by a bad apk
