### ISSUE TITLE
Graphic issue on intel

### ISSUE THREAD

**Issue by KennFatt** [MCMrARM/mcpelauncher-linux#112]
I never had this problem before, and i dont know whats going on.
you can see this pictures : 

![screenshot from 2017-04-02 19-45-39](https://cloud.githubusercontent.com/assets/10755895/24587510/3814ecfc-17e2-11e7-852e-b544f9333f49.png)
![screenshot from 2017-04-02 19-45-27](https://cloud.githubusercontent.com/assets/10755895/24587512/381bbd2a-17e2-11e7-96da-672e6274d71c.png)
![screenshot from 2017-04-02 19-42-28](https://cloud.githubusercontent.com/assets/10755895/24587511/3815ba4c-17e2-11e7-8e96-a48a9cebe45d.png)

**Comment by DaMatrix** [comment]
I am unable to reproduce. What were you doing?

**Comment by InusualZ** [comment]
You have the correct GPU Drivers? They may cause issue

**Comment by KennFatt** [comment]
@DaMatrix i even dont know... @InusualZ yes i have, its normal when i play minecraft desktop or others games with intel, and why i cant launch this app using nvidia driver?

**Comment by KennFatt** [comment]
This problem still happen, i have older version of launcher (and older mcpe version) and everything its normal, it just happen with latest version of launcher and mcpe 1.0.5.

**Comment by kris27mc** [comment]
Can you try it with the latest launcher, and possibly a newer version of MCPE?

**Comment by KennFatt** [comment]
@kris27mc sadly, i moved on to Windows 10 already. I might close this issue for a while.
