### ISSUE TITLE
Error when make

### ISSUE THREAD

**Issue by vzlomka76** [MCMrARM/mcpelauncher-linux#113]
![2017-04-03 21 31 39](https://cloud.githubusercontent.com/assets/16573760/24624564/f23a2340-18b4-11e7-9898-ef044c7fcb8b.png)
`...
[ 71%] Building C object CMakeFiles/mcpelauncher.dir/eglut/eglut_x11.c.o
[ 76%] Building CXX object CMakeFiles/mcpelauncher.dir/src/main.cpp.o
/home/anton/Рабочий стол/MinecraftPE/src/main.cpp:9:19: fatal error: codecvt: Нет такого файла или каталога
 #include <codecvt>
                   ^
compilation terminated.
make[2]: *** [CMakeFiles/mcpelauncher.dir/src/main.cpp.o] Ошибка 1
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Ошибка 2
make: *** [all] Ошибка 2
anton@AntonNotebook:~/Рабочий стол/MinecraftPE$ make
[  4%] Building CXX object CMakeFiles/mcpelauncher.dir/src/main.cpp.o
/home/anton/Рабочий стол/MinecraftPE/src/main.cpp:9:19: fatal error: codecvt: Нет такого файла или каталога
 #include <codecvt>
                   ^
compilation terminated.
make[2]: *** [CMakeFiles/mcpelauncher.dir/src/main.cpp.o] Ошибка 1
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Ошибка 2
make: *** [all] Ошибка 2
anton@AntonNotebook:~/Рабочий стол/MinecraftPE$ 
`

Core: Intel core i5 7200U
Graphic: Amd radeon m445
System: Ubuntu 14.04 LTS

`cmake .` was successfull

**Comment by kukulo2011** [comment]
Install the correct gcc version with codecvt support, then make:

$sudo add-apt-repository ppa:ubuntu-toolchain-r/test
$sudo apt-get update
$sudo apt-get install g++-5
$sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 1
$sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 1
$cd mcpelauncher-linux/
$cmake .
$make

**Comment by Thecraftdu34** [comment]
I've follow your instructions and that don't work !

**Comment by kukulo2011** [comment]
Did you updated the alternatives after installing the latest g++ and gcc?
What is your error message?

**Comment by vzlomka76** [comment]
i installed ubuntu 16.04 and I no longer see this error
