### ISSUE TITLE
eurro when make 

### ISSUE THREAD

**Issue by Thecraftdu34** [MCMrARM/mcpelauncher-linux#115]
[ 95%] Building CXX object CMakeFiles/mcpelauncher.dir/mcpe/types.cpp.o
[100%] Linking CXX executable mcpelauncher
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o : Dans la fonction « my_pthread_attr_getstackaddr » :
hooks.c:(.text+0x3f8): avertissement : the use of `pthread_attr_getstackaddr' is deprecated, use `pthread_attr_getstack'
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o : Dans la fonction « my_pthread_attr_setstackaddr » :
hooks.c:(.text+0x3d7): avertissement : the use of `pthread_attr_setstackaddr' is deprecated, use `pthread_attr_setstack'
/usr/bin/ld : ne peut trouver -lEGL
/usr/bin/ld : ne peut trouver -lGLESv2
collect2: error: ld returned 1 exit status
CMakeFiles/mcpelauncher.dir/build.make:607 : la recette pour la cible « mcpelauncher » a échouée
make[2]: *** [mcpelauncher] Erreur 1
CMakeFiles/Makefile2:67 : la recette pour la cible « CMakeFiles/mcpelauncher.dir/all » a échouée
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Erreur 2
Makefile:83 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

**Comment by vzlomka76** [comment]
https://github.com/MCMrARM/mcpelauncher-linux/issues/61
https://github.com/MCMrARM/mcpelauncher-linux/issues/101
