### ISSUE TITLE
1.0.6 support?

### ISSUE THREAD

**Issue by EpicSteve33** [MCMrARM/mcpelauncher-linux#116]
Is this going to be updated for 1.0.6?

**Comment by DaMatrix** [comment]
It actually takes TIME to update things, and since there's nobody other than MCMrARM working on it there's even more TIME involved. Don't expect everything to work just because something else does.

**Comment by EpicSteve33** [comment]
I am aware it takes time, I was just hoping this could get updated because I cannot play mcpe on my pc 1.0.6 does not allow me to play multiplayer it wants me to buy the game which is annoying because I use my pc for almost everything including mcpe lol

**Comment by guppy42** [comment]
This issue should be closed, 1.0.6 is working after all.

**Comment by EpicSteve33** [comment]
Not for me, The game loads up yes but It asks me to buy the game it is not full game

**Comment by guppy42** [comment]
Have your concidered that your APK is borked
try to md5sum your apk - assuming they don't water mark them it should be;
5cd98633554cacc90d8ce6f865d34d29  com.mojang.minecraftpe 872000652.apk

**Comment by guppy42** [comment]
Also 1.0.7 is out now ;^)

**Comment by EpicSteve33** [comment]
@guppy42 Thank you, I redownloaded my apk and now it works, I think something was wrong with my old one
