### ISSUE TITLE
1.1 Crashes

### ISSUE THREAD

**Issue by guppy42** [MCMrARM/mcpelauncher-linux#118]
```
1.1_beta $ ./mcpelauncher 
loading native libraries
oslib: libGLESv2.so: 161584624
oslib: /home/morten/source/1.1_beta/libs/native/libfmod.so.8.2: 161585728
loading hybris libraries
loading MCPE
loaded MCPE (at 4092858368)
apply patches
original: 85 83 87 86 131
post patch: 233 87 211 70 19
original: 85 83 87 86 131
post patch: 233 237 161 71 19
original: 85 83 87 86 129
post patch: 233 71 159 71 19
original: 83 87 86 131 236
post patch: 233 245 159 71 19
original: 83 131 236 8 232
post patch: 233 113 71 229 17
original: 83 87 86 131 236
post patch: 233 127 78 229 17
original: 85 83 87 86 131
post patch: 233 177 174 217 17
original: 83 87 86 131 236
post patch: 233 115 147 5 18
original: 83 131 236 8 232
post patch: 233 117 134 5 18
original: 83 131 236 8 232
post patch: 233 133 133 5 18
original: 83 86 131 236 20
post patch: 233 131 168 57 19
patches applied!
init app platform vtable
AppPlatform size = 142
init app platform
app platform initialized
init window
EGL_VERSION = 1.4
fetch patch notes
create minecraft client
Signal 11 received
Backtrace elements: 2
#0 ./mcpelauncher(_Z12handleSignaliPv+0x62) [0x806ce5f]
#1 [0xf7747bc0]
Dumping stack...
#366 HYBRIS (null)+0 in libminecraftpe.so+0x2ec8a5c [0xf6e09a5c]
#368 HYBRIS mce::Platform::OGL::GetProcAddress(char const*)+49 in libminecraftpe.so+0x15eca61 [0xf552da61]
#466 HYBRIS (null)+1 in libminecraftpe.so+0x2ec8d01 [0xf6e09d01]
#529 HYBRIS PatchNotesModel::preloadPatchNotes()+0 in libminecraftpe.so+0xd8d2a0 [0xf4cce2a0]
#530 HYBRIS crossplat::JVM+0 in libminecraftpe.so+0x2ebfca0 [0xf6e00ca0]
Signal 6 received
Aborted

```

**Comment by guppy42** [comment]
(gdb) info symbol 0xf7747bc0
No symbol matches 0xf7747bc0.

Near as I can tell ( going though *all* off "info functions ) the only thing that is even close is FMODs functions [0xf77fb090-0xf78d9cc0].

but it seems the backtrace that mcpelauncher print's is not entirely accurate;
![ddd output](http://i.imgur.com/uP3PLYI.png)
#5 is where it crashes #4-#0 is after it's passed to the launchers crashe printer.

so it looks like it's attempts to call a function that is a null pointer ( or am I reading that wrong ? )

**Comment by guppy42** [comment]
Had a bit of a brain wave; seems the function names have changed;
```
 $ nm mcpelauncher | grep MinecraftClient
08082bf8 B _ZN15MinecraftClient22MinecraftClient_updateE
08082bfc B _ZN15MinecraftClient25MinecraftClient_constructE
08082bec B _ZN15MinecraftClient26MinecraftClient_getOptionsE
08082bf4 B _ZN15MinecraftClient32MinecraftClient_setRenderingSizeE
08082bf0 B _ZN15MinecraftClient33MinecraftClient_setUISizeAndScaleE
```
after changing the hybris_dlsym for MinecraftClient::xxx I now I get to crash in a new and exciting place - so progress \o/

time to dig though the rest of the code and see what other functions changed

**Comment by guppy42** [comment]
1.1.beta $ nm -D libs/libminecraftpe.so | grep -i MinecraftClient
yields no results
where as 
/1.0.7 $ nm -D libs/libminecraftpe.so | grep -i MinecraftClient
yeilds a ton - amongst them;
[....]
0129e1b0 T _ZN15MinecraftClientC2EiPPc
[....]


So that's the error - guess there is no longer a 'MinecraftClient' class in mcpe?

**Comment by guppy42** [comment]
victory \o/

Made it work for beta 1.1.0.4, made a pull request.

defeat /o\
apparently 1.1.0.9 is the latest version will download that tomorrow - need some z's

**Comment by MCMrARM** [comment]
Check out the 1.1 branch.

**Comment by guppy42** [comment]
You missed one;
In main.cpp@362 (workaroundAMD)
"_ZN21BlockTessallatorCache5resetER11BlockSourceRK8BlockPos" is renamed "_ZN21BlockTessellatorCache5resetER11BlockSourceRK8BlockPos"

Other than that it seems to work you even fixed the crash I had when generating the world list.

I've a few questions and there isn't really and place I can think of to ask them other than here, so;

I get this in output:
> __bionic_open_tzdata_path: ANDROID_DATA not set!
> __bionic_open_tzdata_path: ANDROID_ROOT not set!

Is that something that can be ignored?


Also while trying to automate the process of figuring out what broke - I got this list of functions they is being remapped and no longer exists;

- _ZN12StoreFactory11createStoreER13StoreListener
- _ZN19AppPlatform_android11getDeviceIdEv
- _ZN4FMOD12ChannelGroup8addGroupEPS0_bPPNS_13DSPConnectionE
- _ZN4FMOD14ChannelControl11getDSPClockEPyS1_
- _ZN4FMOD14ChannelControl12addFadePointEyf
- _ZN4FMOD14ChannelControl15set3DAttributesEPK11FMOD_VECTORS3_S3_
- _ZN4FMOD14ChannelControl4stopEv
- _ZN4FMOD14ChannelControl7setMuteEb
- _ZN4FMOD14ChannelControl8setDelayEyyb
- _ZN4FMOD14ChannelControl8setPitchEf
- _ZN4FMOD14ChannelControl9isPlayingEPb
- _ZN4FMOD14ChannelControl9setPausedEb
- _ZN4FMOD14ChannelControl9setVolumeEf
- _ZN4FMOD5Sound11getSubSoundEiPPS0_
- _ZN4FMOD5Sound15getNumSubSoundsEPi
- _ZN4FMOD5Sound19set3DMinMaxDistanceEff
- _ZN4FMOD5Sound7releaseEv
- _ZN4FMOD5Sound7setModeEj
- _ZN4FMOD5Sound9getFormatEP15FMOD_SOUND_TYPEP17FMOD_SOUND_FORMATPiS5_
- _ZN4FMOD6System10getVersionEPj
- _ZN4FMOD6System11createSoundEPKcjP22FMOD_CREATESOUNDEXINFOPPNS_5SoundE
- _ZN4FMOD6System11mixerResumeEv
- _ZN4FMOD6System12createStreamEPKcjP22FMOD_CREATESOUNDEXINFOPPNS_5SoundE
- _ZN4FMOD6System12mixerSuspendEv
- _ZN4FMOD6System13getDriverInfoEiPciP9FMOD_GUIDPiP16FMOD_SPEAKERMODES4_
- _ZN4FMOD6System13getNumDriversEPi
- _ZN4FMOD6System13set3DSettingsEfff
- _ZN4FMOD6System17getSoftwareFormatEPiP16FMOD_SPEAKERMODES1_
- _ZN4FMOD6System18createChannelGroupEPKcPPNS_12ChannelGroupE
- _ZN4FMOD6System21getMasterChannelGroupEPPNS_12ChannelGroupE
- _ZN4FMOD6System23set3DListenerAttributesEiPK11FMOD_VECTORS3_S3_S3_
- _ZN4FMOD6System4initEijPv
- _ZN4FMOD6System5closeEv
- _ZN4FMOD6System6updateEv
- _ZN4FMOD6System7releaseEv
- _ZN4FMOD6System9playSoundEPNS_5SoundEPNS_12ChannelGroupEbPPNS_7ChannelE
- _ZN4FMOD6System9setDriverEi
- _ZN4FMOD6System9setOutputE15FMOD_OUT

Should I worry about remapping them or is it for backwards compateblility?
eg I'm 90% sure

_ZN19AppPlatform_android11getDeviceIdEv is now _ZN11AppPlatform11getDeviceIdEv

and _ZN12StoreFactory11createStoreER13StoreListener is _ZN12StoreFactory12createStoresER23StoreListenerMultistoreP25OculusPlatformMessagePump ( seemingly adding support for an occulus store )

**Comment by MCMrARM** [comment]
Those functions are simply not used anymore, I left there because I never really checked them for removal, also because it doesn't really matter.
Those warnings generated by bionic aren't really harmful, those only mean that there can possibly be issues with date/time.
getDeviceId is not needed, you only need to implement createDeviceId, I think I may delete getDeviceId altogether.
That createStore symbol reference is commented out anyways, I may remove the comment some time later.
