### ISSUE TITLE
Can i install mcpelauncher-linux on Fedora 25?

### ISSUE THREAD

**Issue by vzlomka76** [MCMrARM/mcpelauncher-linux#124]
Can i install mcpelauncher-linux on Fedora 25?
I can not find the necessary packages, can anyone know where to get the necessary packages?

**Comment by MCMrARM** [comment]
Yep it is possible, I did it some time ago. I don't remember now what packages you need but I guess a bit of googling and you should find the alternatives (you for sure will need a 32-bit gcc to start with, and then figure out all the other packages by cmake or build errors).

**Comment by TjeuKayim** [comment]
Hello,
I want to install this also on Fedora. Did you succeed @vzlomka76? Do you have any tips?

**Comment by kris27mc** [comment]
@vzlomka76 Can you test the aforementioned solution, and close the issue if this solves your problem?

**Comment by vzlomka76** [comment]
@kris27mc I don't have Fedora now, I use ubuntu 16.04 without problems
