### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by stormchaser3000** [MCMrARM/mcpelauncher-linux#126]
operating system: arch linux

loading native libraries
oslib: libGLESv2.so: -143082072
oslib: /home/stormchaser3000/mcpelauncher-linux/libs/native/libfmod.so.8.2: 147199880
loading hybris libraries
loading MCPE
loaded MCPE (at 4096983040)
apply patches
original: 85 83 87 86 131
post patch: 233 145 140 41 18
original: 85 83 87 86 131
post patch: 233 183 36 42 18
original: 85 83 87 86 129
post patch: 233 17 34 42 18
original: 83 87 86 131 236
post patch: 233 191 34 42 18
original: 83 131 236 8 232
post patch: 233 255 57 230 17
original: 83 87 86 131 236
post patch: 233 13 65 230 17
original: 85 83 87 86 131
post patch: 233 63 161 218 17
original: 83 87 86 131 236
post patch: 233 1 134 6 18
original: 83 131 236 8 232
post patch: 233 3 121 6 18
original: 83 131 236 8 232
post patch: 233 19 120 6 18
original: 83 86 131 236 20
post patch: 233 193 89 117 18
patches applied!
init app platform vtable
AppPlatform size = 137
init app platform
app platform initialized
init window
EGL_VERSION = 1.5 (DRI2)
create minecraft client
current storage path = data/current/
userdata path = data/user/
fetch patch notes
userdata path = data/user/
init minecraft client
userdata path = data/user/
userdata path = data/user/
pure virtual method called
terminate called without an active exception
Signal 6 received
Backtrace elements: 10
#0 ./mcpelauncher(_Z12handleSignaliPv+0x4b) [0x806adfd]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf778fca0]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf778fc89]
#3 /usr/lib32/libc.so.6(gsignal+0xc2) [0xf722b562]
#4 /usr/lib32/libc.so.6(abort+0x167) [0xf722cd37]
#5 HYBRIS __gnu_cxx::__verbose_terminate_handler()+469 in libminecraftpe.so+0x2228035 [0xf6558035]
#6 HYBRIS __cxxabiv1::__terminate(void (*)())+25 in libminecraftpe.so+0x21ca389 [0xf64fa389]
#7 HYBRIS __cxxabiv1::__unexpected(void (*)())+0 in libminecraftpe.so+0x21ca420 [0xf64fa420]
#8 HYBRIS (null)+-162550493 in libminecraftpe.so+0x21cad23 [0xf64fad23]
#9 [0x18]
Dumping stack...
#658 HYBRIS __gnu_cxx::__verbose_terminate_handler()+469 in libminecraftpe.so+0x2228035 [0xf6558035]
#673 HYBRIS __gnu_cxx::__verbose_terminate_handler()+11 in libminecraftpe.so+0x2227e6b [0xf6557e6b]
#678 HYBRIS __cxxabiv1::__terminate(void (*)())+25 in libminecraftpe.so+0x21ca389 [0xf64fa389]
#685 HYBRIS __cxxabiv1::__terminate(void (*)())+11 in libminecraftpe.so+0x21ca37b [0xf64fa37b]
#690 HYBRIS __cxxabiv1::__unexpected(void (*)())+0 in libminecraftpe.so+0x21ca420 [0xf64fa420]
#691 HYBRIS __gnu_cxx::__verbose_terminate_handler()+0 in libminecraftpe.so+0x2227e60 [0xf6557e60]
#694 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x21caaa7 [0xf64faaa7]
#695 HYBRIS std::terminate()+9 in libminecraftpe.so+0x21ca409 [0xf64fa409]
#704 HYBRIS (null)+6 in libminecraftpe.so+0x21cacf6 [0xf64facf6]
#706 HYBRIS AppPlatform::getDeviceId()+59 in libminecraftpe.so+0xc2235b [0xf4f5235b]
#718 HYBRIS Social::Events::EventManager::setupCommonProperties()+575 in libminecraftpe.so+0x19c901f [0xf5cf901f]
#786 HYBRIS operator new(unsigned int)+132 in libminecraftpe.so+0x21cab04 [0xf64fab04]
#794 HYBRIS Social::Events::EventManager::EventManager()+276 in libminecraftpe.so+0x19c8d04 [0xf5cf8d04]
#798 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x21caaa7 [0xf64faaa7]
#806 HYBRIS MinecraftEventing::MinecraftEventing(Social::UserManager*, std::string const&)+263 in libminecraftpe.so+0xad1387 [0xf4e01387]
#810 HYBRIS operator delete(void*)+28 in libminecraftpe.so+0x21c87dc [0xf64f87dc]
#826 HYBRIS std::_MakeUniq<Social::ImageService>::__single_object std::make_unique<Social::ImageService, Social::UserManager&, char const (&) [17], bool>(Social::UserManager&, char const (&) [17], bool&&)+175 in libminecraftpe.so+0x1a0a0ff [0xf5d3a0ff]
#866 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x21caaa7 [0xf64faaa7]
#868 HYBRIS AppPlatform::SETTINGS_PATH+0 in libminecraftpe.so+0x2a73454 [0xf6da3454]
#874 HYBRIS MinecraftClient::init()+409 in libminecraftpe.so+0x12a92e9 [0xf55d92e9]
Signal 6 received
Aborted (core dumped)

**Comment by guppy42** [comment]
What mcpe version? If it's a beta then please use the 1.1 branch of the source

**Comment by stormchaser3000** [comment]
i don't think i am using beta. i checked out the 1.1 branch and compilied the 1.1 branch and it still didn't work.
`[stormchaser3000@stormchaser3000-archlinux mcpelauncher-linux]$ ./mcpelauncher 
loading native libraries
oslib: libGLESv2.so: -143401560
oslib: /home/stormchaser3000/mcpelauncher-linux/libs/native/libfmod.so.8.2: 164427864
loading hybris libraries
loading MCPE
loaded MCPE (at 4096663552)
apply patches
original: 85 83 87 86 131
post patch: 233 193 108 46 18
original: 85 83 87 86 131
post patch: 233 231 4 47 18
original: 85 83 87 86 129
post patch: 233 65 2 47 18
original: 83 87 86 131 236
post patch: 233 239 2 47 18
original: 83 131 236 8 232
post patch: 233 47 26 235 17
original: 83 87 86 131 236
post patch: 233 61 33 235 17
original: 85 83 87 86 131
post patch: 233 111 129 223 17
original: 83 87 86 131 236
post patch: 233 49 102 11 18
original: 83 131 236 8 232
post patch: 233 51 89 11 18
original: 83 131 236 8 232
post patch: 233 67 88 11 18
original: 83 86 131 236 20
post patch: 233 241 57 122 18
patches applied!
init app platform vtable
AppPlatform size = 137
init app platform
app platform initialized
init window
EGL_VERSION = 1.5 (DRI2)
fetch patch notes
create minecraft client
Signal 11 received
Backtrace elements: 2
#0 ./mcpelauncher(_Z12handleSignaliPv+0x4b) [0x806ae45]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7741ca0]
Dumping stack...
#422 HYBRIS (null)+0 in libminecraftpe.so+0x2b31884 [0xf6e13884]
#423 HYBRIS (null)+0 in libminecraftpe.so+0x2b31888 [0xf6e13888]
#424 HYBRIS (null)+0 in libminecraftpe.so+0x2b3188c [0xf6e1388c]
#434 HYBRIS (null)+0 in libminecraftpe.so+0x2b318f0 [0xf6e138f0]
#435 HYBRIS (null)+0 in libminecraftpe.so+0x2b318fc [0xf6e138fc]
#436 HYBRIS (null)+0 in libminecraftpe.so+0x2b31930 [0xf6e13930]
#439 HYBRIS (null)+0 in libminecraftpe.so+0x2b31944 [0xf6e13944]
#440 HYBRIS (null)+0 in libminecraftpe.so+0x2b31938 [0xf6e13938]
#450 HYBRIS (null)+0 in libminecraftpe.so+0x2b319a4 [0xf6e139a4]
#484 HYBRIS (null)+1 in libminecraftpe.so+0x2b31b01 [0xf6e13b01]
#574 HYBRIS crossplat::JVM+0 in libminecraftpe.so+0x2b236b8 [0xf6e056b8]
#575 HYBRIS PatchNotesModel::preloadPatchNotes()+0 in libminecraftpe.so+0x15e1470 [0xf58c3470]
Signal 6 received
Aborted (core dumped)
`

**Comment by MCMrARM** [comment]
I'm closing this as this is basically the same as #128 and it's easier for me to manage that issue instead of this one (the crash is in the first message, not in the third).
