### ISSUE TITLE
caution: filename not matched:  lib/x86/libminecraftpe.so

### ISSUE THREAD

**Issue by Sam371254** [MCMrARM/mcpelauncher-linux#129]
caution: filename not matched:  lib/x86/libminecraftpe.so

This happens after doing ./extract.sh on the APK. It is a legitimate version of MCPE, extracted directly from my phone.

**Comment by guppy42** [comment]
Chances are that your phone is not an x86 but rather an ARM, just use the new playstore downloader

**Comment by Sam371254** [comment]
@guppy42 I think you're right. I did some looking and it turns out my phone is an ARM. I've tried to download it in the terminal but I'm not very skilled with Ubuntu at the moment and there's nowhere on the web that I can find an untampered with 1.1.0.9 x86 version of the MCPE apk.

**Comment by guppy42** [comment]
It's not that hard

1) make sure you entered beta via your phone ( you don't have to update your phone, but it needs to say that you are in the beta programme )
2) clone the Goole-Play-API 
3) follow the instructions here;
https://github.com/MCMrARM/Google-Play-API/issues/5#issuecomment-270753883
4) install the dependencies that cmake complains about ( libcurl, libprotobuf )
5) run it and feed it the with your info ( package is com.mojang.minecraftpe )

Alternatively trust a complete stranger to have built it for you;
https://wetransfer.com/downloads/ce6945d75ce8a50be289b20a47189a1620170601072451/f1a524fb7b2c2364f07768cf7715bb9f20170601072451/44535f
( link is only valid for 7 days )

It was built on LMDE2, which is a debian variant so no guarantee it will actually work for you
