### ISSUE TITLE
Error while extracting from apk

### ISSUE THREAD

**Issue by stayandwait** [MCMrARM/mcpelauncher-linux#13]
inflating: assets/ui/furnace_screen.json  
  inflating: assets/ui/gamepad_layout_screen.json  
  inflating: assets/ui/inventory_screen.json  
  inflating: assets/ui/language_choice_screen.json  
  inflating: assets/ui/pause_screen_trial.json  
  inflating: assets/ui/play_screen.json  
  inflating: assets/ui/start_screen.json  
  inflating: assets/ui/test_anims_screen.json  
  inflating: assets/ui/trial_upsell_screen.json  
  inflating: assets/ui/ui_common.json  
  inflating: assets/ui/ui_common_classic.json  
  inflating: assets/ui/xbl_login_screen.json  
caution: filename not matched:  lib/x86/libminecraftpe.so
caution: filename not matched:  lib/x86/libgnustl_shared.so

How do i fix this?

**Comment by jamesguessis** [comment]
are you sure you got the x86 apk?

**Comment by stayandwait** [comment]
How do I do that? I got this apk from my android device using an app extractor from the MCPE app i had installed.

**Comment by jamesguessis** [comment]
Well, the instructions for running it gives a link to MrArm's Google play download tool :P

**Comment by stayandwait** [comment]
I did it using the command line google tool this time and it extracted perfectly! For some reason there is difference in architecture I guess that would make sense.

Yay! http://screencast.com/t/ZGKbgmeUqexO

**Comment by EpicSteve33** [comment]
hey stay and wait can you give me a link to your apk i dont have a paid mc version on google

**Comment by MCMrARM** [comment]
Audio should just work, it uses fmod, check system settings maybe? It works fine for me.

**Comment by EpicSteve33** [comment]
Can someone please give me a mcpe apk that will work with it

**Comment by jamesguessis** [comment]
No, you need to acquire the apk yourself.

**Comment by EpicSteve33** [comment]
I dont have money to buy MCPE

**Comment by stayandwait** [comment]
How can i check if fmod is installed? I get audio when playing videos in linux i just dont get audio from mcpe launcher.

**Comment by stayandwait** [comment]
Ok nevermind I fixed the problem. Is there anyway to make the buttons on the screen show up larger? they are really small!

**Comment by stayandwait** [comment]
Just to report a bug, the game crashes when you turn off Fancy Graphics.

**Comment by stayandwait** [comment]
and was wondering were would the MC worlds folder be?

**Comment by EpicSteve33** [comment]
I paid for mcpe how do I get the x86 apk
