### ISSUE TITLE
Most recommended distro??

### ISSUE THREAD

**Issue by tejasvi8874** [MCMrARM/mcpelauncher-linux#133]
What is the best suited distro(also 32/64 bit) according to the dependencies needed as I have messed my primary distro(mint) which has started to lag.
I've relatively weak specs: 
Ram:2GB
Graphics Card:Radeon 7300

**Comment by guppy42** [comment]
I personally use mint 18.1 ( cinnamon ) so I know that works.

Stick with what you know so any Ubuntu 16.04 variant would do

**Comment by tejasvi8874** [comment]
Is Ubuntu 16.0 based os necessary or any Ubuntu?
And a bit off-topic, did @guppy42 you noticed that I've added the links in my Issue post.

________________________________

**Comment by guppy42** [comment]
> Is Ubuntu 16.0 based os necessary or any Ubuntu?
Sorry I never replied to this.

You could use any version of Ubuntu - I just prefer to stay with the current LTS as it's more stable

**Comment by MCMrARM** [comment]
Overall, any OS will work with this with a bit of work (you need to figure out the dependencies). I have successfully ran this on Ubuntu, Fedora and Arch.

**Comment by kris27mc** [comment]
Added a section to the wiki for this (:

**Comment by tejasvi8874** [comment]
I'm amazed to see a lot of contribution in wiki. Thanks
