### ISSUE TITLE
Any easy way to update to new version?

### ISSUE THREAD

**Issue by tejasvi8874** [MCMrARM/mcpelauncher-linux#134]
Can I just replace assets folder to newer version?
Will it suffice to update as I noticed the version number does'nt change on startup screen after replacing?

**Comment by guppy42** [comment]
I believe you'd have to replace the lib/ folder as well -
to know for certain create a new folder and extract the new version there then do `diff -wbBqr folder1 folder2`

That will give you a ( very long ) list of all files that have been changed

**Comment by guppy42** [comment]
The complete answer is now in the [wiki](https://github.com/MCMrARM/mcpelauncher-linux/wiki/Installation-guide#updating-to-a-new-version-of-minecraft)

**Comment by tejasvi8874** [comment]
Thanks for contribution in wiki. Glad to see project flourish. :)

**Comment by guppy42** [comment]
No worries - the link is dead now tho, somebody kindly split my monolithic piece into smaller pieces the new link is https://github.com/MCMrARM/mcpelauncher-linux/wiki/Updating-Minecraft
