### ISSUE TITLE
core dumped on launch

### ISSUE THREAD

**Issue by mijk84** [MCMrARM/mcpelauncher-linux#136]
$ ./mcpelauncher 
loading native libraries
oslib: libGLESv2.so: 162549376
oslib: /home/mike/build/mcpelauncher-linux/libs/native/libfmod.so.8.2: 162551368
loading hybris libraries
loading MCPE
loaded MCPE (at 4091850752)
apply patches
original: 85 83 87 86 131
post patch: 233 135 129 85 19
original: 85 83 87 86 131
post patch: 233 93 79 86 19
original: 85 83 87 86 129
post patch: 233 183 76 86 19
original: 83 87 86 131 236
post patch: 233 101 77 86 19
original: 83 131 236 8 232
post patch: 233 113 124 237 17
original: 83 87 86 131 236
post patch: 233 127 131 237 17
original: 85 83 87 86 131
post patch: 233 81 237 225 17
original: 83 87 86 131 236
post patch: 233 195 196 13 18
original: 83 131 236 8 232
post patch: 233 197 183 13 18
original: 83 131 236 8 232
post patch: 233 213 182 13 18
original: 83 86 131 236 20
post patch: 233 131 235 71 19
patches applied!
init app platform vtable
AppPlatform size = 141
init app platform
app platform initialized
init window
EGL_VERSION = 1.4 (DRI2)
fetch patch notes
create minecraft client
Signal 11 received
Backtrace elements: 2
#0 ./mcpelauncher(_Z12handleSignaliPv+0x62) [0x806ce5f]
#1 [0xf7723ca0]
Dumping stack...
#370 HYBRIS (null)+0 in libminecraftpe.so+0x2f56e1c [0xf6da1e1c]
#372 HYBRIS mce::Platform::OGL::GetProcAddress(char const*)+49 in libminecraftpe.so+0x164e271 [0xf5499271]
#469 HYBRIS (null)+0 in libminecraftpe.so+0x2f57198 [0xf6da2198]
#470 HYBRIS (null)+1 in libminecraftpe.so+0x2f57101 [0xf6da2101]
#533 HYBRIS PatchNotesModel::preloadPatchNotes()+0 in libminecraftpe.so+0xd9efa0 [0xf4be9fa0]
#534 HYBRIS crossplat::JVM+0 in libminecraftpe.so+0x2f4e048 [0xf6d99048]
Signal 6 received
Aborted (core dumped)

> Build okay, no errors, downloaded the apk using the play downloader, but getting that error now when trying to launch.

**Comment by guppy42** [comment]
What version of Minecraft? (Alternatively the numbers of the APK)
What branch of the launcher source?
What gfx card?
What cpu?

**Comment by mijk84** [comment]
I don't know what version because it downlded a file with a date stamp in the filename. I have a Core i5-2500 and using a Intel Graphics HD.

**Comment by guppy42** [comment]
mijk84 it's not a time stamp that's the internal version numbering, eg. 1.1.2 looks like this "com.mojang.minecraftpe 872010250.apk"

Also it's kind of important that you use the 1.1 branch of the source

**Comment by mijk84** [comment]
Yes, that's the version I downloaded. My mistake, a quick glance gave me the impression it was a date stamp. I cloned whatever is on the main project page. Is that not the 1.1 branch?

**Comment by guppy42** [comment]
No yet no you need to `git checkout 1.1` to get the 1.1 branch

**Comment by guppy42** [comment]
Did you solve the issue?

**Comment by mijk84** [comment]
I did a git checkout 1.1 after doing a git clone, didn't seem to make a difference. I don't know if I missed a step

**Comment by guppy42** [comment]
hmm.. I build & rand it against mesa on a vagant box with no problem - so either you messed something up or it's something else in your system.

What distro are you using?

and could you try to follow the guide I'm creating [on the wiki](https://github.com/MCMrARM/mcpelauncher-linux/wiki/Installation-guide) and see if that makes a difference?
(grasping at straws I know :P)

**Comment by kris27mc** [comment]
Did you recompile the launcher after checking out 1.1? That's most likely the issue in my opinion.

**Comment by guppy42** [comment]
> Although, the 1.1 branch is no longer available

1.1 has been merged into the master branch and is now default

**Comment by kris27mc** [comment]
But that's what I'm saying... 1.1 worked fine for me. And the current master branch doesn't. Using the same compatibility libs and same hardware. And 1.1.3 instead of 1.1.2. 

_Sent from my LGE LG-LS777 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by guppy42** [comment]
1.1.2 still works fine with the master branch - 1.1.3 crashes, there is a separate issue on this

**Comment by kris27mc** [comment]
Thanks for clarifying (: 
I was under the impression it was more likely an issue with the launcher somewhere. I didn't think there would be enough of a change in 1.1.3 to warrant such an issue. I was dead wrong haha

_Sent from my LGE LG-LS777 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by mijk84** [comment]
It's now working, but I had to comment out the line searching for EGL in CMakeList.txt ...
