### ISSUE TITLE
Version 1.1.2.50 fails to launch

### ISSUE THREAD

**Issue by phodopus42** [MCMrARM/mcpelauncher-linux#137]
Original package: com.mojang.minecraftpe780140301.apk [I believe this is 1.1.2.50]
CPU: Ryzen 5 1600X
GPU: RX 570
Branch: 1.1 98ff219

Short summary:  Fails to launch because it's missing libgnustl_shared.so (not included in 1.1 AFAICT).  After extracting to libs and adding that for loading in main.cpp, a number of the patches then fail (missing symbols).

First problem:
loading native libraries
oslib: libGLESv2.so: -143630752
oslib: /home/matthew/development/build/mcpe/mcpelauncher-linux-1.1/libs/native/libfmod.so.8.2: 158611768
loading hybris libraries
loading MCPE
linker/home/matthew/development/build/mcpe/mcpelauncher-linux-1.1/hybris/src/jb/linker.c:1933| ERROR:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1109]: Library 'libgnustl_shared.so' not found)
linker/home/matthew/development/build/mcpe/mcpelauncher-linux-1.1/hybris/src/jb/linker.c:2010| ERROR: failed to link libminecraftpe.so
failed to load MCPE: Cannot load library: link_image[1933]:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1109]: Library 'libgnustl_shared.so' not found)

Second problem:
I had to disable the patches for:
- _ZN9crossplat10threadpool16detach_from_javaEPv
- _ZN9crossplat11get_jvm_envEv
- _ZN3web4http6client7details22verify_X509_cert_chainERKSt6vectorISsSaISsEERKSs
- _ZN4xbox8services20xbox_live_app_config24get_app_config_singletonEv
- _ZN4xbox8services20xbox_live_app_config11set_sandboxESs
- _ZN4xbox8services20xbox_live_app_config29set_title_telemetry_device_idERKSs
- _ZN15PatchNotesModel17preloadPatchNotesEv

Even so, I'm then getting the following:

loading native libraries
oslib: libGLESv2.so: -143733152
oslib: /home/matthew/development/build/mcpe/mcpelauncher-linux-1.1/libs/native/libfmod.so.8.2: 153774392
loading hybris libraries
loading gnustl
loading MCPE
loaded MCPE (at 4129124352)
apply patches
original: 85 87 86 83 232
post patch: 233 152 73 188 17
original: 85 87 86 83 232
post patch: 233 254 119 188 17
original: 85 137 229 87 86
post patch: 233 200 170 183 17
original: 87 86 83 232 136
post patch: 233 150 119 188 17
patches applied!
Signal 11 received
Backtrace elements: 5
#0 ./mcpelauncher(_Z12handleSignaliPv+0x4b) [0x806aeed]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf76f0ca0]
#2 ./mcpelauncher(main+0x14be) [0x8068462]
#3 /lib/libc.so.6(__libc_start_main+0xf6) [0xf71691c6]
#4 ./mcpelauncher() [0x805a521]
Dumping stack...
#498 HYBRIS HTTPRequestInternalAndroid::abort()+0 in libminecraftpe.so+0x2c8200 [0xf649f200]
Signal 6 received
Aborted (core dumped)

**Comment by guppy42** [comment]
Could you try and grab the missing lib from here https://www.sendspace.com/file/lcjehz
 
And see if it works without your source modifications

Since it's a gnu lib it should be ok to share it

**Comment by phodopus42** [comment]
Thanks for sending this through.

There's no libgnustl in there, so which lib did I need? Or just all of them
to replace what I have?

**Comment by guppy42** [comment]
The file contains everything apart from the libmine raft.so and the resources. If you are missing a .so file not there then your system is supposed to provide it. Did you install the dependencies?

**Comment by guppy42** [comment]
FYI:
com.mojang.minecraftpe 872000652.apk - 1.0.6
com.mojang.minecraftpe 872010055.apk - 1.1
com.mojang.minecraftpe 872010101.apk - 1.1.1 (beta)
com.mojang.minecraftpe 872010250.apk - 1.1.2
com.mojang.minecraftpe 872010301.apk - 1.1.3.1 (beta)

So maybe you just have the wrong version?

**Comment by phodopus42** [comment]
Yes, I may well have the wrong version - I used the Google Play Downloader
as linked in the readme.

I'll check again when I'm back home this evening.

Is there an easy way to tell from the APK what version it is?

Thanks.

**Comment by guppy42** [comment]
The readme unfortunately links to an outdated downloader ( for me it always download v 0.14  )
The new one is here https://github.com/MCMrARM/Google-Play-API

if you are on a Ubuntu 16.04 LTS derivative then you will need to either update cmake, or download and build it manually ( as shown here; https://github.com/MCMrARM/Google-Play-API/issues/5 )

**Comment by phodopus42** [comment]
Yes, the downloader must have downloaded a very old version - I have no idea how or why.

I used Android-x86 on a VM to get the APK, and that's working perfectly with the unchanged mcpelauncher source.

Thanks, and sorry for the confusion.

**Comment by guppy42** [comment]
No worries, it's actually not your fault - the README is horribly outdated in places.

I've tried to remidy it a bit by writing an [installation guide in the wiki](https://github.com/MCMrARM/mcpelauncher-linux/wiki/Installation-guide) - feel free to give feed back on that :)
