### ISSUE TITLE
Illegal hardware instruction?

### ISSUE THREAD

**Issue by kris27mc** [MCMrARM/mcpelauncher-linux#138]
`loading native libraries`
`oslib: libGLESv2.so: -143401560`
`oslib: /home/kris27mc/Programming/mcpelauncher-linux/libs/native/libfmod.so.8.2: 167614640`
`loading hybris libraries`
`loading MCPE`
`[1]    5643 illegal hardware instruction (core dumped)  ./mcpelauncher
`

Using the 1.1 branch, this is what I receive when trying to start the launcher.

**Comment by guppy42** [comment]
That's supprisingly early to crash are you sure the all is the x86 version?

**Comment by kris27mc** [comment]
I'm honestly not sure. I used the Google Play API tool from the same developer because the original Google Play Downloader won't function properly.

**Comment by guppy42** [comment]
You may be seeing the same error as #137 try downloading the file I linked in that bug report and add the missing lib to your lib/ folder

**Comment by kris27mc** [comment]
I got the same result. 

`loading native libraries`
`oslib: libGLESv2.so: 151848688`
`oslib: /home/kris27mc/Programming/mcpelauncher-linux/1.1-compiled/libs/native/libfmod.so.8.2: ``151850040`
`loading hybris libraries`
`loading MCPE`
`[1]    11745 illegal hardware instruction (core dumped)  ./mcpelauncher
`

**Comment by kris27mc** [comment]
I found the solution! I personally believe it would be helpful to add to the README, but the solution was to replace the libs with the ones found here: #94
