### ISSUE TITLE
 I can not close the XBOX window. Departure of the client when trying to close.

### ISSUE THREAD

**Issue by trollnuulnuul7** [MCMrARM/mcpelauncher-linux#143]
When you try to close, it crashes. In the options file (... / mcpe / data / user / option) the line: game_haschosennottosignintoxbl was initially set to 0, after the crash it is set to 1, and the client no longer runs at all. You have to manually set the value to 0.

![image](https://user-images.githubusercontent.com/17801891/27987271-6a7d1886-6413-11e7-8bce-944533de5fee.png)

**Comment by guppy42** [comment]
Please don't reference unrelated issues.

Secondly have you tried solving this issue by using the solution proposed by the wiki? https://github.com/MCMrARM/mcpelauncher-linux/wiki/Installation-guide#bypass-xbox-signin

**Comment by trollnuulnuul7** [comment]
@guppy42 But if I edit the option manually. Then the client will not start at all!

**Comment by trollnuulnuul7** [comment]
@guppy42  Heeelp pleas >-<

**Comment by thebigsmileXD** [comment]
Duplicate: #79

**Comment by trollnuulnuul7** [comment]
@thebigsmileXD 
Wait for fix?

**Comment by thebigsmileXD** [comment]
Yes

**Comment by MCMrARM** [comment]
Yep, duplicate.
