### ISSUE TITLE
Armhf 32 bit support?

### ISSUE THREAD

**Issue by TheForgottenKing** [MCMrARM/mcpelauncher-linux#149]
How can I make this run on an arm machine? Samsung Chromebook 2012 arm32

**Comment by MCMrARM** [comment]
Currently running thiis on ARM bit machines is not support.

**Comment by kris27mc** [comment]
I doubt this will help in _ANY_ way but... there is an [old project for Raspberry Pi](https://github.com/ryanterry131/mcpelauncher-pi), so if you have any coding knowledge, maybe you could study that and attempt something?

**Comment by MCMrARM** [comment]
Duplicate of #20.
