### ISSUE TITLE
Game shows black in the distance

### ISSUE THREAD

**Issue by stayandwait** [MCMrARM/mcpelauncher-linux#15]
How do i fix this?
http://screencast.com/t/LR9wxKbr

**Comment by stayandwait** [comment]
This issue can be closed. I believe the black in the distance was caused by me running linux in vmware instead of natively. I also did this on native linux and didn’t see black in the distance.

**Comment by sliceofcode** [comment]
Yes, just drag the window.

**Comment by stayandwait** [comment]
That didn't make the buttons bigger. The buttons are still small and the items in inventory are also still the size they were before I maximized the window.

**Comment by sliceofcode** [comment]
Yes, I think it's because MC:PE doesn't handle things like that.

**Comment by MCMrARM** [comment]
To change the button size you can change 2.f to the scale on this line:
https://github.com/MCMrARM/mcpelauncher-linux/blob/master/src/main.cpp#L181
There isn't any GUI option to change it, so that line is the only option for now. I might add one later.
