### ISSUE TITLE
/usr/bin/ld: cannot find -lEGL

### ISSUE THREAD

**Issue by Connor124** [MCMrARM/mcpelauncher-linux#151]
Although this may seem a very similar issue, I don't think it is.
When running `make` I get:
 `/usr/bin/ld: cannot find -lEGL`
`/usr/bin/ld: cannot find -lGLESv2`
OK, nothing different there, but when I try to fix it as detailed in the wiki the system tries to remove almost everything. My desktop, the x-server, bunch of libraries, and more. This is something to do with the 32bit libwayland not being compatible with the 64bit version. 

Is there any alternative to installing the Mesa GLES libraries?

I'm running KDE Neon (Ubuntu Xenial 16.04 with a PPA) with kernel 4.8.0-56 on an Intel Quad-Core x86_64 without dedicated graphics.

**Comment by guppy42** [comment]
You could always try building on a vagrant box

**Comment by Connor124** [comment]
I just gave up and moved back to pure Debian 9. KDE Neon and even Ubuntu aren't very good in my opinion.
