### ISSUE TITLE
How to install mods using the mod example??

### ISSUE THREAD

**Issue by xExoSk31x** [MCMrARM/mcpelauncher-linux#152]
i found a mod_example file in the files and i don't understand what the txt file is talking about

To compile this modification, use ndk-build in this directory. Then you should copy the output .so from libs/x86/ to the launcher's mods/ directory.

**Comment by MCMrARM** [comment]
Something along this:
`mkdir -p mods && cd mod-example && ndk-build && cp libs/x86/* ../mods/`
