### ISSUE TITLE
XBox auth

### ISSUE THREAD

**Issue by vzlomka76** [MCMrARM/mcpelauncher-linux#153]
In 1.2 Xbox Live Sign-In Required for Online Multiplayer
https://minecraft.net/en-us/article/minecraft-multiplayer-server-safety

mcpelauncher needs implementing this feature
Please implement it :)

**Comment by guppy42** [comment]
Super of #117

**Comment by guppy42** [comment]
Dupe* even

**Comment by vzlomka76** [comment]
@guppy42 oops, sorry :D

**Comment by kris27mc** [comment]
@vzlomka76 Close this issue please. 
## Thank you (:
