### ISSUE TITLE
1.2.0.2 beta support

### ISSUE THREAD

**Issue by MCMrARM** [MCMrARM/mcpelauncher-linux#154]
Crashes on launch.

**Comment by guppy42** [comment]
Given that '[Google-Play-API](https://github.com/MCMrARM/Google-Play-API)' isn't currently working how can I legally obtain an apk to try help fix this?

**Comment by ashkitten** [comment]
I used an android emulator to download the apk :)

**Comment by kris27mc** [comment]
@guppy42 I was going to use Android-x86 inside QEMU but I still can't get it to boot properly on my hardware, even inside a VM. I've only ever had this problem since one of the 4.4 versions. But this may be a plausible solution for you

**Comment by MCMrARM** [comment]
@guppy42 Fully legally? Get a X86 phone and dump the .apk from there. Though obtaining an x86 apk from the internet if you have already purchased MCPE shouldn't be illegal in your country (this is not a legal advice though and I am not a lawyer).

**Comment by guppy42** [comment]
Guess I'll try a vagrant android box

**Comment by AryToNeX** [comment]
I tried Google-Play-API and it worked btw

**Comment by guppy42** [comment]
@AryToNeX turns out that if you already have a playdl.conf with a user_token in it you can indeed still use it.
 But new users cannot sign in which is a bit of a problem for people new to the project

**Comment by guppy42** [comment]
Oh and
> Crashes on launch.

Is the 2nd least useful bug report I've seen to date xD

**Comment by kris27mc** [comment]
@guppy42 well considering he's the boss, I can assure you he has the info he needs 😂

**Comment by guppy42** [comment]
I know that's why it's funny - you'd think he would lead by example :wink:

**Comment by MCMrARM** [comment]
https://github.com/MCMrARM/mcpelauncher-linux/tree/1.2
Done :D

**Comment by guppy42** [comment]
Holy crap, nice work!
