### ISSUE TITLE
[1.2 Branch] Ubuntu 17.04. Unknown Crash

### ISSUE THREAD

**Issue by xExoSk31x** [MCMrARM/mcpelauncher-linux#158]
./mcpelauncher 
loading native libraries
oslib: libGLESv2.so: 1597591128
oslib: /home/a1pha/Desktop/1.2/libs/native/libfmod.so.8.2: 1597593120
loading hybris libraries
loading MCPE
linker/home/a1pha/Desktop/1.2/hybris/src/jb/linker.c:2010| ERROR: failed to link libminecraftpe.so
failed to load MCPE: Cannot load library: reloc_library[1343]:     0 cannot locate '_ZN4FMOD6System17set3DNumListenersEi'...

**Comment by MCMrARM** [comment]
Nope, this is not the 1.2 branch. Download again.

**Comment by guppy42** [comment]
For reference after cloning do;
```
git checkout 1.2
cmake .
make -j8
```

**Comment by xExoSk31x** [comment]
I Downloaded The Zip Instead Of Doing Git Clone But I Got This Error When Making

:~/Desktop/mcpelauncher-linux-1.2-xboxlive$ 
make
[  4%] Building CXX object CMakeFiles/mcpelauncher.dir/src/main.cpp.o
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/src/main.cpp:13:29: fatal error: include/cef_app.h: No such file or directory
 #include "include/cef_app.h"
                             ^
compilation terminated.
CMakeFiles/mcpelauncher.dir/build.make:422: recipe for target 'CMakeFiles/mcpelauncher.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/mcpelauncher.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mcpelauncher.dir/all' failed
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by xExoSk31x** [comment]
I Have Tried 1.2 And It Worked But Xbox Live Didnt Im Going To Try Multiple Times To See If 1.2.0.7 x86 Apk Works I Tried The 1.2.0.2 Cause I Heard 1.2.0.7 Wont Let Apk Players Play

**Comment by xExoSk31x** [comment]
1.2 Making Worked But Xbox Branch make Does Not Work :/

**Comment by guppy42** [comment]
MCMrARM is currently experimenting with adding CEF to fix the Xbox live login issues, that means you will need to install the proper like for chrome embedded framework or rolle back a revision

**Comment by xExoSk31x** [comment]
Thanks For The Quick Reply :)

**Comment by kris27mc** [comment]
The Xbox branch isn't ready just yet (:
But @MCMrARM is working hard on it!

**Comment by xExoSk31x** [comment]
How Will We Know When Its Finished @kris27mc

**Comment by MCMrARM** [comment]
@xExoSk31x when the Xbox Live support issue will be closed ? :p

**Comment by xExoSk31x** [comment]
oi ok

**Comment by xExoSk31x** [comment]
Forgot to mention, Will 1.1.4 Work On 1.2-xboxlive when your done?

**Comment by MCMrARM** [comment]
Nope.

**Comment by xExoSk31x** [comment]
Thx For The Reply.

**Comment by xExoSk31x** [comment]
@MCMrARM Ive Seen You Have Finished The Xbox But The Make Doesnt Work :/
