### ISSUE TITLE
[Xbox Branch]Make Error 2

### ISSUE THREAD

**Issue by M3meZ** [MCMrARM/mcpelauncher-linux#159]
make
Scanning dependencies of target mcpelauncher
[  3%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/cache.c.o
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/cache.c: In function 'cache_update':
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/cache.c:105:10: warning: 'return' with a value, in function returning void
   return NULL;
          ^~~~
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/cache.c:98:13: note: declared here
 static void cache_update()
             ^~~~~~~~~~~~
[  6%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/dlfcn.c.o
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/dlfcn.c: In function 'hybris_dlerror':
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/dlfcn.c:47:12: warning: return discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
     return android_dlerror();
            ^~~~~~~~~~~~~~~~~
[ 10%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c:24:0: warning: "_GNU_SOURCE" redefined
 #define _GNU_SOURCE
 
<command-line>:0:0: note: this is the location of the previous definition
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c: In function 'my_pthread_attr_setstackaddr':
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c:297:5: warning: 'pthread_attr_setstackaddr' is deprecated [-Wdeprecated-declarations]
     return pthread_attr_setstackaddr(realattr, stack_addr);
     ^~~~~~
In file included from /home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c:34:0:
/usr/include/pthread.h:363:12: note: declared here
 extern int pthread_attr_setstackaddr (pthread_attr_t *__attr,
            ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c: In function 'my_pthread_attr_getstackaddr':
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c:303:5: warning: 'pthread_attr_getstackaddr' is deprecated [-Wdeprecated-declarations]
     return pthread_attr_getstackaddr(realattr, stack_addr);
     ^~~~~~
In file included from /home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c:34:0:
/usr/include/pthread.h:355:12: note: declared here
 extern int pthread_attr_getstackaddr (const pthread_attr_t *__restrict
            ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c: In function 'hybris_set_realrwlock':
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c:844:20: warning: comparison between pointer and integer
     if (realrwlock <= ANDROID_TOP_ADDR_VALUE_RWLOCK) {
                    ^~
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c: In function 'my_clearerr':
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c:974:29: warning: passing argument 1 of '_get_actual_fp' from incompatible pointer type [-Wincompatible-pointer-types]
     clearerr(_get_actual_fp(fp));
                             ^~
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c:959:14: note: expected 'struct aFILE *' but argument is of type 'FILE * {aka struct _IO_FILE *}'
 static FILE *_get_actual_fp(struct aFILE *fp)
              ^~~~~~~~~~~~~~
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c: In function 'my_fdopen':
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c:993:25: warning: passing argument 1 of 'fdopen' makes integer from pointer without a cast [-Wint-conversion]
     FILE* file = fdopen(filename, mode);
                         ^~~~~~~~
In file included from /home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c:25:0:
/usr/include/stdio.h:308:14: note: expected 'int' but argument is of type 'const char *'
 extern FILE *fdopen (int __fd, const char *__modes) __THROW __wur;
              ^~~~~~
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c: In function 'my_readdir_r':
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c:1286:5: warning: 'readdir_r' is deprecated [-Wdeprecated-declarations]
     int res = readdir_r(dir, &entry_r, &result_r);
     ^~~
In file included from /home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c:39:0:
/usr/include/dirent.h:183:12: note: declared here
 extern int readdir_r (DIR *__restrict __dirp,
            ^~~~~~~~~
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c: In function 'my_scandirat':
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c:1367:67: warning: passing argument 4 of 'qsort' from incompatible pointer type [-Wincompatible-pointer-types]
             qsort(result, nItems, sizeof(struct bionic_dirent *), compar);
                                                                   ^~~~~~
In file included from /home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c:29:0:
/usr/include/stdlib.h:725:13: note: expected '__compar_fn_t {aka int (*)(const void *, const void *)}' but argument is of type 'int (*)(const struct bionic_dirent **, const struct bionic_dirent **)'
 extern void qsort (void *__base, size_t __nmemb, size_t __size,
             ^~~~~
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c: In function 'my_system_property_get':
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c:1448:28: warning: passing argument 2 of 'property_get' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
  return property_get(name, value, NULL);
                            ^~~~~
In file included from /home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c:57:0:
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/../include/hybris/properties.h:51:6: note: expected 'char *' but argument is of type 'const char *'
  int property_get(const char *key, char *value, const char *default_value);
      ^~~~~~~~~~~~
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c: In function 'convert_addrinfo':
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks.c:1487:23: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         ares->ai_next = convert_addrinfo(res->ai_next);
                       ^
[ 13%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/hooks_shm.c.o
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks_shm.c:21:0: warning: "_GNU_SOURCE" redefined
 #define _GNU_SOURCE
 
<command-line>:0:0: note: this is the location of the previous definition
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks_shm.c: In function '_hybris_shm_init':
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks_shm.c:140:21: warning: implicit declaration of function 'memset' [-Wimplicit-function-declaration]
                     memset((void*)_hybris_shm_data, 0, size_to_map);
                     ^~~~~~
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks_shm.c:140:21: warning: incompatible implicit declaration of built-in function 'memset'
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/hooks_shm.c:140:21: note: include '<string.h>' or provide a declaration of 'memset'
[ 17%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/logging.c.o
[ 20%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/properties.c.o
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/properties.c:28:0: warning: "__USE_GNU" redefined
 #define __USE_GNU
 
In file included from /usr/include/string.h:25:0,
                 from /home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/properties.c:22:
/usr/include/features.h:322:0: note: this is the location of the previous definition
 # define __USE_GNU 1
 
[ 24%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/strlcpy.c.o
[ 27%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/sysconf.c.o
[ 31%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/jb/dlfcn.c.o
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/jb/dlfcn.c:16:0: warning: "_GNU_SOURCE" redefined
 #define _GNU_SOURCE
 
<command-line>:0:0: note: this is the location of the previous definition
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/jb/dlfcn.c: In function 'android_dladdr':
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/jb/dlfcn.c:139:9: warning: implicit declaration of function 'memset' [-Wimplicit-function-declaration]
         memset(info, 0, sizeof(Dl_info));
         ^~~~~~
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/jb/dlfcn.c:139:9: warning: incompatible implicit declaration of built-in function 'memset'
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/jb/dlfcn.c:139:9: note: include '<string.h>' or provide a declaration of 'memset'
[ 34%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/jb/linker.c.o
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/jb/linker.c: In function 'alloc_info':
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/jb/linker.c:287:5: warning: implicit declaration of function 'strlcpy' [-Wimplicit-function-declaration]
     strlcpy((char*) si->name, name, sizeof(si->name));
     ^~~~~~~
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/jb/linker.c: In function 'reloc_library':
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/jb/linker.c:1330:24: warning: implicit declaration of function 'get_hooked_symbol' [-Wimplicit-function-declaration]
             sym_addr = get_hooked_symbol(sym_name);
                        ^~~~~~~~~~~~~~~~~
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/jb/linker.c:1331:26: warning: comparison between pointer and integer
             if (sym_addr != NULL) {
                          ^~
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/hybris/src/jb/linker.c:1337:25: warning: comparison between pointer and integer
             if(sym_addr == NULL)
                         ^~
[ 37%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/jb/linker_environ.c.o
[ 41%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/jb/linker_format.c.o
[ 44%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/jb/rt.c.o
[ 48%] Building C object CMakeFiles/mcpelauncher.dir/eglut/eglut.c.o
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/eglut/eglut.c: In function 'eglutCreateWindow':
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/eglut/eglut.c:324:22: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
     win->keyboard_cb = _eglutDefaultKeyboard;
                      ^
[ 51%] Building C object CMakeFiles/mcpelauncher.dir/eglut/eglut_x11.c.o
[ 55%] Building CXX object CMakeFiles/mcpelauncher.dir/src/main.cpp.o
/home/a1pha/Desktop/mcpelauncher-linux-1.2-xboxlive/src/main.cpp:13:29: fatal error: include/cef_app.h: No such file or directory
 #include "include/cef_app.h"
                             ^
compilation terminated.
CMakeFiles/mcpelauncher.dir/build.make:422: recipe for target 'CMakeFiles/mcpelauncher.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/mcpelauncher.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mcpelauncher.dir/all' failed
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by guppy42** [comment]
Build instructions can be found in #117

**Comment by M3meZ** [comment]
Ive Tried It And it Doesnt Work Sadly

**Comment by M3meZ** [comment]
fatal error: curl/curl.h: No such file or directory
 #include <curl/curl.h>
                       ^
compilation terminated.
CMakeFiles/mcpelauncher.dir/build.make:630: recipe for target 'CMakeFiles/mcpelauncher.dir/src/msa_network.cpp.o' failed
make[2]: *** [CMakeFiles/mcpelauncher.dir/src/msa_network.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mcpelauncher.dir/all' failed
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by M3meZ** [comment]
i deleted it so yeh

**Comment by MCMrARM** [comment]
Install libcurl-dev or whatever is the alternative package on your system.

**Comment by M3meZ** [comment]
i did everything but no hope

**Comment by M3meZ** [comment]
Ima Downgrade To 16.10 It Seems Lower Ubuntu Versions Barely Have Any Problems

**Comment by MCMrARM** [comment]
Pick one of the three, for example libcurl4-openssl-dev.

**Comment by M3meZ** [comment]
i have a new problem and its about the cef
iluvmcmrarm@localhost:~/Desktop/cef_binary_3.3112.1653.gf69
054f_linux32$ make
[ 54%] Built target libcef_dll_wrapper
[ 54%] Building CXX object tests/cefclient/CMakeFiles/cefclient.dir/browser/browser_window.cc.o
In file included from /home/iluvmcmrarm/Desktop/cef_binary_3.3112.1653.gf69054f_linux32/tests/cefclient/browser/client_handler.h:16:0,
                 from /home/iluvmcmrarm/Desktop/cef_binary_3.3112.1653.gf69054f_linux32/tests/cefclient/browser/browser_window.h:11,
                 from /home/iluvmcmrarm/Desktop/cef_binary_3.3112.1653.gf69054f_linux32/tests/cefclient/browser/browser_window.cc:5:
/home/iluvmcmrarm/Desktop/cef_binary_3.3112.1653.gf69054f_linux32/tests/cefclient/browser/client_types.h:12:21: fatal error: gtk/gtk.h: No such file or directory
 #include <gtk/gtk.h>
                     ^
compilation terminated.
tests/cefclient/CMakeFiles/cefclient.dir/build.make:86: recipe for target 'tests/cefclient/CMakeFiles/cefclient.dir/browser/browser_window.cc.o' failed
make[2]: *** [tests/cefclient/CMakeFiles/cefclient.dir/browser/browser_window.cc.o] Error 1
CMakeFiles/Makefile2:140: recipe for target 'tests/cefclient/CMakeFiles/cefclient.dir/all' failed
make[1]: *** [tests/cefclient/CMakeFiles/cefclient.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by M3meZ** [comment]
i downloaded 16.10 and i did sudo apt-get install libcurl4-openssl-dev but i get this error


/home/iluvmcmrarm/Desktop/mcpelauncher-linux-1.2-xboxlive/src/main.cpp:13:29: fatal error: include/cef_app.h: No such file or directory
 #include "include/cef_app.h"
                             ^
compilation terminated.
CMakeFiles/mcpelauncher.dir/build.make:422: recipe for target 'CMakeFiles/mcpelauncher.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/mcpelauncher.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mcpelauncher.dir/all' failed
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by MCMrARM** [comment]
I couldn't compile tests/cefclient either but as it's not really needed I just removed it from the main CMakeLists.txt

**Comment by M3meZ** [comment]
make[2]: *** No rule to make target 'Release/libcef.so', needed by 'tests/cefsimple/Release/cefsimple'.  Stop.
CMakeFiles/Makefile2:140: recipe for target 'tests/cefsimple/CMakeFiles/cefsimple.dir/all' failed
make[1]: *** [tests/cefsimple/CMakeFiles/cefsimple.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
(EX0GAMINGPC~Console)iluvmcmrarm@localhost:~/Desktop/mcpelauncher-linux-1.2-xbox
live/binary$ make
CMake Warning at cmake/cef_variables.cmake:50 (message):
  No CMAKE_BUILD_TYPE value selected, using Release
Call Stack (most recent call first):
  cmake/FindCEF.cmake:38 (include)
  CMakeLists.txt:186 (find_package)


-- *** CEF CONFIGURATION SETTINGS ***
-- Generator:                    Unix Makefiles
-- Platform:                     Linux
-- Project architecture:         x86
-- Build type:                   Release
-- Binary distribution root:     /home/iluvmcmrarm/Desktop/mcpelauncher-linux-1.2-xboxlive/binary
-- Standard libraries:           X11
-- Compile defines:              __STDC_CONSTANT_MACROS;__STDC_FORMAT_MACROS;_FILE_OFFSET_BITS=64
-- Compile defines (Debug):      
-- Compile defines (Release):    NDEBUG
-- C compile flags:              -fno-strict-aliasing;-fPIC;-fstack-protector;-funwind-tables;-fvisibility=hidden;--param=ssp-buffer-size=4;-pipe;-pthread;-Wall;-Werror;-Wno-missing-field-initializers;-Wno-unused-parameter;-msse2;-mfpmath=sse;-mmmx;-m32 -std=c99;-Wno-unused-local-typedefs
-- C compile flags (Debug):      -O0;-g 
-- C compile flags (Release):    -O2;-fdata-sections;-ffunction-sections;-fno-ident;-U_FORTIFY_SOURCE;-D_FORTIFY_SOURCE=2 
-- C++ compile flags:            -fno-strict-aliasing;-fPIC;-fstack-protector;-funwind-tables;-fvisibility=hidden;--param=ssp-buffer-size=4;-pipe;-pthread;-Wall;-Werror;-Wno-missing-field-initializers;-Wno-unused-parameter;-msse2;-mfpmath=sse;-mmmx;-m32 -fno-exceptions;-fno-rtti;-fno-threadsafe-statics;-fvisibility-inlines-hidden;-std=gnu++11;-Wsign-compare;-Wno-literal-suffix;-Wno-narrowing
-- C++ compile flags (Debug):    -O0;-g 
-- C++ compile flags (Release):  -O2;-fdata-sections;-ffunction-sections;-fno-ident;-U_FORTIFY_SOURCE;-D_FORTIFY_SOURCE=2 
-- Exe link flags:               -fPIC;-pthread;-Wl,--disable-new-dtags;-Wl,--fatal-warnings;-Wl,-rpath,.;-Wl,-z,noexecstack;-Wl,-z,now;-Wl,-z,relro;-m32 
-- Exe link flags (Debug):        
-- Exe link flags (Release):     -Wl,-O1;-Wl,--as-needed;-Wl,--gc-sections 
-- Shared link flags:            -fPIC;-pthread;-Wl,--disable-new-dtags;-Wl,--fatal-warnings;-Wl,-rpath,.;-Wl,-z,noexecstack;-Wl,-z,now;-Wl,-z,relro;-m32 
-- Shared link flags (Debug):     
-- Shared link flags (Release):  -Wl,-O1;-Wl,--as-needed;-Wl,--gc-sections 
-- CEF Binary files:             chrome-sandbox;libcef.so;natives_blob.bin;snapshot_blob.bin
-- CEF Resource files:           cef.pak;cef_100_percent.pak;cef_200_percent.pak;cef_extensions.pak;devtools_resources.pak;icudtl.dat;locales
-- Configuring done
-- Generating done
-- Build files have been written to: /home/iluvmcmrarm/Desktop/mcpelauncher-linux-1.2-xboxlive/binary
[ 67%] Built target libcef_dll_wrapper
make[2]: *** No rule to make target 'Release/libcef.so', needed by 'tests/cefsimple/Release/cefsimple'.  Stop.
CMakeFiles/Makefile2:140: recipe for target 'tests/cefsimple/CMakeFiles/cefsimple.dir/all' failed
make[1]: *** [tests/cefsimple/CMakeFiles/cefsimple.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by M3meZ** [comment]
this isnt going so well :(

**Comment by M3meZ** [comment]
ima just wait til the issue is closed
