### ISSUE TITLE
[1.2 Xbox Branch] failed to load MCPE: Cannot load library libs/libminecraftpe.so

### ISSUE THREAD

**Issue by BrainBlasted** [MCMrARM/mcpelauncher-linux#163]
Seems to be it's looking for a file that doesn't exist. ![Libs folder](https://i.imgur.com/X9UFOTI.png)

**Comment by kris27mc** [comment]
What file is it looking for exactly that's missing? You ran `setup_cef.sh` correct?

**Comment by BrainBlasted** [comment]
Yes. The file it's looking for is in the title, libs/libminecraftpe.so in the downloaded folder.

**Comment by guppy42** [comment]
that **highly** suggests that you skipped the ./extract apkfile step as that's where that .so file comes from

**Comment by guppy42** [comment]
also for file list please provide the output of `ls -lA` of the relevant dir instead of posting a screenshot, it's just a whole lot easier to parse

**Comment by BrainBlasted** [comment]
Getting `Bus error (core dumped)`  with the extract step complete. I've done this before, thought it was because I missed a step somewhere and I redownloaded the repo, though I forgot to run extract.sh(sorry). Should the `Bus error` go in a new issue?

**Comment by guppy42** [comment]
yes please ( and close this one )
