### ISSUE TITLE
Bus Error (core dumped) on 1.2-xboxlive

### ISSUE THREAD

**Issue by BrainBlasted** [MCMrARM/mcpelauncher-linux#165]
Getting `Bus error (core dumped)` when running the mcpe launcher. I've gone through the install process twice, but I could be missing a step somewhere. I'm unsure if this is due to a missing dependency - I checked every one I could, and all are installed on my system.

**Distro:** Arch Linux
**Version:** 1.2-xboxlive

**Comment by guppy42** [comment]
please do provide the full output of the console. Providing only the above error is the equivalent of calling a mechanic in another country and telling him "my car wont start" (everybody loves a car analogy ;) )

**Comment by BrainBlasted** [comment]
Ah, sorry, was half sleep when working on this. Here: 
```
loading native libraries
oslib: libGLESv2.so: -142946648
oslib: /home/BrainBlasted/Downloads/mcpelauncher-linux-1.2-xboxlive/libs/native/libfmod.so.8.2: 1477956184
loading hybris libraries
loading MCPE
Bus error (core dumped)
```

**Comment by MCMrARM** [comment]
How did you extract MCPE?

**Comment by BrainBlasted** [comment]
I ran extract.sh on the downloaded apk file.

**Comment by guppy42** [comment]
And how did you obtain the APK ( it must be a x86 apk, not an arm one )

**Comment by BrainBlasted** [comment]
Oop, that's probably where I messed up, didn't know there was a difference between x86 and ARM, since people use so many different terms to categorize CPUs. Downloaded the APK from my phone and extracted it.

**Comment by kris27mc** [comment]
@BrainBlasted You'll need an x86 apk. Which is hard to acquire if you don't have an x86 phone. But @MCMrARM is working on fixing his Google Play utility so hopefully that'll be fixed in the near future

**Comment by guppy42** [comment]
Glad you figured it out - please close this issue
