### ISSUE TITLE
MCPELauncher doesn't start

### ISSUE THREAD

**Issue by Encritary** [MCMrARM/mcpelauncher-linux#169]
Version: 1.1.5.1 x86
`mrgenga@GoldChest:~/mcpelauncher-linux$ ./mcpelauncher 
loading native libraries
oslib: libGLESv2.so: 140305312
oslib: /home/mrgenga/mcpelauncher-linux/libs/native/libfmod.so.8.2: 140307120
loading hybris libraries
loading MCPE
linker/home/mrgenga/mcpelauncher-linux/hybris/src/jb/linker.c:2010| ERROR: failed to link libminecraftpe.so
failed to load MCPE: Cannot load library: reloc_library[1343]: 0 cannot locate '_ZN4FMOD6System17set3DNumListenersEi'...

mrgenga@GoldChest:~/mcpelauncher-linux$`

**Comment by Tarik02** [comment]
Hello. It seems that you haven't/have old libfmod. Please, try to use newer version(1.2) from branch `apk-download`

**Comment by MCMrARM** [comment]
I'll look into it soon, but generally I suggest using the 1.2 betas with the `apk-download` branch instead of using 1.1.
