### ISSUE TITLE
[apk-download] No text in chat log

### ISSUE THREAD

**Issue by AryToNeX** [MCMrARM/mcpelauncher-linux#171]
You can type messages in chat and they will be sent but you can't see them in chat log. You can't also see others' messages and server messages. 

_Sent from my Xiaomi Redmi Note 3 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MCMrARM** [comment]
Fixed with https://github.com/MCMrARM/mcpelauncher-linux/commit/cf5ad889513088160b926ac37bb5487ef69d7355
