### ISSUE TITLE
Build fails with failing to create symbolic link

### ISSUE THREAD

**Issue by phunni** [MCMrARM/mcpelauncher-linux#173]
While attempting to build the apk-download branch, the build fails with the following error:

`[100%] Linking CXX executable mcpelauncher
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_getstackaddr':
hooks.c:(.text+0x5b9): warning: the use of `pthread_attr_getstackaddr' is deprecated, use `pthread_attr_getstack'
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_setstackaddr':
hooks.c:(.text+0x588): warning: the use of `pthread_attr_setstackaddr' is deprecated, use `pthread_attr_setstack'
failed to create symbolic link '/home/paul/tmp/mcpelauncher-linux/src/initial_setup_resources' because existing path cannot be removed: Is a directory
make[2]: *** [CMakeFiles/mcpelauncher.dir/build.make:1004: mcpelauncher] Error 1
make[2]: *** Deleting file 'mcpelauncher'
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/mcpelauncher.dir/all] Error 2
make: *** [Makefile:130: all] Error 2`

I've tried deleting the existing path (although that seems like it's a bad idea - I didn't create it), but that just creates the same error on a different path, until eventually it just fails to compile due to missing libs - presumably, because I deleted them trying to fix this error!

Trying to build on Arch Linux.

**Comment by AryToNeX** [comment]
`mkdir build && cd build && cmake .. && make`

**Comment by phunni** [comment]
Thanks for the reply.  That results in:

`mkdir build && cd build && cmake .. && make
-- Found Protobuf: /usr/lib/libprotobuf.so;-lpthread (found version "3.3.2") 
-- Found Protobuf: /usr/lib/libprotobuf.so;-lpthread;-lpthread (found version "3.3.2") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/paul/tmp/mcpelauncher-linux
make: *** No targets specified and no makefile found.  Stop.
`

**Comment by AryToNeX** [comment]
hmm


clean up folders and git clone / compile again

**Comment by phunni** [comment]
Huh - that seemed to do it... Couldn't tell you what I did differently this time though!

Thanks again!

**Comment by AryToNeX** [comment]
You runned cmake in source dir, messing up things. When I told you to clean up the environment and try again cmake created its files in build/ dir instead of source dir. That's all :D
