### ISSUE TITLE
Cannot start 1.2.0.15 using apk-download branch

### ISSUE THREAD

**Issue by Encritary** [MCMrARM/mcpelauncher-linux#174]
Failed to find data file: assets/xboxservices.config

**Comment by Encritary** [comment]
Problem was solved with: wget https://raw.githubusercontent.com/Microsoft/xbox-live-api/master/Tests/CreatorsCppTestApp/UWP/Cpp/xboxservices.config -O assets/xboxservices.config

**Comment by MCMrARM** [comment]
I'm afraid it was not. Can't you just use the official methods for extracting the apk?
