### ISSUE TITLE
[APK-DOWNLOAD] No sound?

### ISSUE THREAD

**Issue by Encritary** [MCMrARM/mcpelauncher-linux#175]
I just compiled it and tried to play on LifeBoat Network. No sound?
P. S. Yes, my system sound is working.

**Comment by Encritary** [comment]
P.S. Yes I've installed pulseaudio:i386

**Comment by Encritary** [comment]
@MCMrARM please help or fix.

**Comment by Encritary** [comment]
P.S. On master branch with 1.1.5 it works.

**Comment by MCMrARM** [comment]
Hmm, I thought I fixed it. I'll investigate asap.

**Comment by Encritary** [comment]
@MCMrARM so what's up?

**Comment by phunni** [comment]
Also have this problem - also have 32-bit pulse installed - which is what I assume is what pulse:i386 is on other distros...?

**Comment by Encritary** [comment]
@MCMrARM I need sound to make my server D:

**Comment by kris27mc** [comment]
@Encritary it's not that big a deal yet. 1.2 isn't even stable so don't rush. MCMrARM has multiple projects as well as a life to live and I'm sure he'll do what he can as soon as he can

**Comment by MCMrARM** [comment]
Apparently all that has to be done is to update the FMod library. I'll upload a newer version in a moment.

**Comment by MCMrARM** [comment]
Done.
