### ISSUE TITLE
Cannot find /data folder

### ISSUE THREAD

**Issue by phunni** [MCMrARM/mcpelauncher-linux#176]
The wiki says:

> Your worlds are located in /data/current/games/com.mojang/minecraftWorlds

but I simply cannot find this directory anywhere.  I've looked in the game install folder, I've looked for a hidden folder in home - I even looked to see if there was a /data folder under root - even though I knew there couldn't be because of permissions.

I'd mostly like to be able to import my worlds (the world import causes a crash) as well as export them - so it'd be really useful to be able to find this directory...

**Comment by Encritary** [comment]
On apk-download branch it located in (your homefolder)/.local/share/mcpelauncher

**Comment by phunni** [comment]
Thanks!
