### ISSUE TITLE
Segmentation Fault while installing MCPELauncher-linux with NVIDIA drivers

### ISSUE THREAD

**Issue by Fef0** [MCMrARM/mcpelauncher-linux#178]
Hi guys, today I tried to install MCPELauncher on Xubuntu 16.04 LTS, everything was ok but a Segmentation Fault was raised when I chose my Minecraft APK. I debugged the code by Strace and I read that the executable can't find some NVIDIA related files. So I decided to reinstall the NVIDIA drivers and try again, but with the same result. So what could be the problem? 
That's my debug file, generated by Strace:
[debug_mcpelauncher.txt](https://github.com/MCMrARM/mcpelauncher-linux/files/1250136/debug_mcpelauncher.txt)

Thank you in advance for any help,

-Fef0

**Comment by MCMrARM** [comment]
Most likely a kernel module and library version mismatch, uninstall all nvidia drivers files from your system and try again.
