### ISSUE TITLE
I Installed a New Version Of Ubuntu and Now I Cant Install The Required Libaries

### ISSUE THREAD

**Issue by M3meZ** [MCMrARM/mcpelauncher-linux#179]
(yakkety)exo@localhost:~$     sudo apt-get install cmake zlib1g-dev:i386 libncurses5-dev:i386 libgles2-mesa-dev gcc-multilib g++-multilib zlib1g-dev:i386 libx11-dev:i386 linux-libc-dev:i386 uuid-dev:i386 libpng-dev:i386 libx11-dev:i386 libxext6:i386
Reading package lists... Done
Building dependency tree... 50%
Building dependency tree       
Reading state information... Done
libxext6 is already the newest version (2:1.3.3-1).
libxext6 set to manually installed.
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 adduser : Depends: perl-base (>= 5.6.0) but it is not going to be installed
           Depends: passwd (>= 1:4.1.5.1-1.1ubuntu6) but it is not going to be installed
 adwaita-icon-theme : Depends: gtk-update-icon-cache but it is not going to be installed
                      Depends: librsvg2-common but it is not going to be installed
 apt : Depends: gpgv but it is not going to be installed or
                gpgv2 but it is not going to be installed or
                gpgv1 but it is not going to be installed
       Recommends: gnupg but it is not going to be installed or
                   gnupg2 but it is not going to be installed or
                   gnupg1 but it is not going to be installed
 ca-certificates : Depends: openssl (>= 1.0.0) but it is not going to be installed
 cmake : PreDepends: dpkg (>= 1.17.5~) but it is not going to be installed
         Depends: cmake-data (= 3.5.2-2ubuntu1) but it is not going to be installed
         Depends: procps but it is not going to be installed
         Depends: libarchive13 but it is not going to be installed
         Depends: libjsoncpp1 but it is not going to be installed
         Recommends: gcc but it is not going to be installed
         Recommends: make
 console-setup-linux : Depends: kbd (>= 1.15-1ubuntu3) but it is not going to be installed
 dbus-user-session : Depends: dbus (>= 1.10.10-1ubuntu1.1) but it is not going to be installed
                     Depends: libpam-systemd but it is not going to be installed
                     Depends: systemd but it is not going to be installed
                     Recommends: systemd-sysv but it is not going to be installed
 debconf : PreDepends: perl-base (>= 5.6.1-4) but it is not going to be installed
           Recommends: apt-utils (>= 0.5.1) but it is not going to be installed
 debconf-i18n : Depends: liblocale-gettext-perl but it is not going to be installed
                Depends: libtext-iconv-perl but it is not going to be installed
                Depends: libtext-charwidth-perl but it is not going to be installed
 deluge-common : Depends: python (>= 2.7) but it is not going to be installed
                 Depends: python (< 2.8) but it is not going to be installed
 dh-python : Depends: python3:any (>= 3.3.2-2~)
 dpkg-dev : Depends: tar (>= 1.28-1) but it is not going to be installed
            Depends: bzip2 but it is not going to be installed
            Depends: xz-utils but it is not going to be installed
            Depends: patch (>= 2.7) but it is not going to be installed
            Depends: make
            Depends: binutils but it is not going to be installed
            Depends: base-files (>= 5.0.0) but it is not going to be installed
            Recommends: gcc but it is not going to be installed or
                        c-compiler
            Recommends: build-essential but it is not going to be installed
            Recommends: fakeroot
            Recommends: gnupg but it is not going to be installed or
                        gnupg2 but it is not going to be installed
            Recommends: gpgv but it is not going to be installed or
                        gpgv2 but it is not going to be installed
            Recommends: libalgorithm-merge-perl but it is not going to be installed
 evince:amd64 : Depends: evince-common:amd64 (< 3.23) but it is not installable
                Depends: evince-common:amd64 (>= 3.22) but it is not installable
 evolution-data-server-common : Depends: dconf-gsettings-backend but it is not going to be installed or
                                         gsettings-backend
 fonts-droid-fallback : PreDepends: dpkg (>= 1.15.7.2) but it is not going to be installed
 g++-multilib : Depends: cpp (>= 4:6.1.1-1ubuntu2) but it is not going to be installed
                Depends: g++ (>= 4:6.1.1-1ubuntu2) but it is not going to be installed
                Depends: g++-6-multilib (>= 6.1.1-9~) but it is not going to be installed
 gcc-multilib : Depends: cpp (>= 4:6.1.1-1ubuntu2) but it is not going to be installed
                Depends: gcc (>= 4:6.1.1-1ubuntu2) but it is not going to be installed
                Depends: gcc-6-multilib (>= 6.1.1-9~) but it is not going to be installed
                Conflicts: gcc-multilib:amd64 but 4:6.1.1-1ubuntu2 is to be installed
 gcc-multilib:amd64 : Conflicts: gcc-multilib but 4:6.1.1-1ubuntu2 is to be installed
 gconf2:amd64 : Depends: python3:any
 gdebi : Depends: python3:any (>= 3.3.2-2~)
         Depends: gir1.2-gtk-3.0 but it is not going to be installed
         Depends: gir1.2-vte-2.91 but it is not going to be installed
         Depends: python3-gi but it is not going to be installed
         Depends: gksu but it is not going to be installed
         Recommends: libgtk2-perl but it is not going to be installed
         Recommends: shared-mime-info but it is not going to be installed
 gdebi-core : Depends: python3:any (>= 3.3.2-2~)
              Depends: python3-apt but it is not going to be installed
              Depends: file but it is not going to be installed
 gir1.2-ibus-1.0:amd64 : Depends: python3:any (>= 3.3.2-2~)
 glib-networking : Depends: glib-networking-services (>= 2.50.0-1) but it is not going to be installed
                   Depends: glib-networking-services (< 2.50.0-1.1~) but it is not going to be installed
 gnome-icon-theme : Depends: gtk-update-icon-cache but it is not going to be installed
                    Depends: librsvg2-common but it is not going to be installed
 gnome-power-manager:amd64 : Depends: gnome-settings-daemon-schemas:amd64 (>= 3.2) but it is not installable
 gnome-settings-daemon-schemas : Depends: dconf-gsettings-backend but it is not going to be installed or
                                          gsettings-backend
 gsettings-desktop-schemas : Depends: dconf-gsettings-backend but it is not going to be installed or
                                      gsettings-backend
 gsettings-ubuntu-schemas : Depends: dconf-gsettings-backend but it is not going to be installed or
                                     gsettings-backend
 gvfs-common : Depends: desktop-file-utils but it is not going to be installed
               Recommends: gvfs but it is not going to be installed
 hwdata : Depends: usbutils but it is not going to be installed
          Depends: pciutils but it is not going to be installed
 ibus:amd64 : Depends: python3:any (>= 3.3.2-2~)
              Recommends: im-config:amd64 but it is not installable
 im-config : Depends: gettext-base but it is not going to be installed
             Depends: zenity but it is not going to be installed or
                      kde-baseapps-bin but it is not going to be installed or
                      whiptail but it is not going to be installed
             Recommends: whiptail but it is not going to be installed
 indicator-applet:amd64 : Depends: python3-xdg:amd64 but it is not installable
 indicator-session:amd64 : Depends: gnome-settings-daemon-schemas:amd64 but it is not installable
                           Recommends: yelp:amd64 but it is not installable
                           Recommends: unity-control-center:amd64 but it is not installable or
                                       gnome-control-center:amd64 but it is not installable or
                                       mate-control-center:amd64 but it is not installable
                           Recommends: unity-control-center-signon:amd64 but it is not installable or
                                       gnome-control-center-signon:amd64 but it is not installable or
                                       mate-control-center:amd64 but it is not installable
 init-system-helpers : Depends: perl-base (>= 5.20.1-3) but it is not going to be installed
 initramfs-tools-core : Depends: busybox-initramfs (>= 1:1.22.0-17~) but it is not going to be installed
                        Depends: initramfs-tools-bin (= 0.125ubuntu6.3) but it is not going to be installed
                        Depends: klibc-utils (>= 2.0.4-8~) but it is not going to be installed
                        Depends: cpio but it is not going to be installed
                        Depends: kmod but it is not going to be installed or
                                 module-init-tools but it is not going to be installed
                        Depends: udev but it is not going to be installed
 intltool-debian : Depends: perl but it is not going to be installed
                   Depends: gettext but it is not going to be installed
 keyboard-configuration : Depends: liblocale-gettext-perl but it is not going to be installed
 libarchive-zip-perl : Depends: perl but it is not going to be installed
 libauthen-sasl-perl : Depends: perl but it is not going to be installed
 libcgi-fast-perl : Depends: perl but it is not going to be installed
                    Depends: libfcgi-perl but it is not going to be installed
 libcgi-pm-perl : Depends: perl but it is not going to be installed
                  Depends: libhtml-parser-perl but it is not going to be installed
 libclass-accessor-perl : Depends: perl but it is not going to be installed
                          Depends: libsub-name-perl but it is not going to be installed
 libdigest-hmac-perl : Depends: perl but it is not going to be installed
 libdpkg-perl : Depends: dpkg (>= 1.16.3) but it is not going to be installed
                Depends: perl but it is not going to be installed
                Recommends: libfile-fcntllock-perl but it is not going to be installed
                Recommends: bzip2 but it is not going to be installed
                Recommends: xz-utils but it is not going to be installed
 libemail-valid-perl : Depends: perl but it is not going to be installed
 libencode-locale-perl : Depends: perl but it is not going to be installed
 libexporter-tiny-perl : Depends: perl but it is not going to be installed
 libfile-basedir-perl : Depends: perl but it is not going to be installed
 libfile-listing-perl : Depends: perl but it is not going to be installed
 libfont-afm-perl : Depends: perl (>= 5.6.0-16) but it is not going to be installed
 libgda-5.0-4:amd64 : Depends: libgda-5.0-common:amd64 (>= 5.2.4-1ubuntu3) but it is not installable
 libgda-5.0-common : Depends: python:any (>= 2.6.6-7~)
                     Recommends: libgda-5.0-4 but it is not going to be installed
 libgdk-pixbuf2.0-0 : Depends: shared-mime-info but it is not going to be installed
 libgles2-mesa-dev : Depends: libgles2-mesa (= 12.0.6-0ubuntu0.16.10.1) but it is not going to be installed
                     Depends: libegl1-mesa-dev but it is not going to be installed
 libgnome2-common : Depends: gconf2 (>= 2.28.1-2) but it is not going to be installed
 libgnomekbd-common : Depends: dconf-gsettings-backend but it is not going to be installed or
                               gsettings-backend
 libgoa-1.0-common : Depends: dconf-gsettings-backend but it is not going to be installed or
                              gsettings-backend
 libgtk-3-0 : Depends: shared-mime-info but it is not going to be installed
              Recommends: libgtk-3-bin but it is not going to be installed
 libgtk-3-common : Depends: dconf-gsettings-backend but it is not going to be installed or
                            gsettings-backend
 libgtk2.0-0 : Depends: shared-mime-info but it is not going to be installed
               Recommends: libgtk2.0-bin but it is not going to be installed
 libgweather-common : Depends: dconf-gsettings-backend but it is not going to be installed or
                               gsettings-backend
 libhtml-form-perl : Depends: perl but it is not going to be installed
                     Depends: libhtml-parser-perl but it is not going to be installed
 libhtml-format-perl : Depends: perl but it is not going to be installed
 libhtml-parser-perl:amd64 : Depends: libhtml-tagset-perl:amd64 but it is not installable
                             Depends: liburi-perl:amd64 but it is not installable
                             Recommends: libhttp-message-perl:amd64 but it is not installable
 libhtml-tagset-perl : Depends: perl (>= 5.6.0-16) but it is not going to be installed
 libhtml-tree-perl : Depends: perl but it is not going to be installed
                     Depends: libhtml-parser-perl but it is not going to be installed
 libhttp-cookies-perl : Depends: perl but it is not going to be installed
 libhttp-daemon-perl : Depends: perl but it is not going to be installed
 libhttp-date-perl : Depends: perl but it is not going to be installed
 libhttp-message-perl : Depends: perl but it is not going to be installed
                        Depends: perl (>= 5.11) but it is not going to be installed or
                                 libio-compress-perl
 libhttp-negotiate-perl : Depends: perl but it is not going to be installed
 libio-html-perl : Depends: perl but it is not going to be installed
 libio-socket-inet6-perl : Depends: perl but it is not going to be installed
                           Depends: libsocket6-perl but it is not going to be installed
 libio-socket-ssl-perl : Depends: libnet-ssleay-perl (>= 1.59) but it is not going to be installed
                         Depends: perl but it is not going to be installed
                         Recommends: perl (>= 5.15.6) but it is not going to be installed or
                                     libsocket-perl or
                                     libsocket6-perl but it is not going to be installed
 libio-string-perl : Depends: perl but it is not going to be installed
 libipc-run-perl : Depends: perl but it is not going to be installed
                   Depends: libio-pty-perl but it is not going to be installed
 libipc-system-simple-perl : Depends: perl but it is not going to be installed
 libjbig0 : PreDepends: multiarch-support but it is not going to be installed
 libjpeg-turbo8 : PreDepends: multiarch-support but it is not going to be installed
 liblist-moreutils-perl:amd64 : Depends: libexporter-tiny-perl:amd64 but it is not installable
 liblwp-mediatypes-perl : Depends: perl but it is not going to be installed
 liblwp-protocol-https-perl : Depends: perl but it is not going to be installed
 libmailtools-perl : Depends: perl but it is not going to be installed
 libncurses5-dev : Depends: libncurses5 (= 6.0+20160625-1ubuntu1) but it is not going to be installed
                   Depends: libtinfo-dev (= 6.0+20160625-1ubuntu1) but it is not going to be installed
                   Depends: libc6-dev but it is not going to be installed or
                            libc-dev
 libnet-dbus-perl:amd64 : Depends: libxml-twig-perl:amd64 but it is not installable
 libnet-dns-perl : Depends: perl but it is not going to be installed
 libnet-domain-tld-perl : Depends: perl but it is not going to be installed
 libnet-http-perl : Depends: perl but it is not going to be installed
 libnet-ip-perl : Depends: perl but it is not going to be installed
 libnet-smtp-ssl-perl : Depends: perl but it is not going to be installed
 libnotify4 : PreDepends: multiarch-support but it is not going to be installed
 libpam-runtime : Depends: libpam-modules (>= 1.0.1-6) but it is not going to be installed
 libpango-1.0-0 : Depends: fontconfig (>= 2.1.91) but it is not going to be installed
 libpangox-1.0-0 : PreDepends: multiarch-support but it is not going to be installed
 libparse-debianchangelog-perl : Depends: perl but it is not going to be installed
                                 Depends: liblocale-gettext-perl but it is not going to be installed
 libpcre3 : PreDepends: multiarch-support but it is not going to be installed
 libtext-levenshtein-perl : Depends: perl but it is not going to be installed
                            Depends: perl (>= 5.19.7) but it is not going to be installed or
                                     libunicode-collate-perl (>= 1.04)
 libtext-wrapi18n-perl : Depends: libtext-charwidth-perl but it is not going to be installed
 libtie-ixhash-perl : Depends: perl but it is not going to be installed
 libtimedate-perl : Depends: perl but it is not going to be installed
 libtxc-dxtn-s2tc0 : PreDepends: multiarch-support but it is not going to be installed
 liburi-perl : Depends: perl but it is not going to be installed
 libuuid1 : Depends: passwd but it is not going to be installed
            Recommends: uuid-runtime but it is not going to be installed
 libvte9:amd64 : Depends: libvte-common:amd64 (= 1:0.28.2-5ubuntu3) but it is not installable
 libwww-perl : Depends: perl but it is not going to be installed
               Depends: libhtml-parser-perl but it is not going to be installed
 libwww-robotrules-perl : Depends: perl but it is not going to be installed
 libx11-dev : Depends: libxau-dev (>= 1:1.0.0-1) but it is not going to be installed
              Depends: libxdmcp-dev (>= 1:1.0.0-1) but it is not going to be installed
              Depends: x11proto-core-dev (>= 7.0.17) but it is not going to be installed
              Depends: x11proto-input-dev but it is not going to be installed
              Depends: x11proto-kb-dev but it is not going to be installed
              Depends: xtrans-dev but it is not going to be installed
              Depends: libxcb1-dev but it is not going to be installed
              Recommends: libx11-doc but it is not going to be installed
 libxau6 : PreDepends: multiarch-support but it is not going to be installed
 libxcomposite1 : PreDepends: multiarch-support but it is not going to be installed
 libxcursor1 : PreDepends: multiarch-support but it is not going to be installed
 libxdamage1 : PreDepends: multiarch-support but it is not going to be installed
 libxext6 : PreDepends: multiarch-support but it is not going to be installed
 libxft2 : PreDepends: multiarch-support but it is not going to be installed
 libxinerama1 : PreDepends: multiarch-support but it is not going to be installed
 libxml-parser-perl:amd64 : Depends: liburi-perl:amd64 but it is not installable
                            Depends: libwww-perl:amd64 but it is not installable
 libxml-twig-perl : Depends: perl but it is not going to be installed
                    Depends: libxml-parser-perl but it is not going to be installed
                    Recommends: libtext-iconv-perl but it is not going to be installed
                    Recommends: libhtml-parser-perl but it is not going to be installed
 libxml-xpathengine-perl : Depends: perl but it is not going to be installed
 libxshmfence1 : PreDepends: multiarch-support but it is not going to be installed
 libxss1 : PreDepends: multiarch-support but it is not going to be installed
 libxtst6 : PreDepends: multiarch-support but it is not going to be installed
 lintian : Depends: binutils but it is not going to be installed
           Depends: bzip2 but it is not going to be installed
           Depends: diffstat but it is not going to be installed
           Depends: file but it is not going to be installed
           Depends: gettext but it is not going to be installed
           Depends: libapt-pkg-perl but it is not going to be installed
           Depends: libclone-perl but it is not going to be installed
           Depends: libdigest-sha-perl
           Depends: liblist-moreutils-perl but it is not going to be installed
           Depends: libyaml-libyaml-perl but it is not going to be installed
           Depends: man-db but it is not going to be installed
           Depends: patchutils but it is not going to be installed
           Depends: perl but it is not going to be installed
           Depends: t1utils but it is not going to be installed
           Depends: xz-utils but it is not going to be installed
           Recommends: dpkg (>= 1.17.14) but it is not going to be installed
           Recommends: perl (>= 5.20) but it is not going to be installed or
                       libautodie-perl (>= 2.18)
           Recommends: libperlio-gzip-perl but it is not going to be installed
 locales : Depends: libc-bin (> 2.24) but it is not going to be installed
 lsb-release : Depends: python3:any (>= 3.4~)
 lxde : Depends: galculator but it is not going to be installed
        Depends: gpicview but it is not going to be installed
        Depends: leafpad but it is not going to be installed
        Depends: lxappearance but it is not going to be installed
        Depends: lxappearance-obconf but it is not going to be installed
        Depends: lxinput but it is not going to be installed
        Depends: lxrandr but it is not going to be installed
        Depends: lxsession-edit but it is not going to be installed
        Depends: lxterminal but it is not going to be installed
        Depends: xarchiver but it is not going to be installed
        Recommends: alsamixergui but it is not going to be installed
        Recommends: clipit but it is not going to be installed
        Recommends: deluge but it is not going to be installed or
                    transmission-gtk but it is not going to be installed
        Recommends: evince-gtk but it is not going to be installed or
                    pdf-viewer
        Recommends: gnome-disk-utility but it is not going to be installed
        Recommends: gnome-mplayer but it is not going to be installed
        Recommends: gnome-system-tools but it is not going to be installed
        Recommends: gucharmap but it is not going to be installed
        Recommends: lightdm but it is not going to be installed or
                    x-display-manager
        Recommends: lxmusic but it is not going to be installed or
                    audacious but it is not going to be installed
        Recommends: lxpolkit but it is not going to be installed
        Recommends: openbox but it is not going to be installed or
                    x-window-manager
        Recommends: usermode but it is not going to be installed
        Recommends: xserver-xorg but it is not going to be installed
 lxde-common : Depends: lxsession but it is not going to be installed
               Depends: openbox but it is not going to be installed
               Recommends: pcmanfm but it is not going to be installed
               Recommends: lxpanel but it is not going to be installed
               Recommends: lxtask but it is not going to be installed
               Recommends: gnome-screenshot but it is not going to be installed
               Recommends: lxrandr but it is not going to be installed
 lxde-core : Depends: desktop-file-utils but it is not going to be installed
             Depends: lxpanel but it is not going to be installed
             Depends: pcmanfm but it is not going to be installed
             Recommends: gksu but it is not going to be installed
             Recommends: lxterminal but it is not going to be installed or
                         x-terminal-emulator
             Recommends: xscreensaver but it is not going to be installed
 lxpanel:amd64 : Depends: lxpanel-data:amd64 (= 0.8.2-1ubuntu2) but it is not installable
 lxpolkit:amd64 : Depends: lxsession-data:amd64 but it is not installable
 lxsession-edit:amd64 : Depends: lxsession-data:amd64 but it is not installable
 lxsession-logout:amd64 : Depends: lxsession-data:amd64 but it is not installable
 mplayer2 : Depends: mplayer (>= 2:1.2) but it is not going to be installed
 nautilus-data : Depends: dconf-gsettings-backend but it is not going to be installed or
                          gsettings-backend
 netsurf-gtk:amd64 : Depends: netsurf-common:amd64 (= 3.2+dfsg-3) but it is not installable
 opera-stable : Depends: gconf-service but it is not going to be installed
                Depends: gnupg (>= 1.4.1) but it is not going to be installed
                Recommends: pepperflashplugin-nonfree but it is not installable
                Recommends: chromium-codecs-ffmpeg-extra but it is not going to be installed
 packagekit:amd64 : Depends: gdebi-core:amd64 (>= 0.8.2) but it is not installable
 perl-modules-5.22 : PreDepends: dpkg (>= 1.17.17) but it is not going to be installed
                     Depends: perl-base (>= 5.22.2-1) but it is not going to be installed
                     Recommends: perl (>= 5.22.2-1) but it is not going to be installed
 poppler-data : PreDepends: dpkg (>= 1.15.6~) but it is not going to be installed
 python-appindicator:amd64 : Depends: python:any (>= 2.6.6-7~)
                             Depends: python-gobject:amd64 but it is not installable
 python-attr : Depends: python:any (< 2.8)
               Depends: python:any (>= 2.7.5-5~)
 python-cairo:amd64 : Depends: python:any (< 2.8)
                      Depends: python:any (>= 2.7.5-5~)
 python-cffi-backend:amd64 : Depends: python:any (< 2.8)
                             Depends: python:any (>= 2.7~)
 python-chardet : Depends: python:any (< 2.8)
                  Depends: python:any (>= 2.7.5-5~)
 python-cryptography:amd64 : Depends: python-enum34:amd64 but it is not installable
                             Depends: python-idna:amd64 (>= 2.0) but it is not installable
                             Depends: python-ipaddress:amd64 but it is not installable
                             Depends: python-pyasn1:amd64 (>= 0.1.8) but it is not installable
                             Depends: python:any (< 2.8)
                             Depends: python:any (>= 2.7.5-5~)
 python-enum34 : Depends: python:any (< 2.8)
                 Depends: python:any (>= 2.7.5-5~)
 python-gi:amd64 : Depends: python:any (< 2.8)
                   Depends: python:any (>= 2.7.5-5~)
 python-gobject : Depends: python-gi (>= 3.22.0-1) but it is not going to be installed
                  Depends: python-gobject-2 but it is not going to be installed
 python-gobject-2:amd64 : Depends: python:any (>= 2.7.5-5~)
 python-idna : Depends: python:any (< 2.8)
               Depends: python:any (>= 2.7.5-5~)
 python-ipaddress : Depends: python:any (< 2.8)
                    Depends: python:any (>= 2.7.5-5~)
 python-numpy:amd64 : Depends: python2.7:any
                      Depends: python:any (< 2.8)
                      Depends: python:any (>= 2.7.5-5~)
 python-openssl : Depends: python-cryptography (>= 1.3.4) but it is not going to be installed
                  Depends: python:any (< 2.8)
                  Depends: python:any (>= 2.7.5-5~)
 python-pkg-resources : Depends: python:any (< 2.8)
                        Depends: python:any (>= 2.7.5-5~)
 python-pyasn1 : Depends: python:any (< 2.8)
                 Depends: python:any (>= 2.7.5-5~)
 python-pyasn1-modules : Depends: python:any (< 2.8)
                         Depends: python:any (>= 2.7.5-5~)
 python-serial : Depends: python (>= 2.7) but it is not going to be installed
                 Depends: python (< 2.8) but it is not going to be installed
                 Depends: python:any (>= 2.6.6-7~)
 python-service-identity : Depends: python:any (< 2.8)
                           Depends: python:any (>= 2.7.5-5~)
 python-setuptools : Depends: python:any (< 2.8)
                     Depends: python:any (>= 2.7.5-5~)
 python-six : Depends: python:any (< 2.8)
              Depends: python:any (>= 2.7.5-5~)
 python-talloc:amd64 : Depends: python:any (< 2.8)
                       Depends: python:any (>= 2.7~)
 python-twisted-bin:amd64 : Depends: python:any (< 2.8)
                            Depends: python:any (>= 2.7~)
 python-twisted-core : Depends: python-twisted-bin (>= 16.4.1-1) but it is not going to be installed
                       Depends: python-zope.interface (>= 4.0.2) but it is not going to be installed
                       Depends: python:any (< 2.8)
                       Depends: python:any (>= 2.7.5-5~)
                       Recommends: python-pam but it is not going to be installed
 python-xdg : Depends: python (>= 2.7) but it is not going to be installed
              Depends: python (< 2.8) but it is not going to be installed
              Depends: python:any (>= 2.7.1-0ubuntu2)
 python-zope.interface:amd64 : Depends: python-pkg-resources:amd64 but it is not installable
                               Depends: python:any (< 2.8)
                               Depends: python:any (>= 2.7.5-5~)
 python3-apt:amd64 : Depends: python3:any (>= 3.3.2-2~)
                     Depends: python-apt-common:amd64 but it is not installable
 python3-chardet : Depends: python3:any (>= 3.3.2-2~)
 python3-debian : Depends: python3:any (>= 3.3.2-2~)
                  Recommends: python3-apt but it is not going to be installed
 python3-gi:amd64 : Depends: python3:any (>= 3.3.2-2~)
 python3-pkg-resources : Depends: python3:any (>= 3.3.2-2~)
 python3-six : Depends: python3:any (>= 3.4~)
 python3-xdg : Depends: python3:any (>= 3.3.2-2~)
 readline-common : Depends: dpkg (>= 1.15.4) but it is not going to be installed or
                            install-info but it is not going to be installed
 resolvconf : Depends: ifupdown
 sgml-base : PreDepends: dpkg (>= 1.16.4) but it is not going to be installed
 ubuntu-keyring : Depends: gpgv but it is not going to be installed
                  Recommends: gnupg but it is not going to be installed or
                              gnupg1 but it is not going to be installed
 ucf : Depends: coreutils (>= 5.91) but it is not going to be installed
 unity-settings-daemon:amd64 : Depends: gnome-settings-daemon-schemas:amd64 (>= 3.16) but it is not installable
                               Recommends: systemd-services:amd64 but it is not installable
 uuid-dev : Depends: libc6-dev but it is not going to be installed or
                     libc-dev
 xfonts-base : Depends: xfonts-utils (>= 1:7.5+2) but it is not going to be installed
 xfonts-scalable : Depends: xfonts-utils but it is not going to be installed
 xml-core : Depends: sed (>= 4.1.2-8) but it is not going to be installed
 xorg:amd64 : Depends: xorg-docs-core:amd64 but it is not installable
 xscreensaver-data:amd64 : Depends: libwww-perl:amd64 but it is not installable
 xserver-common : Depends: x11-xkb-utils but it is not going to be installed
                  Recommends: xauth but it is not going to be installed
 zlib1g-dev : Depends: libc6-dev but it is not going to be installed or
                       libc-dev
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

**Comment by M3meZ** [comment]
Fixed It

**Comment by guppy42** [comment]
Feel free to write HOW you fixed it, and maybe even add it to the wiki. Others may encounter the same problem and having a solution searchable would be immensely helpful then

**Comment by M3meZ** [comment]
I Fixed it by Using Chromium Cause Opera's C&P Didn't Want To Work
