### ISSUE TITLE
Hooking problem

### ISSUE THREAD

**Issue by InusualZ** [MCMrARM/mcpelauncher-linux#18]
Sometimes when you hook a function, the function got called but when you try to call the original function it crash.

It happens with:

> I18::get(std::string const&, std::vectorstd::string const&)
> Item::addBlockItems()
> BlockEntity::initBlockEntities
> BlockEntityFactory::createBlockEntity

**Comment by sliceofcode** [comment]
I'm pretty sure this isn't specific to MCPELauncher-linux, I've had these kinds of problems when using BlockLauncher, too.

**Comment by InusualZ** [comment]
You have tried to hook does methods in blocklauncher? Especially does?

**Comment by InusualZ** [comment]
I have tested does methods in blocklauncher and work fine so is a SubHook problem, bug, error, etc...

**Comment by MCMrARM** [comment]
Yes it is a SubHook problem. Any other hooking libraries you are aware of that could be used in this project?

**Comment by InusualZ** [comment]
Nope, I was trying to find a replacement but with no luck :(

**Comment by MCMrARM** [comment]
This might be improved as in 0.15 everything can be hooked using PLT.

**Comment by InusualZ** [comment]
Hey @MCMrARM SubHook got a bug fixed, maybe related to this issue. If that doesn't fix the issue there is another library that you could use [FuncHook](https://github.com/kubo/funchook)

**Comment by MCMrARM** [comment]
The PLT hooking method is implemented, this is no longer an issue since a while.
