### ISSUE TITLE
'mcplauncher' binary is not being created.

### ISSUE THREAD

**Issue by pwnrandom** [MCMrARM/mcpelauncher-linux#180]
Compiling is working, but its getting an error before it can create the 'mcpelauncher' binary.
This is what the log says:

"raute@0x00:~/app/mcpelauncher/mcpelauncher-linux$ make
[  4%] Linking CXX executable mcpelauncher
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In Funktion `my_pthread_attr_getstackaddr':
hooks.c:(.text+0x3f8): Warnung: the use of `pthread_attr_getstackaddr' is deprecated, use `pthread_attr_getstack'
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In Funktion `my_pthread_attr_setstackaddr':
hooks.c:(.text+0x3d7): Warnung: the use of `pthread_attr_setstackaddr' is deprecated, use `pthread_attr_setstack'
/usr/bin/ld: cannot find -lEGL
/usr/bin/ld: cannot find -lGLESv2
collect2: error: ld returned 1 exit status
CMakeFiles/mcpelauncher.dir/build.make:607: die Regel für Ziel „mcpelauncher“ scheiterte
make[2]: *** [mcpelauncher] Fehler 1
CMakeFiles/Makefile2:67: die Regel für Ziel „CMakeFiles/mcpelauncher.dir/all“ scheiterte
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Fehler 2
Makefile:83: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2"

Its a bit german. I can translate if needed.

**Comment by guppy42** [comment]
The error is self explanatory;

/usr/bin/ld: cannot find -lEGL
/usr/bin/ld: cannot find -lGLESv2


Please make sure to install the prerequisites

**Comment by pwnrandom** [comment]
My bad, thanks for your help. The binary has been created. Last thing missing for me seems to be an x86 .apk. The Play Store api seems not to be working for me but this is another issue. Thanks for your help, this can be closed I guess.

**Comment by guppy42** [comment]
Try the APK download branch, a lot of work has been put into making it more user friendly- I believe it even downloads the apk it self during compilation

**Comment by Tarik02** [comment]
@guppy42, no, it won't download apk while installing. You need to login your Google account with bought mcpe.

**Comment by guppy42** [comment]
Uhm yes of course you need an account that had bought the game - this is not pirate software...
