### ISSUE TITLE
[APK-DOWNLOAD] MCMrARM Can You Add extract.sh into apkdownload

### ISSUE THREAD

**Issue by M3meZ** [MCMrARM/mcpelauncher-linux#183]
just want to test the new libaries u added in the new branch

**Comment by MCMrARM** [comment]
No. Extracting is now done natively.

**Comment by Tarik02** [comment]
./mcpelauncher setup mcpe.apk

**Comment by M3meZ** [comment]
lel thx @Tarik02

**Comment by MCMrARM** [comment]
actually... ./mcpelauncher extract mcpe.apk
