### ISSUE TITLE
[APK-Download] zip.h error???

### ISSUE THREAD

**Issue by M3meZ** [MCMrARM/mcpelauncher-linux#184]
(xenial)exo@localhost:~/Desktop/mcpelauncher-linux-apk-download$ make
[  2%] Building CXX object CMakeFiles/mcpelauncher.dir/src/main.cpp.o
In file included from /home/exo/Desktop/mcpelauncher-linux-apk-download/src/main.cpp:38:0:
/home/exo/Desktop/mcpelauncher-linux-apk-download/src/extract.h:4:17: fatal error: zip.h: No such file or directory
compilation terminated.
CMakeFiles/mcpelauncher.dir/build.make:446: recipe for target 'CMakeFiles/mcpelauncher.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/mcpelauncher.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mcpelauncher.dir/all' failed
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2

**Comment by MCMrARM** [comment]
Install 32-bit libzip?
