### ISSUE TITLE
Make Error 2

### ISSUE THREAD

**Issue by M3meZ** [MCMrARM/mcpelauncher-linux#186]
(xenial)exo@localhost:~/Desktop/mcpelauncher-linux-apk-download$ make
[ 53%] Built target gplayapi
[ 53%] Linking CXX executable mcpelauncher
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_getstackaddr':
hooks.c:(.text+0x43f): warning: the use of `pthread_attr_getstackaddr' is deprecated, use `pthread_attr_getstack'
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_setstackaddr':
hooks.c:(.text+0x41e): warning: the use of `pthread_attr_setstackaddr' is deprecated, use `pthread_attr_setstack'
failed to create symbolic link '/home/exo/Desktop/mcpelauncher-linux-apk-download/src/initial_setup_resources' because existing path cannot be removed: Is a directory
CMakeFiles/mcpelauncher.dir/build.make:1001: recipe for target 'mcpelauncher' failed
make[2]: *** [mcpelauncher] Error 1
make[2]: *** Deleting file 'mcpelauncher'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mcpelauncher.dir/all' failed
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Tarik02** [comment]
```bash
cd build
cmake ..
make
```

**Comment by M3meZ** [comment]
sry i forgot to close it i solved it yesterday
