### ISSUE TITLE
[APK-DOWNLOAD] Launcher crashes when logging in Xbox Live

### ISSUE THREAD

**Issue by Encritary** [MCMrARM/mcpelauncher-linux#187]
Error:
`terminate called after throwing an instance of 'std::runtime_error'`
`  what():  Failed to find encrypted data`
`Aborted (core dumped)`

**Comment by Encritary** [comment]
It didn't happend before last two commits.

**Comment by Encritary** [comment]
MCPE: 1.2.0.25

**Comment by MCMrARM** [comment]
This means "Failed to log in to xbox live in fact", dunno why, might investigate.

**Comment by MCMrARM** [comment]
Also last 2 commits have absolutely nothing to do with this, perhaps just a temporary issue.

**Comment by Tarik02** [comment]
Did you mean this one https://github.com/MCMrARM/mcpelauncher-linux/commit/cf5ad889513088160b926ac37bb5487ef69d7355, @Encritary?

**Comment by Tarik02** [comment]
@Encritary, maybe. But it is not working for me too.

**Comment by M3meZ** [comment]
idk but its working for me

**Comment by MCMrARM** [comment]
Also, another possible issue is some timezone issue. I sadly am unable to reproduce this currently.

**Comment by Tarik02** [comment]
@MCMrARM maybe, because we live in different timezones(you, Encritary, I)

**Comment by Encritary** [comment]
@MCMrARM this isn't working yet

**Comment by MCMrARM** [comment]
Yeah timezone issue likely. If possible could you post the line before the `terminate called after throwing` line (assuming there are no tokens in it)?

**Comment by Encritary** [comment]
@MCMrARM here you are, everything below OnBrowserCreated, I just typed my email and pass: 

> BrowserApp::OnBrowserCreated 1
XboxLoginBrowserHandler::OnContextCreated
Get Property HasMultipleUsers
Get Property PfUsernames
Set Property AuthenticationBuffer = 
Set Property Password = 
XboxLoginBrowserHandler::OnContextCreated
Get Property HasMultipleUsers
Get Property PfUsernames
Get Property Password
Get Property AuthenticationBuffer
Set Property DAToken = <EncryptedData xmlns="http://www.w3.org/2001/04/xmlenc#" Id="BinaryDAToken0" Type="http://www.w3.org/2001/04/xmlenc#Element"><EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#tripledes-cbc"></EncryptionMethod><ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:KeyName>http://Passport.NET/STS</ds:KeyName></ds:KeyInfo><CipherData><CipherValue>CXECsOUcHbfKWZqFCFiKNi6zf80xwc4kwB/pL7zKeMGG/X+SLk1X9U7hxk+eYIgsUQ87pfe1HqGpbThsDvwIH0mD47H/vvAmqoaVuQZ4byFmhHHXDiJkik2P4EhlaYDskzzZdutDgOU25eiLe7MelxuS9Up77ero53NeD6OyIAzIzUIC3DOiku+nv7WrnfXjnb/6+Xw9bGGDznA24QYfdSTVPtPpIhMUNdtAwd8U/Sagp4+OOq7NG714a1RO/OlDjS/ECfS7SoH6tigFidh48xCCWNSXxyU+ekybM2MK9D978GlkEhQI9UyC7gZzXKAVL1u2seiQFusEgoUvPIXrZiZY9Pss9uqNh+ZjUIgenpn7BY8CpsvSbhyRrla2Ect+JtKxNOPhktBV+gcczpLF0bY1xB725NGYzCL/jLghKsLWosG5+UF91ix+VTlIrM6GQQ2DkI5ffJlxc8+c9Brs4o8vW9wn1MKJW9wxCagy60nNCfjXlzg9b/Na4RBdGwZYZGb0gMqvA+EjrFIRMIpdN8OzNxMN9wB72leEjnelEf+GZGD+Zhq5nVwLGIpPYbpUHlApBpncUX+mKGR5dRTHA9QHScTlf6bnskuoIyGE8jhumSW30DcBBILqSr7PaUscIXyY7ad/ee0ixU7ICM1vjEJdSnSUVMdRUnvYIEk3FOiNvDMNyDVAob1YBnVBJYtvTw==</CipherValue></CipherData></EncryptedData>
Set Property DASessionKey = DPv6XzaKToQj3rsiTnkJBg2VEokRUtk8
Set Property DAStartTime = 2017-09-08T05:21:44Z
Set Property DAExpires = 2017-12-07T05:21:44Z
Set Property STSInlineFlowToken = DcJsDK9YyE4t4V47rhV!r9rMDDMhuFgS1qDVxDILPPc*KNiofrb1diOY3XEMg3dFzDT4WEgleqhbZby98!uLHqNqmF4hsVPUtd*bz65nCTNbQRLEMSzf9qPn7l1QkOjWFw$$
Set Property FirstName = 
Set Property LastName = 
Set Property CID = 
Set Property PUID = 
Set Property Username = encritary@gmail.com
Set Property SigninName = encritary@gmail.com
Set Property BackURL = https://login.live.com/ppsecure/InlineLogin.srf?id=80604&platform=android2.1.0504.0524&client_id=android-app%3A%2F%2Fcom.mojang.minecraftpe.H62DKCBHJP6WXXIV7RBFOGOL4NAK4E6Y&cobrandid=90023&phone=&email=&uaid=4716bf4fb95b4fc882506e05f1f33efa&pid=15181&sicxt=1&contextid=7803D5F620543793&bk=1504848092&vv=1600&loginfmt=encritary%40gmail.com&mkt=EN-US&lc=1033
Send https://login.live.com/RST2.srf: <?xml version="1.0" encoding="UTF-8"?><s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:ps="http://schemas.microsoft.com/Passport/SoapServices/PPCRL" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:saml="urn:oasis:names:tc:SAML:1.0:assertion" xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wssc="http://schemas.xmlsoap.org/ws/2005/02/sc" xmlns:wst="http://schemas.xmlsoap.org/ws/2005/02/trust"><s:Header><wsa:Action s:mustUnderstand="1">http://schemas.xmlsoap.org/ws/2005/02/trust/RST/Issue</wsa:Action><wsa:To s:mustUnderstand="1">https://login.live.com/RST2.srf</wsa:To><wsa:MessageID>1504848104773</wsa:MessageID><ps:AuthInfo xmlns:ps="http://schemas.microsoft.com/Passport/SoapServices/PPCRL" Id="PPAuthInfo"><ps:BinaryVersion>11</ps:BinaryVersion><ps:DeviceType>Android</ps:DeviceType><ps:HostingApp>{F501FD64-9070-46AB-993C-6F7B71D8D883}</ps:HostingApp><ps:InlineUX>Android</ps:InlineUX><ps:ConsentFlags>1</ps:ConsentFlags><ps:IsConnected>1</ps:IsConnected><ps:ClientAppURI>android-app://com.mojang.minecraftpe.H62DKCBHJP6WXXIV7RBFOGOL4NAK4E6Y</ps:ClientAppURI></ps:AuthInfo><wsse:Security><EncryptedData xmlns="http://www.w3.org/2001/04/xmlenc#" Id="BinaryDAToken0" Type="http://www.w3.org/2001/04/xmlenc#Element"><EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#tripledes-cbc"></EncryptionMethod><ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#"><ds:KeyName>http://Passport.NET/STS</ds:KeyName></ds:KeyInfo><CipherData><CipherValue>CXECsOUcHbfKWZqFCFiKNi6zf80xwc4kwB/pL7zKeMGG/X+SLk1X9U7hxk+eYIgsUQ87pfe1HqGpbThsDvwIH0mD47H/vvAmqoaVuQZ4byFmhHHXDiJkik2P4EhlaYDskzzZdutDgOU25eiLe7MelxuS9Up77ero53NeD6OyIAzIzUIC3DOiku+nv7WrnfXjnb/6+Xw9bGGDznA24QYfdSTVPtPpIhMUNdtAwd8U/Sagp4+OOq7NG714a1RO/OlDjS/ECfS7SoH6tigFidh48xCCWNSXxyU+ekybM2MK9D978GlkEhQI9UyC7gZzXKAVL1u2seiQFusEgoUvPIXrZiZY9Pss9uqNh+ZjUIgenpn7BY8CpsvSbhyRrla2Ect+JtKxNOPhktBV+gcczpLF0bY1xB725NGYzCL/jLghKsLWosG5+UF91ix+VTlIrM6GQQ2DkI5ffJlxc8+c9Brs4o8vW9wn1MKJW9wxCagy60nNCfjXlzg9b/Na4RBdGwZYZGb0gMqvA+EjrFIRMIpdN8OzNxMN9wB72leEjnelEf+GZGD+Zhq5nVwLGIpPYbpUHlApBpncUX+mKGR5dRTHA9QHScTlf6bnskuoIyGE8jhumSW30DcBBILqSr7PaUscIXyY7ad/ee0ixU7ICM1vjEJdSnSUVMdRUnvYIEk3FOiNvDMNyDVAob1YBnVBJYtvTw==</CipherValue></CipherData></EncryptedData><wsse:BinarySecurityToken ValueType="urn:liveid:sha1device" Id="DeviceDAToken">ct=1504848105&amp;hashalg=SHA256&amp;bver=11&amp;appid=%7BF501FD64-9070-46AB-993C-6F7B71D8D883%7D&amp;da=%3CEncryptedData%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmlenc%23%22%20Id%3D%22BinaryDAToken0%22%20Type%3D%22http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmlenc%23Element%22%3E%3CEncryptionMethod%20Algorithm%3D%22http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmlenc%23tripledes-cbc%22%2F%3E%3Cds%3AKeyInfo%20xmlns%3Ads%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2F09%2Fxmldsig%23%22%3E%3Cds%3AKeyName%3Ehttp%3A%2F%2FPassport.NET%2FSTS%3C%2Fds%3AKeyName%3E%3C%2Fds%3AKeyInfo%3E%3CCipherData%3E%3CCipherValue%3ECT33fTNNHLMj6VueYr3ROr0mcvCyFJxP5XMsGhDkU1tyq0thZMpQBTt0IUaBAUb9Q6oimKSmBzEM0erJs1rfkj3jNkXR4NWibgFu8mDiXtn6595rBamOffoYcn42U61oGAaGkHYo5nx%2FvMnJz6m2PWj%2BPd%2BDn733J9RR2BoGWOzt6jzuHBrvL6Mmqx4oo1rzbq4aSz7HsNbYgDvAK7gBnfjRWQzLhqyhZhNm9Lgry0s%2BppuoaU2ufAvIb9zqkZnak4cC0hHKbqhdyOOTBYLWdouFJ8NJvRVOeN%2BPVqjkFLmLfkpfPEF8ipEpcQJhhKf6UX8FoYJhv%2F5aXTqCO769E3%2FpRgSIjgTi5KReHExkkUgte4cp4Hv1VdZBoJ7SPETRx7uh9qUEwngUIuq2gLz%2FAygdtk2G%2BwCITzf5M6HjtXsv2pdrIl1A9CQ5WHUchFN3kFpBR3U0NYZKZqhHjMk0YTi2ApHn9v%2BotmPGGGXf2ETiKOomYtlEmdfDCHXgc4FeTExdfxpm6014FZKOXllcaYrTGonL7oWDhEI%2BE5nxcHOz00Wl3sP%2B8eparY2pjRmxKRuJrRq0MoR6XRlxO3CMnduWgZSjVf8QZoFVi1xhJLupgcPNOYCflpRs9X7E9So6f374lKLxGtKVHIEEnPO3S6EgOirIWtR0VndOj3qFxffvwmxdBW7I8Ek83UWPGCSyQ5K%2BNPHr3uS1cKQ17QCgFSAnoQ6zsoPOm1vH4JtOFmjs%3C%2FCipherValue%3E%3C%2FCipherData%3E%3C%2FEncryptedData%3E&amp;nonce=lVqudO7a0hAvjWoqK9Qe2cE89H%2FuoeeHq7aeCrmyskA%3D&amp;hash=usETU5Ses955%2BkY2Qp8NpjCN9GIKbIVPe4BoDFAM%2FQA%3D</wsse:BinarySecurityToken><wssc:DerivedKeyToken wsu:Id="SignKey" Algorithm="urn:liveid:SP800-108CTR-HMAC-SHA256"><wsse:RequestedTokenReference><wsse:KeyIdentifier ValueType="http://docs.oasis-open.org/wss/2004/XX/oasis-2004XX-wss-saml-token-profile-1.0#SAMLAssertionID"/><wsse:Reference URI=""/></wsse:RequestedTokenReference><wssc:Nonce>9CJ7lmn2heWbi4gQWeLFtO7bYc1D2hv68QkiHAj6er8=</wssc:Nonce></wssc:DerivedKeyToken><wsu:Timestamp xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="Timestamp"><wsu:Created>2017-09-08T05:21:44Z</wsu:Created><wsu:Expires>2017-09-08T05:26:44Z</wsu:Expires></wsu:Timestamp><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo xmlns="http://www.w3.org/2000/09/xmldsig#"><CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"></CanonicalizationMethod><SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#hmac-sha256"></SignatureMethod><Reference URI="#PPAuthInfo"><Transforms><Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"></Transform></Transforms><DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></DigestMethod><DigestValue>f8hKv0qDRYsC1V2Kj874CaxXu0qyJ9OSNqNfXO0vUe8=</DigestValue></Reference><Reference URI="#Timestamp"><Transforms><Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"></Transform></Transforms><DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></DigestMethod><DigestValue>TfzJOOmgW1Ihb7v/zwJj5P//zxP5+yykR6+W494e44k=</DigestValue></Reference><Reference URI="#RSTS"><Transforms><Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"></Transform></Transforms><DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></DigestMethod><DigestValue>jKhg+IvDQRiH3Tb2tI4bIrGCYfbhBPcNUXwbtWP7h5Q=</DigestValue></Reference></SignedInfo><SignatureValue>qBqEpTHgkT4HGQ4HRQjqCKMtQSsfiUAyNqFs0d8Myqc=</SignatureValue><KeyInfo><wsse:SecurityTokenReference><wsse:Reference URI="#SignKey"/></wsse:SecurityTokenReference></KeyInfo></Signature></wsse:Security></s:Header><s:Body><ps:RequestMultipleSecurityTokens xmlns:ps="http://schemas.microsoft.com/Passport/SoapServices/PPCRL" Id="RSTS"><wst:RequestSecurityToken xmlns:wst="http://schemas.xmlsoap.org/ws/2005/02/trust" Id="RST0"><wst:RequestType>http://schemas.xmlsoap.org/ws/2005/02/trust/Issue</wst:RequestType><wsp:AppliesTo xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"><wsa:EndpointReference xmlns:wsa="http://www.w3.org/2005/08/addressing"><wsa:Address>http://Passport.NET/tb</wsa:Address></wsa:EndpointReference></wsp:AppliesTo></wst:RequestSecurityToken><wst:RequestSecurityToken xmlns:wst="http://schemas.xmlsoap.org/ws/2005/02/trust" Id="RST0"><wst:RequestType>http://schemas.xmlsoap.org/ws/2005/02/trust/Issue</wst:RequestType><wsp:AppliesTo xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy"><wsa:EndpointReference xmlns:wsa="http://www.w3.org/2005/08/addressing"><wsa:Address>user.auth.xboxlive.com</wsa:Address></wsa:EndpointReference></wsp:AppliesTo><wsp:PolicyReference xmlns:wsp="http://schemas.xmlsoap.org/ws/2004/09/policy" URI="mbi_ssl"></wsp:PolicyReference></wst:RequestSecurityToken></ps:RequestMultipleSecurityTokens></s:Body></s:Envelope>
Reply: <?xml version="1.0" encoding="utf-8" ?><S:Envelope xmlns:S="http://www.w3.org/2003/05/soap-envelope" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:wst="http://schemas.xmlsoap.org/ws/2005/02/trust" xmlns:psf="http://schemas.microsoft.com/Passport/SoapServices/SOAPFault"><S:Header><wsa:Action xmlns:S="http://www.w3.org/2003/05/soap-envelope" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="Action" S:mustUnderstand="1">http://schemas.xmlsoap.org/ws/2005/02/trust/RSTR/Issue</wsa:Action><wsa:To xmlns:S="http://www.w3.org/2003/05/soap-envelope" xmlns:wsa="http://www.w3.org/2005/08/addressing" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="To" S:mustUnderstand="1">http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</wsa:To><wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wssc="http://schemas.xmlsoap.org/ws/2005/02/sc"><wsu:Timestamp xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" wsu:Id="TS"><wsu:Created>2017-09-08T05:21:46Z</wsu:Created><wsu:Expires>2017-09-08T05:26:46Z</wsu:Expires></wsu:Timestamp><wssc:DerivedKeyToken wsu:Id="SignKey" Algorithm="urn:liveid:SP800-108CTR-HMAC-SHA256"><wsse:SecurityTokenReference><wsse:Reference URI="o+pCoefb6XCLZlnZ8EMi+G9hyKI="></wsse:Reference></wsse:SecurityTokenReference><wssc:Nonce>y1gAvM7GP6TjiZWKZUdA1RGQ2wZbEW+jquO7jRK0Xic=</wssc:Nonce></wssc:DerivedKeyToken><wssc:DerivedKeyToken wsu:Id="EncKey" Algorithm="urn:liveid:SP800-108CTR-HMAC-SHA256"><wsse:SecurityTokenReference><wsse:Reference URI="o+pCoefb6XCLZlnZ8EMi+G9hyKI="></wsse:Reference></wsse:SecurityTokenReference><wssc:Nonce>DpGQ5RxnaedEx0PLnRJ4sLjqWtEFBgiNqPpwD1cd714=</wssc:Nonce></wssc:DerivedKeyToken><Signature xmlns="http://www.w3.org/2000/09/xmldsig#"><SignedInfo><CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"></CanonicalizationMethod><SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#hmac-sha256"></SignatureMethod><Reference URI="#EncPsf"><Transforms><Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"></Transform></Transforms><DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></DigestMethod><DigestValue>Ikx8IfpySL2A8Y2+3AbemAv+ebA90EluNLzm4c6O1PY=</DigestValue></Reference><Reference URI="#To"><Transforms><Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"></Transform></Transforms><DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></DigestMethod><DigestValue>bdqxjfqbXAvnW37B+I0LGQNCFrl4hGLZ/joOFUKtayc=</DigestValue></Reference><Reference URI="#Action"><Transforms><Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"></Transform></Transforms><DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></DigestMethod><DigestValue>I9OmA6/3cHJ2+mtJxFNoY3p1Pky2heThzqT05pH0EK8=</DigestValue></Reference><Reference URI="#TS"><Transforms><Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"></Transform></Transforms><DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256"></DigestMethod><DigestValue>TmuqzMnbOorawnhIiTqEntTLEPrZJhsYD48YIXNTxXI=</DigestValue></Reference></SignedInfo><SignatureValue>bGUTFVIv8fBa36wgxWXdRQNQ5VZ053VjxdnDs9TZDck=</SignatureValue><KeyInfo><wsse:SecurityTokenReference><wsse:Reference URI="#SignKey"></wsse:Reference></wsse:SecurityTokenReference></KeyInfo></Signature><e:ReferenceList xmlns:e="http://www.w3.org/2001/04/xmlenc#"><e:DataReference URI="#EncPsf" /></e:ReferenceList></wsse:Security><psf:EncryptedPP xmlns:psf="http://schemas.microsoft.com/Passport/SoapServices/SOAPFault"><EncryptedData xmlns="http://www.w3.org/2001/04/xmlenc#" Id="EncPsf" Type="http://www.w3.org/2001/04/xmlenc#Element"><EncryptionMethod Algorithm="http://www.w3.org/2001/04/xmlenc#aes256-cbc"></EncryptionMethod><KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#"><wsse:SecurityTokenReference xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><wsse:Reference URI="#EncKey"></wsse:Reference></wsse:SecurityTokenReference></KeyInfo><CipherData><CipherValue>Tskhb/hoy1bPqUvUNm0OWdLr6dHSQhNqQ9gMV1SJqAuOEZlIC79CrMGDRxSQnUd+MeeQsqbOAt0J7V5iFav32xVu5m2EN2NgKG2zeZLI3bzy7AM22meBONxTD9BQ12fkjCbi/GqOUos4o/IrwDqctCOCUHcAS9jLVJLNNyTEqqzsdQirzuLqm4RT+3ZPduYx2N4Yxyfp2EL8QLa6sVw7fSOOeXj4cvVVfQZznZj4jLMA32ceDp6fjPGTGYmosm21UqNcm+Rkt84iPnUDvjV2yMTn+d+PGk/ns5fP52OeUpeAWbuOmsvHeomIyXXie3hHqx6F+3vJ02GVLHLjp8a5cptqOTE9vhcvpqzrzSRT0GJ6Yhao+5jKR0T4EltxKtsUKi7pKxnWKQnqgA0UOsNCl9SPf9V/d/FdWDu9oZ5wnBZP1CGPFUHHrQE4/BsfZ9pcyNXW5n5WhGoAGM9ITFkEergBpNiulfOyVrIAdL3Vo0KsNoIO7WrB4raqM7mzbRSCd2tq+BYRmqAzzy6tWYUY81PiyJrwlR/Y0UuarlaQ/2ZxiIoFYEqJ7IYurbhZgkLy794X6jjWzFQSbtwHKYLNTYe7erOPRoWyOoYpoa/kR+MaxpDc6ANge+Ovf23tPWYfI7Pj4zG3Se/L2IrT0KreZLs8ZsF6qrZhZ5OoCI5GWyWzJNugsGUgAbylXDEOiaoblNRiEnLWbBnCbgBWH9lZmH06OkIV7B/AYVB+n4lYWE3kGYbsL4PDcWI9ZYFXVUax4ocfcrLsJgzzFyN+x2seS+2Hi681utinF76wMEckpAgi5q/ZhKcvyMYL4OUDAuUcTuclj32dBm760lcVtEMOmyE6jL606C6qADxxZej5h++K9i1HCILCuO1pM/RhBSI6CyIHiOv1A6qnCLm8o/U0HQMOpQJNETQMmfcRteulzhp2XNqkts0oNQyog+AMoQMI7jmjwJUtNsnzZBco0ZBOPDUUh9qoSq13/kmimQMFigtXPHUCMmChek0/txBQN5TuFQxycBr6o4ZoMavQi0Zg7dF+Xd6NwD8PuUwQ/DjsqqgCrwoQhDaIi7LXtiCVOzuHoC8Ua3lEDtZkLGVaWaNQ9Klly8Lmd/l0BG8rrBZnUBzPk3GLJOUTCkwlrDmyh2B1HS5D5lxq/HKUJFiVXK5TWSaMTiyD/xjY7iGyrP1gaF2zso/5Fv6LXHL2s8P/xiit0vnRyvUxnXzzVGoK0F1LT6MYYijtpLGp5b1MgMKBoQrE/K9jojvhHpf7jNg3qvSLcqG13N9b2NbNP+l86xbYKHktE9HBXUfnMImB3ROC6AsU/ozZrzpd4QBNBAP/S9xi5zbpxQVy+u3k4ZUTcHqzxLB9qQ3yITwyJB3emFqiEvYMEr6xhSXlCH8eoSVIfhyZZYJJZpaMSSLtWIXe3PRCm0KfazRaTP/Cd0iuiXJzMCV7YX0M1H34kqng8kcWV4D1cZgeB9Ic0M6i05Ie+e/x5+IzHkw+d1KI1EekZ1zmhOkMNljdTKUqUyEWugZR/2ahGHXvMxQjYrsFgbzgjS+dIKKfNeTcf9MGi0Xii//P/YXVnmxhcfFuzJwQIAfI4fwGSfwaM6MqzmwpyYZ1rQgnGZOx92a7cxxUAb0mTthETLkCyZNyfzYyuw4rUfdkwj4lHrYKzJfGQBWVVzsN4vTtpmBqhFitPyI+O6KWzpDjCcdm83kvvpM3HNwNIKtxYBuyY6KmYYkt3+4WFFIZ9EnU6uDFcyyrlQqMZjSgUIAlS6+DlLO7/ODjO1RICzrDBJCqU6VIDAQL8OgHe3jJtwbY4U+WuLdKRYvshagrRsBrqRbSfm13a47mqfqBAR8jMRANYNgDi8nYhr5OVZXX/s9Bu/qNXI+QnuEKsGQnykVaNJ5ys0fYRI2K16WikWFlZA1DhgG/ddflNw0EzvSHy821cKMF5uHkBAFp20cATF5StDnBeVGvL68LSoSvLha/CBmSwHBSsnnez4rJZVf4UHCC83jl/vN0WDhZo4AunJPQXraTaMrVVqoO/d6xl1cem6Kbwr203mHcH6487pInmV4DBoGRhXUrZ15Qd1Vd0kD5ubMmn+EqxP2frV9Odxt7NUA/mLVEt3m4QQcWk5aZFaK8HIOtae5xJ+W0ym2nctIxEf0arXZbgY6Bo/cOcerl+nyOB/5CNgQoEaYF9Ds7PK158r/REFiI8/TmpTJ9kMNHCdF7r5tkw4rjLm9InGIGnRs2Z6lkKLYiGRsBFmcApybBxF0qVTxsTM+CP5nhpW6ndl9Smr95PwB3F8qDgaDsZOpKk8VNwPcdyuRv1CuMd7GLvKMJkN3T2PRmkU3sRFIlMPkwA2AE6JqGdlQdJC4AuaCM8hvPM9Ws2oMNIKTXAaoNeTyP3Hd9btJEEKdbl5DrxDBCa/58w9NtURzQnVRqxRafZsIO1OQPWrXsCw7HWjv7jpXnyMaNxRkB9t6LBWLIIEPnY5c40bwDeCn6SQ187dPIREenpYd8tX3B4swqbwlVnXeM8OrpLre8LqV3NDIVBYpJpKHv4i3YCXoceL6ZZp0rxrtQ6iA7ruSL6gnELOYNXkws3/k7x+4aVFRRr7a3mypJbXWBm3dhxiMbL9HAbP+ldPlVsirQ13WQgBHpGWkmpmkuOLZasWOQwG4nHqmQkAzpu9bsDwx8wTQs2MFwqe69</CipherValue></CipherData></EncryptedData></psf:EncryptedPP></S:Header><S:Body><S:Fault><S:Code><S:Value>S:Sender</S:Value><S:Subcode><S:Value>wst:FailedAuthentication</S:Value></S:Subcode></S:Code><S:Reason><S:Text xml:lang="en-US">Authentication Failure</S:Text></S:Reason><S:Detail><psf:error><psf:value>0x800488fb</psf:value><psf:internalerror><psf:code>0x800434c0</psf:code><psf:text>Designates account security interrupt error code, when user account is found to be in service abuse mode&#x000D;&#x000A;</psf:text></psf:internalerror></psf:error></S:Detail></S:Fault></S:Body></S:Envelope>

**Comment by MCMrARM** [comment]
Can you log in with the same account on your phone (please clear MCPE's data before though)?

**Comment by Encritary** [comment]
Account was somehow temporally disabled. Issue is gone after logging in from xbox.com and fixing it with phone number.

**Comment by Tarik02** [comment]
The same...

**Comment by MCMrARM** [comment]
Anyone who has this issue paste the content between <S:Body> </S:Body> from the line above the `terminate called` one but make sure it has no tokens inside (anything that looks like a string made up of seemingly random characters can be a token) as it can potentially be used to log onto your account.
