### ISSUE TITLE
(Gamepad-Support) Make Error 2

### ISSUE THREAD

**Issue by M3meZ** [MCMrARM/mcpelauncher-linux#191]
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_getstackaddr':
hooks.c:(.text+0x43f): warning: the use of `pthread_attr_getstackaddr' is deprecated, use `pthread_attr_getstack'
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_setstackaddr':
hooks.c:(.text+0x41e): warning: the use of `pthread_attr_setstackaddr' is deprecated, use `pthread_attr_setstack'
/usr/bin/ld: cannot find -levdev
collect2: error: ld returned 1 exit status
CMakeFiles/mcpelauncher.dir/build.make:1027: recipe for target 'mcpelauncher' failed
make[2]: *** [mcpelauncher] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mcpelauncher.dir/all' failed
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by M3meZ** [comment]
I Used cmake . . and make in build but still failed i did cmake . . in apk-download and it worked but in gamepad-support it doesn't work

**Comment by MCMrARM** [comment]
Install the evdev 32-bit library.

**Comment by M3meZ** [comment]
@MCMrARM Will Do rn

**Comment by M3meZ** [comment]
Thx
