### ISSUE TITLE
Cannot compile apk-download under Arch Linux.

### ISSUE THREAD

**Issue by Admicos** [MCMrARM/mcpelauncher-linux#193]
Everything up to date, was working perfectly before trying to update.

Tried running `make clean`, tried removing and re-creating the build directory. Nothing worked.

Here's my make log: https://gist.github.com/Admicos/04a314dc0cbe1c98da9e655e092798d7

**Comment by MCMrARM** [comment]
Indeed there was a system update that broke the file, I'll fix it in a while.

**Comment by MCMrARM** [comment]
Fixed! https://github.com/MCMrARM/mcpelauncher-linux/commit/9bbe67f6dc59798d3d43158bb03b4366e2292c9d
