### ISSUE TITLE
libfmod.so not copied to the install directory

### ISSUE THREAD

**Issue by guppy42** [MCMrARM/mcpelauncher-linux#194]
Wanted to try the apk-download branch and every thing went well untill it crashes with ;
```
loading native libraries
oslib: libGLESv2.so.2: 171533288
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to find data file: libs/native/libfmod.so.9.6
```

**Comment by guppy42** [comment]
Manually copying  libs/native to /usr/local/share/mcpelauncher/libs/ solves the issue - but still one would expect "make install" to do that

**Comment by MCMrARM** [comment]
https://github.com/MCMrARM/mcpelauncher-linux/commit/e1569afc53452d64df19fbaeb5a7e57a7b46092d
