### ISSUE TITLE
LAN Multiplayer working?

### ISSUE THREAD

**Issue by paul-acre88** [MCMrARM/mcpelauncher-linux#197]
I'd like to run a copy of MCPE on Ubuntu as an always-on, multiplayer server for my family.

**Ubuntu 16.04 LTS**
**APK is MCPE 1.1.2.50 x86**

Consulting the Wiki (README needs updating), I got mcpelauncher working, and I can launch a game which has multiplayer and LAN settings turned on. The Ubuntu machine isn't going through any routers, and it has no firewall turned on (for now).

From another device on another network (iOS running MCPE 1.2) I add an "external server" using the IP address of the Ubuntu machine and the default port 19132. I can see the server (green; 1 of 5 players connected, as expected) yet I cannot connect. When I try, I very briefly (and only occasionally) see a "Saving world" message, and then I get disconnected and sent back to the Servers tab.

Any suggestions for where I can find **logs** or other **debugging messages**, or any indication of what the problem is, to help track this down? Is this a feature that should even be working?

**Comment by MCMrARM** [comment]
It should be working (but it might be broken), I'll investigate it soon.

**Comment by guppy42** [comment]
You are trying to connect a 1.2 client to 1.1.2 server 1.2 was a pretty massive update so it no wonder that doesn't work

**Comment by MCMrARM** [comment]
^ Ah, thanks, I did not notice the version mismatch.

**Comment by paul-acre88** [comment]
Thanks, that seems to have worked OK. I got a LAN game running with a 1.2 client (iPad) successfully connecting to mcpelauncher running the apk-download branch on Ubuntu 16.04.

(Biggest problem I've seen so far is that mcpelauncher will crash as soon as I try to import a world, but that's a separate issue. Will open a separate ticket for that if I get the time.)
