### ISSUE TITLE
Make errors

### ISSUE THREAD

**Issue by justrobd** [MCMrARM/mcpelauncher-linux#199]
Hi, 
**EDIT: Did some further reading in the issues. Which caused me to switch branch to apk-download. Further information is in the next comment. **

Trying to compile the mcpelauncher and I am getting a couple of errors. The Cmake works without a problem. When I try to use 'make' I get a error and it doesn't finish compiling. 

BTW, My distro is Archlinux. I used the dependencies that are in the wiki for Archlinux and Manjaro. Perhaps I'm missing some dependencies.

me@archlinux ..uncher-linux.git/branches/1.2-xboxlive (svn)-[mcpelauncher-linux.git:156] % cmake .
-- The C compiler identification is GNU 7.2.0
-- The CXX compiler identification is GNU 7.2.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.11") 
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/libX11.so
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'egl'
--   Found egl, version 17.2.1
-- Found EGL: /usr/include  
-- Configuring done
-- Generating done
me@archlinux ..uncher-linux.git/branches/1.2-xboxlive (svn)-[mcpelauncher-linux.git:156] % make
Scanning dependencies of target mcpelauncher
[  3%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/cache.c.o
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/cache.c: In function ‘cache_update’:
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/cache.c:105:10: warning: ‘return’ with a value, in function returning void
   return NULL;
          ^~~~
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/cache.c:98:13: note: declared here
 static void cache_update()
             ^~~~~~~~~~~~
[  6%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/dlfcn.c.o
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/dlfcn.c: In function ‘hybris_dlerror’:
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/dlfcn.c:47:12: warning: return discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
     return android_dlerror();
            ^~~~~~~~~~~~~~~~~
[ 10%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c:24:0: warning: "_GNU_SOURCE" redefined
 #define _GNU_SOURCE
 
<command-line>:0:0: note: this is the location of the previous definition
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c: In function ‘my_pthread_attr_setstackaddr’:
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c:297:5: warning: ‘pthread_attr_setstackaddr’ is deprecated [-Wdeprecated-declarations]
     return pthread_attr_setstackaddr(realattr, stack_addr);
     ^~~~~~
In file included from /home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c:34:0:
/usr/include/pthread.h:364:12: note: declared here
 extern int pthread_attr_setstackaddr (pthread_attr_t *__attr,
            ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c: In function ‘my_pthread_attr_getstackaddr’:
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c:303:5: warning: ‘pthread_attr_getstackaddr’ is deprecated [-Wdeprecated-declarations]
     return pthread_attr_getstackaddr(realattr, stack_addr);
     ^~~~~~
In file included from /home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c:34:0:
/usr/include/pthread.h:356:12: note: declared here
 extern int pthread_attr_getstackaddr (const pthread_attr_t *__restrict
            ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c: In function ‘hybris_set_realrwlock’:
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c:844:20: warning: comparison between pointer and integer
     if (realrwlock <= ANDROID_TOP_ADDR_VALUE_RWLOCK) {
                    ^~
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c: In function ‘my_clearerr’:
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c:974:29: warning: passing argument 1 of ‘_get_actual_fp’ from incompatible pointer type [-Wincompatible-pointer-types]
     clearerr(_get_actual_fp(fp));
                             ^~
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c:959:14: note: expected ‘struct aFILE *’ but argument is of type ‘FILE * {aka struct _IO_FILE *}’
 static FILE *_get_actual_fp(struct aFILE *fp)
              ^~~~~~~~~~~~~~
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c: In function ‘my_fdopen’:
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c:993:25: warning: passing argument 1 of ‘fdopen’ makes integer from pointer without a cast [-Wint-conversion]
     FILE* file = fdopen(filename, mode);
                         ^~~~~~~~
In file included from /home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c:25:0:
/usr/include/stdio.h:265:14: note: expected ‘int’ but argument is of type ‘const char *’
 extern FILE *fdopen (int __fd, const char *__modes) __THROW __wur;
              ^~~~~~
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c: In function ‘my_readdir_r’:
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c:1286:5: warning: ‘readdir_r’ is deprecated [-Wdeprecated-declarations]
     int res = readdir_r(dir, &entry_r, &result_r);
     ^~~
In file included from /home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c:39:0:
/usr/include/dirent.h:183:12: note: declared here
 extern int readdir_r (DIR *__restrict __dirp,
            ^~~~~~~~~
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c: In function ‘my_scandirat’:
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c:1367:67: warning: passing argument 4 of ‘qsort’ from incompatible pointer type [-Wincompatible-pointer-types]
             qsort(result, nItems, sizeof(struct bionic_dirent *), compar);
                                                                   ^~~~~~
In file included from /home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c:29:0:
/usr/include/stdlib.h:712:13: note: expected ‘__compar_fn_t {aka int (*)(const void *, const void *)}’ but argument is of type ‘int (*)(const struct bionic_dirent **, const struct bionic_dirent **)’
 extern void qsort (void *__base, size_t __nmemb, size_t __size,
             ^~~~~
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c: In function ‘my_system_property_get’:
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c:1448:28: warning: passing argument 2 of ‘property_get’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
  return property_get(name, value, NULL);
                            ^~~~~
In file included from /home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c:57:0:
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/../include/hybris/properties.h:51:6: note: expected ‘char *’ but argument is of type ‘const char *’
  int property_get(const char *key, char *value, const char *default_value);
      ^~~~~~~~~~~~
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c: In function ‘convert_addrinfo’:
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c:1487:23: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
         ares->ai_next = convert_addrinfo(res->ai_next);
                       ^
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c: At top level:
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c:1543:15: error: ‘cfree’ undeclared here (not in a function); did you mean ‘free’?
     {"cfree", cfree },
               ^~~~~
               free
/home/me/builds/mcpelauncher-linux.git/branches/1.2-xboxlive/hybris/src/hooks.c:1789:16: error: ‘writev’ undeclared here (not in a function); did you mean ‘write’?
     {"writev", writev},
                ^~~~~~
                write
make[2]: *** [CMakeFiles/mcpelauncher.dir/build.make:111: CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/mcpelauncher.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by justrobd** [comment]
1.  Switched branch to apk-download
2.  Found and installed dependencies in issue #166. Execpt lib32-zip because apparently it can't be found on ArchLinux or the AUR. Any hints that I missed? 
3. Ran ./setup_cef.sh
4. Ran ./setup_bin_libs.sh
5.  Tried to compile without success: 
    me@archlinux ~/builds/mcpelauncher-linux/build (git)-[apk-download] % cmake ..
    CMake Error at CMakeLists.txt:34 (add_subdirectory):
    The source directory

    /home/me/builds/mcpelauncher-linux/gplay_api

    does not contain a CMakeLists.txt file.


    CMake Error at CMakeLists.txt:35 (set_target_properties):
    set_target_properties Can not find target to add properties to: gplaydl


-- Configuring incomplete, errors occurred!
See also "/home/me/builds/mcpelauncher-linux/CMakeFiles/CMakeOutput.log".
See also "/home/me/builds/mcpelauncher-linux/CMakeFiles/CMakeError.log".

**Comment by guppy42** [comment]
git submodule init
git submodule update

**Comment by justrobd** [comment]
@guppy42 @MCMrARM  I know it has to do with protobuf don't know why I installed all packages that ArchLinux and the AUR offer. 
[mcpe.txt](https://github.com/MCMrARM/mcpelauncher-linux/files/1335691/mcpe.txt)

**Comment by kris27mc** [comment]
You need [lib32-libzip](https://aur.archlinux.org/packages/lib32-libzip/) & [lib32-libprotobuf-git](https://aur.archlinux.org/packages/lib32-libprotobuf-git/).

**Comment by justrobd** [comment]
@kris27mc Thank you for maintaining those packages. I already had those packages installed though. Any other ideas/suggestions?

**Comment by jerbear64** [comment]
I'm having the same error. I also have lib32-libzip and lib32-libprotobuf installed.

**Comment by MCMrARM** [comment]
This was fixed with https://github.com/MCMrARM/mcpelauncher-linux/commit/9bbe67f6dc59798d3d43158bb03b4366e2292c9d

**Comment by jerbear64** [comment]
It still is not building for me, same error as before. To be specific, the issue doesn't seem to be with the compilation itself, but the final linking.  https://gist.github.com/jerbear6/289eeacc9b987c27b3a6a23463651c02

If it means anything, I'm using the lib32-protobuf-git package maintained by @kris27mc; there's no release build of lib32-protobuf in the AUR.

**Comment by jerbear64** [comment]
**Solved** by just compiling the latest release of libprotobuf rather than the lastest commit from git. This appears to be a breaking issue with the git version of libprotobuf right now.

**Comment by MCMrARM** [comment]
Mind reuploading the log? I can't access it by the link and would like to check it.

**Comment by jerbear64** [comment]
That's on me, looks like I accidentally erased one of the characters in the URL.

I've edited the link, it's good to go now.
