### ISSUE TITLE
Cant login to get apk

### ISSUE THREAD

**Issue by janisroze** [MCMrARM/mcpelauncher-linux#202]
I read in https://github.com/MCMrARM/Google-Play-API/issues/12
that i need to take the apk-download branch but how can i compile everythinf there and use the browser based auth implemented there?

**Comment by guppy42** [comment]
If only there was some way to search the issues for similar problems before creating a new issue...


https://github.com/MCMrARM/mcpelauncher-linux/issues/196#issuecomment-332191326
