### ISSUE TITLE
does 16.0 work

### ISSUE THREAD

**Issue by roxas55** [MCMrARM/mcpelauncher-linux#203]
i remember trying it because i needed it for my pvp clan thats in 16.0 rn but it would say a couple of stuff when i did ./mcpelauncher and it wouldnt start

**Comment by AryToNeX** [comment]
Mcpelauncher supports mcpe 1.1 in its master branch, 1.2 in apk-download branch. 0.16.0 is way too outdated

**Comment by roxas55** [comment]
oh ok thanks

**Comment by MCMrARM** [comment]
You can try to find a commit where this worked on 0.16; it will have it's own set of problems and is generally unsupported but should more or less work. Quickly looking at the commits it should work with this commit:
https://github.com/MCMrARM/mcpelauncher-linux/commit/f3bb376431a9c34c3acc1fde18223858e22d0555

Please note that if this issue gets enough attention I may consider also supporting one of the older versions on a separate branch.
