### ISSUE TITLE
Update dependencies/README

### ISSUE THREAD

**Issue by guppy42** [MCMrARM/mcpelauncher-linux#205]
The current list of dependencies is more or less voodoo magic passed down though successive builds - it would be a good idea to trim the list down to the libraries that are actually needed and add the ones that are currently missing

**Comment by MCMrARM** [comment]
I got down to the minimal dependencies for Ubuntu in #166.
Minimal: `cmake gcc-multilib g++-multilib zlib1g-dev:i386 libx11-dev:i386 libzip-dev:i386 libpng-dev:i386 uuid-dev:i386 libcurl4-openssl-dev:i386 libssl-dev:i386 libgles2-mesa-dev:i386`
CEF: `libgtk2.0-0:i386 libgtkglext1:i386 libasound2:i386 libnss3:i386 libxss1:i386 libgconf2-4:i386 libxtst6:i386 libudev1:i386`
Setup: `protobuf-compiler libprotobuf-dev:i386` (requires the CEF dependencies as well)

**Comment by MCMrARM** [comment]
This was added to README in the meanwhile.
