### ISSUE TITLE
Crashes when launching.

### ISSUE THREAD

**Issue by Yexeed** [MCMrARM/mcpelauncher-linux#207]
log: https://pastebin.com/nFFKes7A
Actually, its was launch before i installed the nvidia drivers. Its was launch, but i dont like low FPS, so i decided to install nvidia drivers.
System: Ubuntu 16.04.3 LTS x64
GPU: ASUS GTX 1050
Drivers: 387

**Comment by M3meZ** [comment]
Did It Work When U Launched It The First Time

**Comment by Yexeed** [comment]
Yes, it just like you said.

**Comment by guppy42** [comment]
Try recompiling

```git pull
sudo make clean install
mcpelauncher```

**Comment by Yexeed** [comment]
@guppy42 , it wasnt helped

**Comment by MCMrARM** [comment]
The log link has expired. Please repost it and reopen the issue if needed.
