### ISSUE TITLE
Cant run MCPE

### ISSUE THREAD

**Issue by AqyxHD** [MCMrARM/mcpelauncher-linux#211]
when i try to run mcpe i get this:
deniz@deniz-HP-Compaq-dc5700-Microtower:~/Schreibtisch/mcpelauncher-linux-master.2$ ./mcpelauncher
loading native libraries
oslib: libGLESv2.so: 147025760
oslib: /home/deniz/Schreibtisch/mcpelauncher-linux-master.2/libs/native/libfmod.so.8.2: 147027840
loading hybris libraries
loading MCPE
linker/home/deniz/Schreibtisch/mcpelauncher-linux-master/hybris/src/jb/linker.c:2010| ERROR: failed to link libminecraftpe.so
failed to load MCPE: Cannot load library: reloc_library[1343]:     0 cannot locate '_ZN4FMOD6System17set3DNumListenersEi'...

Please help me out. And is it possible to conecct to XBL?

**Comment by Tarik02** [comment]
What version of minecraft did you extracted?

**Comment by AqyxHD** [comment]
1.2.something

**Comment by Tarik02** [comment]
You are using master branch that are not for 1.2 version. Please, use xboxlive branch

**Comment by AqyxHD** [comment]
sorry im a total noob, but can i have the link?

**Comment by M3meZ** [comment]
Look In The Branches

**Comment by M3meZ** [comment]
And Select apk-download extract and do ./setup_cef.sh && ./setup_bin_libs.sh && ./download_icon.sh

Then do cmake and make

**Comment by M3meZ** [comment]
Also If U Have Errors With Compiling Look In The Issues

**Comment by AqyxHD** [comment]
when i do ./mcpelauncher i get the error 
Invalid machine command (memory dumped)

**Comment by AqyxHD** [comment]
btw i used to 1.2 branch not the 1.2 xbox live because i dont want to mess with 100 compiling issues
