### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by AqyxHD** [MCMrARM/mcpelauncher-linux#217]
when i do cmake .. i get:
denis@denis-HP-Compaq-dc5700-Microtower:~/mcpelauncher-linux/build$ cmake ..-- Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR) 
CMake Warning at CMakeLists.txt:28 (message):
  Protobuf not found.  Downloading the apk with a Google account will not be
  possible.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/denis/mcpelauncher-linux/build
denis@denis-HP-Compaq-dc5700-Microtower:~/mcpelauncher-linux/build$ cmake ..
-- Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR) 
CMake Warning at CMakeLists.txt:28 (message):
  Protobuf not found.  Downloading the apk with a Google account will not be
  possible.

-- Configuring done
-- Generating done
-- Build files have been written to: /home/denis/mcpelauncher-linux/build
denis@denis-HP-Compaq-dc5700-Microtower:~/mcpelauncher-linux/build$ 

but i want to use my Google acc. I did sudo apt-get install protobuf-compiler and i get the same error.
Please help ASAP

**Comment by guppy42** [comment]
If your still having this issue try the fix I present in #253
