### ISSUE TITLE
XBL crashes game

### ISSUE THREAD

**Issue by AqyxHD** [MCMrARM/mcpelauncher-linux#218]
when i log in into XBL it crashes after 20-30 seconds. Thats the log i get:
 Signal 11 received
Backtrace elements: 3
#0 /usr/local/share/mcpelauncher/bin/mcpelauncher(_Z12handleSignaliPv+0x62) [0x82adb12]
#1 [0xb7731cf0]
#2 HYBRIS xbox::services::system::auth_manager::initialize_default_nsal()+37 in libminecraftpe.so+0x26a2795 [0xac629795]
Dumping stack...
#17 HYBRIS xbox::services::system::auth_manager::initialize_default_nsal()+37 in libminecraftpe.so+0x26a2795 [0xac629795]
#60 HYBRIS xbox::services::system::auth_manager::initialize_default_nsal()+37 in libminecraftpe.so+0x26a2795 [0xac629795]
#388 HYBRIS xbox::services::system::auth_manager::initialize_default_nsal()+12 in libminecraftpe.so+0x26a277c [0xac62977c]
#405 HYBRIS xbox::services::system::auth_manager::initialize_default_nsal()+0 in libminecraftpe.so+0x26a2770 [0xac629770]
Signal 6 received
deniz@deniz-HP-Compaq-dc5700-Microtower:~$ 

I would love to play on Servers. Please help me

**Comment by AqyxHD** [comment]
If McMrARM does fix this Problem its even better then the Windows 10 version. Cheaper (the Playstore price is 7.99 Euro for me) and better FPS (60fps with recording on an Intel Core 2 Duo 1.83Ghz and onboard graphics with 2gb of Ram)

**Comment by M3meZ** [comment]
@AqyxHD I Consider Getting a Upgrade Since Windows 10 Has Less Problems

**Comment by MCMrARM** [comment]
I'll look into it today.

**Comment by AqyxHD** [comment]
@M3meZ What do you mean? I have the latest Version of W10 and im Dual booting with Mint

**Comment by MCMrARM** [comment]
I'll see what's broken and fix it, is what I meant.

**Comment by MCMrARM** [comment]
https://github.com/MCMrARM/mcpelauncher-linux/commit/aecbe81f22941d3a8add7319e4151b0b79287c29
