### ISSUE TITLE
libGLESv2.so: 151706304 libfmod.so.7.2: 151708320 Error on the bus (the core recorded image)

### ISSUE THREAD

**Issue by Docmine7** [MCMrARM/mcpelauncher-linux#22]
![2016-02-02-215644_1366x768_scrot](https://cloud.githubusercontent.com/assets/9872328/12768605/dfd17ada-c9f7-11e5-8f2b-08ade06d1cd1.png)

**Comment by MCMrARM** [comment]
Do you perhaps use a AMD CPU? I'll upload an alternative set of libraries soon.

**Comment by Docmine7** [comment]
I am using Intel CPU

**Comment by AryToNeX** [comment]
use the libs provided in #14
