### ISSUE TITLE
1.2.50 build 2 Support.

### ISSUE THREAD

**Issue by AqyxHD** [MCMrARM/mcpelauncher-linux#222]
I have saw on my phone that a new version of MCPE is out- 1.2.5 build 2. Please add support for that version, mcpelauncher-linux crashes when trying to launch

**Comment by MCMrARM** [comment]
https://github.com/MCMrARM/mcpelauncher-linux/commit/1a69ad51cb72b4f5f71a0c5906867ec00294267d
