### ISSUE TITLE
`make` fails on Arch

### ISSUE THREAD

**Issue by 10c8** [MCMrARM/mcpelauncher-linux#223]
When trying to build `master`, `1.2` or `1.2-xboxlive` on Arch, `make` fails with:

```
/tmp/mcpelauncher-linux/hybris/src/hooks.c: At top level:
/tmp/mcpelauncher-linux/hybris/src/hooks.c:1543:15: error: ‘cfree’ undeclared here (not in a function); did you mean ‘free’?
     {"cfree", cfree },
               ^~~~~
               free
/tmp/mcpelauncher-linux/hybris/src/hooks.c:1789:16: error: ‘writev’ undeclared here (not in a function); did you mean ‘write’?
     {"writev", writev},
                ^~~~~~
                write
```

**Solution:** You can fix this issue by editing `hybris/src/hooks.c`. Change line **1543** to:
```
{"cfree", free}
```
and line **1789** to:
```
{"writev", write}
```
Then run `make` again.

**Comment by guppy42** [comment]
cfree -> free is a no brainer;
http://www.linuxhowtos.org/manpages/3/cfree.htm:
> This function should never be used. Use free(3) instead. Starting with version 2.26, it has been removed from glibc.  

writev -> write
is actually different on glibc versions lower than 2.20 on systems running kernel 2.6.18 or older
if  your glibc version is higher than 2.20 there is no difference between the versions.

you can display your glibc version with `ldd --version` ( ubuntu 16.04 uses 2.23  )

**Comment by MCMrARM** [comment]
Note that it has been fixed on apk-download (which is now in master), and the branches mentioned in the issue are not supported.
