### ISSUE TITLE
CURL not found

### ISSUE THREAD

**Issue by AqyxHD** [MCMrARM/mcpelauncher-linux#226]
CMake Error at /usr/local/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CURL (missing: CURL_LIBRARY) (found version "7.47.0")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.9/Modules/FindCURL.cmake:48 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  gplay_api/CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/denis/mcpelauncher-linux/build/CMakeFiles/CMakeOutput.log".
See also "/home/denis/mcpelauncher-linux/build/CMakeFiles/CMakeError.log".

I have installed curl

**Comment by 10c8** [comment]
You need the 32-bit `libcurl` and not just the `curl` utility.

**Comment by AqyxHD** [comment]
I cant. I get this:
t install libcurl4-openssl-dev:i386
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.       
Statusinformationen werden eingelesen.... Fertig
Vorgeschlagene Pakete:
  libcurl4-doc:i386 libcurl3-dbg:i386 libidn11-dev:i386 libkrb5-dev:i386
  libldap2-dev:i386 librtmp-dev:i386
Die folgenden NEUEN Pakete werden installiert:
  libcurl4-openssl-dev:i386
0 aktualisiert, 1 neu installiert, 0 zu entfernen und 4 nicht aktualisiert.
Es müssen noch 0 B von 290 kB an Archiven heruntergeladen werden.
Nach dieser Operation werden 1.148 kB Plattenplatz zusätzlich benutzt.
(Lese Datenbank ... 274577 Dateien und Verzeichnisse sind derzeit installiert.)
Vorbereitung zum Entpacken von .../libcurl4-openssl-dev_7.47.0-1ubuntu2.4_i386.deb ...
Entpacken von libcurl4-openssl-dev:i386 (7.47.0-1ubuntu2.4) ...
dpkg: Fehler beim Bearbeiten des Archivs /var/cache/apt/archives/libcurl4-openssl-dev_7.47.0-1ubuntu2.4_i386.deb (--unpack):
 Versuch, gemeinsam benutztes »/usr/include/curl/curlbuild.h« zu überschreiben, welches verschieden von anderen Instanzen des Paketes libcurl4-openssl-dev:i386 ist
dpkg-deb: Fehler: Unterprozess einfügen wurde durch Signal (Datenübergabe unterbrochen (broken pipe)) getötet
Trigger für man-db (2.7.5-1) werden verarbeitet ...
Fehler traten auf beim Bearbeiten von:
 /var/cache/apt/archives/libcurl4-openssl-dev_7.47.0-1ubuntu2.4_i386.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by guppy42** [comment]
Delete the cached file and try again
/var/cache/apt/archives/libcurl4-openssl-dev_7.47.0-1ubuntu2.4_i386.deb

**Comment by AqyxHD** [comment]
i get the same error

**Comment by guppy42** [comment]
Then take it up with the package maintainer(s) : https://packages.ubuntu.com/xenial/libcurl4-openssl-dev 

it's **not** an error related to mcpelauncher.

**Comment by AqyxHD** [comment]
**Maybe** it is. I deleted the mcpelauncher-linux folder and reinstalled/compiled (how you want to say it) and cmake .. worked.
