### ISSUE TITLE
How to update the branch?

### ISSUE THREAD

**Issue by AqyxHD** [MCMrARM/mcpelauncher-linux#227]
Since MCMrARM (hopefully) fixed the Xbox Live login issue, how do i update the branch? Do i need to delete the current one?

**Comment by guppy42** [comment]
To get the latest source code use `git pull`
To change branch use checkout

See https://try.github.io/levels/1/challenges/19

**Comment by AqyxHD** [comment]
so just git pull and i can log in in Xbox Live?

**Comment by AqyxHD** [comment]
got it, just got the latest source code and recompiled it. Now i can play on Servers!
