### ISSUE TITLE
(Cmake) and Make Error

### ISSUE THREAD

**Issue by AqyxHD** [MCMrARM/mcpelauncher-linux#229]
when i try cmake .. i get: 
-- Found Protobuf: /usr/lib/i386-linux-gnu/libprotobuf.so;-lpthread (found version "2.6.1") 
/usr/local/bin/protoc: 1: /usr/local/bin/protoc: Syntax error: "(" unexpected
CMake Warning at /usr/local/share/cmake-3.9/Modules/FindProtobuf.cmake:429 (message):
  Protobuf compiler version doesn't match library version 2.6.1
Call Stack (most recent call first):
  gplay_api/CMakeLists.txt:8 (find_package)

-- Found Protobuf: /usr/lib/i386-linux-gnu/libprotobuf.so;-lpthread;-lpthread (found version "2.6.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/deniz/mcpelauncher-linux/build

and when i try Sudo make install:
 deniz@deniz-HP-Compaq-dc5700-Microtower:~/mcpelauncher-linux/build$ sudo make install
[  1%] Running C++ protocol buffer compiler on proto/play_details.proto
/usr/local/bin/protoc: 1: /usr/local/bin/protoc: Syntax error: "(" unexpected
gplay_api/CMakeFiles/gplayapi.dir/build.make:174: die Regel für Ziel „gplay_api/play_details.pb.cc“ scheiterte
make[2]: *** [gplay_api/play_details.pb.cc] Fehler 2
CMakeFiles/Makefile2:123: die Regel für Ziel „gplay_api/CMakeFiles/gplayapi.dir/all“ scheiterte
make[1]: *** [gplay_api/CMakeFiles/gplayapi.dir/all] Fehler 2
Makefile:129: die Regel für Ziel „all“ scheiterte
make: *** [all] Fehler 2

Is something wrong with my protobuf version?

**Comment by MCMrARM** [comment]
Yep, you need protobuf version 3, you have a 2.* version installed.
