### ISSUE TITLE
 I loved your project

### ISSUE THREAD

**Issue by AndrusGerman** [MCMrARM/mcpelauncher-linux#230]
I've been following it for a long time, how hard would it be if other games are passed to linux? example games x86 android "Need for Speed ​​™ No Limits, Asphalt 8" if you have any test with another game I would love to try it or try one of these games.

Pos= 
note the new update has been testing without flaws, very well.

If something of what I said does not have coherences, I do not speak english with fluides

**Comment by AryToNeX** [comment]
Oh damn this is hilarious.

**Comment by AqyxHD** [comment]
Would only work with games written in C or C++

**Comment by MCMrARM** [comment]
Most of the android games are written in C or C++ anyways. The issue however, is how much of the code is written in Java as it has to be rewritten.

It might be possible to get other games working with some work -- note that for this to be realistically possible those games would have to have debug symbols on (most of the popular titles probably don't).

I don't have the will to try porting other games currently, but it should be possible for someone skilled enough.

**Comment by MCMrARM** [comment]
I believe it is not an issue with the project itself :)
