### ISSUE TITLE
[Feauture Request]

### ISSUE THREAD

**Issue by AqyxHD** [MCMrARM/mcpelauncher-linux#232]
Could you look into it to optimize the fps when on a Server (eg. Mineplex) ? Im getting the same wierd fps dorps on my Samsung Galaxy S6. I tried Lifeboat and Mineplex so far. In Singlerplayer (or lan) World i have constant 60fps thanks to the low amount of recources C++ needs (for me).
Example:
I have 60fps on Mineplex but when i or many people fight the fps drops to 5~10fps. Maybe its Minecraft itself because the same happens on my phone, would be interesting to see if you could fix that.
Sidenote: I dont get any lag when fighting in Lan or XBL shared Worlds.

**Comment by guppy42** [comment]
"same happens on my phone"
Please file the bug here then:
https://bugs.mojang.com/secure/CreateIssue!default.jspa
