### ISSUE TITLE
Crash after logging in to Google account/mcpelauncher command not found

### ISSUE THREAD

**Issue by cytaleweb** [MCMrARM/mcpelauncher-linux#236]
Crashes after logging in to Google account
`christopher@christopher:~/mcpelauncher-linux$ ./mcpelauncher
InitialSetupBrowserClient::OpenBrowser
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.
BrowserApp::OnBrowserCreated 1
InitialSetupRenderHandler::OnContextCreated
StartGoogleLogin
GoogleLoginBrowserClient::OpenBrowser
BrowserApp::OnBrowserCreated 2
OnAddressChange https://accounts.google.com/embedded/setup/v2/android 1
GoogleLoginRenderHandler::OnContextCreated
OnAddressChange https://accounts.google.com/embedded/setup/v2/android 1
OnAddressChange https://accounts.google.com/embedded/setup/v2/android 1
OnAddressChange https://accounts.google.com/embedded/setup/v2/android/identifier 1
log: Loading page: identifier
GoogleLoginRenderHandler::OnContextCreated
Show
SetAccountIdentifier
OnAddressChange https://accounts.google.com/signin/v2/challenge/pwd 1
log: Loading page: signin/v2/challenge/pwd
GoogleLoginRenderHandler::OnContextCreated
Show
OnAddressChange https://accounts.google.com/embedded/setup/v2/android/signinconsent 1
log: Loading page: signinconsent
OnAddressChange https://accounts.google.com/embedded/setup/v2/android/signinconsent 1
Cookie: oauth_token
Cookie: user_id
http request: https://android.clients.google.com/auth, body = accountType=HOSTED_OR_GOOGLE&Token=oauth2_4%2F2jRibPQ3CxBtuV8fW87Yp8_Chq7U-xuffptiBU_iC2g&ACCESS_TOKEN=1&Email=censored&add_account=1&has_permission=1&service=ac2dm&source=android&app=com.google.android.gsf&device_country=us&lang=en_US&sdk_version=23&client_sig=38918a453d07199354f8b19af05ec6562ced5788&system_partition=1
[1110/200418.330332:WARNING:spdy_session.cc(2908)] Received HEADERS for invalid stream 9
[1110/200418.359441:WARNING:x11_util.cc(1364)] X error received: serial 6566, error_code 3 (BadWindow (invalid Window parameter)), request_code 4, minor_code 0 (X_DestroyWindow)
http response body: 
terminate called after throwing an instance of 'std::runtime_error'
  what():  No auth cookie field returned
Aborted (core dumped)
christopher@christopher:~/mcpelauncher-linux$ 
`
I think I'm supposed to run `mcpelauncher ` without the `./`, but that just tells me the command doesn't exist.

**Comment by AqyxHD** [comment]
idk why, but it helped my friend tying gksu mcpelauncher

**Comment by cytaleweb** [comment]
@AqyxHD I can't run `mcpelauncher`, it tells me that the command doesn't exist. `gksu ./mcprlauncher` doesn't do anything at all, `gksudo ./mcpelauncher` works, but the same issue occurs.

**Comment by cytaleweb** [comment]
Managed to get an apk without using the pop-up. Closing issue.
