### ISSUE TITLE
libgles2-mesa-dev unment dependancies Ubuntu 15.04

### ISSUE THREAD

**Issue by mhsjlw** [MCMrARM/mcpelauncher-linux#24]
I'm running Ubuntu 15.04 desktop edition and I am able to install every required package but `libgles2-mesa-dev`. When I try to install it, I get this:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help resolve the situation:

The following packages have unmet dependencies:
 libgles2-mesa-dev : Depends: libgles2-mesa (= 11.0.2-1ubuntu4) but it is not going to be installed
                     Depends: libegl1-mesa-dev but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by MCMrARM** [comment]
Try doing:
`sudo dpkg --add-architecture i386`
Also, try googling this problem if that doesn't help.

**Comment by mhsjlw** [comment]
I've created the issue mainly because I couldn't find the solution on my own. I've already tried adding x86 architecture to dpkg and it didn't fix the problem.

**Comment by MCMrARM** [comment]
anyways, why not update to 15.10? 15.04's kinda old and unsupported I think.

**Comment by mhsjlw** [comment]
Alright, I'll update as soon as I can, and I'll let you know if this fixes the issue.

**Comment by mhsjlw** [comment]
After running the commands on Ubuntu 15.10 this has not fixed the issue.

**Comment by mhsjlw** [comment]
Adding the xorg-edgers ppa is really hacky, but it solves the problem.
