### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by coolkidsrule101** [MCMrARM/mcpelauncher-linux#247]
The system is: Linux - 4.10.0-28-generic - x86_64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: /usr/bin/cc 
Build flags: -m32
Id flags: -c

The output was:
0

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CMakeCCompilerId.o"

The C compiler identification is GNU, found in "/home/macus/mcpe/tmp_cef/cef_binary_3.3112.1653.gf69054f_linux32_minimal/build/CMakeFiles/3.5.1/CompilerIdC/CMakeCCompilerId.o"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler: /usr/bin/c++ 
Build flags: -m32
Id flags: -c

The output was:
0

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CMakeCXXCompilerId.o"

The CXX compiler identification is GNU, found in "/home/macus/mcpe/tmp_cef/cef_binary_3.3112.1653.gf69054f_linux32_minimal/build/CMakeFiles/3.5.1/CompilerIdCXX/CMakeCXXCompilerId.o"

**Comment by elvaalxv** [comment]
Don't worry about that! 
I have recorded a video to guide you how to install mcpelauncher with the easiest way. Follow the the video, I sure that you will install mcpelauncher successfully. 
Check it! 
https://youtu.be/KsuS9IbMaVI

**Comment by guppy42** [comment]
Elvaalxv remove that video, you are distributing copyrighted material by including the apk in the zip file! That's piracy...

**Comment by coolkidsrule101** [comment]
dont scam me

**Comment by elvaalxv** [comment]
I think this apk is not problem.  I saw to many link include the apk that has copyright. This video just help people who don't have any thing about Linux like Ubuntu. I want everyone can compile mcpelauncher with the easiest way.  They can't Chinese,  Vietnamese,  some countries in Asean,  which is the area have poor education. I am a example. When I read the tutorial of MCMRARM, some location I can't do with true way,  because his command is not clear.  So that, I have compile mcpelauncher over 3 days. The time is very costly. That's the reason I make this tutorial,  to make people don't same me. Let's to identify me

**Comment by elvaalxv** [comment]
They can Chinese,  Vietnamese,...

**Comment by elvaalxv** [comment]
If you don't agree with me,  I can remove this video forever. So, to help people to compile mcpelauncher,  I will usually support them

**Comment by elvaalxv** [comment]
coolkidsrule101 it's really. I have test it in my PC and in some Virtual Box Machine. It's working

**Comment by guppy42** [comment]
-_- sure they don't mind you distributing their material for free. 

Please keep piracy off this project, we don't need to give Microsoft an excuse to shut it down

**Comment by coolkidsrule101** [comment]
how you compile the the McMrARM . im using everything but i still get it to
work . also elvaalxv could you change it to 1.6.2 with xbox live support
please

**Comment by elvaalxv** [comment]
My country is in midnight, so i much to go to sleep. Tomorrow?

**Comment by elvaalxv** [comment]
No no no. I'm not sure I can compile xbox support. Maybe I tried to compile it 4 days ago, and I was failed, too. But my log are different from you. I can try it again

**Comment by coolkidsrule101** [comment]
i got everything to work thank you but now 1.2.6 doesnt work . some please fix

**Comment by coolkidsrule101** [comment]
Thank dude I just went to your YouTuber vid it's good thanks bud aye make
one for 1.2.6 when they decided to update the code lol

**Comment by elvaalxv** [comment]
My Facebook: https://facebook.com/elvaa.lxv
