### ISSUE TITLE
mcpelauncher doesn't work

### ISSUE THREAD

**Issue by elvaalxv** [MCMrARM/mcpelauncher-linux#249]
Log:

`./mcpelauncher
loading native libraries
oslib: libGLESv2.so: 151552896
oslib: /home/elvaa/Desktop/Docker/mcpelauncher-linux/libs/native/libfmod.so.8.2: 151554768
loading hybris libraries
loading MCPE
linker/home/elvaa/Desktop/Docker/mcpelauncher-linux/hybris/src/jb/linker.c:2038| ERROR: failed to link libminecraftpe.so
failed to load MCPE: Cannot load library: reloc_library[1371]:     0 cannot locate '_ZN4FMOD6System17set3DNumListenersEi'...
`

How I can sovel this error?

**Comment by MCMrARM** [comment]
I don't know what version did you run, but definitely not the latest.

Clone the `master` branch recursively (`git clone --recursive https://github.com/MCMrARM/mcpelauncher-linux`) and follow the README.
