### ISSUE TITLE
Sensitivity too fast

### ISSUE THREAD

**Issue by elvaalxv** [MCMrARM/mcpelauncher-linux#250]
Allthougt 0, but the sensitivity still too fast. Who can decrease the speed? Thanks for that before

**Comment by coolkidsrule101** [comment]
turn it down in mcpe settings

**Comment by MCMrARM** [comment]
He said he set it to the lowest setting. Unfortunately, I'm not sure what I should do about it as this seems more of a MCPE bug than mine.

**Comment by coolkidsrule101** [comment]
Oh ouch ok
Hopefully they fix it

**Comment by MCMrARM** [comment]
Duplicate of https://github.com/MCMrARM/mcpelauncher-linux/issues/88
