### ISSUE TITLE
mcpelauncher still doesn't work

### ISSUE THREAD

**Issue by elvaalxv** [MCMrARM/mcpelauncher-linux#251]
MCPE Version: 1.0.6.52

Log:

`Signal 6 received`
`Backtrace elements: 13`
`#0 ./mcpelauncher(_Z12handleSignaliPv+0x62) [0x80b94ff]`
`#1 [0xf76f1ca0]`
`#2 [0xf76f1c89]`
`#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf6ed5ea9]`
`#4 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf6ed7407]`
`#5 /usr/lib/i386-linux-gnu/libstdc++.so.6(_ZN9__gnu_cxx27__verbose_terminate_handlerEv+0x155) [0xf7145d35]`
`#6 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x70833) [0xf7143833]`
`#7 /usr/lib/i386-linux-gnu/libstdc++.so.6(+0x708ad) [0xf71438ad]`
`#8 /usr/lib/i386-linux-gnu/libstdc++.so.6(__cxa_rethrow+0) [0xf7143b70]`
`#9 ./mcpelauncher(_ZN10PathHelper12findDataFileERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x3c0) [0x80dea94]`
`#10 ./mcpelauncher(main+0x73e) [0x80b2ac3]`
`#11 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf7) [0xf6ec2637]`
`#12 ./mcpelauncher() [0x80a2851]`
`Dumping stack...`
`Signal 6 received`
`Aborted (core dumped)`

**Comment by guppy42** [comment]
Old versions generally aren't supported - the latest version is 1.2.5(.52)

**Comment by elvaalxv** [comment]
Really? The last version of Minecraft is 1.2.6.2. I have try with this version and fail too

**Comment by elvaalxv** [comment]
Update: 1.2.5.52 version is fail too

**Comment by guppy42** [comment]
1.2.6.x are beta versions , 1.2.5.x are stable

Also if you do not post the specific error that those versions fail with, then nobody will be able to help you.

**Comment by elvaalxv** [comment]
I have tried to run 1.2.5.52 versoin, and fail too

**Comment by elvaalxv** [comment]
i have a same error

**Comment by opkiler22789** [comment]
+1

**Comment by opkiler22789** [comment]
@elvaalxv how did you solve the problem?

**Comment by elvaalxv** [comment]
I use Master project and cmake 3.9.6, and some file require in cmaker folder

**Comment by elvaalxv** [comment]
Do you mind if I send you my tutorial?

**Comment by opkiler22789** [comment]
@elvaalxv Thanks, I have not against

**Comment by elvaalxv** [comment]
https://youtu.be/KsuS9IbMaVI

**Comment by elvaalxv** [comment]
Just read the derciption

**Comment by elvaalxv** [comment]
Just read the decription

**Comment by MCMrARM** [comment]
@elvaalxv Please do not spam and do not advertise your own YouTube channel or Facebook. Linking to videos containing links to an illegal copy of Minecraft: PE are not allowed.

**Comment by elvaalxv** [comment]
He want to see it

**Comment by elvaalxv** [comment]
I will not comment this link again
