### ISSUE TITLE
Can not launch mcpelauncher

### ISSUE THREAD

**Issue by eddir** [MCMrARM/mcpelauncher-linux#258]
When I try to launch mcpelauncher I get this error (Ubuntu 14, xfce, MCPE 1.0.5). But some time ago it was fixed with gksu and when I fixed other errors it happened again. What I should do?

> Signal 11 received
Backtrace elements: 6
#0 ./mcpelauncher(_Z12handleSignaliPv+0x62) [0x82acf28]
#1 [0xf77c2bc0]
#2 ./mcpelauncher(_Z20patchCallInstructionPvS_b+0x31) [0x82acde5]
#3 ./mcpelauncher(main+0x1206) [0x82a3e7d]
#4 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf7) [0xef5da637]
#5 ./mcpelauncher() [0x82931f5]
Dumping stack...
#471 HYBRIS xbox::services::java_interop::get_local_storage_path()+0 in libminecraftpe.so+0x217e5d0 [0xec4855d0]
Signal 6 received

**Comment by coolkidsrule101** [comment]
me too it crashes too often like after20-30 mins\

**Comment by MCMrARM** [comment]
Is this the full log? If not, please post the full log, removing any Xbox Live tokens if you're signed in to Xbox Live.

**Comment by guppy42** [comment]
Your writing Minecraft version **1.0.5** is that a mistake? Current version is 1.2.6

Generally older Minecraft versions are not guaranteed to work with this launcher

**Comment by coolkidsrule101** [comment]
Current version is 1.2.7

**Comment by coolkidsrule101** [comment]
Make sure you deleted mclauncher everything before recompiling for the new version. And save any world's ,bp ,and rp

**Comment by guppy42** [comment]
There is absolutely no need to delete anything before recompiling!

Why would you say such a thing? that's just mean :(

**Comment by coolkidsrule101** [comment]
no because i  had the same problem as you and it ended up me deleting everything that say mcpe launcher and recompiling it and it worked as fine . and also that the folder with you worlds wont update once the version of mcpe is set btw

**Comment by coolkidsrule101** [comment]
aye dude if you need an 1.2.7 apk i be happy to give it to you

**Comment by eddir** [comment]
Thank you very much! I reinstalled the launcher and launched with MCPE v1.2.7 and all work fine.

**Comment by coolkidsrule101** [comment]
You welcome

**Comment by manuelface123** [comment]
@coolkidsrule101 hey you could pass me the apk to my ps I do not have money to buy it please

**Comment by lukeeey** [comment]
@manuelface123 no

**Comment by eddir** [comment]
@manuelface123 You can download x86 apk from this forum: https://4pda.ru/forum/index.php?showtopic=260256 . Yes, its russian. Use google translate. Before download you should pass through an simple email registration to prevent any 404 errors.

**Comment by lukeeey** [comment]
~~I would say dont talk about piracy, but its a free country~~

**Comment by manuelface123** [comment]
Jajajaj esta muy dificil registrarse por que tiene un capcha en ruso

**Comment by Artistic-Waffle** [comment]
im so sorry yes i can get it for u i haven't been on GitHub for a while

**Comment by Artistic-Waffle** [comment]
ill try to get on sunday because my linux is acting up right now

**Comment by Artistic-Waffle** [comment]
@manuelface123
