### ISSUE TITLE
add color support

### ISSUE THREAD

**Issue by coolkidsrule101** [MCMrARM/mcpelauncher-linux#259]
we use linux is control and y in the game the get the duoble ss

**Comment by guppy42** [comment]
colour coded text works just fine in mcpelauncher - press shift + ½ to get §

There is a bit of an oddity where it deletes the 2 characters that makes up the colour code §(1-F) but doesn't anyway so you seem to be a few characters behind your actual position when typing. I am however not convinced this has anything to do with the launcher.

**Comment by coolkidsrule101** [comment]
wait what is the 1/2 sign

**Comment by coolkidsrule101** [comment]
ik that this doesnt do with the launcher but i need help with simple stuff because its my first time play mcpe on mouse and keyboard without an controller

**Comment by guppy42** [comment]
please close this issue as it's not an issue with the launcher, if your having trouble with the game it self I reccomend trying online forums like
http://www.minecraftforum.net/forums/minecraft
or searching for "minecraft bedrock edition" on youtube
