### ISSUE TITLE
Can't Compile Launcher with Cmake

### ISSUE THREAD

**Issue by Tiago1098** [MCMrARM/mcpelauncher-linux#260]
thegameratort@thegameratort-Intel-powered-classmate-PC:~/mcpelauncher-linux$ cmake .
CMake Error at /usr/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.9/Modules/FindCURL.cmake:48 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  gplay_api/CMakeLists.txt:7 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/thegameratort/mcpelauncher-linux/CMakeFiles/CMakeOutput.log".
See also "/home/thegameratort/mcpelauncher-linux/CMakeFiles/CMakeError.log".
thegameratort@thegameratort-Intel-powered-classmate-PC:~/mcpelauncher-linux$ 
[CMakeError.log](https://github.com/MCMrARM/mcpelauncher-linux/files/1564868/CMakeError.log)

**Comment by guppy42** [comment]
You are missing libcurl please make sure to install the prerequisites first

**Comment by Tiago1098** [comment]
I installed all the pre requisites

**Comment by Tiago1098** [comment]
Maybe is a lubuntu problem (Ubuntu on LXDE Desktop), because it is the only library causing problems. I think it just can't install it. :( But the others libs do.

**Comment by guppy42** [comment]
Do;
 apt search libcurl | grep installed
and past the result here.

**Comment by Tiago1098** [comment]
I tried to install libcurl again after rebooting the system and it worked It seems that Ubuntu launched a patch for the system, thanks!

**Comment by coolkidsrule101** [comment]
ok hold on the libcurl is not the problem

**Comment by coolkidsrule101** [comment]
when open in termal with mclauncher install all requirements then start it with in the terminal and mclauncher
marcus@marcus-Latitude-D830:~/mcpelauncher-linux$ 

like this

**Comment by coolkidsrule101** [comment]
that an example of mine your name will be different
