### ISSUE TITLE
Connection to server error with Minecraft 1.2.7

### ISSUE THREAD

**Issue by ErnyTech** [MCMrARM/mcpelauncher-linux#261]
I can not connect to any server other than "LiveBoot Network", I always get an error saying "You need to authenticate to Xbox Live", is it a known bug?
Below I will put the log generated by pressing the server button onwards
Thanks for great work

`log_cll 2535444812239686 Microsoft.XboxLive.T1934598432.ScreenChanged {"baseData":{"measurements":null,"name":"ScreenChanged","playerSessionId":"a3bccd39-dd7f-4c63-942b-6b35b8cbd304","properties":{"AccountType":1,"AppSessionID":"2a32e13f-49d9-499e-b8a0-1f1934485007","Build":"1.2.7","BuildPlat":4294967295,"Cheevos":1,"ClientId":"linux","DeviceSessionId":"d44d24f6-95ac-4a34-8656-f99c6fdfa07b","Direction":"forward","NetworkType":2,"Plat":"","PreviousScreenName":"play_screen - servers","ScreenName":"world_loading_progress_screen - joining_multiplayer_external_server","ScreenVersion":"1","Seconds":4.2937220000000025,"TimeStamp":214.231201,"Treatments":"mc-rp-12days-control","UserId":"2535444812239686","locale":"0xdeadbeef"},"serviceConfigId":"00000000-0000-0000-0000-0000734fa120","titleId":"1934598432","userId":"2535444812239686","ver":1},"baseType":"Microsoft.XboxLive.InGame"}
log_cll 2535444812239686 Microsoft.XboxLive.T1934598432.StartWorld {"baseData":{"measurements":null,"name":"StartWorld","playerSessionId":"a3bccd39-dd7f-4c63-942b-6b35b8cbd304","properties":{"AccountType":1,"AppSessionID":"2a32e13f-49d9-499e-b8a0-1f1934485007","Build":"1.2.7","BuildPlat":4294967295,"Cheevos":1,"ClientId":"linux","DeviceSessionId":"d44d24f6-95ac-4a34-8656-f99c6fdfa07b","Host":"play.warspvp.ml","NetworkType":2,"Plat":"","Treatments":"mc-rp-12days-control","UserId":"2535444812239686","locale":"0xdeadbeef"},"serviceConfigId":"00000000-0000-0000-0000-0000734fa120","titleId":"1934598432","userId":"2535444812239686","ver":1},"baseType":"Microsoft.XboxLive.InGame"}
verifycertchain
verifycertchain
log_cll 2535444812239686 Microsoft.XboxLive.T1934598432.ScreenChanged {"baseData":{"measurements":null,"name":"ScreenChanged","playerSessionId":"a3bccd39-dd7f-4c63-942b-6b35b8cbd304","properties":{"AccountType":1,"AppSessionID":"2a32e13f-49d9-499e-b8a0-1f1934485007","Build":"1.2.7","BuildPlat":4294967295,"Cheevos":1,"ClientId":"linux","DeviceSessionId":"d44d24f6-95ac-4a34-8656-f99c6fdfa07b","Direction":"forward","NetworkType":2,"Plat":"","PreviousScreenName":"world_loading_progress_screen - joining_multiplayer_external_server","ScreenName":"world_saving_progress_screen - world_loading_progress_screen","ScreenVersion":"1","Seconds":0.84704600000000596,"TimeStamp":215.078247,"Treatments":"mc-rp-12days-control","UserId":"2535444812239686","locale":"0xdeadbeef"},"serviceConfigId":"00000000-0000-0000-0000-0000734fa120","titleId":"1934598432","userId":"2535444812239686","ver":1},"baseType":"Microsoft.XboxLive.InGame"}
log_cll 2535444812239686 Microsoft.XboxLive.T1934598432.ScreenChanged {"baseData":{"measurements":null,"name":"ScreenChanged","playerSessionId":"a3bccd39-dd7f-4c63-942b-6b35b8cbd304","properties":{"AccountType":1,"AppSessionID":"2a32e13f-49d9-499e-b8a0-1f1934485007","Build":"1.2.7","BuildPlat":4294967295,"Cheevos":1,"ClientId":"linux","DeviceSessionId":"d44d24f6-95ac-4a34-8656-f99c6fdfa07b","Direction":"forward","NetworkType":2,"Plat":"","PreviousScreenName":"world_saving_progress_screen - world_loading_progress_screen","ScreenName":"disconnect_screen - disconnectionScreen.notAuthenticated","ScreenVersion":"1","Seconds":0.0069019999999966331,"TimeStamp":215.085149,"Treatments":"mc-rp-12days-control","UserId":"2535444812239686","locale":"0xdeadbeef"},"serviceConfigId":"00000000-0000-0000-0000-0000734fa120","titleId":"1934598432","userId":"2535444812239686","ver":1},"baseType":"Microsoft.XboxLive.InGame"}
verifycertchain
verifycertchain
Request: {"ver":"2.1","name":"Microsoft.XboxLive.T1934598432.ScreenChanged","time":"2017-12-16T22:03:30.217Z","popSample":100.0,"epoch":"4863375265727804706","seqNum":14,"iKey":"P-XBL-T1739947436","flags":514,"os":"Android","osVer":"7.1.1","appId":"A:com.mojang.minecraftpe","appVer":"1.2.7","ext":{"user":{"ver":"1.0","localId":""},"os":{"ver":"1.0","locale":"en-US"},"device":{"ver":"1.0","localId":"","deviceClass":"Android.PC"},"android":{"ver":"1.0","libVer":"3.160623.0","tickets":["2535444812239686"]}},"data":{"baseData":{"measurements":null,"name":"ScreenChanged","playerSessionId":"a3bccd39-dd7f-4c63-942b-6b35b8cbd304","properties":{"AccountType":1,"AppSessionID":"2a32e13f-49d9-499e-b8a0-1f1934485007","Build":"1.2.7","BuildPlat":4294967295,"Cheevos":1,"ClientId":"linux","DeviceSessionId":"d44d24f6-95ac-4a34-8656-f99c6fdfa07b","Direction":"backward","NetworkType":2,"Plat":"","PreviousScreenName":"disconnect_screen - disconnectionScreen.notAuthenticated","ScreenName":"world_saving_progress_screen - world_loading_progress_screen","ScreenVersion":"1","Seconds":52.946352999999988,"TimeStamp":208.139703,"Treatments":"mc-rp-12days-control","UserId":"2535444812239686","locale":"0xdeadbeef"},"serviceConfigId":"00000000-0000-0000-0000-0000734fa120","titleId":"1934598432","userId":"2535444812239686","ver":1},"baseType":"Microsoft.XboxLive.InGame"}}
{"ver":"2.1","name":"Microsoft.XboxLive.T1934598432.ScreenHeartbeat","time":"2017-12-16T22:03:30.218Z","popSample":100.0,"epoch":"2319623189702727630","seqNum":15,"iKey":"P-XBL-T1739947436","flags":514,"os":"Android","osVer":"7.1.1","appId":"A:com.mojang.minecraftpe","appVer":"1.2.7","ext":{"user":{"ver":"1.0","localId":""},"os":{"ver":"1.0","locale":"en-US"},"device":{"ver":"1.0","localId":"","deviceClass":"Android.PC"},"android":{"ver":"1.0","libVer":"3.160623.0","tickets":["2535444812239686"]}},"data":{"baseData":{"measurements":null,"name":"ScreenHeartbeat","playerSessionId":"a3bccd39-dd7f-4c63-942b-6b35b8cbd304","properties":{"AccountType":1,"AppSessionID":"2a32e13f-49d9-499e-b8a0-1f1934485007","Build":"1.2.7","BuildPlat":4294967295,"Cheevos":1,"ClientId":"linux","DeviceSessionId":"d44d24f6-95ac-4a34-8656-f99c6fdfa07b","NetworkType":2,"Plat":"","ScreenName":"disconnect_screen - disconnectionScreen.notAuthenticated","TimeStamp":166.54588100000001,"Treatments":"mc-rp-12days-control","UserId":"2535444812239686","locale":"0xdeadbeef"},"serviceConfigId":"00000000-0000-0000-0000-0000734fa120","titleId":"1934598432","userId":"2535444812239686","ver":1},"baseType":"Microsoft.XboxLive.InGame"}}
{"ver":"2.1","name":"Microsoft.XboxLive.T1934598432.ScreenChanged","time":"2017-12-16T22:03:31.910Z","popSample":100.0,"epoch":"4888854021182164353","seqNum":16,"iKey":"P-XBL-T1739947436","flags":514,"os":"Android","osVer":"7.1.1","appId":"A:com.mojang.minecraftpe","appVer":"1.2.7","ext":{"user":{"ver":"1.0","localId":""},"os":{"ver":"1.0","locale":"en-US"},"device":{"ver":"1.0","localId":"","deviceClass":"Android.PC"},"android":{"ver":"1.0","libVer":"3.160623.0","tickets":["2535444812239686"]}},"data":{"baseData":{"measurements":null,"name":"ScreenChanged","playerSessionId":"a3bccd39-dd7f-4c63-942b-6b35b8cbd304","properties":{"AccountType":1,"AppSessionID":"2a32e13f-49d9-499e-b8a0-1f1934485007","Build":"1.2.7","BuildPlat":4294967295,"Cheevos":1,"ClientId":"linux","DeviceSessionId":"d44d24f6-95ac-4a34-8656-f99c6fdfa07b","Direction":"backward","NetworkType":2,"Plat":"","PreviousScreenName":"world_saving_progress_screen - world_loading_progress_screen","ScreenName":"world_loading_progress_screen - joining_multiplayer_external_server","ScreenVersion":"1","Seconds":1.768999000000008,"TimeStamp":209.90870200000001,"Treatments":"mc-rp-12days-control","UserId":"2535444812239686","locale":"0xdeadbeef"},"serviceConfigId":"00000000-0000-0000-0000-0000734fa120","titleId":"1934598432","userId":"2535444812239686","ver":1},"baseType":"Microsoft.XboxLive.InGame"}}
{"ver":"2.1","name":"Microsoft.XboxLive.T1934598432.ScreenChanged","time":"2017-12-16T22:03:31.938Z","popSample":100.0,"epoch":"1589196725033063378","seqNum":17,"iKey":"P-XBL-T1739947436","flags":514,"os":"Android","osVer":"7.1.1","appId":"A:com.mojang.minecraftpe","appVer":"1.2.7","ext":{"user":{"ver":"1.0","localId":""},"os":{"ver":"1.0","locale":"en-US"},"device":{"ver":"1.0","localId":"","deviceClass":"Android.PC"},"android":{"ver":"1.0","libVer":"3.160623.0","tickets":["2535444812239686"]}},"data":{"baseData":{"measurements":null,"name":"ScreenChanged","playerSessionId":"a3bccd39-dd7f-4c63-942b-6b35b8cbd304","properties":{"AccountType":1,"AppSessionID":"2a32e13f-49d9-499e-b8a0-1f1934485007","Build":"1.2.7","BuildPlat":4294967295,"Cheevos":1,"ClientId":"linux","DeviceSessionId":"d44d24f6-95ac-4a34-8656-f99c6fdfa07b","Direction":"backward","NetworkType":2,"Plat":"","PreviousScreenName":"world_loading_progress_screen - joining_multiplayer_external_server","ScreenName":"play_screen - servers","ScreenVersion":"1","Seconds":0.028776999999990949,"TimeStamp":209.937479,"Treatments":"mc-rp-12days-control","UserId":"2535444812239686","locale":"0xdeadbeef"},"serviceConfigId":"00000000-0000-0000-0000-0000734fa120","titleId":"1934598432","userId":"2535444812239686","ver":1},"baseType":"Microsoft.XboxLive.InGame"}}
{"ver":"2.1","name":"Microsoft.XboxLive.T1934598432.ScreenChanged","time":"2017-12-16T22:03:36.231Z","popSample":100.0,"epoch":"6289962959691981030","seqNum":18,"iKey":"P-XBL-T1739947436","flags":514,"os":"Android","osVer":"7.1.1","appId":"A:com.mojang.minecraftpe","appVer":"1.2.7","ext":{"user":{"ver":"1.0","localId":""},"os":{"ver":"1.0","locale":"en-US"},"device":{"ver":"1.0","localId":"","deviceClass":"Android.PC"},"android":{"ver":"1.0","libVer":"3.160623.0","tickets":["2535444812239686"]}},"data":{"baseData":{"measurements":null,"name":"ScreenChanged","playerSessionId":"a3bccd39-dd7f-4c63-942b-6b35b8cbd304","properties":{"AccountType":1,"AppSessionID":"2a32e13f-49d9-499e-b8a0-1f1934485007","Build":"1.2.7","BuildPlat":4294967295,"Cheevos":1,"ClientId":"linux","DeviceSessionId":"d44d24f6-95ac-4a34-8656-f99c6fdfa07b","Direction":"forward","NetworkType":2,"Plat":"","PreviousScreenName":"play_screen - servers","ScreenName":"world_loading_progress_screen - joining_multiplayer_external_server","ScreenVersion":"1","Seconds":4.2937220000000025,"TimeStamp":214.231201,"Treatments":"mc-rp-12days-control","UserId":"2535444812239686","locale":"0xdeadbeef"},"serviceConfigId":"00000000-0000-0000-0000-0000734fa120","titleId":"1934598432","userId":"2535444812239686","ver":1},"baseType":"Microsoft.XboxLive.InGame"}}
{"ver":"2.1","name":"Microsoft.XboxLive.T1934598432.StartWorld","time":"2017-12-16T22:03:36.232Z","popSample":100.0,"epoch":"4178664957675422481","seqNum":19,"iKey":"P-XBL-T1739947436","flags":514,"os":"Android","osVer":"7.1.1","appId":"A:com.mojang.minecraftpe","appVer":"1.2.7","ext":{"user":{"ver":"1.0","localId":""},"os":{"ver":"1.0","locale":"en-US"},"device":{"ver":"1.0","localId":"","deviceClass":"Android.PC"},"android":{"ver":"1.0","libVer":"3.160623.0","tickets":["2535444812239686"]}},"data":{"baseData":{"measurements":null,"name":"StartWorld","playerSessionId":"a3bccd39-dd7f-4c63-942b-6b35b8cbd304","properties":{"AccountType":1,"AppSessionID":"2a32e13f-49d9-499e-b8a0-1f1934485007","Build":"1.2.7","BuildPlat":4294967295,"Cheevos":1,"ClientId":"linux","DeviceSessionId":"d44d24f6-95ac-4a34-8656-f99c6fdfa07b","Host":"play.warspvp.ml","NetworkType":2,"Plat":"","Treatments":"mc-rp-12days-control","UserId":"2535444812239686","locale":"0xdeadbeef"},"serviceConfigId":"00000000-0000-0000-0000-0000734fa120","titleId":"1934598432","userId":"2535444812239686","ver":1},"baseType":"Microsoft.XboxLive.InGame"}}
{"ver":"2.1","name":"Microsoft.XboxLive.T1934598432.ScreenChanged","time":"2017-12-16T22:03:37.288Z","popSample":100.0,"epoch":"7849444525089330473","seqNum":20,"iKey":"P-XBL-T1739947436","flags":514,"os":"Android","osVer":"7.1.1","appId":"A:com.mojang.minecraftpe","appVer":"1.2.7","ext":{"user":{"ver":"1.0","localId":""},"os":{"ver":"1.0","locale":"en-US"},"device":{"ver":"1.0","localId":"","deviceClass":"Android.PC"},"android":{"ver":"1.0","libVer":"3.160623.0","tickets":["2535444812239686"]}},"data":{"baseData":{"measurements":null,"name":"ScreenChanged","playerSessionId":"a3bccd39-dd7f-4c63-942b-6b35b8cbd304","properties":{"AccountType":1,"AppSessionID":"2a32e13f-49d9-499e-b8a0-1f1934485007","Build":"1.2.7","BuildPlat":4294967295,"Cheevos":1,"ClientId":"linux","DeviceSessionId":"d44d24f6-95ac-4a34-8656-f99c6fdfa07b","Direction":"forward","NetworkType":2,"Plat":"","PreviousScreenName":"world_loading_progress_screen - joining_multiplayer_external_server","ScreenName":"world_saving_progress_screen - world_loading_progress_screen","ScreenVersion":"1","Seconds":0.84704600000000596,"TimeStamp":215.078247,"Treatments":"mc-rp-12days-control","UserId":"2535444812239686","locale":"0xdeadbeef"},"serviceConfigId":"00000000-0000-0000-0000-0000734fa120","titleId":"1934598432","userId":"2535444812239686","ver":1},"baseType":"Microsoft.XboxLive.InGame"}}
{"ver":"2.1","name":"Microsoft.XboxLive.T1934598432.ScreenChanged","time":"2017-12-16T22:03:37.288Z","popSample":100.0,"epoch":"1226999485638565265","seqNum":21,"iKey":"P-XBL-T1739947436","flags":514,"os":"Android","osVer":"7.1.1","appId":"A:com.mojang.minecraftpe","appVer":"1.2.7","ext":{"user":{"ver":"1.0","localId":""},"os":{"ver":"1.0","locale":"en-US"},"device":{"ver":"1.0","localId":"","deviceClass":"Android.PC"},"android":{"ver":"1.0","libVer":"3.160623.0","tickets":["2535444812239686"]}},"data":{"baseData":{"measurements":null,"name":"ScreenChanged","playerSessionId":"a3bccd39-dd7f-4c63-942b-6b35b8cbd304","properties":{"AccountType":1,"AppSessionID":"2a32e13f-49d9-499e-b8a0-1f1934485007","Build":"1.2.7","BuildPlat":4294967295,"Cheevos":1,"ClientId":"linux","DeviceSessionId":"d44d24f6-95ac-4a34-8656-f99c6fdfa07b","Direction":"forward","NetworkType":2,"Plat":"","PreviousScreenName":"world_saving_progress_screen - world_loading_progress_screen","ScreenName":"disconnect_screen - disconnectionScreen.notAuthenticated","ScreenVersion":"1","Seconds":0.0069019999999966331,"TimeStamp":215.085149,"Treatments":"mc-rp-12days-control","UserId":"2535444812239686","locale":"0xdeadbeef"},"serviceConfigId":"00000000-0000-0000-0000-0000734fa120","titleId":"1934598432","userId":"2535444812239686","ver":1},"baseType":"Microsoft.XboxLive.InGame"}}

Response: {"ipv":false,"pvm":null,"rej":0,"bln":0,"acc":8,"efi":[]}`

**Comment by coolkidsrule101** [comment]
dude do you have an xbox live account first of all 
second it works fine with me with all servers
no hard-feeling
 bro but please recheck the steps.

**Comment by ErnyTech** [comment]
then obviously I have a functioning Microsoft account, I use it for years in the Android version so it's not my account. 
can you send me one your server to try?

**Comment by coolkidsrule101** [comment]
Than it some wrong with you compiling

**Comment by coolkidsrule101** [comment]
I send you mine when ilI send you one when I get home ok dude

**Comment by coolkidsrule101** [comment]
![screenshot from 2017-12-15 22-56-01](https://user-images.githubusercontent.com/31514218/34085101-3cd0fd4c-e359-11e7-8188-baa859b3a6e5.png)

**Comment by ErnyTech** [comment]
I managed to make it work by reloading the apk
