### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by AryToNeX** [MCMrARM/mcpelauncher-linux#27]
Hi there! I've some suggestions which can make this launcher really awesome.

- [x] Windows 10 Full GUI (health and hunger on top of the hotbar)
- [x] Hide mouse pointer when playing (it looks weird)
- [x] Custom skin selector (or tell us how we can have skins)
- [ ] An icon for the MCPE window and the name "Minecraft: Pocket Edition" instead of "MCPE"
- [x] Fullscreen mode
- [ ] BlockLauncher patch support and ModPE (if possible)
- [ ] Custom keymappings
- [x] Support for custom shaders

Thanks a lot for this launcher!

**Comment by MCMrARM** [comment]
Fullscreen mode - that's definitely a thing I would like to implement. And mouse pointer, haha, were just lazy to look into how to hide it :P (and same about icon)
You can get yourself a custom skin, by placing the skin in data/user/minecraftpe/custom_skin.png I think. I implemented the image picker using a hacky way locally, might push it soon.
W10 Ed. GUI should be easy to hack in, may do that.
BL patch support isn't going to happen as this loads the x86 variant of MCPE (while the format itself is easy to implement, most of patches won't work), and ModPE is way too much work now that BlockLauncher is closed source.
Custom keymappings - hmm, that's a 'nice' to have feature, I guess I'll just wait for MS/Mojang to implement it :P
Custom shaders - just copy them to assets/ ?

**Comment by AryToNeX** [comment]
Custom shaders -- I copied them to assets/ but I got "working" only one shader, and 3/4 of the blocks disappeared. With other shaders I get this:

```
loading MCPE
oslib: /usr/lib/i386-linux-gnu/libGLESv2.so: 144456384
oslib: /home/anthony/Scrivania/mcpelauncher-linux-master/libs/native/libfmod.so.7.7: 144458408
loaded MCPE (at 3055312896)
apply patches
original: 85 87 86 83 232
post patch: 233 0 94 180 81
original: 85 87 86 83 232
post patch: 233 118 236 177 81
original: 85 137 229 87 86
post patch: 233 69 25 176 81
original: 87 86 83 232 115
post patch: 233 99 234 177 81
patches applied!
init app platform vtable
init app platform
app platform initialized
init window
EGL_VERSION = 1.4 (DRI2)
create minecraft client
userdata path = data/user/
init minecraft client
userdata path = data/user/
readAssetFile: loc/languages.json
readAssetFile: loc/en_US-pocket.lang
readAssetFile: loc/de_DE-pocket.lang
get system region: 0xdeadbeef
get data url: assets/
get data url: assets/
readAssetFile: sounds/sounds.json
readAssetFile: loc/es_ES-pocket.lang
readAssetFile: loc/fr_FR-pocket.lang
readAssetFile: shaders/uniforms.json
readAssetFile: images/terrain.meta
readAssetFile: images/items.meta
device id = linux
internal storage path = data/private/
creating fake store <MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqU9snkqLkTCYZQfQgNy9eabP/OcumQTgcoYhuBbmx2isicIX8mSUNJn64yxiA6acqnJzJxGbKW9H+gSWMuRtCtwI3Exb3sCq19EiVtjos4u5BJatzBKXXDDJeeYrejGk8FgT6ffokcilJFY4wgQQxDGFdfE/reAqm6+VKUtoqnjMpG0wVZn+o0bJfxNvE/ydJPlabDmoywEn9zEl0hXo0i+cimVlFZcTT6ed7U9celM2Ywg+7qVIu7fmBHPucTIoUAbipEAIvP2EntOqrhUG6GKJ219Qhdr43fvnyBailudNBiDRqA+x0rCH1JgmV/BvyAHTBylPzroeh9rWJNNPxQIDAQAB>
register license change callback
readAssetFile: materials/common.json
readAssetFile: materials/particles.material
readAssetFile: shaders/color_uv.vertex
readAssetFile: shaders/color_texture.fragment
warn: readAssetFile with empty path!
readAssetFile: shaders/color_uv.vertex
readAssetFile: shaders/color_texture.fragment
warn: readAssetFile with empty path!
readAssetFile: materials/shadows.material
readAssetFile: shaders/shadows.glsl
readAssetFile: loc/ko_KR-pocket.lang
readAssetFile: shaders/flat_white.fragment
warn: readAssetFile with empty path!
readAssetFile: shadows.glsl
readAssetFile failed
readAssetFile: loc/zh_TW-pocket.lang
readAssetFile: loc/zh_CN-pocket.lang
readAssetFile: loc/ru_RU-pocket.lang
readAssetFile: loc/pt_PT-pocket.lang
readAssetFile: loc/ja_JP-pocket.lang
readAssetFile: loc/pt_BR-pocket.lang
readAssetFile: loc/it_IT-pocket.lang
readAssetFile: loc/es_MX-pocket.lang
readAssetFile: loc/fr_CA-pocket.lang
```

and MCPE does not start.

**Comment by AryToNeX** [comment]
Windows 10 GUI -- I contacted the creator of the Win 10 UI mod for BlockLauncher (KsyMC) and he told me those three functions:

getScreenType() = 0
getCenteredGUI() = 1
getEdition() = "win10"

**Comment by stayandwait** [comment]
Hes added the win10 style to this now like PC. I just tried it recently. See this photo
http://screencast.com/t/pIm8JpppDH6o

**Comment by AryToNeX** [comment]
I am moving all my issues to #48
