### ISSUE TITLE
this is annoying

### ISSUE THREAD

**Issue by coolkidsrule101** [MCMrARM/mcpelauncher-linux#274]
#0 ./mcpelauncher(_Z12handleSignaliPv+0x62) [0x82acf28]
#1 [0xf7748ca0]
#2 HYBRIS UIScene::screenDrawsLast() const+9 in libminecraftpe.so+0xfef639 [0xea8a9639]
Dumping stack...
#17 HYBRIS UIScene::screenDrawsLast() const+9 in libminecraftpe.so+0xfef639 [0xea8a9639]
#32 HYBRIS ClientInputHandler::onToastChanged(RectangleArea const&)+39 in libminecraftpe.so+0x1018017 [0xea8d2017]
#56 HYBRIS vtable for UIScene+8 in libminecraftpe.so+0x379853c [0xed05253c]
#60 HYBRIS UIScene::screenDrawsLast() const+9 in libminecraftpe.so+0xfef639 [0xea8a9639]
#68 HYBRIS getTimeS()+36 in libminecraftpe.so+0x24c1c14 [0xebd7bc14]
#76 HYBRIS ScreenView::_renderBatches(UIRenderContext&, ScreenRenderBatch&, RectangleArea&, float)+1503 in libminecraftpe.so+0x1862adf [0xeb11cadf]
#77 HYBRIS ProfilerLite::gProfilerLiteInstance+0 in libminecraftpe.so+0x38c2878 [0xed17c878]
#85 HYBRIS ProfilerLite::gProfilerLiteInstance+0 in libminecraftpe.so+0x38c2878 [0xed17c878]
#96 HYBRIS ScreenRenderBatch::_populateRenderBatch(UIRenderContext&)+12 in libminecraftpe.so+0x185654c [0xeb11054c]
#123 HYBRIS RectangleArea::isEmpty() const+5 in libminecraftpe.so+0x1a24f95 [0xeb2def95]
#124 HYBRIS ScreenView::setupAndRender(UIRenderContext&)+4101 in libminecraftpe.so+0x1862125 [0xeb11c125]
#136 HYBRIS ProfilerLite::gProfilerLiteInstance+0 in libminecraftpe.so+0x38c2878 [0xed17c878]
#392 HYBRIS ScreenView::ignoreAsTop() const+36 in libminecraftpe.so+0x186a864 [0xeb124864]
#396 HYBRIS UIScene::screenDrawsLast() const+9 in libminecraftpe.so+0xfef639 [0xea8a9639]
#400 HYBRIS CompositeSceneStackView::forEachVisibleScreen(std::function<void (std::shared_ptr<AbstractScene>&)>, bool, bool, bool)+698 in libminecraftpe.so+0xfda64a [0xea89464a]
#404 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x2c7ac47 [0xec534c47]
#420 HYBRIS ClientInstance::forEachVisibleScreen(std::function<void (std::shared_ptr<AbstractScene>&)>, bool)+618 in libminecraftpe.so+0xd9c33a [0xea65633a]
#448 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x2c7ac47 [0xec534c47]
#456 HYBRIS MinecraftGame::update()+2275 in libminecraftpe.so+0xdc7c53 [0xea681c53]
#465 HYBRIS PatchNotesModel::mPreloadedPatchNotes+0 in libminecraftpe.so+0x3896080 [0xed150080]
#466 HYBRIS ProfilerLite::gProfilerLiteInstance+0 in libminecraftpe.so+0x38c2878 [0xed17c878]
#648 HYBRIS xbox::services::java_interop::log_cll(std::string const&, std::string const&, std::string const&)+0 in libminecraftpe.so+0x2791820 [0xec04b820]
#649 HYBRIS crossplat::JVM+0 in libminecraftpe.so+0x394e618 [0xed208618]
Signal 6 received
Aborted (core dumped)

**Comment by coolkidsrule101** [comment]
ITS KEEP CRASHING THE GAME AND IT ANNOYING  sorry for caps

**Comment by coolkidsrule101** [comment]
ITS KEEP CRASHING THE GAME AND IT ANNOYING  sorry for caps

**Comment by Tiago1098** [comment]
My MInecraft is also crashing!

**Comment by MCMrARM** [comment]
Does this also happen if you sign out of Xbox Live?

**Comment by coolkidsrule101** [comment]
no ,not at all

**Comment by coolkidsrule101** [comment]
sorry i ment yes

**Comment by MCMrARM** [comment]
Merged with #270
