### ISSUE TITLE
Invite Button Not Appearing?

### ISSUE THREAD

**Issue by M3meZ** [MCMrARM/mcpelauncher-linux#279]
The Button Does Not Appear When I Make a World And I Set All The Settings To Online To The World This Does Not Let Me Invite People To The Game and My Game Doesnt Pop Up in The Game List Cause I Tested It On My Windows PC This Is Either a Bug Or a Problem With the mcpelauncher Can You Atleast Give Me Some Info Cause I Think The Game Thinks Im Playing Offline
 https://imgur.com/a/vpqXn

**Comment by AryToNeX** [comment]
Okay But Please Do Not Capitalize All The Words In Your Message And Use Some Punctuation

Then, Xbox Live issues are common in mcpelauncher and, as reported before, inviting friends and joining their worlds in friends list is bugged. MCMrARM already knows about that, no need to spam with useless issue tickets here.

**Comment by M3meZ** [comment]
sorry my fault about that
