### ISSUE TITLE
Draw distance too short

### ISSUE THREAD

**Issue by fazo96** [MCMrARM/mcpelauncher-linux#28]
On my phone I have 4 levels of draw distance I can choose from, but using this there's only two. I guess it's because the game thinks my device is not capable of the highest draw distance (which is not true).

Maybe there's a way to work around this?

**Comment by MCMrARM** [comment]
Fixed with commit:
https://github.com/MCMrARM/mcpelauncher-linux/commit/35e96ced892472eb235a26d9c3c9ef2531b7ffa2
