### ISSUE TITLE
fatal error: include/cef_app.h: No such file or directory

### ISSUE THREAD

**Issue by M3meZ** [MCMrARM/mcpelauncher-linux#282]
(xenial)vroom@localhost:~/Desktop/dedicated server/mcpelauncher-linux-master$ make
[ 39%] Built target gplayapi
[ 40%] Building CXX object CMakeFiles/mcpelauncher.dir/src/main.cpp.o
In file included from /home/vroom/Desktop/dedicated server/mcpelauncher-linux-master/src/main.cpp:40:0:
/home/vroom/Desktop/dedicated server/mcpelauncher-linux-master/src/browser.h:10:29: fatal error: include/cef_app.h: No such file or directory
compilation terminated.
CMakeFiles/mcpelauncher.dir/build.make:638: recipe for target 'CMakeFiles/mcpelauncher.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/mcpelauncher.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mcpelauncher.dir/all' failed
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

I think i had this problem before but i cant find it.

**Comment by guppy42** [comment]
You need to init the submosules

**Comment by InusualZ** [comment]
You need to download the CEF dependencies or disable CEF support in the CMake script

**Comment by M3meZ** [comment]
I have installed the cef dependencies and why would i disable cef?

**Comment by guppy42** [comment]
your compiling in a new directory so you need to run the shell scripts (.sh) again eg. ./setup_cef.sh
as it installs per directory and not globally

**Comment by M3meZ** [comment]
i did it several times and still makes that same error sadly ;/

**Comment by M3meZ** [comment]
I just saw a new commit and im going to recompile and close if theres no problem

**Comment by M3meZ** [comment]
still the same problem

**Comment by MCMrARM** [comment]
Paste output for `./setup_cef.sh`?

**Comment by M3meZ** [comment]
Is this the reason why this is happening?
cp: target 'version/mcpelauncher-linux-master/libs/cef/include' is not a directory
Plus there is no files in the include folder but there is some in my other folder of mcpelauncher

**Comment by M3meZ** [comment]
so the problem was that i was extracting in a folder for another folder?

:/ wow
