### ISSUE TITLE
uummm whats happining

### ISSUE THREAD

**Issue by coolkidsrule101** [MCMrARM/mcpelauncher-linux#285]
#0 ./mcpelauncher(_Z12handleSignaliPv+0x62) [0x82a229c]
#1 [0xf77acca0]
#2 HYBRIS Player::updateCreativeItemList(std::vector<ItemInstance, std::allocator<ItemInstance> > const&)+179 in libminecraftpe.so+0x1e5fda3 [0xeb77bda3]
Dumping stack...
#17 HYBRIS Player::updateCreativeItemList(std::vector<ItemInstance, std::allocator<ItemInstance> > const&)+179 in libminecraftpe.so+0x1e5fda3 [0xeb77bda3]
#60 HYBRIS Player::updateCreativeItemList(std::vector<ItemInstance, std::allocator<ItemInstance> > const&)+179 in libminecraftpe.so+0x1e5fda3 [0xeb77bda3]
#232 HYBRIS ScreenView::_bindData(bool)+1644 in libminecraftpe.so+0x185e91c [0xeb17a91c]
#259 HYBRIS ScreenView::_bindData(bool)+1644 in libminecraftpe.so+0x185e91c [0xeb17a91c]
#364 HYBRIS ItemInstance::_updateCompareHashes()+12 in libminecraftpe.so+0x1f45dfc [0xeb861dfc]
#368 HYBRIS std::vector<Block const*, std::allocator<Block const*> >::operator=(std::vector<Block const*, std::allocator<Block const*> > const&)+12 in libminecraftpe.so+0x1f4681c [0xeb86281c]
#370 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x2c78966 [0xec594966]
#372 HYBRIS std::_Rb_tree<std::string, std::pair<std::string const, std::unique_ptr<Tag, std::default_delete<Tag> > >, std::_Select1st<std::pair<std::string const, std::unique_ptr<Tag, std::default_delete<Tag> > > >, std::less<std::string>, std::allocator<std::pair<std::string const, std::unique_ptr<Tag, std::default_delete<Tag> > > > >::_M_erase(std::_Rb_tree_node<std::pair<std::string const, std::unique_ptr<Tag, std::default_delete<Tag> > > >*)+180 in libminecraftpe.so+0x1ab6c04 [0xeb3d2c04]
#392 HYBRIS Player::updateCreativeItemList(std::vector<ItemInstance, std::allocator<ItemInstance> > const&)+106 in libminecraftpe.so+0x1e5fd5a [0xeb77bd5a]
#396 HYBRIS operator delete(void*)+28 in libminecraftpe.so+0x2c7897c [0xec59497c]
#423 HYBRIS Item::mCreativeList+0 in libminecraftpe.so+0x38d596c [0xed1f196c]
#424 HYBRIS LegacyClientNetworkHandler::handle(NetworkIdentifier const&, InventoryContentPacket const&)+2143 in libminecraftpe.so+0x10a1e0f [0xea9bde0f]
#426 HYBRIS Item::mCreativeList+0 in libminecraftpe.so+0x38d596c [0xed1f196c]
#434 HYBRIS Item::mCreativeList+0 in libminecraftpe.so+0x38d596c [0xed1f196c]
#536 HYBRIS std::_Rb_tree<CommandRegistry::Symbol, CommandRegistry::Symbol, std::_Identity<CommandRegistry::Symbol>, std::less<CommandRegistry::Symbol>, std::allocator<CommandRegistry::Symbol> >::_M_erase(std::_Rb_tree_node<CommandRegistry::Symbol>*)+12 in libminecraftpe.so+0x1c127dc [0xeb52e7dc]
#620 HYBRIS HealthAttributeDelegate::change(float, float, AttributeBuffInfo)+202 in libminecraftpe.so+0x22559ea [0xebb719ea]
#624 HYBRIS ScreenController::handleGameEventNotification(ui::GameEventNotification)+12 in libminecraftpe.so+0xfded3c [0xea8fad3c]
#640 HYBRIS getTimeS()+36 in libminecraftpe.so+0x24c1c14 [0xebdddc14]
#648 HYBRIS ScreenView::_bindData(bool)+1761 in libminecraftpe.so+0x185e991 [0xeb17a991]
#649 HYBRIS ProfilerLite::gProfilerLiteInstance+0 in libminecraftpe.so+0x38c2878 [0xed1de878]
#660 HYBRIS AttributeInstance::addBuff(AttributeBuff const&)+347 in libminecraftpe.so+0x1ce650b [0xeb60250b]
#661 HYBRIS ProfilerLite::gProfilerLiteInstance+0 in libminecraftpe.so+0x38c2878 [0xed1de878]
#704 HYBRIS LegacyClientNetworkHandler::handle(NetworkIdentifier const&, PlayerHotbarPacket const&)+217 in libminecraftpe.so+0x10a29a9 [0xea9be9a9]
#708 HYBRIS vtable for LegacyClientNetworkHandler+8 in libminecraftpe.so+0x3798c18 [0xed0b4c18]
#712 HYBRIS InventoryContentPacket::handle(NetworkIdentifier const&, NetEventCallback&) const+48 in libminecraftpe.so+0x1ae0d30 [0xeb3fcd30]
#716 HYBRIS PlayerHotbarPacket::~PlayerHotbarPacket()+53 in libminecraftpe.so+0x1197485 [0xeaab3485]
#720 HYBRIS NetworkHandler::_eventLoop(unsigned char, NetEventCallback&, NetworkHandler::Connection&)+193 in libminecraftpe.so+0x1ad2501 [0xeb3ee501]
#730 HYBRIS ClientNetworkHandler::allowIncomingPacketId(NetworkIdentifier const&, int)+0 in libminecraftpe.so+0x18b5c60 [0xeb1d1c60]
#753 HYBRIS operator new(unsigned int)+12 in libminecraftpe.so+0x2c7ac2c [0xec596c2c]
#764 HYBRIS BatchedNetworkPeer::receivePacket(std::string&)+64 in libminecraftpe.so+0x21cd0c0 [0xebae90c0]
#768 HYBRIS operator delete(void*)+28 in libminecraftpe.so+0x2c7897c [0xec59497c]
#774 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x2c78966 [0xec594966]
#784 HYBRIS NetworkHandler::_sortAndPacketizeEvents(NetworkHandler::Connection&)+1027 in libminecraftpe.so+0x1ad2323 [0xeb3ee323]
#795 HYBRIS vtable for ReadOnlyBinaryStream+8 in libminecraftpe.so+0x37aa94c [0xed0c694c]
#808 HYBRIS NetworkHandler::runEvents()+151 in libminecraftpe.so+0x1ad1e27 [0xeb3ede27]
#820 HYBRIS Minecraft::update()+646 in libminecraftpe.so+0x2152dc6 [0xeba6edc6]
#860 HYBRIS GGDevice::clearEvents()+11 in libminecraftpe.so+0x1a1665b [0xeb33265b]
#871 HYBRIS Multitouch::resetThisUpdate()+5 in libminecraftpe.so+0x1a24d05 [0xeb340d05]
#872 HYBRIS TouchMapper::clearInputDeviceQueue()+26 in libminecraftpe.so+0x1a25b8a [0xeb341b8a]
#884 HYBRIS ClientInstance::update(bool)+156 in libminecraftpe.so+0xd96acc [0xea6b2acc]
#910 HYBRIS ProfilerLite::gProfilerLiteInstance+0 in libminecraftpe.so+0x38c2878 [0xed1de878]
#912 HYBRIS getTimeS()+36 in libminecraftpe.so+0x24c1c14 [0xebdddc14]
#917 HYBRIS ProfilerLite::gProfilerLiteInstance+0 in libminecraftpe.so+0x38c2878 [0xed1de878]
#925 HYBRIS ServiceLocator<AppPlatform>::mService+0 in libminecraftpe.so+0x3890ddc [0xed1acddc]
#944 HYBRIS MinecraftGame::update()+1123 in libminecraftpe.so+0xdc77d3 [0xea6e37d3]
#953 HYBRIS PatchNotesModel::mPreloadedPatchNotes+0 in libminecraftpe.so+0x3896080 [0xed1b2080]
#954 HYBRIS ProfilerLite::gProfilerLiteInstance+0 in libminecraftpe.so+0x38c2878 [0xed1de878]
Signal 6 received
Aborted (core dumped)

**Comment by MCMrARM** [comment]
When does it happen?

**Comment by coolkidsrule101** [comment]
When I join a world from another device

**Comment by coolkidsrule101** [comment]
The world on the other device was nodded

**Comment by coolkidsrule101** [comment]
MCMrARM

**Comment by MCMrARM** [comment]
Is the other device using a modded MCPE? If yes, does it happen in vanilla?

I don't have much clue, I don't have this issue myself.

**Comment by MCMrARM** [comment]
This looks like something caused by a mod.

**Comment by AndroPort-Owner** [comment]
i have the same but not on a mod, onlly shaders

**Comment by coolkidsrule101** [comment]
Sorry I haven't responded it I was moving and it's being caused from
devices that may have mods, shader,it even plugin . Is there a patch for
this???

**Comment by MCMrARM** [comment]
Use vanilla or load the same mods. There's nothing I can do about it.

Before reporting a crash here, please make sure it happens with vanilla clients too.
