### ISSUE TITLE
[old-1.1] Can't start after installing nvidia-390 drivers

### ISSUE THREAD

**Issue by Encritary** [MCMrARM/mcpelauncher-linux#287]
Signal 11 received
Backtrace elements: 4
#0 ./mcpelauncher(_Z12handleSignaliPv+0x62) [0x806cee5]
#1 [0xf7748ca0]
#2 /lib/i386-linux-gnu/libc.so.6(strstr+0x1a) [0xf72ba36a]
#3 HYBRIS mce::FeatureSupportOGL::FeatureSupportOGL()+379 in libminecraftpe.so+0x163137b [0xf539c37b]
Dumping stack...
#18 HYBRIS mce::FeatureSupportOGL::FeatureSupportOGL()+379 in libminecraftpe.so+0x163137b [0xf539c37b]
#25 HYBRIS operator new(unsigned int)+12 in libminecraftpe.so+0x2553f6c [0xf62bef6c]
#72 HYBRIS Json::Reader::decodeString(Json::Reader::Token&)+208 in libminecraftpe.so+0x1e6bed0 [0xf5bd6ed0]
#92 HYBRIS Json::Reader::decodeString(Json::Reader::Token&, std::string&)+48 in libminecraftpe.so+0x1e6c870 [0xf5bd7870]
#104 HYBRIS operator delete(void*)+28 in libminecraftpe.so+0x2551cbc [0xf62bccbc]
#110 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x2551ca6 [0xf62bcca6]
#120 HYBRIS Json::Reader::readObject(Json::Reader::Token&)+896 in libminecraftpe.so+0x1e6b380 [0xf5bd6380]
#140 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x2553f87 [0xf62bef87]
#148 HYBRIS std::_Rb_tree_iterator<std::pair<Json::Value::CZString const, Json::Value> > std::_Rb_tree<Json::Value::CZString, std::pair<Json::Value::CZString const, Json::Value>, std::_Select1st<std::pair<Json::Value::CZString const, Json::Value> >, std::less<Json::Value::CZString>, std::allocator<std::pair<Json::Value::CZString const, Json::Value> > >::_M_insert_<std::pair<Json::Value::CZString const, Json::Value>&>(std::_Rb_tree_node_base*, std::_Rb_tree_node_base*, std::pair<Json::Value::CZString const, Json::Value>&)+269 in libminecraftpe.so+0x1e72fad [0xf5bddfad]
#156 HYBRIS Json::Reader::readToken(Json::Reader::Token&)+12 in libminecraftpe.so+0x1e6beec [0xf5bd6eec]
#164 HYBRIS Json::Reader::readValue()+200 in libminecraftpe.so+0x1e6ac88 [0xf5bd5c88]
#172 HYBRIS Json::Value::~Value()+12 in libminecraftpe.so+0x1e6f63c [0xf5bda63c]
#180 HYBRIS operator delete(void*)+28 in libminecraftpe.so+0x2551cbc [0xf62bccbc]
#188 HYBRIS Json::Reader::readToken(Json::Reader::Token&)+12 in libminecraftpe.so+0x1e6beec [0xf5bd6eec]
#196 HYBRIS Json::Reader::readArray(Json::Reader::Token&)+444 in libminecraftpe.so+0x1e6b7bc [0xf5bd67bc]
#208 HYBRIS Json::Value::~Value()+12 in libminecraftpe.so+0x1e6f63c [0xf5bda63c]
#228 HYBRIS Json::Reader::decodeString(Json::Reader::Token&, std::string&)+48 in libminecraftpe.so+0x1e6c870 [0xf5bd7870]
#366 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x2551ca6 [0xf62bcca6]
#368 HYBRIS Json::Value::~Value()+67 in libminecraftpe.so+0x1e6f673 [0xf5bda673]
#404 HYBRIS gl::Version::_findMajorMinor()+82 in libminecraftpe.so+0x1632ed2 [0xf539ded2]
#424 HYBRIS gl::getOpenGLExtensions()+76 in libminecraftpe.so+0x163347c [0xf539e47c]
#436 HYBRIS mce::FeatureSupportOGL::FeatureSupportOGL()+379 in libminecraftpe.so+0x163137b [0xf539c37b]
#440 HYBRIS mce::ImmediateBuffer::ImmediateBuffer()+28 in libminecraftpe.so+0x164d0ec [0xf53b80ec]
#452 HYBRIS mce::RenderContext::RenderContext()+27 in libminecraftpe.so+0x162f61b [0xf539a61b]
#456 HYBRIS mce::RenderDeviceBase::RenderDeviceBase()+85 in libminecraftpe.so+0x162d7f5 [0xf53987f5]
#458 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x2551ca6 [0xf62bcca6]
#464 HYBRIS mce::RenderDevice::RenderDevice()+38 in libminecraftpe.so+0x162fce6 [0xf539ace6]
#466 HYBRIS mce::Singleton<mce::RenderDevice, std::unique_ptr<mce::RenderDevice, std::default_delete<mce::RenderDevice> > >::instance+0 in libminecraftpe.so+0x2ead94c [0xf6c1894c]
#468 HYBRIS MinecraftGame::setupRenderer(HolographicPlatform&)+460 in libminecraftpe.so+0xcf0f2c [0xf4a5bf2c]
#474 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x2551ca6 [0xf62bcca6]
#475 HYBRIS AppPlatform::readAssetFile(std::string const&)+0 in libminecraftpe.so+0x17700a0 [0xf54db0a0]
#479 HYBRIS vtable for ResourcePackStack+8 in libminecraftpe.so+0x2dc65a8 [0xf6b315a8]
#480 HYBRIS ResourcePackManager::setStack(std::unique_ptr<ResourcePackStack, std::default_delete<ResourcePackStack> >, ResourcePackStackType, bool)+722 in libminecraftpe.so+0x17aee82 [0xf5519e82]
#491 HYBRIS vtable for ResourcePackStack+8 in libminecraftpe.so+0x2dc65a8 [0xf6b315a8]
#492 HYBRIS MinecraftGame::init()+3560 in libminecraftpe.so+0xceb028 [0xf4a56028]
#506 HYBRIS vtable for ResourcePackStack+8 in libminecraftpe.so+0x2dc65a8 [0xf6b315a8]
Signal 6 received
Aborted (core dumped)

**Comment by Encritary** [comment]
p.s. current master branch is working well

**Comment by MCMrARM** [comment]
Your best idea would be to likely revert a few commits post-1.1 (revert the store header to 1.1, see what's still broken and eventually fix those stuff). I do not provide support for 1.1's old code, if there's enough attention I can look into providing support for older versions of Minecraft.

Commits related:
https://github.com/MCMrARM/mcpelauncher-linux/commit/ee5bc0123a8d058b45e23257d4b7be9922cb59bf
https://github.com/MCMrARM/mcpelauncher-linux/commit/d14041dcdcfa289851c61cf99991c7e1b9684c6c
https://github.com/MCMrARM/mcpelauncher-linux/commit/8a4db3b991d1ee0a93fe82acc697ff5e2e05fe3d
https://github.com/MCMrARM/mcpelauncher-linux/commit/b14c6395a9f02110372d747f00409df811f052f5
https://github.com/MCMrARM/mcpelauncher-linux/commit/b14c6395a9f02110372d747f00409df811f052f5
https://github.com/MCMrARM/mcpelauncher-linux/commit/0b5fe034f0f4ca9007b701d2c34dd1097b5886f4
https://github.com/MCMrARM/mcpelauncher-linux/commit/b9f6c110ae763f21803c2fe56fdd5ead763c3f51

**Comment by Encritary** [comment]
@MCMrARM this commit fixed it: https://github.com/MCMrARM/mcpelauncher-linux/commit/e2e4ebcad52ae2bdef645f83673a2da924ee602b
