### ISSUE TITLE
[server]separate the server / client build script(or just add a option)

### ISSUE THREAD

**Issue by codehz** [MCMrARM/mcpelauncher-linux#288]
Some dependencies are useless for server(headless) builds.
e.g X11 glfw cef and `extract.cpp`(with zip, I mean the `extract.cpp` file can be moved to client folder)

If done, the server-side build can also be statically linked and portable. (the only thing that cannot be statically linked is `libm`, but it is easy to adapt).

in fact, I've write a CMakeLists.txt to produce a statically linked server binary(https://github.com/codehz/mcpe-server), and it have a automated build(https://hub.docker.com/r/codehz/mcpe-server)

**Comment by MCMrARM** [comment]
Yes, I definitely want to do this asap.

**Comment by MCMrARM** [comment]
Please try https://github.com/MCMrARM/mcpelauncher-linux/commit/5d55bc8577464dc5c83c968ac9ff806f88d1bcdc

**Comment by codehz** [comment]
@MCMrARM 
I don't think libzip is necessary for building the server binary...extract.cpp is unused...

**Comment by wiktorek140** [comment]
@codehz i suppose u need resources from apk so that why libzip stay in building server :)

**Comment by codehz** [comment]
@wiktorek140 but it can be done manually or just use client binary to do that..
The server does not use any function inside `extract.cpp` actually..

**Comment by guppy42** [comment]
@codehz it server should be able to do the extract it self - otherwise running a headless server would be impossible.

**Comment by codehz** [comment]
@guppy42 I mean, add this feature, or remove this feature and then remove the extra dependencies..

See https://github.com/codehz/mcpe-demo 

And I think people who have a headless server should have some ability to use script. This built-in extracting function for such people is not necessary.

**Comment by MCMrARM** [comment]
This feature is planned.

**Comment by MCMrARM** [comment]
Does this work just fine otherwise?

**Comment by codehz** [comment]
@MCMrARM yes, it worked for me!
