### ISSUE TITLE
 fatal error: ../common/symbols/gles_symbols.h: No such file or directory

### ISSUE THREAD

**Issue by M3meZ** [MCMrARM/mcpelauncher-linux#289]
make
[ 34%] Built target gplayapi
[ 73%] Built target mcpelauncher
[ 74%] Building CXX object CMakeFiles/server.dir/src/server/server.cpp.o
/home/vroom/Desktop/mcpelauncher-linux-master/src/server/server.cpp:9:44: fatal error: ../common/symbols/gles_symbols.h: No such file or directory
compilation terminated.
CMakeFiles/server.dir/build.make:710: recipe for target 'CMakeFiles/server.dir/src/server/server.cpp.o' failed
make[2]: *** [CMakeFiles/server.dir/src/server/server.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/server.dir/all' failed
make[1]: *** [CMakeFiles/server.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

Any solutions anyone?

**Comment by MCMrARM** [comment]
Fixed with https://github.com/MCMrARM/mcpelauncher-linux/commit/e80076f2adee7b7d4ff5ac1d6bf39029916e385d

**Comment by M3meZ** [comment]
Wow your on point!
