### ISSUE TITLE
Keyboard issue: Can't insert some symbols

### ISSUE THREAD

**Issue by AryToNeX** [MCMrARM/mcpelauncher-linux#29]
I can't insert some symbols and accented letters (§, ò, à, ù, °, ç, ì, etc.)
This limits communication on servers in certain languages, so it must be fixed.
@MCMrARM

**Comment by MCMrARM** [comment]
likely, I limited the text input, will check how can I fix that

**Comment by AryToNeX** [comment]
Other keyboard issue: enter key does not work when writing in signs

**Comment by AryToNeX** [comment]
Please fix that issue asap, I can't type my password on servers
