### ISSUE TITLE
[server] cpu usage is always at 100%

### ISSUE THREAD

**Issue by julianwi** [MCMrARM/mcpelauncher-linux#292]
If i use the gnu top command while the dedicated server is running it reports 100% cpu usage for it. Even if no player is connected to the server. I can workaround it by adding
```c
usleep(50000);
```
to the main loop of server.cpp.
I think the launcher should look if the call to `processCoroutines` took less then 50 milliseconds and then sleep the remaining time.

**Comment by MCMrARM** [comment]
Fixed with https://github.com/MCMrARM/mcpelauncher-linux/commit/d8245d96694f79c3ceccf12caa98879545659b80
