### ISSUE TITLE
mcpe 1.2.9

### ISSUE THREAD

**Issue by masrourmouad** [MCMrARM/mcpelauncher-linux#293]
the ui is wrong

**Comment by MCMrARM** [comment]
What do you mean? MCPE 1.2.9 works just fine for me.

**Comment by masrourmouad** [comment]
i mean  the home layout is messed up

**Comment by MCMrARM** [comment]
Wtf, did you manage to fix this?

**Comment by masrourmouad** [comment]
the new ui code is buggy replace it with the old one

**Comment by masrourmouad** [comment]
hey MCMrARM can you make a standalone cli application that replace the old version with the new (via apk extraction)

**Comment by MCMrARM** [comment]
Why would you need a standalone app for that? Simply run `mcpelauncher extract ` + path

**Comment by masrourmouad** [comment]
when apk extracted launcher will not show up only the game (btw: thanks for the replies)
