### ISSUE TITLE
Dedicated server not working on 1.2.9

### ISSUE THREAD

**Issue by MCMrARM** [MCMrARM/mcpelauncher-linux#296]
I hope to fix it tomorrow.

1.2.8 has to be used until then.

**Comment by codehz** [comment]
But I have tested in 3 different server, and they are all working..
![screenshot](https://i.imgur.com/7rp3uBp.jpg)

**Comment by guppy42** [comment]
That's not what he meant

**Comment by MCMrARM** [comment]
Nevermind -- it's not broken, I unzipped an older version instead lol.
