### ISSUE TITLE
CMake uses the 64-bit version of libPNG

### ISSUE THREAD

**Issue by sliceofcode** [MCMrARM/mcpelauncher-linux#3]
This causes CMake to die when `cmake ..`.
Fix using: `sudo apt-get install libpng12-dev`
Is that a problem?

**Comment by byteandahalf** [comment]
Doing this still gives me errors:
`/usr/bin/ld: cannot find -lEGL
/usr/bin/ld: cannot find -lpng`

**Comment by SopaXorzTaker** [comment]
@byteandahalf, you will need to install these:

`sudo apt-get install libpng:i386 libpng-dev:i386 libgles2-mesa:i386 libegl1-mesa:i386 libgles2-mesa-dev:i386 libegl1-mesa-dev:i386`. This worked for me.

**Comment by SopaXorzTaker** [comment]
Also, you might need to install these before:
`sudo apt-get install libz1-dev:i386 libncurses5-dev:i386 libbz2-1.0-dev:i386`

**Comment by MCMrARM** [comment]
I think I fixed this.

**Comment by byteandahalf** [comment]
Thanks.

**Comment by byteandahalf** [comment]
You also need to install `libglapi-mesa:i386` before `libgles2-mesa:i386`, etc.

**Comment by byteandahalf** [comment]
Also, why the heck does it keep telling me that `libpng:i386` doesn't exist?
I installed `libpng-dev:i386`, but that one doesn't get rid of the build error.

**Comment by stayandwait** [comment]
I read through this, it only fixed one of my problems. When I was getting:
/usr/bin/ld: cannot find -lEGL
/usr/bin/ld: cannot find -lpng

Then I added a symlink hoping this would fix the problem.
ln -s /usr/lib/x86_64-linux-gnu/libpng.so /usr/lib/libpng.so

and this is the new error I am getting now..
[100%] Building CXX object CMakeFiles/mcpelauncher.dir/mcpe/types.cpp.o
make[2]: *** No rule to make target /usr/lib/libpng.so', needed bymcpelauncher'. Stop.
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
make: *** [all] Error 2

**Comment by egr7v8** [comment]
@stayandwait solved a problem?
