### ISSUE TITLE
Can't launch launcher.

### ISSUE THREAD

**Issue by Yexeed** [MCMrARM/mcpelauncher-linux#300]
yexeed@yexeed-pc:~/Рабочий стол/mcpelauncher-linux$ ./mcpelauncher 
17:57:15 Trace [Launcher] Loading native libraries
17:57:15 Trace [Launcher] Loaded OS library /home/yexeed/Рабочий стол/mcpelauncher-linux/libs/native/libfmod.so.9.6
17:57:15 Trace [Launcher] Loaded OS library libm.so.6
17:57:15 Trace [Launcher] Loading hybris libraries
17:57:15 Trace [Launcher] Loading Minecraft library
17:57:15 Info [Launcher] Loaded Minecraft library
17:57:15 Debug [Launcher] Minecraft is at offset 0xf36b3000
17:57:15 Info [Launcher] Applying patches
17:57:15 Trace [Launcher] Patching - original: 85 83 87 86 131
17:57:15 Trace [Launcher] Patching - result: 233 171 158 39 98
17:57:15 Trace [Launcher] Patching - original: 85 83 87 86 131
17:57:15 Trace [Launcher] Patching - result: 233 159 108 40 98
17:57:15 Trace [Launcher] Patching - original: 85 83 87 86 129
17:57:15 Trace [Launcher] Patching - result: 233 3 106 40 98
17:57:15 Trace [Launcher] Patching - original: 83 87 86 131 236
17:57:15 Trace [Launcher] Patching - result: 233 191 106 40 98
17:57:15 Trace [Launcher] Patching - original: 83 131 236 8 232
17:57:15 Trace [Launcher] Patching - result: 233 219 156 188 96
17:57:15 Trace [Launcher] Patching - original: 83 87 86 131 236
17:57:15 Trace [Launcher] Patching - result: 233 247 163 188 96
17:57:15 Trace [Launcher] Patching - original: 85 83 87 86 131
17:57:15 Trace [Launcher] Patching - result: 233 39 123 178 96
17:57:15 Trace [Launcher] Patching - original: 85 83 87 86 131
17:57:15 Trace [Launcher] Patching - result: 233 231 61 220 96
17:57:15 Trace [Launcher] Patching - original: 85 83 87 86 131
17:57:15 Trace [Launcher] Patching - result: 233 190 67 220 96
17:57:15 Trace [Launcher] Patching - original: 85 83 87 86 131
17:57:15 Trace [Launcher] Patching - result: 233 241 62 220 96
Signal 11 received
Backtrace elements: 6
#0 ./mcpelauncher(_Z12handleSignaliPv+0x70) [0x565dc3d5]
#1 [0xf7fc7dd0]
#2 ./mcpelauncher(_Z20patchCallInstructionPvS_b+0x3f) [0x565dc267]
#3 ./mcpelauncher(main+0x1028) [0x565f7c2d]
#4 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf6) [0xf769b986]
#5 ./mcpelauncher(+0x6f651) [0x565ce651]
Dumping stack...
Signal 6 received
Аварийный останов (стек памяти сброшен на диск)

I getting this when trying to launch launcher using ./mcpelauncher. I installed all libs from readme (except libs to work xbox) and extracted x86 1.1.4 mcpe

**Comment by codehz** [comment]
You may need using the latest version of the Minecraft....

**Comment by Yexeed** [comment]
ok, creating new issue and closing this
