### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by stormchaser3000** [MCMrARM/mcpelauncher-linux#306]
/home/stormchaser3000/mcpelauncher-linux/src/common/openssl_multithread.cpp: In static member function ‘static void OpenSSLMultithreadHelper::init()’:
/home/stormchaser3000/mcpelauncher-linux/src/common/openssl_multithread.cpp:12:6: error: invalid user-defined conversion from ‘OpenSSLMultithreadHelper::init()::<lambda()>’ to ‘long unsigned int (*)()’ [-fpermissive]
     });
      ^

**Comment by MCMrARM** [comment]
https://github.com/MCMrARM/mcpelauncher-linux/commit/42181186387d3bf9a9732e469313fab69b2a8ac5 should fix it
