### ISSUE TITLE
Compiling Error [Make]

### ISSUE THREAD

**Issue by M3meZ** [MCMrARM/mcpelauncher-linux#309]
[ 33%] Built target gplayapi
[ 34%] Building CXX object CMakeFiles/mcpelauncher.dir/src/common/openssl_multithread.cpp.o
/home/vroom/Desktop/mcpelauncher-linux-master/src/common/openssl_multithread.cpp: In lambda function:
/home/vroom/Desktop/mcpelauncher-linux-master/src/common/openssl_multithread.cpp:15:48: error: cannot convert 'pthread_mutex_t' to 'pthread_mutex_t*' for argument '1' to 'int pthread_mutex_lock(pthread_mutex_t*)'
             pthread_mutex_lock(mutexes[n].mutex);
                                                ^
/home/vroom/Desktop/mcpelauncher-linux-master/src/common/openssl_multithread.cpp:17:50: error: cannot convert 'pthread_mutex_t' to 'pthread_mutex_t*' for argument '1' to 'int pthread_mutex_unlock(pthread_mutex_t*)'
             pthread_mutex_unlock(mutexes[n].mutex);
                                                  ^
CMakeFiles/mcpelauncher.dir/build.make:870: recipe for target 'CMakeFiles/mcpelauncher.dir/src/common/openssl_multithread.cpp.o' failed
make[2]: *** [CMakeFiles/mcpelauncher.dir/src/common/openssl_multithread.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mcpelauncher.dir/all' failed
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by AqyxHD** [comment]
I have the same error :(

**Comment by M3meZ** [comment]
@AqyxHD I read your post about updating protobuf #310  but I updated the protobuf to 3.5.1 but still cant get pass the make error

**Comment by AqyxHD** [comment]
@M3meZ i had an Google Play submodule error, thats another story xD

**Comment by M3meZ** [comment]
oh ok.

**Comment by M3meZ** [comment]
i have a new error now

(xenial)vroom@localhost:~/Desktop/mcpelauncher-linux-master$ make
[ 33%] Built target gplayapi
[ 34%] Linking CXX executable mcpelauncher
/usr/local/lib/libprotobuf.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
CMakeFiles/mcpelauncher.dir/build.make:1267: recipe for target 'mcpelauncher' failed
make[2]: *** [mcpelauncher] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mcpelauncher.dir/all' failed
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
