### ISSUE TITLE
Error on the bus (the core recorded image) 

### ISSUE THREAD

**Issue by Docmine7** [MCMrARM/mcpelauncher-linux#31]
I have kubuntu 15:10 using intel cpu, I followed the following steps:
I downloaded said packages in the readme file.
then I used the 'cmake .'... command OK
then 'make' OK ...
and I put the minecraft pe 0.X.X x86 (i try MCPE 0.13.0 b4 to 0.14.0) i not using google play downloader.

i and run command ./extract.sh Mine.apk .... OK

and then I used the command ./mcpelauncher

and appears the following log:
Loading mcpe
libGLESv2.so: 151706304 
libfmod.so.7.2: 151708320 
erro no barramento (a imagem do núcleo gravada) | <-this  Error is in Portuguese
---------------------------------------------------
erro in english:
Loading mcpe
libGLESv2.so: 151706304 
libfmod.so.7.2: 151708320 
Error on the bus (the core recorded image)

------------------------------------------
(please help me) 

my english it's a shit

**Comment by ozzyjrs** [comment]
o meu nao ta completamente em portugues mas acontece isso 
my linux has not completly in portugues but this happen

`root@ozzus-Aspire-E1-421:/home/ozzus/Área de Trabalho/linux# ./mcpelauncher
loading MCPE
oslib: /usr/lib/i386-linux-gnu/libGLESv2.so: 151763648
oslib: /home/ozzus/Área de Trabalho/linux/libs/native/libfmod.so.7.7: 151765608
Illegal instruction (core dumped)
`
o mesmo erro!
the same error!
