### ISSUE TITLE
Error.

### ISSUE THREAD

**Issue by zyware** [MCMrARM/mcpelauncher-linux#317]
**Ubuntu 17.10 x64**

`[ 77%] Building CXX object CMakeFiles/server.dir/src/common/extract.cpp.o
In file included from /home/usr/mcpelauncher-linux/src/common/extract.h:4:0,
                 from /home/usr/mcpelauncher-linux/src/common/extract.cpp:1:
/usr/include/zip.h:59:10: fatal error: zipconf.h: Нет такого файла или каталога
 #include <zipconf.h>
          ^~~~~~~~~~~
compilation terminated.
CMakeFiles/server.dir/build.make:614: ошибка выполнения рецепта для цели «CMakeFiles/server.dir/src/common/extract.cpp.o»
make[2]: *** [CMakeFiles/server.dir/src/common/extract.cpp.o] Ошибка 1
CMakeFiles/Makefile2:67: ошибка выполнения рецепта для цели «CMakeFiles/server.dir/all»
make[1]: *** [CMakeFiles/server.dir/all] Ошибка 2
Makefile:83: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2`

**Comment by guppy42** [comment]
Do your self a favor install apt-file;
```
sudo apt install apt-file
apt-file update
```


Now in the future when your suddenly missing a file, you can answer it in seconds;
```
apt-file search /zipconf.h
```

yields

$ apt-file search /zipconf.h
**libzip-dev**: /usr/include/x86_64-linux-gnu/zipconf.h
**libzip-dev**: /usr/lib/x86_64-linux-gnu/libzip/include/zipconf.h


which is a requirement for this project.
