### ISSUE TITLE
Graphic issues

### ISSUE THREAD

**Issue by AryToNeX** [MCMrARM/mcpelauncher-linux#32]
- Some entities are glitched (personally I found only the enchanting table book with weird texture)
- Cannot disable fancy graphics

**Comment by svilex** [comment]
![bug](https://cloud.githubusercontent.com/assets/16593861/13993363/5f7b6e04-f120-11e5-9c77-f24160b7ea7e.png)

**Comment by stayandwait** [comment]
I'm having this problem too. The book is multicolored and black textured.
