### ISSUE TITLE
headless seems not working with 1.2.10

### ISSUE THREAD

**Issue by huhongbo** [MCMrARM/mcpelauncher-linux#323]
1.2.9 is working fine. But I update the minecraft to 1.2.10 and it seems not working. I already test the 1.2.10 branch, and it not working either.
11:01:58 Trace [Launcher] Loading hybris libraries
11:01:58 Trace [Launcher] Loaded OS library libm.so.6
11:01:58 Trace [Launcher] Loading Minecraft library
11:02:04 Info [Launcher] Loaded Minecraft library
11:02:04 Debug [Launcher] Minecraft is at offset 0xb3667000
11:02:04 Error [MinecraftSymbols] Unresolved symbol: _ZN14NetworkHandlerC2Ev
11:02:04 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppRK9WhitelistRK7OpsListP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSsRK19IContentKeyProviderSs13LevelSettingsRN9minecraft3api3ApiEibiiibRKSt6vectorISsSaISsEESsRKN3mce4UUIDER17MinecraftEventingR14NetworkHandlerR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerPS15_St8functionIFvRKSsEE
11:02:04 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance28mainThreadNetworkUpdate_HACKEv
11:02:04 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackib
11:02:04 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler9singletonEv
11:02:04 Info [Launcher] Starting server initialization
11:02:04 Trace [Launcher] Initializing AppPlatform (vtable)
11:02:04 Trace [AppPlatform] Vtable size = 206
11:02:04 Trace [Launcher] Initializing AppPlatform (create instance)
11:02:04 Trace [Launcher] Initializing AppPlatform (initialize call)
11:02:04 Trace [AppPlatform] createDeviceID:
11:02:05 Debug [Launcher] AppPlatform initialized successfully
11:02:05 Trace [Launcher] Loading whitelist and operator list
11:02:05 Trace [Launcher] Initializing Minecraft API classes
11:02:05 Trace [Launcher] Setting up level settings
11:02:05 Trace [Launcher] Initializing FilePathManager
11:02:05 Trace [AppPlatform] getCurrentStoragePath: /root/.local/share/mcpelauncher/
11:02:05 Trace [Launcher] Initializing resource loaders
11:02:05 Trace [Launcher] Initializing MinecraftEventing (create instance)
11:02:05 Trace [Launcher] Initializing MinecraftEventing (init call)
11:02:05 Trace [AppPlatform] getSystemRegion: 0xdeadbeef
11:02:05 Trace [Launcher] Initializing ResourcePackManager
11:02:05 Trace [Launcher] Initializing PackManifestFactory
11:02:05 Trace [Launcher] Initializing SkinPackKeyProvider
11:02:05 Trace [Launcher] Initializing PackSourceFactory
11:02:05 Trace [Launcher] Initializing ResourcePackRepository
11:02:05 Trace [AppPlatform] getInternalStoragePath: /root/.local/share/mcpelauncher/
11:02:05 Trace [AppPlatform] getInternalStoragePath: /root/.local/share/mcpelauncher/
11:02:05 Trace [AppPlatform] getInternalStoragePath: /root/.local/share/mcpelauncher/
11:02:05 Trace [AppPlatform] getInternalStoragePath: /root/.local/share/mcpelauncher/
11:02:05 Trace [AppPlatform] getInternalStoragePath: /root/.local/share/mcpelauncher/
11:02:05 Trace [AppPlatform] getInternalStoragePath: /root/.local/share/mcpelauncher/
11:02:05 Trace [AppPlatform] getInternalStoragePath: /root/.local/share/mcpelauncher/
11:02:05 Trace [Launcher] Adding vanilla resource pack
Signal 11 received
Backtrace elements: 2
#0 ./server(_Z12handleSignaliPv+0x62) [0x808ee43]
#1 [0xb77a6c14]
Dumping stack...
#12 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x2f6fb07 [0xb65d6b07]
#18 HYBRIS Core::FileSystemImpl::~FileSystemImpl()+11 in libminecraftpe.so+0x27a136b [0xb5e0836b]
#96 HYBRIS Core::StorageAreaState::_notifyOutOfDiskSpaceError()+81 in libminecraftpe.so+0x27a9001 [0xb5e10001]
#104 HYBRIS std::vector<std::string, std::allocator<std::string> >::operator=(std::vector<std::string, std::allocator<std::string> > const&)+12 in libminecraftpe.so+0xeb997c [0xb452097c]
#116 HYBRIS PlayScreenController::_getLegacyWorldConvertCallback(LegacyWorldInfo const&)+944 in libminecraftpe.so+0x1999000 [0xb5000000]
#134 HYBRIS xbox::services::game_server_platform::game_server_ticket_status::status() const+0 in libminecraftpe.so+0x2999000 [0xb6000000]
#164 HYBRIS MinecraftUnitTest::TokenTests::generateTestDataFor_Token_IsNumberWithNumberFollowedByComma_ReturnsTrue()+113 in libminecraftpe.so+0xe69001 [0xb44d0001]
#176 HYBRIS std::string* std::__uninitialized_copy<false>::__uninit_copy<__gnu_cxx::__normal_iterator<std::string const*, std::vector<std::string, std::allocator<std::string> > >, std::string*>(__gnu_cxx::__normal_iterator<std::string const*, std::vector<std::string, std::allocator<std::string> > >, __gnu_cxx::__normal_iterator<std::string const*, std::vector<std::string, std::allocator<std::string> > >, std::string*)+12 in libminecraftpe.so+0xd9253c [0xb43f953c]
#188 HYBRIS SemVersion::SemVersion(SemVersion const&)+98 in libminecraftpe.so+0xe72992 [0xb44d9992]
#202 HYBRIS xbox::services::game_server_platform::game_server_ticket_status::status() const+0 in libminecraftpe.so+0x2999000 [0xb6000000]
#212 HYBRIS operator delete(void*)+28 in libminecraftpe.so+0x2f6d83c [0xb65d483c]
#216 HYBRIS PackReport::~PackReport()+12 in libminecraftpe.so+0xd9219c [0xb43f919c]
#218 HYBRIS operator delete(void*)+6 in libminecraftpe.so+0x2f6d826 [0xb65d4826]
#228 HYBRIS ResourcePackRepository::KnownPackInfo::~KnownPackInfo()+490 in libminecraftpe.so+0x1ea8a9a [0xb550fa9a]
#433 HYBRIS vtable for SkinPackKeyProvider+8 in libminecraftpe.so+0x3b5b86c [0xb71c286c]
#483 HYBRIS vtable for minecraft::api::Api+8 in libminecraftpe.so+0x3b5602c [0xb71bd02c]
#485 HYBRIS vtable for minecraft::api::PlayerInterface+8 in libminecraftpe.so+0x3b56074 [0xb71bd074]
#486 HYBRIS vtable for minecraft::api::EntityInterface+8 in libminecraftpe.so+0x3b5608c [0xb71bd08c]
#487 HYBRIS vtable for minecraft::api::NetworkInterface+8 in libminecraftpe.so+0x3b5609c [0xb71bd09c]
#488 HYBRIS vtable for minecraft::api::PlayerInteractionInterface+8 in libminecraftpe.so+0x3b560b0 [0xb71bd0b0]
#674 HYBRIS vtable for MinecraftEventing+8 in libminecraftpe.so+0x3b6b9cc [0xb71d29cc]
Signal 6 received
Aborted (core dumped)

**Comment by masrourmouad** [comment]
use the normal one, replace the one you have with this after extracting it in /usr/local/share/mcpelauncher/bin

[mcpelauncher.zip](https://github.com/MCMrARM/mcpelauncher-linux/files/1710611/mcpelauncher.zip)

**Comment by MCMrARM** [comment]
Will look into it tomorrow.

**Comment by MCMrARM** [comment]
Works with the release, but not the beta. Beta releases are not fully supported, therefore I am closing the issue.
