### ISSUE TITLE
Can't sign in With xbox account

### ISSUE THREAD

**Issue by OmarRind** [MCMrARM/mcpelauncher-linux#324]
Pease help I cant sign in!
Error!
To log in please build the launcher with CEF support.
10:57:58 Trace [Launcher] init_sign_in_activity 6
10:57:58 Trace [Launcher] log_telemetry_signin 0 Exiting - runtime_error
10:57:58 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
10:57:58 Trace [Launcher] LinuxHttpRequestInternal::~LinuxHttpRequestInternal
10:57:58 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
10:57:58 Trace [Launcher] LinuxHttpRequestInternal::~LinuxHttpRequestInternal

**Comment by MCMrARM** [comment]
I don't know if you did this on purpose or not, but do not create duplicate issues. You also opened #325.
