### ISSUE TITLE
Cant sign in xbox live

### ISSUE THREAD

**Issue by OmarRind** [MCMrARM/mcpelauncher-linux#325]
Pease help I cant sign in!
Error!
To log in please build the launcher with CEF support.
10:57:58 Trace [Launcher] init_sign_in_activity 6
10:57:58 Trace [Launcher] log_telemetry_signin 0 Exiting - runtime_error
10:57:58 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
10:57:58 Trace [Launcher] LinuxHttpRequestInternal::~LinuxHttpRequestInternal
10:57:58 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
10:57:58 Trace [Launcher] LinuxHttpRequestInternal::~LinuxHttpRequestInternal

**Comment by InusualZ** [comment]
You need to build the program with CEF enabled

**Comment by OmarRind** [comment]
can you please explain How can i build?

**Comment by MCMrARM** [comment]
Read the README?

**Comment by OmarRind** [comment]
i did still not working

**Comment by MCMrARM** [comment]
Install CEF depedencies, do setup_cef.sh and recompile.
