### ISSUE TITLE
[server] Verbosity

### ISSUE THREAD

**Issue by nic96** [MCMrARM/mcpelauncher-linux#332]
Is there a simple way to increase the verbosity of the server? I'd like to be able to see in game chat, joining, and leaving of players in the console.

**Comment by codehz** [comment]
You can write a mod for that, for example, hook "minecraft::api::PlayerInterface::handlePlayerJoinedEvent"

**Comment by nic96** [comment]
Thanks, I'll try that.

**Comment by nic96** [comment]
I got it going by adding `-L../libs/mod_stub_lib/obj/local/x86` to LOCAL_LDLIBS := in the Android.mk after running ndk-build in the mod_stub_lib directory.

**Comment by nic96** [comment]
After modifying the mod_example a bit I figured it out:
![](https://i.imgur.com/uK7d9aa.jpg)
Check the version number at the button right corner.

**Comment by codehz** [comment]
I think you should link it with libminecraft.so.

**Comment by codehz** [comment]
Do you linked it with libminecraft.so?

**Comment by codehz** [comment]
Do you linked it with libminecraft.so?

**Comment by nic96** [comment]
I just thought about that. I thought I had, but I'll try it when I get home.

**Comment by nic96** [comment]
I tried linking it with libminecraftpe.so, but I still get the same result.

The example works compiling fine though.

**Comment by julianwi** [comment]
hi nic96, the function handlePlayerJoinedEvent has one parameter, it is not `static`, it has the modifier `const` and its return type isn't `std::string`. Because of this your compiler can't find it. I got your code working. You have to write it like this:
```c++
#include <iostream>

class Player;

namespace minecraft{
    namespace api{
        struct PlayerInterface{
            void handlePlayerJoinedEvent(Player&) const;
            static void (*$handlePlayerJoinedEvent)(Player&);
            void $$handlePlayerJoinedEvent(Player&) const {
                std::cout << "Player joined.\n";
            }
        };
    }
}

void (*minecraft::api::PlayerInterface::$handlePlayerJoinedEvent)(Player&);

extern "C" {

void *mcpelauncher_hook(void* symbol, void* hook, void** original);
void mcpelauncher_unhook(void* hook);

void mod_init() {
    std::cout << "init display player events mod\n";
    mcpelauncher_hook((void*) &minecraft::api::PlayerInterface::handlePlayerJoinedEvent, (void*) &minecraft::api::PlayerInterface::$$handlePlayerJoinedEvent, (void**) &minecraft::api::PlayerInterface::$handlePlayerJoinedEvent);
}

}
```

**Comment by nic96** [comment]
Thanks, is it possible though to also get the name of the player that joined?

**Comment by julianwi** [comment]
Yes, that should be possible with the Entity::getNameTag function. This is a virtual function. Using it is a bit complicated. If I have some time, I will try to get this working and post some example code.

**Comment by nic96** [comment]
But the getNameTag function is of type void. Maybe I'm missing something, but void functions don't return anything.

**Comment by MCMrARM** [comment]
>But the getNameTag function is of type void. Maybe I'm missing something, but void functions don't return anything.
I don't know where did you come with this from, but you're wrong. It returns a `std::string const&`.

**Comment by nic96** [comment]
I used a script I found to extract the headers from libminecraftpe.so. In it the header declares it as type void. My question is then where could I get the right headers or how do you get the information?

**Comment by MCMrARM** [comment]
Through manual reverse engineering. There are no tools available to automatically figure out the return types.

**Comment by nic96** [comment]
Thanks

**Comment by nic96** [comment]
I thought I had it solved, but by changing the type it still compiles fine, but when using the mod when a player connects the server crashes.

**Comment by julianwi** [comment]
You need a header with prototypes of all virtual functions of class Player and all virtual functions of its super classes Mob and Entity. If you have a working header it is as easy as writing:
```c++
void $$handlePlayerJoinedEvent(Player& player) const {
    std::cout << "Player joined: " << player.getNameTag() << "\n";
}
```
I created a header with [SymbolExporter](https://github.com/InusualZ/SymbolExporter) by InusualZ and added missing things manually. I uploaded the header here: [https://pastebin.com/JbyrU1wm](https://pastebin.com/JbyrU1wm)

**Comment by codehz** [comment]
@julianwi it's not necessary to dump all virtual function, the linker will automatically choose the right function...
The getNameTag function's return type is maybe `const std::string& ` (tested)

**Comment by julianwi** [comment]
But virtual functions should be called with a vtable and not with the symbol table, the compiler needs to know the position of the function in the vtable. So we need at least prototypes of all function which are in the vtalbe above the function we want to call.

**Comment by codehz** [comment]
@julianwi yes, but in this case, you (and compiler) already know the actual type of the object(ServerPlayer, and it extended Player, Entity. And the only implementation of the function is in the Entity class), so it is not necessary to use the vtable :)

**Comment by julianwi** [comment]
@codehz, ok you're right. In this case we can make it simple. To tell the compiler to not use the vtable we have to remove the keyword virtual from the function prototype. The following code worked for me:
```c++
#include <iostream>

class Entity {
public:
    std::string const& getNameTag() const;
};

class Player: public Entity{};

namespace minecraft{
    namespace api{
        struct PlayerInterface{
            void handlePlayerJoinedEvent(Player& player) const;
            static void (*$handlePlayerJoinedEvent)(Player& player);
            void $$handlePlayerJoinedEvent(Player& player) const {
                std::cout << "Player joined: " << player.getNameTag() << "\n";
            }
        };
    }
}

void (*minecraft::api::PlayerInterface::$handlePlayerJoinedEvent)(Player& player);

extern "C" {

void *mcpelauncher_hook(void* symbol, void* hook, void** original);
void mcpelauncher_unhook(void* hook);

void mod_init() {
    std::cout << "init display player events mod\n";
    mcpelauncher_hook((void*) &minecraft::api::PlayerInterface::handlePlayerJoinedEvent, (void*) &minecraft::api::PlayerInterface::$$handlePlayerJoinedEvent, (void**) &minecraft::api::PlayerInterface::$handlePlayerJoinedEvent);
}

}
```

**Comment by InusualZ** [comment]
If you are going to use one virtual table, you need have all th virtual methods. If not the compiler/linker would put your hooked function pointer in the wrong offset and then when minecraft call that function would be calling the wrong function.

**Comment by nic96** [comment]
How to you get the return type of a method? I know how to get the list of available methods with objdump, nm, or readelf, but I don't know how to get the return type.

**Comment by InusualZ** [comment]
Like @MCMrARM said, `Through manual reverse engineering`. There is no other way.

**Comment by nic96** [comment]
Could you point me to some place where I could learn reverse engineering?

**Comment by nic96** [comment]
I guess I'll stick to guessing the return types since I don't know how to reverse engineer anything. Thanks for all the help. I think I can close this issue now.
