### ISSUE TITLE
[server] Server doesn't load world resource packs when not in LAN multiplayer

### ISSUE THREAD

**Issue by AryToNeX** [MCMrARM/mcpelauncher-linux#337]
I am playing a realm with my friends and we decided to put a resource pack in the world folder (by using world_resource_packs.json). It seems the server doesn't push the resource packs to the players when a connection happens. Further investigation needed.

**Comment by AryToNeX** [comment]
So, I came up with another bug: In my current world and server setup, vanilla resource pack is always forced (even if I have other resource packs set up).

**Comment by AryToNeX** [comment]
@MCMrARM any plans on solving this anytime soon?

**Comment by MCMrARM** [comment]
Fixed loading world resource packs:
https://github.com/MCMrARM/mcpelauncher-linux/commit/58493973890003e9e986a2fab7160fbfcad8cc87

This issue never was related to LAN multiplayer.
