### ISSUE TITLE
Incorrect DeviceOS field in LoginPacket

### ISSUE THREAD

**Issue by TheNewHEROBRINEX** [MCMrARM/mcpelauncher-linux#340]
Currently DeviceOS is -1 but it should be the same as the Windows 10 Edition because some servers have some features only for Windows 10 players or mobile players or they give different kits based on if a player is from mobile or computer

**Comment by MCMrARM** [comment]
Fixed
https://github.com/MCMrARM/mcpelauncher-linux/commit/7ece4d46212a7071ea00dc4ff2510a2897e44e55
