### ISSUE TITLE
[client] Minecraft stays open even if its window is closed

### ISSUE THREAD

**Issue by AryToNeX** [MCMrARM/mcpelauncher-linux#342]
Tried closing the window or exiting by asking Minecraft to exit. The process remains active unless it's killed.

**Comment by AryToNeX** [comment]
Fixed in [this commit](https://github.com/MCMrARM/mcpelauncher-linux/commit/3df9474090b7b0a7fa94eacdeb9c71c7ce6d4ea5)

**Comment by Tarik02** [comment]
Thanks!
