### ISSUE TITLE
#include <zip.h> file not found

### ISSUE THREAD

**Issue by MasterOfTheTiger** [MCMrARM/mcpelauncher-linux#349]
I am installing it via the instructions in the Wiki. I get caught up with this:
<pre>
Scanning dependencies of target server
[  3%] Building C object CMakeFiles/server.dir/libs/hybris/src/hooks.c.o
[  9%] Building C object CMakeFiles/server.dir/libs/hybris/src/hooks_shm.c.o
[  9%] Building C object CMakeFiles/server.dir/libs/hybris/src/dlfcn.c.o
[ 12%] Building C object CMakeFiles/server.dir/libs/hybris/src/cache.c.o
[ 16%] Building C object CMakeFiles/server.dir/libs/hybris/src/logging.c.o
[ 19%] Building C object CMakeFiles/server.dir/libs/hybris/src/properties.c.o
[ 22%] Building C object CMakeFiles/server.dir/libs/hybris/src/ctype.c.o
[ 25%] Building C object CMakeFiles/server.dir/libs/hybris/src/sysconf.c.o
[ 29%] Building C object CMakeFiles/server.dir/libs/hybris/src/jb/dlfcn.c.o
[ 32%] Building C object CMakeFiles/server.dir/libs/hybris/src/jb/linker.c.o
[ 38%] Building C object CMakeFiles/server.dir/libs/hybris/src/jb/linker_environ.c.o
[ 35%] Building C object CMakeFiles/server.dir/libs/hybris/src/jb/linker_format.c.o
/home/josias/mcpelauncher-linux/libs/hybris/src/jb/linker.c: In function ‘alloc_info’:
/home/josias/mcpelauncher-linux/libs/hybris/src/jb/linker.c:289:5: warning: implicit declaration of function ‘strlcpy’; did you mean ‘strncpy’? [-Wimplicit-function-declaration]
     strlcpy((char*) si->name, name, sizeof(si->name));
     ^~~~~~~
     strncpy
[ 41%] Building C object CMakeFiles/server.dir/libs/hybris/src/hooks_pthread.c.o
[ 45%] Building C object CMakeFiles/server.dir/libs/hybris/src/jb/rt.c.o
/home/josias/mcpelauncher-linux/libs/hybris/src/jb/linker.c: In function ‘reloc_library’:
/home/josias/mcpelauncher-linux/libs/hybris/src/jb/linker.c:1360:24: warning: implicit declaration of function ‘get_hooked_symbol’ [-Wimplicit-function-declaration]
             sym_addr = get_hooked_symbol(sym_name);
                        ^~~~~~~~~~~~~~~~~
/home/josias/mcpelauncher-linux/libs/hybris/src/jb/linker.c:1361:26: warning: comparison between pointer and integer
             if (sym_addr != NULL) {
                          ^~
/home/josias/mcpelauncher-linux/libs/hybris/src/jb/linker.c:1367:25: warning: comparison between pointer and integer
             if(sym_addr == NULL)
                         ^~
[ 48%] Building C object CMakeFiles/server.dir/libs/hybris/src/hooks_dirent.c.o
[ 51%] Building C object CMakeFiles/server.dir/libs/hybris/src/hooks_io.c.o
/home/josias/mcpelauncher-linux/libs/hybris/src/hooks_dirent.c: In function ‘my_readdir_r’:
/home/josias/mcpelauncher-linux/libs/hybris/src/hooks_dirent.c:60:5: warning: ‘readdir_r’ is deprecated [-Wdeprecated-declarations]
     int res = readdir_r(dir, &entry_r, &result_r);
     ^~~
In file included from /home/josias/mcpelauncher-linux/libs/hybris/src/hooks_dirent.c:3:0:
/usr/include/dirent.h:183:12: note: declared here
 extern int readdir_r (DIR *__restrict __dirp,
            ^~~~~~~~~
[ 54%] Building C object CMakeFiles/server.dir/libs/hybris/src/hooks_net.c.o
[ 58%] Building C object CMakeFiles/server.dir/libs/hybris/src/strlcpy.c.o
[ 61%] Building CXX object CMakeFiles/server.dir/src/common/common.cpp.o
[ 64%] Building CXX object CMakeFiles/server.dir/src/common/hook.cpp.o
[ 67%] Building CXX object CMakeFiles/server.dir/src/client/appplatform.cpp.o
[ 70%] Building CXX object CMakeFiles/server.dir/src/common/base64.cpp.o
[ 74%] Building CXX object CMakeFiles/server.dir/src/common/extract.cpp.o
[ 77%] Building CXX object CMakeFiles/server.dir/src/common/path_helper.cpp.o
In file included from /home/josias/mcpelauncher-linux/src/common/extract.cpp:1:0:
/home/josias/mcpelauncher-linux/src/common/extract.h:4:10: fatal error: zip.h: No such file or directory
 #include <zip.h>
          ^~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/server.dir/build.make:591: CMakeFiles/server.dir/src/common/extract.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/server.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
</pre>

I am using Fedora 27. This is the output for the command `make -j$(nproc)`. I have tried installing many different libzip packages. Both 64 and 32 bit.

**Comment by MCMrARM** [comment]
Wiki instructions are deprecated and out of date.

**Comment by MCMrARM** [comment]
Please use the README instead.

**Comment by MasterOfTheTiger** [comment]
Okay. Will do.

**Comment by AryToNeX** [comment]
@MCMrARM I have updated the wiki yesterday, now it is up to date.

**Comment by MCMrARM** [comment]
Not updated for all distros though.

**Comment by AryToNeX** [comment]
@MCMrARM tbh the wiki needs a total rewrite: the Table of Contents is missing; requirements for distros can and should be merged all in one page and the bugs and workarounds section should be reviewed and updated. Also, a FAQ should be there.

**Comment by MasterOfTheTiger** [comment]
@MCMrARM the README does not contain instructions for Fedora. Must I use Ubuntu?

**Comment by AryToNeX** [comment]
@MasterOfTheTiger nope, if you can find the required packages then list them here and I'll add them to the wiki.

**Comment by MasterOfTheTiger** [comment]
@AryToNex okay. I will do that.

**Comment by Dhrhciebcy** [comment]
Same error here #423 
But I have Ubuntu 16.04. Is this a problem?
