### ISSUE TITLE
Compile error (again)

### ISSUE THREAD

**Issue by Alee14** [MCMrARM/mcpelauncher-linux#352]
I got an error when I was compiling it
andrew at AleePC build
$ make
[ 26%] Built target server
[ 60%] Built target gplayapi
[ 61%] Linking CXX executable mcpelauncher
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../libprotobuf.so when searching for -lprotobuf
/usr/bin/ld: skipping incompatible /usr/lib/libprotobuf.so when searching for -lprotobuf
/usr/bin/ld: cannot find -lprotobuf
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/mcpelauncher.dir/build.make:1266: mcpelauncher] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/mcpelauncher.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by codehz** [comment]
install `protobuf-compiler libprotobuf-dev:i386` and try again

**Comment by Alee14** [comment]
I'm in arch linux

**Comment by codehz** [comment]
try `https://aur.archlinux.org/packages/lib32-libprotobuf/` ?

**Comment by Alee14** [comment]
Okay that worked thanks!
