### ISSUE TITLE
how to export world data to mcpe

### ISSUE THREAD

**Issue by galenzhao** [MCMrARM/mcpelauncher-linux#353]
hi

I want to export the world data folder to mcpe win10 
But nothing happened after I copy all files to win10 save folder
The world likes a new one

**Comment by MCMrARM** [comment]
Dedicated server or the client?

**Comment by codehz** [comment]
I think you can try to pack them into a mcworld file, and then click it on win10 to import it.

**Comment by galenzhao** [comment]
@MCMrARM 

I want to export the world data from dedicated server to original mcpe client like win10 version or android version.

**Comment by AryToNeX** [comment]
@galenzhao the dedicated server is buggy and right now no matter what you do it is not possible to transfer worlds between server and client

**Comment by MCMrARM** [comment]
Indeed, the dedicated server does some magic with worlds that makes it impossible to transfer back to the client.

**Comment by AryToNeX** [comment]
@MCMrARM I hope that magic will still be read by the server in future versions of Minecraft at least.

**Comment by MCMrARM** [comment]
This was figured out to be caused by the dedicated server encrypting the worlds with an internal Minecraft key due to a code bug. Anyone with an encrypted world that would like to have it decrypted, please contact me with the world file and I can decrypt it.
