### ISSUE TITLE
[client] Import/export worlds in-game makes the launcher crash

### ISSUE THREAD

**Issue by AryToNeX** [MCMrARM/mcpelauncher-linux#354]
It seems importing and exporting worlds is broken. I click the import button and then the game hangs. The log is flooded of "square unknown unicode characters" and it keeps flooding until my entire bash session is bugged and I can terminate it only via Ctrl+D (so I don't really have any logs to post this time).

It behaves the same way when exporting worlds. It does not behave this way when loading skins.

![Log_flood](https://user-images.githubusercontent.com/13177694/37464635-3f5b60a8-2859-11e8-839d-18fa260eb631.png)

**Comment by MCMrARM** [comment]
Fixed: https://github.com/MCMrARM/mcpelauncher-linux/commit/fe05497b10c90fd79059b2174573284a55edd9a5
