### ISSUE TITLE
port to arm

### ISSUE THREAD

**Issue by galenzhao** [MCMrARM/mcpelauncher-linux#357]
Hi,

I can build on ARM linux success,
but when I run server, it shows error like

focus@NanoPi-NEO:~/mcpe/build$ ./server 
05:31:53 Trace [Launcher] Loading hybris libraries
05:31:53 Trace [Launcher] Loaded OS library libm.so.6
05:31:53 Trace [Launcher] 11Loading Minecraft library
linker/home/focus/mcpe/libs/hybris/src/jb/linker.c:2040| ERROR: failed to link libminecraftpe.so
05:31:53 Error [Launcher] 22Failed to load Minecraft: Cannot load library: reloc_library[1373]:     0 cannot locate '_Unwind_Resume'...

and I lookup the so lib,

the '_Unwind_Resume' function is not in the libminecraftpe.so,

focus@NanoPi-NEO:~/.local/share/mcpelauncher/libs$ nm -D libminecraftpe.so | grep nwind_
         U __aeabi_unwind_cpp_pr0
         U __aeabi_unwind_cpp_pr1
         U __gnu_unwind_frame
         U _Unwind_Complete
         U _Unwind_DeleteException
         U _Unwind_GetDataRelBase
         U _Unwind_GetLanguageSpecificData
         U _Unwind_GetRegionStart
         U _Unwind_GetTextRelBase
         U _Unwind_RaiseException
         U _Unwind_Resume
         U _Unwind_Resume_or_Rethrow
         U _Unwind_VRS_Get
         U _Unwind_VRS_Set

it was implement in libfmod.so,

focus@NanoPi-NEO:~/.local/share/mcpelauncher/libs$ nm -D libfmod.so | grep nwind_
000aa9dc T __aeabi_unwind_cpp_pr0
000aa9e4 W __aeabi_unwind_cpp_pr1
000aa9ec W __aeabi_unwind_cpp_pr2
000aa528 T __gnu_Unwind_Backtrace
000aaf88 T __gnu_unwind_execute
         w __gnu_Unwind_Find_exidx
000aa350 T __gnu_Unwind_ForcedUnwind
000ab320 T __gnu_unwind_frame
000aa2ac T __gnu_Unwind_RaiseException
000aad68 T __gnu_Unwind_Restore_VFP
000aad78 T __gnu_Unwind_Restore_VFP_D
000aad88 T __gnu_Unwind_Restore_VFP_D_16_to_31
000aae20 T __gnu_Unwind_Restore_WMMXC
000aad98 T __gnu_Unwind_Restore_WMMXD
000aa36c T __gnu_Unwind_Resume
000aa3e0 T __gnu_Unwind_Resume_or_Rethrow
000aad70 T __gnu_Unwind_Save_VFP
000aad80 T __gnu_Unwind_Save_VFP_D
000aad90 T __gnu_Unwind_Save_VFP_D_16_to_31
000aae34 T __gnu_Unwind_Save_WMMXC
000aaddc T __gnu_Unwind_Save_WMMXD
000aaed8 T ___Unwind_Backtrace
000aaed8 T _Unwind_Backtrace
000aa400 T _Unwind_Complete
000aa404 T _Unwind_DeleteException
000aaeb4 T ___Unwind_ForcedUnwind
000aaeb4 T _Unwind_ForcedUnwind
000aa2a4 T _Unwind_GetCFA
000ab38c T _Unwind_GetDataRelBase
000ab370 T _Unwind_GetLanguageSpecificData
000ab360 T _Unwind_GetRegionStart
000ab394 T _Unwind_GetTextRelBase
000aae48 T ___Unwind_RaiseException
000aae48 T _Unwind_RaiseException
000aae6c T ___Unwind_Resume
000aae6c T _Unwind_Resume
000aae90 T ___Unwind_Resume_or_Rethrow
000aae90 T _Unwind_Resume_or_Rethrow
000aa41c T _Unwind_VRS_Get
000aa9f4 T _Unwind_VRS_Pop
000aa4a0 T _Unwind_VRS_Set

is there any way to fix that,

thanks,

**Comment by AryToNeX** [comment]
This launcher was intended for i386 arch, so I don't know how can you fix that with the current sources. Are you using arm libs, right? `setup_bin_libs.sh` will download an x86 version of FMOD afaik.

**Comment by MCMrARM** [comment]
Indeed, ARM compilation is currently not supported. https://github.com/MCMrARM/mcpelauncher-linux/issues/20
