### ISSUE TITLE
I'm getting this: /usr/include/c++/5/iostream:38:28: fatal error: bits/c++config.h: No such file or directory - when compiling

### ISSUE THREAD

**Issue by stayandwait** [MCMrARM/mcpelauncher-linux#36]
[ 68%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/jb/rt.c.o
[ 73%] Building C object CMakeFiles/mcpelauncher.dir/eglut/eglut.c.o
/home/liam/Downloads/mcpelauncher-linux/eglut/eglut.c: In function ‘eglutCreateWindow’:
/home/liam/Downloads/mcpelauncher-linux/eglut/eglut.c:320:22: warning: assignment from incompatible pointer type [-Wincompatible-pointer-types]
     win->keyboard_cb = _eglutDefaultKeyboard;
                      ^
[ 78%] Building C object CMakeFiles/mcpelauncher.dir/eglut/eglut_x11.c.o
[ 84%] Building C object CMakeFiles/mcpelauncher.dir/subhook/subhook.c.o
[ 89%] Building CXX object CMakeFiles/mcpelauncher.dir/src/main.cpp.o
In file included from /home/liam/Downloads/mcpelauncher-linux/src/main.cpp:1:0:
/usr/include/c++/5/iostream:38:28: fatal error: bits/c++config.h: No such file or directory
compilation terminated.
CMakeFiles/mcpelauncher.dir/build.make:422: recipe for target 'CMakeFiles/mcpelauncher.dir/src/main.cpp.o' failed
make[2]: *** [CMakeFiles/mcpelauncher.dir/src/main.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/mcpelauncher.dir/all' failed
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
Makefile:75: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by stayandwait** [comment]
Please close this issues. I figured out the problem, your c++ libraries were no longer 4.9. I had to update to c++ 5.

**Comment by svilex** [comment]
@stayandwait You can close it
