### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XCreaTivic** [MCMrARM/mcpelauncher-linux#365]
/Users/tigrankashapov/build/mcpelauncher-linux/start_mcpelauncher.sh: line 12: exec: /Users/tigrankashapov/build/mcpelauncher-linux/mcpelauncher: cannot execute: No such file or directory

**Comment by MCMrARM** [comment]
Use the mcpelauncher binary directly, the start_mcpelauncher.sh script is only intended for installation package.

**Comment by XCreaTivic** [comment]
how?
