### ISSUE TITLE
I found a bug in the game

### ISSUE THREAD

**Issue by stayandwait** [MCMrARM/mcpelauncher-linux#37]
Please see this photo, the sword is bent looking
http://screencast.com/t/CRY0q2MyRnJO

**Comment by AryToNeX** [comment]
This is not a bug, close your issue please.

**Comment by stayandwait** [comment]
No?

**Comment by AryToNeX** [comment]
It is a window proportion issue, so your graphics card cuts off some pixels of that sword. I'm not facing that issue btw.
