### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by Gambulec** [MCMrARM/mcpelauncher-linux#370]
Minecraft turns on for a moment showing the logo. This is how it looks at the terminal

> 15:45:50 Trace [Launcher] Loading native libraries
15:45:50 Trace [Launcher] Loaded OS library /home/jarek/Programy/mcpelauncher-linux/libs/native/libfmod.so.9.6
15:45:50 Trace [Launcher] Loaded OS library libm.so.6
15:45:50 Trace [Launcher] Loading hybris libraries
15:45:50 Trace [Launcher] Loading Minecraft library
15:45:51 Info [Launcher] Loaded Minecraft library
15:45:51 Debug [Launcher] Minecraft is at offset 0xe97e9000
15:45:51 Info [Launcher] Applying patches
15:45:51 Trace [Launcher] Patching - original: 85 83 87 86 131
15:45:51 Trace [Launcher] Patching - result: 233 111 152 65 108
15:45:51 Trace [Launcher] Patching - original: 85 83 87 86 131
15:45:51 Trace [Launcher] Patching - result: 233 83 107 66 108
15:45:51 Trace [Launcher] Patching - original: 85 83 87 86 129
15:45:51 Trace [Launcher] Patching - result: 233 183 104 66 108
15:45:51 Trace [Launcher] Patching - original: 83 87 86 131 236
15:45:51 Trace [Launcher] Patching - result: 233 115 105 66 108
15:45:51 Trace [Launcher] Patching - original: 85 83 87 86 129
15:45:51 Trace [Launcher] Patching - result: 233 159 229 69 106
15:45:51 Trace [Launcher] Patching - original: 85 83 87 86 129
15:45:51 Trace [Launcher] Patching - result: 233 31 170 126 106
15:45:51 Trace [Launcher] Patching - original: 85 83 87 86 129
15:45:51 Trace [Launcher] Patching - result: 233 54 182 126 106
15:45:51 Trace [Launcher] Patching - original: 85 83 87 86 129
15:45:51 Trace [Launcher] Patching - result: 233 249 168 126 106
15:45:51 Trace [Launcher] Patching - original: 85 83 87 86 129
15:45:51 Trace [Launcher] Patching - result: 233 97 33 126 106
15:45:51 Trace [Launcher] Patching - original: 85 83 87 86 129
15:45:51 Trace [Launcher] Patching - result: 233 73 37 126 106
15:45:51 Trace [Launcher] Patching - original: 85 83 87 86 129
15:45:51 Trace [Launcher] Patching - result: 233 168 2 128 106
15:45:51 Trace [Launcher] Patching - original: 83 87 86 131 236
15:45:51 Trace [Launcher] Patching - result: 233 27 177 126 106
15:45:51 Trace [Launcher] Patching - original: 85 83 87 86 129
15:45:51 Trace [Launcher] Patching - result: 233 247 206 126 106
15:45:51 Info [Launcher] Patches were successfully applied
15:45:51 Info [Launcher] Game version: 1.2.13
15:45:51 Info [Launcher] Creating window
EGL_VERSION = 1.5 (DRI2)
15:45:51 Info [Launcher] Starting game initialization
15:45:51 Trace [Launcher] Initializing AppPlatform (vtable)
15:45:51 Trace [AppPlatform] Vtable size = 218
15:45:51 Trace [Launcher] Initializing AppPlatform (create instance)
15:45:51 Trace [Launcher] Initializing AppPlatform (initialize call)
15:45:51 Trace [AppPlatform] createDeviceID: 
15:45:52 Trace [Launcher] Initializing OpenGL bindings
15:45:52 Trace [Launcher] Initializing MinecraftGame (create instance)
15:45:52 Trace [AppPlatform] getSystemRegion: 0xdeadbeef
15:45:52 Trace [AppPlatform] getCurrentStoragePath: /home/jarek/.local/share/mcpelauncher/
15:45:52 Trace [Launcher] Initializing MinecraftGame (init call)
15:45:52 Trace [AppPlatform] getAssetFileFullPath: uniforms.json
15:45:52 Trace [AppPlatform] getCurrentStoragePath: /home/jarek/.local/share/mcpelauncher/
15:45:52 Trace [AppPlatform] getDataUrl: /home/jarek/.local/share/mcpelauncher/assets/
15:45:52 Trace [AppPlatform] getInternalStoragePath: /home/jarek/.local/share/mcpelauncher/
15:45:52 Trace [AppPlatform] getInternalStoragePath: /home/jarek/.local/share/mcpelauncher/
15:45:52 Trace [AppPlatform] getInternalStoragePath: /home/jarek/.local/share/mcpelauncher/
15:45:52 Trace [AppPlatform] getInternalStoragePath: /home/jarek/.local/share/mcpelauncher/
15:45:52 Trace [AppPlatform] getInternalStoragePath: /home/jarek/.local/share/mcpelauncher/
15:45:52 Trace [AppPlatform] getInternalStoragePath: /home/jarek/.local/share/mcpelauncher/
15:45:52 Trace [AppPlatform] getInternalStoragePath: /home/jarek/.local/share/mcpelauncher/
15:45:52 Trace [Launcher] Reading xbox config file
15:45:52 Trace [AppPlatform] getAssetFileFullPath: texture_backwards_compatibility_mapping.json
15:45:52 Trace [AppPlatform] getAssetFileFullPath: texture_backwards_compatibility_mapping.json
15:45:52 Trace [AppPlatform] getUserdataPathForLevels: /home/jarek/.local/share/mcpelauncher/
15:45:52 Trace [AppPlatform] getUserdataPathForLevels: /home/jarek/.local/share/mcpelauncher/
15:45:52 Trace [AppPlatform] getInternalStoragePath: /home/jarek/.local/share/mcpelauncher/
15:45:52 Trace [AppPlatform] getDataUrl: /home/jarek/.local/share/mcpelauncher/assets/
15:45:52 Trace [AppPlatform] getAssetFileFullPath: profanity_filter.wlist
15:45:52 Trace [AppPlatform] getInternalStoragePath: /home/jarek/.local/share/mcpelauncher/
15:45:52 Trace [Launcher] Creating fake store (MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqU9snkqLkTCYZQfQgNy9eabP/OcumQTgcoYhuBbmx2isicIX8mSUNJn64yxiA6acqnJzJxGbKW9H+gSWMuRtCtwI3Exb3sCq19EiVtjos4u5BJatzBKXXDDJeeYrejGk8FgT6ffokcilJFY4wgQQxDGFdfE/reAqm6+VKUtoqnjMpG0wVZn+o0bJfxNvE/ydJPlabDmoywEn9zEl0hXo0i+cimVlFZcTT6ed7U9celM2Ywg+7qVIu7fmBHPucTIoUAbipEAIvP2EntOqrhUG6GKJ219Qhdr43fvnyBailudNBiDRqA+x0rCH1JgmV/BvyAHTBylPzroeh9rWJNNPxQIDAQAB)
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] getProductSkuPrefix: 
15:45:52 Trace [Store] allowsSubscriptions: true
15:45:52 Trace [Store] getRealmsSkuPrefix: 
15:45:52 Trace [Store] allowsSubscriptions: true
15:45:52 Trace [Store] getRealmsSkuPrefix: 
15:45:52 Trace [Store] allowsSubscriptions: true
15:45:52 Trace [Store] getRealmsSkuPrefix: 
15:45:52 Trace [Store] allowsSubscriptions: true
15:45:52 Trace [Store] getRealmsSkuPrefix: 
15:45:52 Trace [Store] allowsSubscriptions: true
15:45:52 Trace [Store] getRealmsSkuPrefix: 
15:45:52 Trace [Store] allowsSubscriptions: true
15:45:52 Trace [Store] getRealmsSkuPrefix: 
15:45:52 Trace [Store] allowsSubscriptions: true
15:45:52 Trace [Store] getRealmsSkuPrefix: 
15:45:52 Trace [Store] allowsSubscriptions: true
15:45:52 Trace [Store] restoreFromCache
15:45:52 Trace [Store] registerLicenseChangeCallback
15:45:52 Trace [AppPlatform] getSystemRegion: 0xdeadbeef
15:45:52 Trace [AppPlatform] isTablet: true
15:45:52 Trace [AppPlatform] getSystemRegion: 0xdeadbeef
15:45:52 Trace [AppPlatform] getApplicationId: com.mojang.minecraftpe
15:45:52 Trace [AppPlatform] getAssetFileFullPath: renderer/the_end/time_of_day_clear.json
15:45:52 Trace [AppPlatform] getAssetFileFullPath: renderer/the_end/time_of_day_rain.json
15:45:52 Trace [AppPlatform] getAssetFileFullPath: renderer/the_end/time_of_day_thunder.json
15:45:52 Trace [AppPlatform] getAssetFileFullPath: renderer/nether/time_of_day_clear.json
15:45:52 Trace [AppPlatform] getAssetFileFullPath: renderer/nether/time_of_day_rain.json
15:45:52 Trace [AppPlatform] getAssetFileFullPath: renderer/nether/time_of_day_thunder.json
15:45:52 Trace [AppPlatform] getAssetFileFullPath: renderer/overworld/time_of_day_clear.json
15:45:52 Trace [AppPlatform] getAssetFileFullPath: renderer/overworld/time_of_day_rain.json
15:45:52 Trace [AppPlatform] getAssetFileFullPath: renderer/overworld/time_of_day_thunder.json
15:45:52 Trace [AppPlatform] getAssetFileFullPath: renderer/the_end/renderoptions.json
15:45:52 Trace [AppPlatform] getAssetFileFullPath: renderer/nether/renderoptions.json
15:45:52 Trace [AppPlatform] getAssetFileFullPath: renderer/overworld/renderoptions.json
15:45:52 Trace [Store] getStoreId: android.googleplay
15:45:52 Trace [Store] getSubPlatformStoreId: 
15:45:52 Trace [AppPlatform] getUserdataPathForLevels: /home/jarek/.local/share/mcpelauncher/
15:45:52 Trace [AppPlatform] getInternalStoragePath: /home/jarek/.local/share/mcpelauncher/
15:45:52 Trace [AppPlatform] getInternalStoragePath: /home/jarek/.local/share/mcpelauncher/
15:45:52 Trace [AppPlatform] getUserdataPathForLevels: /home/jarek/.local/share/mcpelauncher/
15:45:52 Trace [AppPlatform] getInternalStoragePath: /home/jarek/.local/share/mcpelauncher/
15:45:52 Info [Launcher] Game initialized
15:45:52 Trace [Launcher] Initialized display
15:45:52 Trace [Launcher] Start loop
15:45:52 Trace [AppPlatform] getInternalStoragePath: /home/jarek/.local/share/mcpelauncher/
15:45:52 Trace [AppPlatform] getInternalStoragePath: /home/jarek/.local/share/mcpelauncher/
15:45:52 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:45:52 Trace [Launcher] LinuxHttpRequestInternal::~LinuxHttpRequestInternal
15:45:52 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:45:52 Trace [Launcher] LinuxHttpRequestInternal::~LinuxHttpRequestInternal
15:45:52 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:45:52 Trace [Launcher] LinuxHttpRequestInternal::~LinuxHttpRequestInternal
15:45:52 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:45:52 Trace [Launcher] LinuxHttpRequestInternal::~LinuxHttpRequestInternal
15:45:52 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:45:52 Trace [Launcher] LinuxHttpRequestInternal::~LinuxHttpRequestInternal
15:45:52 Trace [Launcher] verify_cert_chain_platform_specific stub called
15:45:52 Trace [Launcher] verify_cert_chain_platform_specific stub called
15:45:52 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:45:52 Trace [Launcher] LinuxHttpRequestInternal::~LinuxHttpRequestInternal
15:45:52 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:45:52 Trace [Launcher] LinuxHttpRequestInternal::~LinuxHttpRequestInternal
15:45:52 Trace [AppPlatform] getSystemRegion: 0xdeadbeef
15:45:52 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:45:52 Trace [Launcher] LinuxHttpRequestInternal::~LinuxHttpRequestInternal
15:45:52 Trace [Launcher] HTTPRequestInternalAndroid::send stub called
15:45:52 Trace [Launcher] LinuxHttpRequestInternal::~LinuxHttpRequestInternal
15:45:53 Trace [Launcher] verify_cert_chain_platform_specific stub called
15:45:53 Trace [Launcher] verify_cert_chain_platform_specific stub called
15:45:53 Trace [Launcher] verify_cert_chain_platform_specific stub called
15:45:53 Trace [Launcher] verify_cert_chain_platform_specific stub called
Illegal instruction (core dumped)

Xubuntu 17.10
Intel(R) Pentium(R) D CPU 3.40GHz
Radeon HD 6450  Mesa 17.2.8

**Comment by Gambulec** [comment]
I tried the manjaro, but with a similar effect
These are the results after starting with valgrind

> ==1088== Memcheck, a memory error detector
==1088== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==1088== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==1088== Command: ./mcpelauncher
==1088== 
vex x86->IR: unhandled instruction bytes: 0x67 0xE8 0xFB 0xD7
==1088== valgrind: Unrecognised instruction at address 0xebd482f.
==1088==    at 0xEBD482F: ??? (in /usr/lib32/libp11-kit.so.0.3.0)
==1088==    by 0xC165914: __pthread_once_slow (in /usr/lib32/libpthread-2.26.so)
==1088==    by 0xEB33C2E: ??? (in /usr/lib32/libp11-kit.so.0.3.0)
==1088==    by 0x400F85A: call_init.part.0 (in /usr/lib32/ld-2.26.so)
==1088==    by 0x400F966: _dl_init (in /usr/lib32/ld-2.26.so)
==1088==    by 0x4000C9E: ??? (in /usr/lib32/ld-2.26.so)
==1088== Your program just tried to execute an instruction that Valgrind
==1088== did not recognise.  There are two possible reasons for this.
==1088== 1. Your program has a bug and erroneously jumped to a non-code
==1088==    location.  If you are running Memcheck and you just saw a
==1088==    warning about a bad jump, it's probably your program's fault.
==1088== 2. The instruction is legitimate but Valgrind doesn't handle it,
==1088==    i.e. it's Valgrind's fault.  If you think this is the case or
==1088==    you are not sure, please let us know and we'll try to fix it.
==1088== Either way, Valgrind will now raise a SIGILL signal which will
==1088== probably kill your program.
==1088== 
==1088== Process terminating with default action of signal 4 (SIGILL): dumping core
==1088==  Illegal opcode at address 0xEBD482F
==1088==    at 0xEBD482F: ??? (in /usr/lib32/libp11-kit.so.0.3.0)
==1088==    by 0xC165914: __pthread_once_slow (in /usr/lib32/libpthread-2.26.so)
==1088==    by 0xEB33C2E: ??? (in /usr/lib32/libp11-kit.so.0.3.0)
==1088==    by 0x400F85A: call_init.part.0 (in /usr/lib32/ld-2.26.so)
==1088==    by 0x400F966: _dl_init (in /usr/lib32/ld-2.26.so)
==1088==    by 0x4000C9E: ??? (in /usr/lib32/ld-2.26.so)
==1088== 
==1088== HEAP SUMMARY:
==1088==     in use at exit: 0 bytes in 0 blocks
==1088==   total heap usage: 1 allocs, 1 frees, 25 bytes allocated
==1088== 
==1088== All heap blocks were freed -- no leaks are possible
==1088== 
==1088== For counts of detected and suppressed errors, rerun with: -v
==1088== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
Illegal instruction (core dumped)

**Comment by caramel7** [comment]
Exact same issue here.

**Comment by min20120907** [comment]
This issue is fixed by updating the latest version of mcpelauncher!

**Comment by Gambulec** [comment]
@min20120907 Rather, it's not the same mistake as it is with me, but it does not matter anymore.

I followed the instructions in reademe, but on the wiki it looks a bit different and the whole operation should end with "sudo make install" and then I get the same error as here: https://github.com/MCMrARM/mcpelauncher-linux/issues/373
So anyway, this topic can probably be closed.

**Comment by Gambulec** [comment]
Please, reopen this problem.
I got the missing files by unpacking them from the deb package https://github.com/MCMrARM/mcpelauncher-linux/issues/268 , and then compiled mpclauncher in the / usr directory, but again I have this error as above

**Comment by masrourmouad** [comment]
same

**Comment by min20120907** [comment]
But, I install the recent package I didn't get any error anymore
