### ISSUE TITLE
Help 

### ISSUE THREAD

**Issue by coolkidsrule101** [MCMrARM/mcpelauncher-linux#376]
#0 /home/youtube/mcpelauncher-linux/mcpelauncher(_Z12handleSignaliPv+0x62) [0x82d6745]
#1 [0xf7f7ade0]
#2 HYBRIS TexturePair::_loadTexData()+384 in libminecraftpe.so+0x1b25390 [0xebac4390]
Dumping stack...
#17 HYBRIS TexturePair::_loadTexData()+384 in libminecraftpe.so+0x1b25390 [0xebac4390]
#28 HYBRIS Core::FileSystemImpl::openFile(std::unique_ptr<Core::FileImpl, std::default_delete<Core::FileImpl> >&, Core::Path, Core::FileOpenMode, Core::FileBufferingMode)+418 in libminecraftpe.so+0x25c4c12 [0xec563c12]
#36 HYBRIS vtable for Core::FileSystemImpl+8 in libminecraftpe.so+0x38ff430 [0xed89e430]
#60 HYBRIS TexturePair::_loadTexData()+384 in libminecraftpe.so+0x1b25390 [0xebac4390]
#90 HYBRIS Core::FileStorageArea::getStorageAreaForPath(std::shared_ptr<Core::FileStorageArea>&, Core::Path)+112 in libminecraftpe.so+0x25b7000 [0xec556000]
#372 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x2d9b547 [0xecd3a547]
#412 HYBRIS mce::TextureContainer::getImageData(unsigned int, unsigned int)+48 in libminecraftpe.so+0x25dfb90 [0xec57eb90]
#416 HYBRIS TexturePair::_loadTexData()+378 in libminecraftpe.so+0x1b2538a [0xebac438a]
#420 HYBRIS ImageUtils::uncompress(mce::TextureContainer&, bool)+37 in libminecraftpe.so+0x1d60785 [0xebcff785]
#468 HYBRIS TexturePair::load()+28 in libminecraftpe.so+0x1b255fc [0xebac45fc]
#472 HYBRIS mce::TextureGroup::uploadTexture(ResourceLocation const&, TexturePair&&, bool)+481 in libminecraftpe.so+0x1b1d2a1 [0xebabc2a1]
#479 HYBRIS mce::TextureBase::TextureBase()+5 in libminecraftpe.so+0x1b28225 [0xebac7225]
#488 HYBRIS TexturePair::TexturePair(mce::TextureContainer&&)+213 in libminecraftpe.so+0x1b251b5 [0xebac41b5]
#496 HYBRIS mce::TextureGroup::loadTexture(ResourceLocation const&, bool)+127 in libminecraftpe.so+0x1b1aecf [0xebab9ecf]
#564 HYBRIS mce::TextureGroup::_getTexture(ResourceLocation const&, bool, bool)+444 in libminecraftpe.so+0x1b1a9bc [0xebab99bc]
#580 HYBRIS Json::Value::~Value()+10 in libminecraftpe.so+0x250920a [0xec4a820a]
#608 HYBRIS operator new(unsigned int)+39 in libminecraftpe.so+0x2d9b547 [0xecd3a547]
#616 HYBRIS std::pair<std::__detail::_Node_iterator<mce::TexturePtr*, true, false>, bool> std::_Hashtable<mce::TexturePtr*, mce::TexturePtr*, std::allocator<mce::TexturePtr*>, std::__detail::_Identity, std::equal_to<mce::TexturePtr*>, std::hash<mce::TexturePtr*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, true, true> >::_M_emplace<mce::TexturePtr*>(std::integral_constant<bool, true>, mce::TexturePtr*&&)+208 in libminecraftpe.so+0x1b1f380 [0xebabe380]
#628 HYBRIS mce::TexturePtr::onGroupReloaded(bool, bool)+244 in libminecraftpe.so+0x1b26004 [0xebac5004]
#644 HYBRIS mce::TexturePtr::TexturePtr(mce::TextureGroup&, ResourceLocation, bool)+136 in libminecraftpe.so+0x1b259d8 [0xebac49d8]
#652 HYBRIS mce::TextureGroup::getTexture(ResourceLocation, bool)+86 in libminecraftpe.so+0x1b1c886 [0xebabb886]
#664 HYBRIS MinecraftUIRenderContext::getTexture(ResourceLocation const&, bool) const+190 in libminecraftpe.so+0x12a1bbe [0xeb240bbe]
#680 HYBRIS SpriteComponent::render(UIRenderContext&)+293 in libminecraftpe.so+0x15a6465 [0xeb545465]
Signal 6 received
Aborted (core dumped)

**Comment by nicman23** [comment]
did you download the apk or logged in to play store? if you downloaded it, there might be something wrong with the libminecraftpe.so (which is basically minecraft)

**Comment by MCMrARM** [comment]
Version please.

**Comment by min20120907** [comment]
I have the same problem on 1.2.13 on manjaro linux 64bit with FX-8370, 32GB RAM, and GT 610. And below are my error codes.

```

21:57:57 Trace [Launcher] Loading native libraries
21:57:57 Trace [Launcher] Loaded OS library /opt/mcpelauncher-linux/libs/native/libfmod.so.9.6
21:57:57 Trace [Launcher] Loaded OS library libm.so.6
21:57:57 Trace [Launcher] Loading hybris libraries
21:57:57 Trace [Launcher] Loading Minecraft library
21:57:58 Info [Launcher] Loaded Minecraft library
21:57:58 Debug [Launcher] Minecraft is at offset 0xe9b6f000
21:57:58 Info [Launcher] Applying patches
21:57:58 Trace [Launcher] Patching - original: 85 83 87 86 131
21:57:58 Trace [Launcher] Patching - result: 233 45 114 12 108
21:57:58 Trace [Launcher] Patching - original: 85 83 87 86 131
21:57:58 Trace [Launcher] Patching - result: 233 17 69 13 108
21:57:58 Trace [Launcher] Patching - original: 85 83 87 86 129
21:57:58 Trace [Launcher] Patching - result: 233 117 66 13 108
21:57:58 Trace [Launcher] Patching - original: 83 87 86 131 236
21:57:58 Trace [Launcher] Patching - result: 233 49 67 13 108
21:57:58 Trace [Launcher] Patching - original: 85 83 87 86 129
21:57:58 Trace [Launcher] Patching - result: 233 93 191 16 106
21:57:58 Trace [Launcher] Patching - original: 85 83 87 86 129
21:57:58 Trace [Launcher] Patching - result: 233 221 131 73 106
21:57:58 Trace [Launcher] Patching - original: 85 83 87 86 129
21:57:58 Trace [Launcher] Patching - result: 233 244 143 73 106
21:57:58 Trace [Launcher] Patching - original: 85 83 87 86 129
21:57:58 Trace [Launcher] Patching - result: 233 183 130 73 106
21:57:58 Trace [Launcher] Patching - original: 85 83 87 86 129
21:57:58 Trace [Launcher] Patching - result: 233 31 251 72 106
21:57:58 Trace [Launcher] Patching - original: 85 83 87 86 129
21:57:58 Trace [Launcher] Patching - result: 233 7 255 72 106
21:57:58 Trace [Launcher] Patching - original: 85 83 87 86 129
21:57:58 Trace [Launcher] Patching - result: 233 102 220 74 106
21:57:58 Trace [Launcher] Patching - original: 83 87 86 131 236
21:57:58 Trace [Launcher] Patching - result: 233 217 138 73 106
21:57:58 Trace [Launcher] Patching - original: 85 83 87 86 129
21:57:58 Trace [Launcher] Patching - result: 233 181 168 73 106
21:57:58 Info [Launcher] Patches were successfully applied
21:57:58 Error [MinecraftSymbols] Unresolved symbol: _ZN14NetworkHandlerC2Ev
21:57:58 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppRK9WhitelistRK7OpsListP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSsRK19IContentKeyProviderSs13LevelSettingsRN9minecraft3api3ApiEibiiibRKSt6vectorISsSaISsEESsRKN3mce4UUIDER17MinecraftEventingR14NetworkHandlerR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerPS15_St8functionIFvRKSsEE
21:57:58 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance6updateEv
21:57:58 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstance28mainThreadNetworkUpdate_HACKEv
21:57:58 Error [MinecraftSymbols] Unresolved symbol: _ZN4I18n13loadLanguagesER19ResourcePackManagerP14SkinRepositoryRKSs
21:57:58 Error [MinecraftSymbols] Unresolved symbol: _ZN12PackInstanceC2EP12ResourcePackib
21:57:58 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler9singletonEv
21:57:58 Info [Launcher] Game version: 1.2.13
21:57:58 Info [Launcher] Creating window
EGL_VERSION = 1.4
21:57:58 Info [Launcher] Starting game initialization
21:57:58 Trace [Launcher] Initializing AppPlatform (vtable)
21:57:58 Trace [AppPlatform] Vtable size = 218
21:57:58 Trace [Launcher] Initializing AppPlatform (create instance)
21:57:58 Trace [Launcher] Initializing AppPlatform (initialize call)
pure virtual method called
terminate called without an active exception
Signal 6 received
Backtrace elements: 11
#0 mcpelauncher(_Z12handleSignaliPv+0x70) [0x568a0b56]
#1 linux-gate.so.1(__kernel_sigreturn+0) [0xf7f6f070]
#2 linux-gate.so.1(__kernel_vsyscall+0x9) [0xf7f6f059]
#3 /usr/lib32/libc.so.6(gsignal+0xc2) [0xef73ce42]
#4 /usr/lib32/libc.so.6(abort+0x1b6) [0xef73e556]
#5 HYBRIS __gnu_cxx::__verbose_terminate_handler()+469 in libminecraftpe.so+0x2dfafb5 [0xec969fb5]
#6 HYBRIS __cxxabiv1::__terminate(void (*)())+25 in libminecraftpe.so+0x2d9ae29 [0xec909e29]
#7 HYBRIS __cxxabiv1::__unexpected(void (*)())+0 in libminecraftpe.so+0x2d9aec0 [0xec909ec0]
#8 HYBRIS (null)+-326064189 in libminecraftpe.so+0x2d9b7c3 [0xec90a7c3]
#9 mcpelauncher(main+0x19ed) [0x568be0c0]
#10 /usr/lib32/libc.so.6(__libc_start_main+0xf3) [0xef728793]
Dumping stack...
#20 HYBRIS __gnu_cxx::__verbose_terminate_handler()+469 in libminecraftpe.so+0x2dfafb5 [0xec969fb5]
#21 HYBRIS __cxxabiv1::__terminate(void (*)())+25 in libminecraftpe.so+0x2d9ae29 [0xec909e29]
#22 HYBRIS __cxxabiv1::__unexpected(void (*)())+0 in libminecraftpe.so+0x2d9aec0 [0xec909ec0]
#644 HYBRIS __gnu_cxx::__verbose_terminate_handler()+469 in libminecraftpe.so+0x2dfafb5 [0xec969fb5]
#659 HYBRIS __gnu_cxx::__verbose_terminate_handler()+11 in libminecraftpe.so+0x2dfadeb [0xec969deb]
#664 HYBRIS __cxxabiv1::__terminate(void (*)())+25 in libminecraftpe.so+0x2d9ae29 [0xec909e29]
#671 HYBRIS __cxxabiv1::__terminate(void (*)())+11 in libminecraftpe.so+0x2d9ae1b [0xec909e1b]
#676 HYBRIS __cxxabiv1::__unexpected(void (*)())+0 in libminecraftpe.so+0x2d9aec0 [0xec909ec0]
#677 HYBRIS __gnu_cxx::__verbose_terminate_handler()+0 in libminecraftpe.so+0x2dfade0 [0xec969de0]
#681 HYBRIS std::terminate()+9 in libminecraftpe.so+0x2d9aea9 [0xec909ea9]
#690 HYBRIS (null)+6 in libminecraftpe.so+0x2d9b796 [0xec90a796]
#692 HYBRIS AppPlatform::initialize()+47 in libminecraftpe.so+0x1c5c90f [0xeb7cb90f]
#763 HYBRIS xbox::services::java_interop::log_cll(std::string const&, std::string const&, std::string const&)+0 in libminecraftpe.so+0x28b2150 [0xec421150]
#765 HYBRIS crossplat::JVM+0 in libminecraftpe.so+0x3a5eac0 [0xed5cdac0]
Signal 6 received
已經終止 (核心已傾印)

```

**Comment by MCMrARM** [comment]
Looks like a launcher version mismatch.

**Comment by min20120907** [comment]
so, is there any configuration file that i can edit it?Or it is supported 1.2.10 currently?
