### ISSUE TITLE
libGLESv2.so couldn't be find on Manjaro

### ISSUE THREAD

**Issue by SantX27** [MCMrARM/mcpelauncher-linux#41]
Hello, after some time I switched on Manjaro, and then I decided to compile `mcpelauncher-linux`
All goes fine until I launch the application. It says:
```
[santx@SantX-1001PXD mcpelauncher-linux-master]$ ./mcpelauncher
loading MCPE
could not find os library: libGLESv2.so
Annullato (core dump creato)
```
Then I checked `mhwd-gpu --setgl mesa` and the output is:
```
[santx@SantX-1001PXD ~]$ sudo mhwd-gpu --setgl mesa
libGl: '/usr/lib/mesa/libGL.so.1.2.0'
libGLESv1: '/usr/lib/mesa/libGLESv1_CM.so.1.1.0'
libGLESv2: '/usr/lib/mesa/libGLESv2.so.2.0.0'
libEGL: '/usr/lib/mesa/libEGL.so.1.0.0'
libglx: '/usr/lib/xorg/modules/extensions/libglx.xorg'
```
What should I do?

**Comment by mhsjlw** [comment]
Try renaming `/usr/lib/mesa/libGLESv2.so.2.0.0` to `/usr/lib/mesa/libGLESv2.so`

**Comment by SantX27** [comment]
I watched the `/usr/lib/mesa` directory and inside I found `libGLESv2.so` `libGLESv2.so.2` which are syslinked to `libGLESv2.so.2.0.0` in the same directory which is the one showed by `mhwd`... Other solutions?

**Comment by SantX27** [comment]
So... Manjaro Linux isn't supported? What damn is happening here @MCMrARM

**Comment by mhsjlw** [comment]
@SantX27 try adding the xorg-edgers repo then reinstall all of the dependencies

**Comment by SantX27** [comment]
@mhsjlw There's no repo called `xorg-edgers` on Arch / Manjaro Linux... I can't get what is stopping `mcpelauncher-linux` from working.

**Comment by jython234** [comment]
Reproduced on Fedora 23

**Comment by SantX27** [comment]
Actually no solution, I tried putting libGLESv2.so everywere on the PC, I tried also compiling libmesa-libgl from AUR and Source, the problem MUST be stuck someware in the code @MCMrARM .

**Comment by SantX27** [comment]
Crazy buttons...

**Comment by MCMrARM** [comment]
basically, here is how I am looking for all system libraries: https://github.com/MCMrARM/mcpelauncher-linux/blob/master/src/main.cpp#L270. If you would symlink /usr/lib/i386-linux-gnu/libGLESv2.so to the actual libGLESv2.so on your system, it should run. Remember however that this file needs to be compiles as x86 not x86_64 or it will crash.

**Comment by Stormwind99** [comment]
Under Fedora, install the mesa-libGLES-devel package and make this change to mcpelauncher so it will find libGLESv2.so:

```
diff --git a/src/main.cpp b/src/main.cpp
index 2e5d59e..19a0373 100644
--- a/src/main.cpp
+++ b/src/main.cpp
@@ -293,6 +293,10 @@ std::string getOSLibraryPath(std::string libName) {
     if (access(p.c_str(), F_OK) != -1) {
         return p;
     }
+    p = std::string("/usr/lib/") + libName;
+    if (access(p.c_str(), F_OK) != -1) {
+        return p;
+    }

     std::cout << "could not find os library: " << libName << "\n";
     abort();
```

**Comment by SantX27** [comment]
Thanks @MCMrARM, now all works fine. Add a line watching libs in `/usr/lib/mesa` that will simplify the process of pasting libs ;D
