### ISSUE TITLE
Win 10 Edition

### ISSUE THREAD

**Issue by Madis0** [MCMrARM/mcpelauncher-linux#410]
Could this be also used for running the Windows 10 Edition? Assuming the user extracts any needed files first.

**Comment by lukeeey** [comment]
No, it could not. If you want to run the Windows 10 Edition then buy Windows 10 because this project does the exact same.

**Comment by Madis0** [comment]
No, it is not the same. The same would be saying "go buy an (Android) phone" or "go get an emulator" (compared to using a Windows virtual machine).

The question is rather about whether this program runs an Android application or the underlying native code. If latter, my suggestion would be doable.

**Comment by lukeeey** [comment]
It runs the native code.... Windows 10 Edition and MCPE have virtually the *same* codebase, just configured differently. 

And no, your solution would not work. Windows 10 Edition is compiled for Windows, the Android version is compiled for Android, a Linux based operating system.

**Comment by MCMrARM** [comment]
It can not be used to run the Win 10 Edition executable, because that one has no symbols and uses Win32/WinRT APIs, and not the Linux ones like Android does.

The code base is indeed basically the same, and you lose nothing running the Android build instead of Win10.

**Comment by MCMrARM** [comment]
If Windows 10 Edition had symbols, I'd definitely pick that one up, because it's 64-bit.

**Comment by lukeeey** [comment]
@MCMrARM You do lose the chat location at the bottom of the screen though

**Comment by Madis0** [comment]
Thanks for clarifying. Just to be clear, I didn't suggest Windows 10 Edition because it would be any better from Android's, but just because it is free for Java Edition users 😀

**Comment by MCMrARM** [comment]
@lukeeey I guess that's just a JSON thing that can easily be changed. If I'll have a while I'll look into making it look like that by default.
@Madis0 heh, I guess so :D but well, unfortunately, it's not really possible (well actually, it's doable, it'd just 5x the effort of maintaining this launcher, that I'm not really willing to spend) due to that edition lacking symbol information.

**Comment by lukeeey** [comment]
@MCMrARM i guessed it was because you set the game version to pe to fix some problem instead of leaving it as win 10.
