### ISSUE TITLE
Make/Cmake compiling issue

### ISSUE THREAD

**Issue by SmakLi** [MCMrARM/mcpelauncher-linux#411]
So I've tried everything i can think of to fix the error and I'm at a loss for ideas now, I've checked all the other issues similar to mine and have yet to find a solution I may be missing something though. Here's my error:
`/usr/local/lib/libz.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
CMakeFiles/server.dir/build.make:849: recipe for target 'server' failed
make[2]: *** [server] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/server.dir/all' failed
make[1]: *** [CMakeFiles/server.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
/usr/local/lib/libz.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
CMakeFiles/mcpelauncher.dir/build.make:1164: recipe for target 'mcpelauncher' failed
make[2]: *** [mcpelauncher] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/mcpelauncher.dir/all' failed
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`
I'm running Linux Mint 18.3 Sylvia

**Comment by lukeeey** [comment]
You need to follow the README instructions and install the 32-bit libraries. I assume you havent, because `libz` is zlib and a quick google of the error said something about loading the wrong arch binaries.

**Comment by SmakLi** [comment]
I've completely uninstalled everything and started from scratch doing exactly as told in the README instructions. I've checked all the files over and over and it says they're all at the newest version. I'm pretty sure I have the 32-bit libraries downloaded and installed, yet I'm still getting the same error. I've done several google searchs and I know that it's loading the wrong binary but I cant find a clear solution to my issue.

**Comment by lukeeey** [comment]
Can you execute `file /usr/local/lib/libz.so`

**Comment by SmakLi** [comment]
When I executed `file /usr/local/lib/libz.so` I got `/usr/local/lib/libz.so: symbolic link to libz.so.1.2.11` so I decided to execute `file /usr/local/lib/libz.so.1.2.11` and the result was `/usr/local/lib/libz.so.1.2.11: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=2dc79627b98ba61774a76a185cd64ed391076d5e, not stripped`

**Comment by lukeeey** [comment]
Try `sudo apt purge zlib1g-dev -y && sudo apt install zlib1g-dev:i386`

**Comment by SmakLi** [comment]
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'zlib1g-dev' is not installed, so not removed. Did you mean 'zlib1g-dev:i386'?
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
zlib1g-dev:i386 is already the newest version (1:1.2.8.dfsg-2ubuntu4.1).
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.`
