### ISSUE TITLE
Server failed to start

### ISSUE THREAD

**Issue by GoneTone** [MCMrARM/mcpelauncher-linux#413]
I see these messages when I run the `./server` command, `./mcpelauncher` works fine, help me.
```
17:56:31 Trace [Launcher] Loading hybris libraries
17:56:31 Trace [Launcher] Loaded OS library libm.so.6
17:56:31 Trace [Launcher] Loading Minecraft library
17:56:42 Info [Launcher] Loaded Minecraft library
17:56:42 Debug [Launcher] Minecraft is at offset 0xf36c4000
17:56:42 Error [MinecraftSymbols] Unresolved symbol: _ZN8Resource14registerLoaderE18ResourceFileSystemSt10unique_ptrI14ResourceLoaderSt14default_deleteIS2_EE
17:56:42 Error [MinecraftSymbols] Unresolved symbol: _ZN14ServerInstanceC2ER13IMinecraftAppR9WhitelistRK7OpsListP15FilePathManagerNSt6chrono8durationIxSt5ratioILx1ELx1EEEESsSsSs13LevelSettingsRN9minecraft3api3ApiEibiiibRKSt6vectorISsSaISsEESsRKN3mce4UUIDER17MinecraftEventingR22ResourcePackRepositoryRK18ContentTierManagerR19ResourcePackManagerSt8functionIFSt10unique_ptrI12LevelStorageSt14default_deleteIS13_EER9SchedulerEERKSsP9LevelDataPSZ_S11_IFvS1C_EES1H_
17:56:42 Error [MinecraftSymbols] Unresolved symbol: _ZN9Scheduler6clientEv
17:56:42 Error [MinecraftSymbols] Unresolved symbol: _ZN30ExternalFileLevelStorageSource18createLevelStorageER9SchedulerRKSsS3_RK19IContentKeyProvider
17:56:42 Info [Launcher] Applying patches
17:56:42 Trace [Launcher] Patching - original: 85 83 87 86 131
17:56:42 Trace [Launcher] Patching - result: 233 237 72 91 18
17:56:42 Info [Launcher] Starting server initialization
17:56:42 Trace [Launcher] Initializing AppPlatform (vtable)
17:56:42 Trace [AppPlatform] Vtable size = 242
17:56:42 Trace [Launcher] Initializing AppPlatform (create instance)
17:56:42 Trace [Launcher] Initializing AppPlatform (initialize call)
17:56:42 Trace [AppPlatform] createDeviceID:
17:56:42 Debug [Launcher] AppPlatform initialized successfully
17:56:42 Trace [Launcher] Loading whitelist and operator list
17:56:42 Trace [Launcher] Initializing Minecraft API classes
17:56:42 Trace [Launcher] Setting up level settings
17:56:42 Trace [Launcher] Initializing FilePathManager
17:56:42 Trace [AppPlatform] getCurrentStoragePath: /root/.local/share/mcpelauncher/
17:56:42 Trace [Launcher] Initializing resource loaders
Signal 11 received
Backtrace elements: 2
#0 ./server(_Z12handleSignaliPv+0x62) [0x808f805]
#1 [0xf7f64de0]
Dumping stack...
#591 HYBRIS Level::_checkUserStorage()+0 in libminecraftpe.so+0x242be60 [0xf5aefe60]
Signal 6 received
已經終止 (core dumped)
```

**Comment by min20120907** [comment]
你沒有開GUI是不行的哦，你有用GUI嗎？

**Comment by GoneTone** [comment]
GUI 一樣不能

**Comment by min20120907** [comment]
好吧，我試試看新版的

**Comment by GoneTone** [comment]
ok

**Comment by min20120907** [comment]
`20:38:02 Trace [Launcher] Loading hybris libraries
20:38:02 Trace [Launcher] Loaded OS library libm.so.6
20:38:02 Trace [Launcher] Loading Minecraft library
20:38:03 Info [Launcher] Loaded Minecraft library
20:38:03 Debug [Launcher] Minecraft is at offset 0xf3772000
20:38:03 Info [Launcher] Applying patches
20:38:03 Trace [Launcher] Patching - original: 85 83 87 86 131
20:38:03 Trace [Launcher] Patching - result: 233 221 21 173 96
20:38:03 Info [Launcher] Starting server initialization
20:38:03 Trace [Launcher] Initializing AppPlatform (vtable)
20:38:03 Trace [AppPlatform] Vtable size = 224
20:38:03 Trace [Launcher] Initializing AppPlatform (create instance)
20:38:03 Trace [Launcher] Initializing AppPlatform (initialize call)
20:38:03 Trace [AppPlatform] createDeviceID: 
20:38:04 Debug [Launcher] AppPlatform initialized successfully
20:38:04 Trace [Launcher] Loading whitelist and operator list
20:38:04 Trace [Launcher] Initializing Minecraft API classes
20:38:04 Trace [Launcher] Setting up level settings
20:38:04 Trace [Launcher] Initializing FilePathManager
20:38:04 Trace [AppPlatform] getCurrentStoragePath: /home/min20120907/.local/share/mcpelauncher/
20:38:04 Trace [Launcher] Initializing resource loaders
20:38:04 Trace [Launcher] Initializing MinecraftEventing (create instance)
20:38:04 Trace [Launcher] Initializing MinecraftEventing (init call)
20:38:04 Trace [AppPlatform] getSystemRegion: 0xdeadbeef
20:38:04 Trace [Launcher] Initializing ResourcePackManager
20:38:04 Trace [Launcher] Initializing PackManifestFactory
20:38:04 Trace [Launcher] Initializing SkinPackKeyProvider
20:38:04 Trace [Launcher] Initializing StubKeyProvider
20:38:04 Trace [Launcher] Initializing PackSourceFactory
20:38:04 Trace [Launcher] Initializing ResourcePackRepository
20:38:04 Trace [AppPlatform] getInternalStoragePath: /home/min20120907/.local/share/mcpelauncher/
20:38:04 Trace [AppPlatform] getInternalStoragePath: /home/min20120907/.local/share/mcpelauncher/
20:38:04 Trace [AppPlatform] getInternalStoragePath: /home/min20120907/.local/share/mcpelauncher/
20:38:04 Trace [AppPlatform] getInternalStoragePath: /home/min20120907/.local/share/mcpelauncher/
20:38:04 Trace [AppPlatform] getInternalStoragePath: /home/min20120907/.local/share/mcpelauncher/
20:38:04 Trace [AppPlatform] getInternalStoragePath: /home/min20120907/.local/share/mcpelauncher/
20:38:04 Trace [AppPlatform] getInternalStoragePath: /home/min20120907/.local/share/mcpelauncher/
20:38:04 Trace [Launcher] Adding vanilla resource pack
20:38:04 Trace [Launcher] Adding world resource packs
20:38:04 Trace [Launcher] Initializing Automation::AutomationClient
20:38:04 Debug [Launcher] Initializing SaveTransactionManager
20:38:04 Debug [Launcher] Initializing ExternalFileLevelStorageSource
20:38:04 Debug [Launcher] Initializing ServerInstance
[MTU] Max MTU Size 1492 bytes
[IPv6] multicast listen on interface 0
20:38:05 Trace [Launcher] Loading language data
20:38:05 Info [Launcher] Server initialized
`
我的是正常的哦，你的系統環境是什麼

**Comment by GoneTone** [comment]
你使用的 MCPE APK 版本是?

**Comment by GoneTone** [comment]
我的 Google Play 的 MCPE 是測試版，我取不到正式版的 x86 APK

**Comment by GoneTone** [comment]
Sorry, is the version issue, does not support 1.6.0.5
