### ISSUE TITLE
Does not contain a CMakeLists.txt file.

### ISSUE THREAD

**Issue by MasterOfTheTiger** [MCMrARM/mcpelauncher-linux#417]
Operating System: Linux Mint 19 (based on Ubuntu 18.04)
Cmake version: 3.10.2
Install type: CEF and Gplay

This is outputted when I run `cmake ..`. I have all dependencies listed installed. 
```
CMake Error at CMakeLists.txt:106 (add_subdirectory):
  The source directory

    /home/$USER/mcpelauncher-linux/gplay_api

  does not contain a CMakeLists.txt file.


CMake Error at CMakeLists.txt:107 (set_target_properties):
  set_target_properties Can not find target to add properties to: gplaydl


-- Configuring incomplete, errors occurred!
See also "/home/$USER/mcpelauncher-linux/build/CMakeFiles/CMakeOutput.log".
See also "/home/$USER/mcpelauncher-linux/build/CMakeFiles/CMakeError.log".
```

**Comment by lukeeey** [comment]
You didnt clone with --recursive

**Comment by MasterOfTheTiger** [comment]
@lukeeey It worked. Thank you. That should really be mentioned in the README and the wiki.

**Comment by lukeeey** [comment]
Personally i think people should just add that option when cloning any repo

**Comment by MasterOfTheTiger** [comment]
That makes sense, but if it does not work if you do not do it that way here, a lot of people can be left confused and making issues that do not need to be made. Also, what does recursive do exactly?

**Comment by lukeeey** [comment]
It clones all submodules too
