### ISSUE TITLE
[Linux] Cmake fails when compiling with 'setup_cef.sh' installed

### ISSUE THREAD

**Issue by Detor** [MCMrARM/mcpelauncher-linux#418]
Hi, I compiled mcpelauncher without cef, it succeeded and ran mcpe alright. But i tried compiling it with `./setup_cef.sh` installed (with all the minimal, cef, and first time setup dependencies installed) and when i try to cmake the source code, i get this:

`CMake Error at CMakeLists.txt:106 [(add_subdirectory)`
  `The source `
    `/home/user/Documents/Games/mcpelauncher-linux-master/gplay_api`
  `does not contain a CMakeLists.txt file.`
`CMake Error at CMakeLists.txt:107 (set_target_properties):`
  `set_target_properties Can not find target to add properties to: gplaydl`
`-- Configuring incomplete, errors occurred!`

[CMakeError.log](https://github.com/MCMrARM/mcpelauncher-linux/files/2168717/CMakeError.log)
[CMakeOutput.log](https://github.com/MCMrARM/mcpelauncher-linux/files/2168718/CMakeOutput.log)

**Comment by MasterOfTheTiger** [comment]
You need to clone as --recursive. https://github.com/MCMrARM/mcpelauncher-linux/issues/417

**Comment by Detor** [comment]
Thanks
