### ISSUE TITLE
cmake is giving me fatal error: zconf.h: No such file or directory why??

### ISSUE THREAD

**Issue by stayandwait** [MCMrARM/mcpelauncher-linux#42]
Why is cmake giving me this error??
[ 94%] Building CXX object CMakeFiles/mcpelauncher.dir/src/LinuxAppPlatform.cpp.o
In file included from /usr/include/png.h:536:0,
                 from /mnt/c/Users/band1/Desktop/mcpelauncher-linux/src/LinuxAppPlatform.cpp:6:
/usr/include/zlib.h:34:19: fatal error: zconf.h: No such file or directory
 #include "zconf.h"
                   ^
compilation terminated.
make[2]: *** [CMakeFiles/mcpelauncher.dir/src/LinuxAppPlatform.cpp.o] Error 1
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
make: *** [all] Error 2

**Comment by rigortek** [comment]
Suggested workaround from bugzilla.mozilla org:
sudo ln -s /usr/include/x86_64-linux-gnu/zconf.h /usr/include
