### ISSUE TITLE
I cannot get the system to accept the commands

### ISSUE THREAD

**Issue by demonitize** [MCMrARM/mcpelauncher-linux#422]
The system Terminal is not working. Does anyone want to use Remmina Desktop Sharing to help me?

**Comment by MasterOfTheTiger** [comment]
This is not a problem with mcpe-launcher. Questions like this probably should be discussed in the Discord server if at all.

**Comment by demonitize** [comment]
@MasterOfTheTiger Could you give me the link for that, please. Thanks.

**Comment by MasterOfTheTiger** [comment]
Here it is @dexterateed: https://discord.gg/TaUNBXr. I will also be willing to help you out of I can (I am on the Discord).
