### ISSUE TITLE
./make -j$(nproc)..../extract.h:4:17: fatal error: zip.h: File or directory does not exist

### ISSUE THREAD

**Issue by Dhrhciebcy** [MCMrARM/mcpelauncher-linux#423]
When I wrote `cmake ..`, I recived this error in my terminal

root@VEGAS:/home/dhrhciebcy/mcpelauncher-linux-master# mkdir build/ && cd build/root@VEGAS:/home/dhrhciebcy/mcpelauncher-linux-master/build# cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found ZLIB: /usr/lib/i386-linux-gnu/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib/i386-linux-gnu/libpng.so (found version "1.2.54") 
-- Found CURL: /usr/lib/i386-linux-gnu/libcurl.so (found version "7.47.0") 
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Looking for XOpenDisplay in /usr/lib/i386-linux-gnu/libX11.so;/usr/lib/i386-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/i386-linux-gnu/libX11.so;/usr/lib/i386-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found X11: /usr/lib/i386-linux-gnu/libX11.so
-- Found Protobuf: /usr/lib/i386-linux-gnu/libprotobuf.so  
CMake Error at CMakeLists.txt:106 (add_subdirectory):
  The source directory

    /home/dhrhciebcy/mcpelauncher-linux-master/gplay_api

  does not contain a CMakeLists.txt file.

CMake Error at CMakeLists.txt:107 (set_target_properties):
  set_target_properties Can not find target to add properties to: gplaydl

-- Configuring incomplete, errors occurred!
See also "/home/dhrhciebcy/mcpelauncher-linux-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/dhrhciebcy/mcpelauncher-linux-master/build/CMakeFiles/CMakeError.log".
root@VEGAS:/home/dhrhciebcy/mcpelauncher-linux-master/build#

Please help :(

**Comment by Dhrhciebcy** [comment]
UPDATE

I have found that the directory "gplay_api" for some strange reason was empty. I have downloaded the directory's files and I received a new issue but, this time, it is very clear:

`dhrhciebcy@VEGAS:~/mcpelauncher-linux-master$ mkdir build/ && cd build/
dhrhciebcy@VEGAS:~/mcpelauncher-linux-master/build$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found ZLIB: /usr/lib/i386-linux-gnu/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib/i386-linux-gnu/libpng.so (found version "1.2.54") 
-- Found CURL: /usr/lib/i386-linux-gnu/libcurl.so (found version "7.47.0") 
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Looking for XOpenDisplay in /usr/lib/i386-linux-gnu/libX11.so;/usr/lib/i386-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/i386-linux-gnu/libX11.so;/usr/lib/i386-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found X11: /usr/lib/i386-linux-gnu/libX11.so
-- Found Protobuf: /usr/lib/i386-linux-gnu/libprotobuf.so  
CMake Error at gplay_api/CMakeLists.txt:1 (cmake_minimum_required):
  CMake 3.6 or higher is required.  You are running version 3.5.1


-- Configuring incomplete, errors occurred!
See also "/home/dhrhciebcy/mcpelauncher-linux-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/dhrhciebcy/mcpelauncher-linux-master/build/CMakeFiles/CMakeError.log".
dhrhciebcy@VEGAS:~/mcpelauncher-linux-master/build$`

I have to update cmake but, until now, I did not succeed. I am using Ubuntu 16.04. Anyway, now I will dedicate myself to the cmake update. If someone would like to help, it will always be welcome :)

Thanks



P. S.  Perhaps the object of the issue will change if I will find other problems, or it will be closed if all will works fine

**Comment by Dhrhciebcy** [comment]
UPDATE 2

Finally I managed to update cmake from version 3.5.1 to 3.7.1

dhrhciebcy@VEGAS:~/mcpelauncher-linux-master$ mkdir build/ && cd build/
dhrhciebcy@VEGAS:~/mcpelauncher-linux-master/build$ cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found ZLIB: /usr/lib/i386-linux-gnu/libz.so (found version "1.2.8") 
-- Found PNG: /usr/lib/i386-linux-gnu/libpng.so (found version "1.2.54") 
-- Found CURL: /usr/lib/i386-linux-gnu/libcurl.so (found version "7.47.0") 
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Looking for XOpenDisplay in /usr/lib/i386-linux-gnu/libX11.so;/usr/lib/i386-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/i386-linux-gnu/libX11.so;/usr/lib/i386-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found X11: /usr/lib/i386-linux-gnu/libX11.so
-- Found Protobuf: /usr/lib/i386-linux-gnu/libprotobuf.so;-lpthread (found version "2.6.1") 
-- Found Protobuf: /usr/lib/i386-linux-gnu/libprotobuf.so;-lpthread;-lpthread (found version "2.6.1") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dhrhciebcy/mcpelauncher-linux-master/build
dhrhciebcy@VEGAS:~/mcpelauncher-linux-master/build$

Now, as you can see, cmake works correctly, but there is a problem with the last command `make -j$(nproc)`

```
dhrhciebcy @ VEGAS: ~ / mcpelauncher-linux-master / build $ make -j $ (nproc)
[1%] Running C ++ protocol buffer compiler on proto / play_details.proto
Scanning dependencies of target server
[1%] Running C ++ protocol buffer compiler on proto / gsf.proto
[2%] Running C ++ protocol buffer compiler on proto / play_common.proto
[2%] Building C object CMakeFiles / server.dir / libs / hybris / src / cache.c.o
[3%] Running C ++ protocol buffer compiler on proto / play_document.proto
[4%] Running C ++ protocol buffer compiler on proto / play_respone.proto
[5%] Running C ++ protocol buffer compiler on proto / play_settings.proto
[libprotobuf WARNING google / protobuf / descriptor.cc: 5411] Warning: Unused import: "play_settings.proto" imports "play_search.proto" which is not used.
[5%] Running C ++ protocol buffer compiler on proto / play_toc.proto
[6%] Running C ++ protocol buffer compiler on proto / play_download.proto
[7%] Running C ++ protocol buffer compiler on proto / play_filter_rules.proto
[8%] Running C ++ protocol buffer compiler on proto / play_ownership.proto
[9%] Building C object CMakeFiles / server.dir / libs / hybris / src / dlfcn.c.o
[10%] Building C object CMakeFiles / server.dir / libs / hybris / src / hooks.c.o
[11%] Running C ++ protocol buffer compiler on proto / play_containers.proto
[12%] Building C object CMakeFiles / server.dir / libs / hybris / src / hooks_shm.c.o
[12%] Running C ++ protocol buffer compiler on proto / play_link.proto
[13%] Running C ++ protocol buffer compiler on proto / play_device_config.proto
[14%] Building C object CMakeFiles / server.dir / libs / hybris / src / logging.c.o
[libprotobuf WARNING google / protobuf / descriptor.cc: 5411] Warning: Unused import: "play_device_config.proto" imports "play_common.proto" which is not used.
[15%] Running C ++ protocol buffer compiler on proto / play_search.proto
[16%] Running C ++ protocol buffer compiler on proto / play_browse.proto
[16%] Building C object CMakeFiles / server.dir / libs / hybris / src / properties.c.o
[17%] Building C object CMakeFiles / server.dir / libs / hybris / src / ctype.c.o
[18%] Building C object CMakeFiles / server.dir / libs / hybris / src / sysconf.c.o
[19%] Building C object CMakeFiles / server.dir / libs / hybris / src / jb / dlfcn.c.o
[20%] Building C object CMakeFiles / server.dir / libs / hybris / src / jb / linker.c.o
[20%] Building C object CMakeFiles / server.dir / libs / hybris / src / jb / linker_environ.c.o
Scanning dependencies of target gplayapi
[21%] Building C object CMakeFiles / server.dir / libs / hybris / src / jb / linker_format.c.o
/home/dhrhciebcy/mcpelauncher-linux-master/libs/hybris/src/jb/linker.c: In function 'alloc_info':
/home/dhrhciebcy/mcpelauncher-linux-master/libs/hybris/src/jb/linker.c:289:5: warning: implicit declaration of function 'strlcpy' [-Wimplicit-function-declaration]
     strlcpy ((char *) yes-> name, name, sizeof (yes-> name));
     ^
/home/dhrhciebcy/mcpelauncher-linux-master/libs/hybris/src/jb/linker.c: In function 'reloc_library':
/home/dhrhciebcy/mcpelauncher-linux-master/libs/hybris/src/jb/linker.c:1360:24: warning: implicit declaration of function 'get_hooked_symbol' [-Wimplicit-function-declaration]
             sym_addr = get_hooked_symbol (sym_name);
                        ^
/home/dhrhciebcy/mcpelauncher-linux-master/libs/hybris/src/jb/linker.c:1361:26: warning: comparison between pointer and integer
             if (sym_addr! = NULL) {
                          ^
/home/dhrhciebcy/mcpelauncher-linux-master/libs/hybris/src/jb/linker.c:1367:25: warning: comparison between pointer and integer
             if (sym_addr == NULL)
                         ^
[22%] Building C object CMakeFiles / server.dir / libs / hybris / src / jb / rt.c.o
[23%] Building C object CMakeFiles / server.dir / libs / hybris / src / hooks_pthread.c.o
[24%] Building C object CMakeFiles / server.dir / libs / hybris / src / hooks_dirent.c.o
[24%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / lib / playapi / login.cpp.o
[25%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / lib / playapi / device_info.cpp.o
[26%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / lib / playapi / checkin.cpp.o
[26%] Building C object CMakeFiles / server.dir / libs / hybris / src / hooks_io.c.o
[27%] Building C object CMakeFiles / server.dir / libs / hybris / src / hooks_net.c.o
[28%] Building C object CMakeFiles / server.dir / libs / hybris / src / strlcpy.c.o
[29%] Building CXX object CMakeFiles / server.dir / src / common / common.cpp.o
[30%] Building CXX object CMakeFiles / server.dir / src / common / hook.cpp.o
[30%] Building CXX object CMakeFiles / server.dir / src / client / appplatform.cpp.o
[31%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / lib / playapi / api.cpp.o
[32%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / lib / playapi / experiments.cpp.o
[32%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / lib / playapi / util / http.cpp.o
[33%] Building CXX object CMakeFiles / server.dir / src / common / base64.cpp.o
[34%] Building CXX object CMakeFiles / server.dir / src / common / extract.cpp.o
In file included from /home/dhrhciebcy/mcpelauncher-linux-master/src/common/extract.cpp:1:0:
/ Home / dhrhciebcy / mcpelauncher-linux-master / src / common / extract.h: 4: 17: fatal error: zip.h: File or directory not existing compilation terminated.CMakeFiles / server.dir / build.make: 590: set of instructions for the target "CMakeFiles /server.dir/src/common/extract.cpp.o "not successful [2]: *** [CMakeFiles / server.dir / src / common / extract.cpp.o] 1CMakeFiles / Makefile2: 104 error: set of "CMakeFiles / server.dir / all" failed instructions [1]: *** [CMakeFiles / server.dir / all] 2make error [1]: *** Waiting for unfinished processes ... . [35%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / lib / playapi / util / config.cpp.o [36%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / lib / playapi / util / rand. cpp.o [37%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / lib / playapi / util / base64.cpp.o [38%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / gsf.pb.cc. o [38%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / play_common.pb.cc.o [39%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / play_do cument.pb.cc.o [40%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / play_respone.pb.cc.o [41%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / play_settings.pb.cc. o [42%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / play_toc.pb.cc.o [43%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / play_download.pb.cc.o [43%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / play_filter_rules.pb.cc.o [44%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / play_ownership.pb.cc.o [45%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / play_containers.pb.cc.o [46%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / play_link.pb.cc.o [47%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / play_device_config. pb.cc.o [47%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / play_search.pb.cc.o [48%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / play_browse.pb.cc.o [ 50%] Building CXX object gplay_api / CMakeFiles / gplayapi.dir / play_details.pb.cc.o [51% ] Linking CXX static library libgplayapi.a [51%] Built-in target gplayapiMakefile: 127: set of instructions for the goal "all" failed: *** [all] Error 2dhrhciebcy @ VEGAS: ~ / mcpelauncher-linux-master / build $
```

What kind of error it could be?

Please help :'(

Thanks

**Comment by lukeeey** [comment]
It would help if the error was in english

**Comment by Dhrhciebcy** [comment]
Ok, I am sorry, I will translate the italian parts as soon as I can

**Comment by guppy42** [comment]
The error pretty much transends language...
`/home/dhrhciebcy/mcpelauncher-linux-master/src/common/extract.h:4:17: fatal error: zip.h: File o directory non esistente
`

Please install all the required libraries  ;)

**Comment by guppy42** [comment]
Also apparently people keep missing the wiki - has the information you need to compile;
https://github.com/MCMrARM/mcpelauncher-linux/wiki

**Comment by Dhrhciebcy** [comment]
@guppy42 

```
dhrhciebcy @ VEGAS: ~ $ up
Password:
root @ VEGAS: / home / dhrhciebcy # apt-get install gcc-multilib g ++ - multilib zlib1g-dev: i386 libx11-dev: i386 libzip-dev: i386 libpng-dev: i386 libcurl4-openssl-dev: i386 libssl-dev: i386 libgles2-mesa-dev: i386 libudev-dev: i386 libevdev-dev: i386
Reading package list ... Done
Tree generation of dependencies
Reading status information ... Done
Note, "libpng12-dev: i386" is selected instead of "libpng-dev: i386"
g ++ - multilib is already the newest version (4: 5.3.1-1ubuntu1).
gcc-multilib is already the newest version (4: 5.3.1-1ubuntu1).
libevdev-dev: i386 is already the newest version (1.4.6 + dfsg-1).
libx11-dev: i386 is already the newest version (2: 1.6.3-1ubuntu2).
libzip-dev: i386 is already the newest version (1.0.1-0ubuntu1).
libcurl4-openssl-dev: i386 is already the newest version (7.47.0-1ubuntu2.8).
libgles2-mesa-dev: i386 is already the newest version (18.0.5-0ubuntu0 ~ 16.04.1).
libpng12-dev: i386 is already the newest version (1.2.54-1ubuntu1.1).
libssl-dev: i386 is already the newest version (1.0.2g-1ubuntu4.13).
libudev-dev: i386 is already the newest version (229-4ubuntu21.4).
zlib1g-dev: i386 is already the newest version (1: 1.2.8.dfsg-2ubuntu4.1).
It is useful to run "apt-get -f install" to correct these problems:
The following packages have unmet dependencies:
 libudev-dev: i386: Depends: libkmod2: i386 (> = 5 ~) but is not about to be installed
E: Unsatisfied dependencies. Try "apt-get -f install" without packages (or specify a solution).
root @ VEGAS: / home / dhrhciebcy # apt-get install libgtk2.0-0: i386 libgtkglext1: i386 libasound2: i386 libnss3: i386 libxss1: i386 libgconf2-4: i386 libxtst6: i386 libudev1: i386
Reading package list ... Done
Tree generation of dependencies
Reading status information ... Done
libasound2: i386 is already the newest version (1.1.0-0ubuntu1).
libxss1: i386 is already the newest version (1: 1.2.2-1).
libxtst6: i386 is already the newest version (2: 1.2.2-1).
libgconf2-4: i386 is already the newest version (3.2.6-3ubuntu6).
libgtkglext1: i386 is already the newest version (1.2.0-3.2fakesync1ubuntu1).
libgtk2.0-0: i386 is already the newest version (2.24.30-1ubuntu1.16.04.2).
libnss3: i386 is already the newest version (2: 3.28.4-0ubuntu0.16.04.3).
libudev1: i386 is already the newest version (229-4ubuntu21.4).
It is useful to run "apt-get -f install" to correct these problems:
The following packages have unmet dependencies:
 libudev-dev: i386: Depends: libkmod2: i386 (> = 5 ~) but is not about to be installed
E: Unsatisfied dependencies. Try "apt-get -f install" without packages (or specify a solution).
root @ VEGAS: / home / dhrhciebcy # apt-get install protobuf-compiler libprotobuf-dev: i386
Reading package list ... Done
Tree generation of dependencies
Reading status information ... Done
protobuf-compiler is already the newest version (2.6.1-1.3).
libprotobuf-dev: i386 is already the newest version (2.6.1-1.3).
It is useful to run "apt-get -f install" to correct these problems:
The following packages have unmet dependencies:
 libudev-dev: i386: Depends: libkmod2: i386 (> = 5 ~) but is not about to be installed
E: Unsatisfied dependencies. Try "apt-get -f install" without packages (or specify a solution).
root @ VEGAS: / home / dhrhciebcy #
```

As you can see, if I'm not wrong, I have just installed all packages, or what required libraries have I to install?

Thanks

**Comment by guppy42** [comment]
@Dhrhciebcy I don't speak Italian either but it does seem to be complaining about unmet dependencies ?

At any rate try installing libzip and libzip-dev 

yes the non i386 versions the build scripts are rather wonkey - there is a reason this entire project has been deprected and moved to a newer source base

after that try re-run cmake/make


But maybe save your self some trouble, and do as the project note suggests;

> Please note this is a legacy repository, if you're interested in participating in testing of the launcher rewrite please join the Discord for help & instructions: https://discord.gg/TaUNBXr

I'm fairly sure this code base has not been updated to support 1.5 / aquatic, where as the new one apparently has.

**Comment by Dhrhciebcy** [comment]
```
dhrhciebcy @ VEGAS: ~ $ sudo apt-get install libzip libzip-dev
[sudo] dhrhciebcy password:
Reading package list ... Done
Tree generation of dependencies
Reading status information ... Done
E: The libzip package could not be found
dhrhciebcy @ VEGAS: ~ $
```

Maybe I did something wrong... anyway now I will translate all the error messages in English, in order to make the problem clear. @guppy42 thanks for the discord link and, specially, for your support :smiley:

**Comment by Dhrhciebcy** [comment]
UPDATE 3

I have just discovered that one of the required packages, `libudev-dev:i386`, was damaged. I have completely removed it but, when I have tried to reinstall it, I have had this error:

```
dhrhciebcy@VEGAS:~$ su
Password: 
root @ VEGAS: / home / dhrhciebcy # apt-get install libudev-dev: i386
Reading package list ... Done
Tree generation of dependencies
Reading status information ... Done
The following packages have been installed automatically and are no longer required:
  libllvm3.8 libllvm3.8: i386 linux-headers-4.4.0-31
  linux-headers-4.4.0-31-generic linux-headers-4.4.0-87
  linux-headers-4.4.0-87-generic linux-headers-4.4.0-89
  linux-headers-4.4.0-89-generic linux-image-4.4.0-31-generic
  linux-image-4.4.0-87-generic linux-image-4.4.0-89-generic
  linux-image-4.4.0-31-generic-extra
  linux-image-4.4.0-87-generic-extra
  linux-image-4.4.0-89-generic-extra
  signed-linux-image-4.4.0-31-generic
  signed-linux-image-4.4.0-87-generic
  signed-linux-image-4.4.0-89-generic
Use "apt autoremove" to remove them.
The following additional packages will be installed:
  libkmod2: i386
The following NEW packages will be installed:
  libkmod2: i386 libudev-dev: i386
0 updated, 2 installed, 0 to remove and 512 not updated.
0 B / 202 kB of archives must be downloaded.
After this operation, 668 KB of disk space will be occupied.
To continue? [S / n] S
(Read the database ... 339914 currently installed files and directories.)
Preparations for extracting ... / libkmod2_22-1ubuntu5_i386.deb ...
Extraction of libkmod2: i386 (22-1ubuntu5) ...
dpkg: error processing the archive /var/cache/apt/archives/libkmod2_22-1ubuntu5_i386.deb (--unpack):
 attempted to overwrite "/usr/share/doc/libkmod2/changelog.Debian.gz" (shared), different from other instances of the libkmod2 package: i386
Selected the libudev-dev package: i386 not previously selected.
Preparations for extracting ... / libudev-dev_229-4ubuntu21.4_i386.deb ...
Extraction of libudev-dev: i386 (229-4ubuntu21.4) ...
Trigger processing for libc-bin (2.23-0ubuntu9) ...
Trigger processing for man-db (2.7.5-1) ...
There were errors in the processing:
 /var/cache/apt/archives/libkmod2_22-1ubuntu5_i386.deb
E: Sub-process / usr / bin / dpkg returned an error code (1)
root @ VEGAS: / home / dhrhciebcy #
```
So there were really one of the required packages that was not working, but now I can not even install it :sob:

```
dhrhciebcy @ VEGAS: ~ $ up
Password:
root @ VEGAS: / home / dhrhciebcy # apt-get -f install libudev-dev: i386
Reading package list ... Done
Tree generation of dependencies
Reading status information ... Done
libudev-dev: i386 is already the newest version (229-4ubuntu21.4).
It is useful to run "apt-get -f install" to correct these problems:
The following packages have unmet dependencies:
 libudev-dev: i386: Depends: libkmod2: i386 (> = 5 ~) but is not about to be installed
E: Unsatisfied dependencies. Try "apt-get -f install" without packages (or specify a solution).
root @ VEGAS: / home / dhrhciebcy # apt-get -f install
Reading package list ... Done
Tree generation of dependencies
Reading status information ... Done
Correction of addictions ... Done
The following packages have been installed automatically and are no longer required:
  libllvm3.8 libllvm3.8: i386 linux-headers-4.4.0-31
  linux-headers-4.4.0-31-generic linux-headers-4.4.0-87
  linux-headers-4.4.0-87-generic linux-headers-4.4.0-89
  linux-headers-4.4.0-89-generic linux-image-4.4.0-31-generic
  linux-image-4.4.0-87-generic linux-image-4.4.0-89-generic
  linux-image-extra-4.4.0-31-generic linux-image-extra-4.4.0-87-generic
  linux-image-extra-4.4.0-89-generic linux-signed-image-4.4.0-31-generic
  linux-signed-image-4.4.0-87-generic linux-signed-image-4.4.0-89-generic
Use "apt autoremove" to remove them.
The following additional packages will be installed:
  libkmod2: i386
The following NEW packages will be installed:
  libkmod2: i386
0 updated, 1 installed, 0 to remove and 512 not updated.
1 not completely installed or removed.
0 B / 45 kB of archives must be downloaded.
After this operation, 136 KB of disk space will be occupied.
To continue? [S / n] s
(Read the database ... 339988 files and directories currently installed.)
Preparations for extracting ... / libkmod2_22-1ubuntu5_i386.deb ...
Extraction of libkmod2: i386 (22-1ubuntu5) ...
dpkg: error processing the archive /var/cache/apt/archives/libkmod2_22-1ubuntu5_i386.deb (--unpack):
 attempted to overwrite "/usr/share/doc/libkmod2/changelog.Debian.gz" (shared), different from other instances of the libkmod2 package: i386
Trigger processing for libc-bin (2.23-0ubuntu9) ...
There were errors in the processing:
 /var/cache/apt/archives/libkmod2_22-1ubuntu5_i386.deb
E: Sub-process / usr / bin / dpkg returned an error code (1)
root @ VEGAS: / home / dhrhciebcy #
```

**Comment by Dhrhciebcy** [comment]
UPDATE 4

I have just reinstalled the package `libkmod2:i386` and I have tried to reinstall `libudev-dev:i386` and now all worked fine :tada: :tada:

Now I will try again all

**Comment by Dhrhciebcy** [comment]
Now all works and for the first time the mcpelauncher setup has started but, when I choose the .apk file x86, I received an error that I remember very well... I'm talking about the error 6, only that now the problem does not seem to be the .apk file. In order to do not open another issue for the same problem, I open again the old issue of the error 6. Please move here #148
