### ISSUE TITLE
Make[Error] near 59%

### ISSUE THREAD

**Issue by ghost** [MCMrARM/mcpelauncher-linux#427]
[ 59%] Linking CXX executable mcpelauncher
/usr/lib/gcc/x86_64-linux-gnu/7/../../../i386-linux-gnu/libGLESv2.so: Warnung: undefinierter Verweis auf »_glapi_tls_Current«
collect2: error: ld returned 1 exit status
CMakeFiles/mcpelauncher.dir/build.make:1343: recipe for target 'mcpelauncher' failed
make[2]: *** [mcpelauncher] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/mcpelauncher.dir/all' failed
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lukeeey** [comment]
This is a legacy repo. Please see https://github.com/minecraft-linux/mcpelauncher-manifest/wiki
