### ISSUE TITLE
MCPE has no audio Ubuntu 16.04 bug

### ISSUE THREAD

**Issue by stayandwait** [MCMrARM/mcpelauncher-linux#44]
I did a fresh install of Ubuntu 16.04. Setup the launcher/game and installed all the packages as instructed. I noticed that there is no audio in mcpe at all. Sound cards are correctly installed since I can play youtube videos with sound. I'm using MCPE 0.14.1. It shouldn't be the version of minecraft though. So this must be a bug.

**Comment by stayandwait** [comment]
@MCMrARM Do you know how to fix this or is this just a bug with the launcher?

**Comment by MCMrARM** [comment]
Please check again.

**Comment by stayandwait** [comment]
Still no audio. I upgraded all the required libraries to the latest, reinstalled the launcher, then extracted the apk file for 0.14.2. I retested this using a virtual machine running Ubuntu 16.04. Sound works just fine when looking at youtube videos and testing audio in settings panel.

Could it be the way I installed the libraries?

I installed these first:
sudo apt-get install libgles2-mesa-dev:i386 libegl1-mesa-dev:i386

I also did an upgrade for them so they're the latest:
sudo apt-get upgrade libgles2-mesa-dev:i386 libegl1-mesa-dev:i386

Then I installed these:
sudo apt-get install cmake zlib1g-dev:i386 libncurses5-dev:i386 gcc-multilib g++-multilib zlib1g-dev:i386 libx11-dev:i386 linux-libc-dev:i386 uuid-dev:i386 libpng-dev:i386 libx11-dev:i386

I also did an upgrade for these so they're the latest:
sudo apt-get upgrade cmake zlib1g-dev:i386 libncurses5-dev:i386 gcc-multilib g++-multilib zlib1g-dev:i386 libx11-dev:i386 linux-libc-dev:i386 uuid-dev:i386 libpng-dev:i386 libx11-dev:i386

**Comment by AryToNeX** [comment]
I am on Ubuntu 16.04 and I don't have this issue. Maybe is your sound card

**Comment by MCMrARM** [comment]
Does this issue still exist?

**Comment by MCMrARM** [comment]
Going to close this issue for now as I got no reply; please reopen it if needed.

**Comment by BrokenR3C0RD** [comment]
I have this issue on my Xubuntu 16.04 PC. Audio works everywhere except for MCPE.
