### ISSUE TITLE
MCPE 0.14.2 doesn't work with this launcher

### ISSUE THREAD

**Issue by stayandwait** [MCMrARM/mcpelauncher-linux#45]
When opening the launcher after compiling i'm getting this error. However, I don't get this error when using previous apks with this launcher.
liam@ubuntu:~/Desktop/mcpelauncher-linux$ ./mcpelauncher 
loading MCPE
oslib: /usr/lib/i386-linux-gnu/libGLESv2.so: 163052224
oslib: /home/liam/Desktop/mcpelauncher-linux/libs/native/libfmod.so.7.7: 163054200
linker/home/liam/Desktop/mcpelauncher-linux/hybris/src/jb/linker.c:2010| ERROR: failed to link libminecraftpe.so
failed to load MCPE: Cannot load library: reloc_library[1343]:     0 cannot locate 'eglSwapInterval'...

**Comment by ColtonDRG** [comment]
I ran into this too. Are you going to update this anymore.

Also, is there some way I can download an old version from the Play Store?

**Comment by MCMrARM** [comment]
now it's supported.
