### ISSUE TITLE
MCPElauncher-linux 1.0.0 - Issues and workarounds

### ISSUE THREAD

**Issue by AryToNeX** [MCMrARM/mcpelauncher-linux#48]
# Major issues
- [x] 1.0.0 support.
- [ ] Xbox Live authentication.
- [ ] Window title name to "Minecraft: Pocket Edition" instead of "Minecraft".
- [ ] Local servers don't show up.
- [ ] Fix for in-built libraries - meanwhile we can use 'compatibility' libs provided in #14 .

# Minor issues
- [x] Enchanted table book with wrong and weird texture.
  ![Svilex's Image showing this bug -- 0.15.0](https://cloud.githubusercontent.com/assets/16593861/13993363/5f7b6e04-f120-11e5-9c77-f24160b7ea7e.png)
- [ ] Gamepad support does not exist.
- [x] Pressing TAB in chat makes a strange 'o' appear and can't be 'properly' used for commands auto-completion.

# Workarounds
```
LibEGL: DRI2: Failed to authenticate.
```
Common in NVIDIA GPUs.
Link your libEGL.so library (from your driver folder, like `/usr/lib32/nvidia-xxx/libEGL.so`, to `/usr/lib/i386-linux-gnu/libEGL.so`, overriding if necessary.

```
loading MCPE
oslib: /usr/lib/i386-linux-gnu/libGLESv2.so: 1472995016
oslib: /home/tarik02/.mcpe/mcpelauncher-linux/libs/native/libfmod.so.8.2: 1472996992
Illegal instruction (core dumped)
```
Use compatibility libs from issue #14

**Comment by MCMrARM** [comment]
You get a warning when you type --temp-amd-fix in the console and I know why it happens.
I know about the accented letters thing, I'll try to fix it some time later.

**Comment by MCMrARM** [comment]
Fixed the accented letters bug :)

**Comment by stayandwait** [comment]
Add audio to the list. There isn't any audio in the game. The last time I had audio was with an older launcher, I've updated the launcher since 0.14.1 and don't get audio anymore.

**Comment by AryToNeX** [comment]
@MCMrARM remember of the lighting bug for AMD CPUs

**Comment by MCMrARM** [comment]
Fixed the lightning bug on AMD CPUs.

**Comment by AryToNeX** [comment]
Added newest issues and suggestions.
@MCMrARM if you want please add the TODO flag on this issue

**Comment by MCMrARM** [comment]
" It takes too long to ping the servers " How is it my fault? I'm not going to fix Mojang bugs!

**Comment by AryToNeX** [comment]
Srsly? Ok ok removing it

**Comment by MCMrARM** [comment]
About 0.15 support - I'll look into it soon. However no clue how would I do Xbox Live auth though :(

**Comment by Matsv** [comment]
@MCMrARM https://twitter.com/_tomcc/status/720247445234393090

**Comment by AryToNeX** [comment]
@Matsv that post was about the Realms Alpha test. In the final 0.15 Xbox auth will exist but it will be optional

**Comment by AryToNeX** [comment]
Updated :)

**Comment by MCMrARM** [comment]
I'm going to close this as Invalid; there are multiple problems specified in this single issue; please open a different issue for each of them.
