### ISSUE TITLE
Any way to launch a headless MCPE server using mcpelauncher-linux?

### ISSUE THREAD

**Issue by Stormwind99** [MCMrARM/mcpelauncher-linux#50]
Is there any known way to launch a headless MCPE server using mcpelauncher-linux?

**Comment by MCMrARM** [comment]
No, but it should be easy enough to add.

**Comment by Stormwind99** [comment]
That would be great.   I could then adapt my Minecraft PC server system startup scripts and make a MCPE server startup script and contribute it.

**Comment by Stormwind99** [comment]
... and we (users in general) could run headless/console MCPE servers on server-like systems where we already run MC PC Edition servers.

**Comment by mhsjlw** [comment]
Any update on this? I'd love it 😄

**Comment by mhsjlw** [comment]
Any way to talk about this informally? Do you have a Gitter room or IRC channel?

**Comment by DaMatrix** [comment]
Nice idea, assuming that there isn't one a Discord would be great :D

**Comment by MCMrARM** [comment]
Omg I got this working. I need to clean it up & I'll upload the sources.

**Comment by MCMrARM** [comment]
Some work was made on `master`.

**Comment by hugheaves** [comment]
This is resolved, right? Works for me using "server" on the latest master! (Thanks for the hard work on this awesome wrapper / adapter / whatever you call it :)

**Comment by mhsjlw** [comment]
Yes this can be closed
