### ISSUE TITLE
Invalid instruction when trying to load a world

### ISSUE THREAD

**Issue by thebigsmileXD** [MCMrARM/mcpelauncher-linux#54]
root@xUbuntu-Xenial:/home/xenialdan/Dokumente/MCPE/mcpelauncher-linux# ./mcpelauncher 
loading MCPE
oslib: /usr/lib/i386-linux-gnu/libGLESv2.so: 143253192
oslib: /home/xenialdan/Dokumente/MCPE/mcpelauncher-linux/libs/native/libfmod.so.8.2: 143255216
Ungültiger Maschinenbefehl (Speicherabzug geschrieben) // This means: Invalid command

**Comment by thebigsmileXD** [comment]
./mcpelauncher —temp-amd-fix

**Comment by MCMrARM** [comment]
On 0.14.3 this can be fixed using --amd-fix, on 0.15 it's probably broken again.

**Comment by thebigsmileXD** [comment]
it is not fixed, still occurrs, thats why i opened the issue.

2016-06-19 15:10 GMT+02:00 MCMrARM <notifications@github.com>:

**Comment by MCMrARM** [comment]
Does this still happen on 1.0.0?

**Comment by thebigsmileXD** [comment]
Yes. I always have to switch to custom librarys provided by @arytonex

**Comment by AryToNeX** [comment]
@thebigsmileXD I didn't provide those libs; MCMrARM did ;P

**Comment by thebigsmileXD** [comment]
@AryToNeX but you've sendt me the files

**Comment by MCMrARM** [comment]
If it works with the libs fine, I'm closing the issue.

**Comment by thebigsmileXD** [comment]
![image](https://cloud.githubusercontent.com/assets/8733998/22067805/1a14e146-dd93-11e6-8170-0d4636cf25e4.png)

**Comment by AryToNeX** [comment]
@thebigsmileXD "That doesn't happen on my machine" lol
