### ISSUE TITLE
mcpe 0.15

### ISSUE THREAD

**Issue by svilex** [MCMrARM/mcpelauncher-linux#56]
`loading MCPE
oslib: /usr/lib/i386-linux-gnu/libGLESv2.so: 139693768
oslib: /home/giovanni/Desktop/mcpe2/libs/native/libfmod.so.8.2: 139695704
linker/home/giovanni/Desktop/mcpe2/hybris/src/jb/linker.c:1933| ERROR:     0 could not load needed library 'libGLESv1_CM.so' for 'libminecraftpe.so' (load_library[1109]: Library 'libGLESv1_CM.so' not found)
linker/home/giovanni/Desktop/mcpe2/hybris/src/jb/linker.c:2010| ERROR: failed to link libminecraftpe.so
failed to load MCPE: Cannot load library: link_image[1933]:     0 could not load needed library 'libGLESv1_CM.so' for 'libminecraftpe.so' (load_library[1109]: Library 'libGLESv1_CM.so' not found)`

**Comment by AryToNeX** [comment]
#48

**Comment by MCMrARM** [comment]
I'll look into implementing this soon. However, I'm NOT going to implement ANY of the xbox live or realms stuff.

**Comment by AryToNeX** [comment]
@MCMrARM what if Xbox Live auth can be used for server production? I mean, it is kinda cool for server owners but not cool for Linux mcpelauncher users... Anyway there will be time to do that if that can be done.

**Comment by MCMrARM** [comment]
I've just comitted some early support for 0.15. But it's pretty much unuseable right now as you can't load up local worlds most of the time, I'm trying to fix that. (You can play on multiplayer just fine)

**Comment by MCMrARM** [comment]
Fixed that bug, closing the issue.
