### ISSUE TITLE
could not find os library: libGLESv2.so

### ISSUE THREAD

**Issue by guppy42** [MCMrARM/mcpelauncher-linux#66]
Finally got it to compile but now this;

```
loading MCPE
could not find os library: libGLESv2.so
Signal 6 received
```

(omitted a whole pile of coredump stuff)

but libGLES is there;

```
mcpelauncher-linux$ ldconfig -p | grep libGLESv2.so
    libGLESv2.so.2 (libc6,x86-64) => /usr/lib/nvidia-361/libGLESv2.so.2
    libGLESv2.so.2 (libc6) => /usr/lib32/nvidia-361/libGLESv2.so.2
    libGLESv2.so (libc6,x86-64) => /usr/lib/nvidia-361/libGLESv2.so
    libGLESv2.so (libc6) => /usr/lib32/nvidia-361/libGLESv2.so
```

and the link is fine;

```
mcpelauncher-linux$ls -l /usr/lib32/nvidia-361/ | grep libGLESv2
lrwxrwxrwx 1 root root       26 Apr 14 17:53 libGLESv2_nvidia.so.2 -> libGLESv2_nvidia.so.361.42
-rw-r--r-- 1 root root    71384 Mar 23 03:05 libGLESv2_nvidia.so.361.42
lrwxrwxrwx 1 root root       14 Apr 14 17:53 libGLESv2.so -> libGLESv2.so.2
-rw-r--r-- 1 root root    38160 Mar 23 01:38 libGLESv2.so.2
```

I even took a fresh clone of the repository, sadly with the same result :(

**Comment by guppy42** [comment]
going over the code it seems the search paths are hardcoded 

https://github.com/MCMrARM/mcpelauncher-linux/blob/master/src/main.cpp#L281

so this can be "solved" with

sudo ln -s /usr/lib32/nvidia-361/libGLESv2.so /usr/lib32/libGLESv2.so

sadly after this the program just segfault with no visible cause : #67

**Comment by guppy42** [comment]
This is still a problem 

Just with a new driver version it's now;
sudo ln -s /usr/lib32/nvidia-367/libGLESv2.so /usr/lib32/libGLESv2.so


:|

**Comment by MCMrARM** [comment]
Fixed with https://github.com/MCMrARM/mcpelauncher-linux/commit/bda075278a828e4ce45250ac505fffde4ecc1042
