### ISSUE TITLE
compile with cmake fails

### ISSUE THREAD

**Issue by stayandwait** [MCMrARM/mcpelauncher-linux#7]
[100%] Building CXX object CMakeFiles/mcpelauncher.dir/mcpe/types.cpp.o
Linking CXX executable mcpelauncher
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_getstackaddr':
hooks.c:(.text+0x3f7): warning: the use of `pthread_attr_getstackaddr' is deprecated, use `pthread_attr_getstack'
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_setstackaddr':
hooks.c:(.text+0x3d6): warning: the use of `pthread_attr_setstackaddr' is deprecated, use `pthread_attr_setstack'
/usr/bin/ld: cannot find -lpng
collect2: error: ld returned 1 exit status
make[2]: *** [mcpelauncher] Error 1
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
make: *** [all] Error 2

I am sooo close..

EDIT

I added a symlink for hoping this would fix the problem
ln -s /usr/lib/x86_64-linux-gnu/libpng.so /usr/lib/libpng.so

and this is the new error I am getting
[100%] Building CXX object CMakeFiles/mcpelauncher.dir/mcpe/types.cpp.o
make[2]: *** No rule to make target `/usr/lib/libpng.so', needed by `mcpelauncher'.  Stop.
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
make: *** [all] Error 2

**Comment by InusualZ** [comment]
I have experienced this issue. It seems that your Linux distro don't support multi-arch. So you need to download a new one that support it(Recommended: Ubuntu 14.0>)

**Comment by iksaku** [comment]
Strange, I get a similar error during compilation... Even when the Launcher starts, here goes my logs:

-

During compilation (`make`):
```CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_getstackaddr':
hooks.c:(.text+0x3f7): warning: the use of `pthread_attr_getstackaddr' is deprecated, use `pthread_attr_getstack'
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_setstackaddr':
hooks.c:(.text+0x3d6): warning: the use of `pthread_attr_setstackaddr' is deprecated, use `pthread_attr_setstack'
[100%] Built target mcpelauncher
```

While starting the launcher (`./mcpelauncher`)
```
oslib: /usr/lib/i386-linux-gnu/libGLESv2.so: 167747768
oslib: /home/iksaku/Desktop/Servers/MCPEClient/Launcher/libs/native/libfmod.so.7.2: 167749784
```

BTW: I'm in Ubuntu 15.04 ;)

**Comment by stayandwait** [comment]
InusualZ I agree with you there. It's probably the version Linux I am using.

**Comment by stayandwait** [comment]
InusualZ I agree with you there. It's probably the version Linux I am using. I'm using Ubuntu 14.04.

**Comment by InusualZ** [comment]
I was using Linux Mint and I have to switch to Ubuntu. Now I have compiled mcpelauncher-linux but when I open it immediately after close.... Maybe is a bug?

**Comment by InusualZ** [comment]
I was wrong I downloaded the wrong MCPE(0.12.0). Downloaded the 0.13.0b5 and work perfectly
