### ISSUE TITLE
/usr/bin/ld: cannot find -lEGL

### ISSUE THREAD

**Issue by badp1g** [MCMrARM/mcpelauncher-linux#71]
How to fix? (ubuntu 16.04.1 x64)

user@ThinkPad-Edge:~/mcpelauncher-linux$ make
[  4%] Linking CXX executable mcpelauncher
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_getstackaddr':
hooks.c:(.text+0x3f8): warning: the use of`pthread_attr_getstackaddr' is deprecated, use `pthread_attr_getstack'
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function`my_pthread_attr_setstackaddr':
hooks.c:(.text+0x3d7): warning: the use of `pthread_attr_setstackaddr' is deprecated, use`pthread_attr_setstack'
/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status
CMakeFiles/mcpelauncher.dir/build.make:581: ошибка выполнения рецепта для цели «mcpelauncher»
make[2]: **\* [mcpelauncher] Ошибка 1
CMakeFiles/Makefile2:67: ошибка выполнения рецепта для цели «CMakeFiles/mcpelauncher.dir/all»
make[1]: **\* [CMakeFiles/mcpelauncher.dir/all] Ошибка 2
Makefile:83: ошибка выполнения рецепта для цели «all»
make: **\* [all] Ошибка 2

**Comment by guppy42** [comment]
Try and see if this works for you also;

https://github.com/MCMrARM/mcpelauncher-linux/issues/62#issuecomment-242860044

basically;

sudo apt-get install libmirclient-dev:i386 libmircommon-dev:i386 libxkbcommon-dev:i386 libmirclient-dev:i386 libwayland-dev:i386 libwayland-egl1-mesa:i386 libegl1-mesa-drivers libegl1-mesa-dev:i386 libegl1-mesa:i386

and then try again

**Comment by badp1g** [comment]
Thanks. there is no errors when i run ./extract.sh mcpe.apk but ./mcpelauncher : 
#19 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf72613e7]
#20 ./mcpelauncher(_Z18detachFromJavaStubv+0) [0x8062d81]
#21 [0xf7755bc0]
#22 [0xf7755be9]
#23 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf725fe89]
#24 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf72613e7]
Ошибка сегментирования (сделан дамп памяти)

**Comment by guppy42** [comment]
That's a known issue - you will need minecraft pocket version 0.15.0 aparently - more recent versions will not work.

It may get support for more recent version but not any time soon;

https://twitter.com/ohforffs/status/774925430063325184

**Comment by badp1g** [comment]
Where can i find 0.15 x86? I found only 0.15.1.2

**Comment by guppy42** [comment]
I do not think you can legally download it from the google play store, so unless you kept a copy of the .apk then you are out of luck :(
