### ISSUE TITLE
MCPE will not work with 0.16.0

### ISSUE THREAD

**Issue by Armored-Dragon** [MCMrARM/mcpelauncher-linux#73]
MCPELauncher won't start the game, it crashes during launch with "Bus error (core dumped)".
CPU: Intel Core i7-6500k
Distro: Ubuntu 16.10, Kernel 4.8
Log:

```
loading MCPE
oslib: /usr/lib/i386-linux-gnu/libGLESv2.so: 1469081304
oslib: /home/dragon/Downloads/mcpelauncher-linux/libs/native/libfmod.so.8.2: 1469082392
Bus error (core dumped)
```

It seems that the numbers change every time I attempt to launch it - are they memory addresses?
Also tested on Intel Core i5 Sandy Bridge laptop running Arch Linux (kernel 4.7), same error. (Bus error)

Does libfmod need updating?

EDIT:
Further tested with older APK, MCPE 0.14.3 x86.
This one gets much further, and does output a lot of text, but it keeps repeating this:

```
#0 ./mcpelauncher(_Z12handleSignali+0x57) [0x565d105c]
#1 [0xf774ecb0]
#2 [0xf774ec99]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0xb0) [0xf726c050]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf726d577]
#5 ./mcpelauncher(_Z18detachFromJavaStubv+0) [0x565d124b]
#6 [0xf774ecb0]
#7 [0xf774ec99]
#8 /lib/i386-linux-gnu/libc.so.6(gsignal+0xb0) [0xf726c050]
#9 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf726d577]
#10 ./mcpelauncher(_Z18detachFromJavaStubv+0) [0x565d124b]
#11 [0xf774ecb0]
#12 [0xf774ec99]
#13 /lib/i386-linux-gnu/libc.so.6(gsignal+0xb0) [0xf726c050]
#14 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf726d577]
#15 ./mcpelauncher(_Z18detachFromJavaStubv+0) [0x565d124b]
#16 [0xf774ecb0]
#17 [0xf774ec99]
#18 /lib/i386-linux-gnu/libc.so.6(gsignal+0xb0) [0xf726c050]
#19 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf726d577]
#20 ./mcpelauncher(_Z18detachFromJavaStubv+0) [0x565d124b]
#21 [0xf774ecb0]
#22 [0xf774ec99]
#23 /lib/i386-linux-gnu/libc.so.6(gsignal+0xb0) [0xf726c050]
#24 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf726d577]
Signal 6 received
Getting stacktrace...
Backtrace elements: 25
```

Repeats more than 10000 lines until eventually it segfaults: `Segmentation fault (core dumped)`.

EDIT 2: Further tested with 0.15.1.2 apk, and it works. So, it seems that the problem is just that the launcher needs to be updated to work with 0.15.9 and 0.16.0, when it releases.

**Comment by DaMatrix** [comment]
this project is (temporarily) dead, so it's not going to work

**Comment by MCMrARM** [comment]
I'm going to skip over 0.16 support and instead release support for the 0.17 betas.

**Comment by SuperGeniusZeb** [comment]
I think this issue should be closed now, since it's not really valid.

**Comment by Armored-Dragon** [comment]
Oh, yes, I forgot. Thanks for the reminder
