### ISSUE TITLE
failed to load library /usr/lib32/libGLESv2.so

### ISSUE THREAD

**Issue by DaMatrix** [MCMrARM/mcpelauncher-linux#74]
`daporkchop@daporkchop-thinkpad-t420:~/mcpe/mcpelauncher-linux$ ./mcpelauncher loading MCPE
failed to load library /usr/lib32/libGLESv2.so: libstdc++.so: cannot open shared object file: No such file or directory
oslib: /home/daporkchop/mcpe/mcpelauncher-linux/libs/native/libfmod.so.8.2: 157474848
daporkchop@daporkchop-thinkpad-t420:~/mcpe/mcpelauncher-linux$`

**Comment by guppy42** [comment]
You've got two errors, for the first see See issue #66 - there is a temp fix there

**Comment by DaMatrix** [comment]
I've tried that, it said "no such file or directory"

**Comment by guppy42** [comment]
Well you need to point the symlink to the correct file. 

Are you using nVidia? What is the output of ls -la /usr/lib32/nvidia*

**Comment by DaMatrix** [comment]
I'm using intel HD.

**Comment by DaMatrix** [comment]
There are no files on my hard disk named libfmod.so.8.2 *except* in the libs/native folder.

**Comment by guppy42** [comment]
That is correct but the real error occurs a few lines before;

./mcpelauncher loading MCPE failed to load library /usr/lib32/libGLESv2.so


The doc says

"if you use mesa you'll need to install the libgles2-mesa-dev:i386 and libegl1-mesa-dev:i386 packages"

So try

sudo apt-get install libgles2-mesa-dev:i386 libegl1-mesa-dev:i386

And do the cmake & make again

**Comment by DaMatrix** [comment]
I had to install them in order to make in the first place.

**Comment by guppy42** [comment]
@DaMatrix 

do a 
find /usr -iname libGLESv2.so

( ignore the line going "/usr/lib/x86_64-linux-gnu/libGLESv2.so" )

symlink the other to /usrlib32/libGLESv2.so

sudo ln -s /theotherpath/libGLESv2.so /usr/lib32/libGLESv2.so

and note down somewhere that you've done this as it's a really rather bad "fix" and you will properly need to update the linke every so often or remove it once a proper fix is introduced.

**Comment by DaMatrix** [comment]
Which one? There are four.
`daporkchop@daporkchop-thikpad-t420:~$ find /usr -iname libGLESv2.so
/usr/lib32/libGLESv2.so
/usr/lib/x86_64-linux-gnu/mesa-egl/libGLESv2.so
/usr/lib/x86_64-linux-gnu/libGLESv2.so
/usr/lib/i386-linux-gnu/libGLESv2.so
daporkchop@daporkchop-thikpad-t420:~$`

**Comment by guppy42** [comment]
is /usr/lib32/libGLESv2.so really there or is it a broken link, if it's there and a valid file then I have no clue what's gone wrong..  (might be a wrong glibc version or something, but at that point I'm just guessing )

**Comment by DaMatrix** [comment]
Seems to be, `cat` returns a bunch of gibberish text and the words "GCC: (GNU)"
