### ISSUE TITLE
libEGL warning: DRI2: failed to authenticate

### ISSUE THREAD

**Issue by AryToNeX** [MCMrARM/mcpelauncher-linux#75]
I have this issue when launching MCPE 0.17b2
(Edit: This is 0.17b2 apk for sure)
```
loading MCPE
oslib: /usr/lib32/libGLESv2.so: 149794552
oslib: /home/anthony/mcpelauncher-linux-master/libs/native/libfmod.so.8.2: 149795728
loaded MCPE (at 4101439488)
apply patches
original: 85 83 87 86 131
post patch: 233 63 93 40 18
original: 85 83 87 86 131
post patch: 233 229 206 40 18
original: 85 83 87 86 129
post patch: 233 63 204 40 18
original: 83 87 86 131 236
post patch: 233 237 204 40 18
original: 83 131 236 8 232
post patch: 233 98 0 230 17
original: 83 87 86 131 236
post patch: 233 112 7 230 17
original: 83 87 86 131 236
post patch: 233 26 113 6 18
original: 83 131 236 8 232
post patch: 233 28 100 6 18
original: 83 131 236 8 232
post patch: 233 44 99 6 18
original: 83 86 80 232 0
post patch: 233 154 175 106 18
patches applied!
init app platform vtable
AppPlatform size = 116
init app platform
app platform initialized
init window
libEGL warning: DRI2: failed to authenticate
EGL_VERSION = 1.4 (DRI2)
fetch patch notes
Signal 11 received
Getting stacktrace...
Backtrace elements: 2
#0 ./mcpelauncher(_Z12handleSignali+0x5d) [0x80627e6]
#1 [0xf7702bc0]
Signal 6 received
Annullato (core dump creato)
```

Using ElementaryOS 0.4 Loki (based on Ubuntu 16.04)
Intel Pentium Dual Core E5300
NVIDIA GeForce 9400 GT (nvidia-340 drivers)

Using compatibility libs from #14

**Comment by DaMatrix** [comment]
It *is* there.

-------- Original message --------

**Comment by KennFatt** [comment]
Fix this issue as soon as possible

**Comment by guppy42** [comment]
Maybe I'm daft but how do I download the beta apk - using playdl.jar I get the same version ( 780140301 ) weather I join the beta program or not

What am I missing?

**Comment by KennFatt** [comment]
@guppy42 try this ones https://cloud.mail.ru/public/KLxp/jsU68i3tA
i download with my asus phone from play store, it has x86 machine.

**Comment by guppy42** [comment]
@KennFatt Thanks that seems to work

**Comment by KennFatt** [comment]
i had this issue too when try to join servers (not LAN)

```
[MinecraftPE] VERBOSE RAKNET [IPv6] multicast listen on interface 0



send http request
destroying http request
send http request
destroying http request
Signal 11 received
Getting stacktrace...
Backtrace elements: 3
#0 ./mcpelauncher(_Z12handleSignali+0x6d) [0x56601d68]
#1 [0xf777acb0]
#2 HYBRIS Level::getRuntimeEntity(EntityRuntimeID, bool) const+63 in libminecraftpe.so+0xe3bd9f [0xf5601d9f]
Signal 6 received
Aborted (core dumped)
```

**Comment by guppy42** [comment]
+KenFatt I think you should make a sepperate issue for that, it doesn't really seem related

**Comment by guppy42** [comment]
@AryToNeX a quick google search for the error "DRI2: failed to authenticate" suggests that it may be driver related.

Have your tried reinstalling the driver?

**Comment by AryToNeX** [comment]
@guppy42 I have nvidia-340 drivers and they are the latest drivers for my graphics card as far as I know. I can use nouveau but I don't know if it can work...

**Comment by guppy42** [comment]
It may be that the 32bit drivers libs are missing if you only recently added the i386 arch to the system, if you can try re-installing the driver. 

I'm not sure if switching to nouveau and back is enough.

**Comment by AryToNeX** [comment]
```-- Checking for module 'egl'
--   No package 'egl' found
-- Could NOT find EGL (missing:  EGL_LIBRARIES) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/anthony/mcpelauncher-linux-master```


in `cmake .` command, I haven't seen this before

**Comment by guppy42** [comment]
@AryToNeX 
the cmake error is due to cmake looking for the wrong library version - it tries to find the x86_64 version, if the library is found you instead get issue #76  ;)

The good news is that once you finally manage to navigate the maze of library linking it actually does currently work.

**Comment by AryToNeX** [comment]
@guppy42 So should I link the EGL libs to x86_64 folders or simply modify cmake to look into lib32 folder?

**Comment by guppy42** [comment]
It needs the lib32 version to work, so if you know enough cmake to modify it to actually find the lib32 one I suggest you make the change and do a pull request.

Personally I've had to resort to modifying cmake's output as I cannot make heads or tails the cmake commands

**Comment by AryToNeX** [comment]
I don't know how to fix it. @MCMrARM do you have any idea?

**Comment by MCMrARM** [comment]
Driver issue or an issue with the code finding the wrong libEGL.so library.
