### ISSUE TITLE
Minecraft: PE 1.0.0.0 support?

### ISSUE THREAD

**Issue by mhsjlw** [MCMrARM/mcpelauncher-linux#80]
The beta was released, it'd be nice for mcpelauncher to have support for it, thanks! (0.16 would be nice, too :smile:)

**Comment by guppy42** [comment]
Does it actually not Work? If so what is the error?

**Comment by mhsjlw** [comment]
```
loading MCPE
oslib: /usr/lib32/libGLESv2.so: 155596416
oslib: /home/mhsjlw/Documents/mcpelauncher-linux1.0.0.0/libs/native/libfmod.so.8.2: 155597648
linker/home/mhsjlw/Documents/mcpelauncher-linux1.0.0.0/hybris/src/jb/linker.c:2010| ERROR: failed to link libminecraftpe.so
failed to load MCPE: Cannot load library: reloc_library[1343]:     0 cannot locate '__android_log_write'...
```

**Comment by mhsjlw** [comment]
However I can make Minecraft: PE 0.17b2 work with this, it's just that my x86 1.0.0.0 apk fails to work.

**Comment by jerbear64** [comment]
This was an inconvenient time to find the project, given beta is now in 1.0.0.0 and 0.16 is incompatible.

**Comment by MCMrARM** [comment]
Added support for that beta.

**Comment by mhsjlw** [comment]
Thanks!
