### ISSUE TITLE
Android STL Library error

### ISSUE THREAD

**Issue by sprenten** [MCMrARM/mcpelauncher-linux#81]
failed to load MCPE: Cannot load library: link_image[1933]:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1109]: Library 'libgnustl_shared.so' not found)

**Comment by jerbear64** [comment]
0.16.x is not compatible. The latest compatible version is 0.17b2 (not the 1.0.0.0 beta yet) or the 0.15.x versions.
