### ISSUE TITLE
A way to download x86 apks

### ISSUE THREAD

**Issue by DaMatrix** [MCMrARM/mcpelauncher-linux#82]
@MCMrARM 's program doesn't seem to download the beta, only the latest release (0.16)

**Comment by mhsjlw** [comment]
A good way to do this is via bluestacks. If you're in the beta program and you download it inside of there you'll be good to go.

**Comment by DaMatrix** [comment]
ok, thanks. and is there a way to do it without bluestacks? bluestacks inside a windows vm probably won't be pretty.

**Comment by mhsjlw** [comment]
Ah, I see. You could _try_ Toolbox, although I've never used it personally: https://chrome.google.com/webstore/detail/toolbox-for-google-play-s/fepaalfjfchbdianlgginbmpeeacahoo

**Comment by guppy42** [comment]
@mhsjlw That seems to just add extensions to apk mirrors ( who afaik does not have payed apps )

This issue properly belongs here btw;
https://github.com/MCMrARM/google_play_downloader/

it might even be related to https://github.com/MCMrARM/google_play_downloader/issues/11

**Comment by mhsjlw** [comment]
I recommended this because to my understanding betas are stored in a completely different area than Google olsy

**Comment by InusualZ** [comment]
if you are in the beta tester group, google play download the beta auto

**Comment by DaMatrix** [comment]
I know that. But i don't have an x86 device, only ARM, and that still doesn't give me the APK (although i can extract it)

**Comment by InusualZ** [comment]
That's why you use MrARM google play apk downloader. It gave you the option to dowload the x86 option

**Comment by guppy42** [comment]
@InusualZ but not the debug version, see the first post in this thread....

**Comment by InusualZ** [comment]
What you mean with debug version?

**Comment by guppy42** [comment]
Typo, should have been "beta"

**Comment by InusualZ** [comment]
I repeat. If you are in the beta tester group and you input the correct credentials into the MrARM's program. You could download the x86 version of the beta of MCPE. That's why he created that program.

**Comment by DaMatrix** [comment]
Strange, for me it always downloads version 0.14.2.

**Comment by guppy42** [comment]
And I get the 0.16.x non beta, when should make a bug report.. ohwait
