### ISSUE TITLE
/usr/bin/ld: cannot find -lEGL

### ISSUE THREAD

**Issue by enoter** [MCMrARM/mcpelauncher-linux#84]
[ 90%] Building ASM object CMakeFiles/mcpelauncher.dir/src/amdfix.s.o
[ 95%] Building CXX object CMakeFiles/mcpelauncher.dir/mcpe/types.cpp.o
[100%] Linking CXX executable mcpelauncher
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_getstackaddr':
hooks.c:(.text+0x3f8): warning: the use of `pthread_attr_getstackaddr' is deprecated, use `pthread_attr_getstack'
CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o: In function `my_pthread_attr_setstackaddr':
hooks.c:(.text+0x3d7): warning: the use of `pthread_attr_setstackaddr' is deprecated, use `pthread_attr_setstack'
/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status
CMakeFiles/mcpelauncher.dir/build.make:581: ошибка выполнения рецепта для цели «mcpelauncher»
make[2]: *** [mcpelauncher] Ошибка 1
CMakeFiles/Makefile2:67: ошибка выполнения рецепта для цели «CMakeFiles/mcpelauncher.dir/all»
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Ошибка 2
Makefile:83: ошибка выполнения рецепта для цели «all»
make: *** [all] Ошибка 2
root@marat-VirtualBox:/root/mcpelauncher-linux-master#

**Comment by DaMatrix** [comment]
run `make` a second time

**Comment by enoter** [comment]
@DaMatrix i cant run launcher. I get it:

marat@marat-VirtualBox:~/Рабочий стол/mcpelauncher-linux-master$ ./mcpelauncher
loading MCPE
could not find os library: libGLESv2.so
Signal 6 received
Getting stacktrace...
Backtrace elements: 9
#0 ./mcpelauncher(_Z12handleSignali+0x5d) [0x80628b1]
#1 [0xf7739bc0]
#2 [0xf7739be9]
#3 /lib/i386-linux-gnu/libc.so.6(gsignal+0x39) [0xf723bea9]
#4 /lib/i386-linux-gnu/libc.so.6(abort+0x157) [0xf723d407]
#5 ./mcpelauncher(_Z16getOSLibraryPathSs+0x229) [0x8062776]
#6 ./mcpelauncher(main+0x667) [0x8063270]
#7 /lib/i386-linux-gnu/libc.so.6(__libc_start_main+0xf7) [0xf7228637]
#8 ./mcpelauncher() [0x8054301]
Signal 6 received
Аварийный останов (сделан дамп памяти)
marat@marat-VirtualBox:~/Рабочий стол/mcpelauncher-linux-master$
