### ISSUE TITLE
Error when starting the launcher

### ISSUE THREAD

**Issue by Tarik02** [MCMrARM/mcpelauncher-linux#85]
```
tarik02@tarik02:~/.mcpe/mcpelauncher-linux$ ./mcpelauncher 
loading MCPE
oslib: /usr/lib/i386-linux-gnu/libGLESv2.so: 1472995016
oslib: /home/tarik02/.mcpe/mcpelauncher-linux/libs/native/libfmod.so.8.2: 1472996992
Illegal instruction (core dumped)
tarik02@tarik02:~/.mcpe/mcpelauncher-linux$ 
```

**Comment by AryToNeX** [comment]
Use libraries provided in #14

**Comment by thebigsmileXD** [comment]
```
xenialdan@xUbuntu-Xenial:~/Dokumente/MCPE$ ./start.sh 
loading MCPE
oslib: /usr/lib/i386-linux-gnu/libGLESv2.so: 167722696
oslib: /home/xenialdan/Dokumente/MCPE/mcpelauncher-linux/libs/native/libfmod.so.8.2: 167724720
linker/home/xenialdan/Dokumente/MCPE/mcpelauncher-linux/hybris/src/jb/linker.c:1933| ERROR:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1109]: Library 'libgnustl_shared.so' not found)
linker/home/xenialdan/Dokumente/MCPE/mcpelauncher-linux/hybris/src/jb/linker.c:2010| ERROR: failed to link libminecraftpe.so
failed to load MCPE: Cannot load library: link_image[1933]:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1109]: Library 'libgnustl_shared.so' not found)
```

**Comment by AryToNeX** [comment]
@thebigsmileXD you are using a 0.16 apk

**Comment by DaMatrix** [comment]
@AryToNeX I get the same error as the OP, and I've got all the required libraries.

**Comment by AryToNeX** [comment]
Try compatibility libs from #14, again.
They need to be replaced with existing ones in ./libs/

**Comment by DaMatrix** [comment]
I'm on intel, not AMD. And even adding the libraries still didn't change anything.

**Comment by AryToNeX** [comment]
I'm also on Intel and compatibility libs work well. If your PC doesn't work you shall find those libs yourself.

**Comment by thebigsmileXD** [comment]
@arytonex sorry, it was 0.17 aka 1.0

**Comment by AryToNeX** [comment]
@thebigsmileXD use the apk I provided in telegram .^.

**Comment by Ganjalf-Amsterdoom** [comment]
@AryToNeX Would you be so kind to pass me the apk? In an open issue there was a link to an apk that doesn't have multiplayer enable, I think is some kind of demo, but I bought the app to play with my son online and I can't get it to work, but the demo downloaded from another issue works just fine (mcpe01702intel-androidoyunclub.apk) but I can't connect it to my account/play multiplayer.
The downloader seem to download the wrong apk.
Grazie mille! :D

**Comment by AryToNeX** [comment]
@Ganjalf-Amsterdoom
Xbox Live authentication isn't supported (yet);
LAN multiplayer should work;
Now that 1.0.0 is officially out you should use the apk downloader; also I can't provide you APK because it's not legal (but Google has it :laughing: ).

**Comment by Ganjalf-Amsterdoom** [comment]
@AryToNeX I'm not talking about xbox live, I went to the house of a windows user friend and installed bluestack and I could play with my google account that I bought the game. I don't want a cracked apk. I know I can find them on google but I don't want them, and off course I'm not going to buy a windows license or install a cracked windows on my box. Lan multiplayer on mcpe01702intel-androidoyunclub.apk doesn't work, it's a demo version.
I hope the google play downloader will be fixed soon or I'll have to buy a tablet for myself.

**Comment by AryToNeX** [comment]
@Ganjalf-Amsterdoom That is not a demo version, that is a beta version. Protocol changed between that old beta release and official one, so you have to grab latest APK now; now that 1.0.0 is OFFICIAL and not in the beta channel anymore you should use the Google Play Downloader or login with a x86 device into Google Play and then grab the installed apk somehow.

**Comment by guppy42** [comment]
The Google Play downloader downloads and old version unfortunately

**Comment by thebigsmileXD** [comment]
@AryToNeX didnt work.

**Comment by Tarik02** [comment]
Not works even with your libs.

**Comment by thebigsmileXD** [comment]
With the libs and apk provided by @AryToNeX i get this: #79
