### ISSUE TITLE
Very high sensitivity

### ISSUE THREAD

**Issue by vzlomka76** [MCMrARM/mcpelauncher-linux#88]
How can I change the sensitivity? After setting the game does not change

**Comment by MCMrARM** [comment]
The sensitivity option in the game _indeed_ works. Make sure you're changing the one under "Mouse/Keyboard". It might still be too high but it will be better.

**Comment by MrGenga** [comment]
@MCMrARM how to make sensitivity lower? It is not comfortable to play with that

**Comment by DaMatrix** [comment]
It changes, but after restarting the game it needs to be changed again.

**Comment by MCMrARM** [comment]
Should be fixed with https://github.com/MCMrARM/mcpelauncher-linux/commit/9dac6dda4588f5469eb5ba7037ed3e29764cc356
