### ISSUE TITLE
Toolbox not working

### ISSUE THREAD

**Issue by ashyon** [MCMrARM/mcpelauncher-linux#89]
I copied libtoolbox.so and libgnustl_shared.so from the x86 libs in the Toolbox apk, but it won't load. The output of the launcher shows that it failed to link libtoolbox.so, and it does not load the mod. Any help?

**Comment by InusualZ** [comment]
They are not compiled for x86

**Comment by ashyon** [comment]
Ah okay. @MCMrARM would it be too much work to compile a version of Toolbox for mcpelauncher-linux?

**Comment by MCMrARM** [comment]
Not an actual issue with this project. It's not supported for now (due to hooking issues).
