### ISSUE TITLE
Unknown CMake command "target_compile_definitions"

### ISSUE THREAD

**Issue by stayandwait** [MCMrARM/mcpelauncher-linux#9]
This is the error I get when compiling. I'm using Ubuntu 12.04. Using cmake version 2.8.7
How do I fix this?

-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include files CMAKE_HAVE_PTHREAD_H
-- Looking for include files CMAKE_HAVE_PTHREAD_H - found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.3.4")
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so 
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- checking for module 'egl'
--   found egl, version 8.0.4
-- Found EGL: /usr/include 
CMake Error at CMakeLists.txt:27 (target_compile_definitions):
  Unknown CMake command "target_compile_definitions".

-- Configuring incomplete, errors occurred!

**Comment by stayandwait** [comment]
Updated cmake to 3.4.0 to fix previous problem and compile is failing in the middle of doing a "make"

[ 15%] Building C object CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o
/mcpelauncher-linux/hybris/src/hooks.c:24:0: warning: "_GNU_SOURCE" redefined
 #define _GNU_SOURCE
 ^
<command-line>:0:0: note: this is the location of the previous definition
/mcpelauncher-linux/hybris/src/hooks.c:52:22: fatal error: sys/auxv.h: No such file or directory
 #include <sys/auxv.h>
                      ^
compilation terminated.
make[2]: *** [CMakeFiles/mcpelauncher.dir/hybris/src/hooks.c.o] Error 1
make[1]: *** [CMakeFiles/mcpelauncher.dir/all] Error 2
make: *** [all] Error 2

**Comment by MCMrARM** [comment]
what distro and version?

**Comment by stayandwait** [comment]
Ubuntu 12.04 I had it listed at the top

**Comment by sliceofcode** [comment]
You should use Ubuntu 15.04. Ubuntu 14.04 has some problems with libPNG.

**Comment by stayandwait** [comment]
Upgrading to Ubuntu 15.04 fixed my problem.
