### ISSUE TITLE
Support for multiplayer servers

### ISSUE THREAD

**Issue by mathiascode** [MCMrARM/mcpelauncher-linux#90]
Is there currently support for multiplayer servers? Servers do not ping, and I can't join them.

**Comment by MCMrARM** [comment]
I'll look into this some time soon.

**Comment by MCMrARM** [comment]
There should be support for non-Xbox Live servers though.

**Comment by AryToNeX** [comment]
@mathiascode Servers don't ping because of a Mojang-related bug that's reported in their bug tracker; anyway XBL servers aren't joinable, sadly.

**Comment by DaMatrix** [comment]
Servers don't ping on Android either, it's not just mcpelauncher-linux

**Comment by MrGenga** [comment]
It is server soft's bug, close the issue. Tesseract servers are pinging normally

**Comment by mathiascode** [comment]
Seems like I can join servers now. Maybe it was a temporary issue on my end.
