### ISSUE TITLE
Library 'libgnustl_shared.so' not found

### ISSUE THREAD

**Issue by shaitand** [MCMrARM/mcpelauncher-linux#93]
shaitand@shaitand-Lenovo-Y50-70 ~/Downloads/mcpelauncher-linux $ ./mcpelauncher 
loading MCPE
oslib: /usr/lib/i386-linux-gnu/libGLESv2.so: 165697240
oslib: /home/shaitand/Downloads/mcpelauncher-linux/libs/native/libfmod.so.8.2: 165698328
linker/home/shaitand/Downloads/mcpelauncher-linux/hybris/src/jb/linker.c:1933| ERROR:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1109]: Library 'libgnustl_shared.so' not found)
linker/home/shaitand/Downloads/mcpelauncher-linux/hybris/src/jb/linker.c:2010| ERROR: failed to link libminecraftpe.so
failed to load MCPE: Cannot load library: link_image[1933]:     0 could not load needed library 'libgnustl_shared.so' for 'libminecraftpe.so' (load_library[1109]: Library 'libgnustl_shared.so' not found)

Not sure what provides this library. I saw indications the ndk supplies this but installing that didn't place it anywhere on my system.

**Comment by MCMrARM** [comment]
Use the latest version of Minecraft (1.0.0.16)
