### ISSUE TITLE
Merge the "AMD" support libraries into master

### ISSUE THREAD

**Issue by MCMrARM** [MCMrARM/mcpelauncher-linux#94]
Older CPUs can't use the libraries that are currently used by default (users with those CPUs can use ~http://mrarm.io/download/mcpelauncher_libs_amd.zip~ https://mrarm.io/u/mcpelauncher_libs_amd.zip ).

**Comment by InusualZ** [comment]
You should add this to the Readme, there are going to be people who are not gonna bother looking in the issues

**Comment by AryToNeX** [comment]
I think these "compatibility" libs should replace default ones: in fact they are compatible with every PC/laptop I've tested mcpelauncher on.
Current libs can also be in another folder like "compatibility-libs" or something like that.

**Comment by MCMrARM** [comment]
This issue will be closed when `apk-download` will be merged to master.

**Comment by MCMrARM** [comment]
Note that if anyone still needs it, the new link is https://mrarm.io/u/mcpelauncher_libs_amd.zip

**Comment by AryToNeX** [comment]
I think this is not needed anymore, is it?

**Comment by MCMrARM** [comment]
Indeed it is not, thanks for noticing this.
