### ISSUE TITLE
Error when building launcher

### ISSUE THREAD

**Issue by MrGenga** [MCMrARM/mcpelauncher-linux#97]
![image](https://cloud.githubusercontent.com/assets/6199266/21982629/187ac5e2-dc0f-11e6-9ed9-6c875c792a04.png)

**Comment by InusualZ** [comment]
Wrong EGL Library installed or installed in the wrong place

**Comment by MrGenga** [comment]
@InusualZ how to install it?

**Comment by MrGenga** [comment]
Oh I found it in issues, thanks
